
CREATE VIEW [dbo].[REFERRALPROGRAMPART2] (
   ID, 
   IDAPPLICANT, 
   REWARDTYPE, 
   REWARDPAID, 
   NOTES, 
   CREATED, 
   REWARDPAIDDATE)
AS 
   SELECT 
      REFERRALPROGRAM.ID, 
      REFERRALPROGRAM.IDAPPLICANT, 
      REFERRALPROGRAM.REWARDTYPE, 
      REFERRALPROGRAM.REWARDPAID, 
      REFERRALPROGRAM.NOTES, 
      REFERRALPROGRAM.CREATED, 
      REFERRALPROGRAM.REWARDPAIDDATE
   FROM dbo.REFERRALPROGRAM
   WHERE REFERRALPROGRAM.REWARDTYPE = '2'