



CREATE VIEW  [dbo].[WSOL_VW_HIREIQ_DATA] AS

SELECT IDAPPLICANT,CANDIDATEFULLNAME,[STATE] ,OVERALLSCORE,QUALIFIERSSCORE
,QUIZSCORE,TYPINGSCORE,LANGUAGEIQSCORE,PHONESCREENSCORE,REVIEWINGLINK,COMPLETEDDATE,WORDSPERMINUTE,ERRORRATE,RISKBAND,createddate FROM WSOL_TB_HIREIQ_RESULT

union

SELECT 
IDAPPLICANT,CANDIDATEFULLNAME,'Completed' AS [STATE] ,0 AS OVERALLSCORE,0 AS QUALIFIERSSCORE,QUIZSCORE,0 AS TYPINGSCORE,LANGUAGEIQSCORE,0 AS PHONESCREENSCORE
,REVIEWINGLINK,COMPLETEDDATE,WORDSPERMINUTE,ERRORRATE,RISKBAND,created FROM WSOL_TB_HIREIQ_CATS_IMPORT






