
CREATE PROCEDURE [dbo].[uspIMPORTS_MONAT_INVOICING_IMPORT]
AS
SET NOCOUNT ON

--  EXECUTE [dbo].[uspIMPORTS_MONAT_INVOICING_IMPORT]

--  SELECT * FROM WSOL_TB_IMPORTS_MONAT_INVOICING_1

--	Data is received in Eastern Time Zone.  Data will be converted to Central Time Zone.
--  Durations are in H:MM:S format and will be converted and stored in seconds.

--=================================================================================================
DECLARE @TENANT_KEY INT
SET @TENANT_KEY = 160  -- Monat Global Corp. CLIENT_ID in WSOL Database
--=================================================================================================
DELETE FROM WSOL_TB_IMPORT_ERRORS_FOUND
WHERE TENANT_KEY		= @TENANT_KEY
  AND SUB_GROUP_NAME	= 'MONAT_INVOICING'
  --  SELECT * FROM WSOL_TB_IMPORT_ERRORS_FOUND WHERE TENANT_KEY = 160
--=================================================================================================

--===========================================================================================================
--  USING @WS_ROW_CREATED_TIME FOR ALL INSERTS WILL ALLOW TO DELETE SPECIFIC INSERT PROCESSES/FILES.
--  IN CASE OF EMERGENCY, BREAK GLASS.
--===========================================================================================================
DECLARE @WS_ROW_CREATED_TIME AS DATETIME
SET @WS_ROW_CREATED_TIME = DBO.GETDATE()  --CLOSE ENOUGH TO ACTUAL INSERT TIME!
--===========================================================================================================

--	SELECT * FROM WSOL_TB_IMPORTS_MONAT_INVOICING_1
--=================================================================================================
--	CONVERT DATETIME FROM EASTERN TIME TO CENTRAL TIME
--=================================================================================================
UPDATE WSOL_TB_IMPORTS_MONAT_INVOICING_1 SET
 [DATETIME] = DATEADD(hh,-1, CAST((FF_DATE + ' ' + FF_TIME) AS DATETIME))

--===================================================================================
--	POPULATE ADDITIONAL FIELDS IN WORK (_1) TABLE THAT WEREN'T IN IMPORTED FILE:
--===================================================================================
UPDATE WSOL_TB_IMPORTS_MONAT_INVOICING_1 SET
 HOUR_INTERVAL				=	DATEPART(HH, [DATETIME])
,AGENT_NAME					=	ISNULL(FF_AGENT_NAME,'')
,ANSWERED_SESSIONS			=	ISNULL(CAST(FF_ANSWERED_SESSIONS	AS INT),0)
,RONA_CNT					=	ISNULL(CAST(FF_RONAS				AS INT),0)
,DID_CNT					=	ISNULL(CAST(FF_DIDS					AS INT),0)
,DOD_CNT					=	ISNULL(CAST(FF_DODS					AS INT),0)
,STARTED_IMS				=	ISNULL(CAST(FF_STARTED_IMS			AS INT),0)
,STARTED_CALLS				=	ISNULL(CAST(FF_STARTED_CALLS		AS INT),0)
,ESCALATIONS				=	ISNULL(CAST(FF_ESCALATIONS			AS INT),0)
,CONSULTS					=	ISNULL(CAST(FF_CONSULTS				AS INT),0)
,TRANSFERS					=	ISNULL(CAST(FF_TRANSFERS			AS INT),0)
,SUPERVISOR_JOINS			=	ISNULL(CAST(FF_SUPERVISOR_JOINS		AS INT),0)
,AVAILABLE_TIME				=	(CAST(LEFT(FF_AVAILABLE_TIME			,2) AS DECIMAL(10,2)) * 3600) + (CAST(SUBSTRING(FF_AVAILABLE_TIME			,4,2) AS DECIMAL(10,2)) * 60) + CAST(RIGHT(FF_AVAILABLE_TIME			,2) AS DECIMAL(10,2))
,RING_TIME					=	(CAST(LEFT(FF_RINGING_TIME1				,2) AS DECIMAL(10,2)) * 3600) + (CAST(SUBSTRING(FF_RINGING_TIME1			,4,2) AS DECIMAL(10,2)) * 60) + CAST(RIGHT(FF_RINGING_TIME1				,2) AS DECIMAL(10,2))
,CONNECT_IM_SESSION_TIME	=	(CAST(LEFT(FF_CONNECT_IM_SESSION_TIME	,2) AS DECIMAL(10,2)) * 3600) + (CAST(SUBSTRING(FF_CONNECT_IM_SESSION_TIME	,4,2) AS DECIMAL(10,2)) * 60) + CAST(RIGHT(FF_CONNECT_IM_SESSION_TIME	,2) AS DECIMAL(10,2))
,CONNECT_PHONE_CALL_TIME	=	(CAST(LEFT(FF_CONNECT_PHONE_CALL_TIME	,2) AS DECIMAL(10,2)) * 3600) + (CAST(SUBSTRING(FF_CONNECT_PHONE_CALL_TIME	,4,2) AS DECIMAL(10,2)) * 60) + CAST(RIGHT(FF_CONNECT_PHONE_CALL_TIME	,2) AS DECIMAL(10,2))
,CONNECT_DID_CALL_TIME		=	(CAST(LEFT(FF_CONNECT_DID_CALL_TIME		,2) AS DECIMAL(10,2)) * 3600) + (CAST(SUBSTRING(FF_CONNECT_DID_CALL_TIME	,4,2) AS DECIMAL(10,2)) * 60) + CAST(RIGHT(FF_CONNECT_DID_CALL_TIME		,2) AS DECIMAL(10,2))
,CONNECT_DOD_CALL_TIME		=	(CAST(LEFT(FF_CONNECT_DOD_CALL_TIME		,2) AS DECIMAL(10,2)) * 3600) + (CAST(SUBSTRING(FF_CONNECT_DOD_CALL_TIME	,4,2) AS DECIMAL(10,2)) * 60) + CAST(RIGHT(FF_CONNECT_DOD_CALL_TIME		,2) AS DECIMAL(10,2))
,NON_CONNECT_CALL_TIME		=	(CAST(LEFT(FF_NON_CONNECT_CALL_TIME		,2) AS DECIMAL(10,2)) * 3600) + (CAST(SUBSTRING(FF_NON_CONNECT_CALL_TIME	,4,2) AS DECIMAL(10,2)) * 60) + CAST(RIGHT(FF_NON_CONNECT_CALL_TIME		,2) AS DECIMAL(10,2))
,ACW_TIME					=	(CAST(LEFT(FF_AFTERCALL_TIME			,2) AS DECIMAL(10,2)) * 3600) + (CAST(SUBSTRING(FF_AFTERCALL_TIME			,4,2) AS DECIMAL(10,2)) * 60) + CAST(RIGHT(FF_AFTERCALL_TIME			,2) AS DECIMAL(10,2))
,RONA_TIME					=	(CAST(LEFT(FF_RONA_TIME					,2) AS DECIMAL(10,2)) * 3600) + (CAST(SUBSTRING(FF_RONA_TIME				,4,2) AS DECIMAL(10,2)) * 60) + CAST(RIGHT(FF_RONA_TIME					,2) AS DECIMAL(10,2))
,UNAVAILABLE_TIME			=	(CAST(LEFT(FF_UNAVAILABLE_TIME			,2) AS DECIMAL(10,2)) * 3600) + (CAST(SUBSTRING(FF_UNAVAILABLE_TIME			,4,2) AS DECIMAL(10,2)) * 60) + CAST(RIGHT(FF_UNAVAILABLE_TIME			,2) AS DECIMAL(10,2))
,OFF_WORK_TIME				=	(CAST(LEFT(FF_OFF_WORK_TIME				,2) AS DECIMAL(10,2)) * 3600) + (CAST(SUBSTRING(FF_OFF_WORK_TIME			,4,2) AS DECIMAL(10,2)) * 60) + CAST(RIGHT(FF_OFF_WORK_TIME				,2) AS DECIMAL(10,2))
,LOGGED_OUT_TIME			=	(CAST(LEFT(FF_LOGGED_OUT_TIME			,2) AS DECIMAL(10,2)) * 3600) + (CAST(SUBSTRING(FF_LOGGED_OUT_TIME			,4,2) AS DECIMAL(10,2)) * 60) + CAST(RIGHT(FF_LOGGED_OUT_TIME			,2) AS DECIMAL(10,2))
,ON_PHONE_TIME				=	(CAST(LEFT(FF_ON_PHONE_TIME				,2) AS DECIMAL(10,2)) * 3600) + (CAST(SUBSTRING(FF_ON_PHONE_TIME			,4,2) AS DECIMAL(10,2)) * 60) + CAST(RIGHT(FF_ON_PHONE_TIME				,2) AS DECIMAL(10,2))
,Q_ON_PHONE_TIME			=	(CAST(LEFT(FF_Q_ON_PHONE_TIME			,2) AS DECIMAL(10,2)) * 3600) + (CAST(SUBSTRING(FF_Q_ON_PHONE_TIME			,4,2) AS DECIMAL(10,2)) * 60) + CAST(RIGHT(FF_Q_ON_PHONE_TIME			,2) AS DECIMAL(10,2))
,TALK_TIME					=	(CAST(LEFT(FF_TALK_TIME					,2) AS DECIMAL(10,2)) * 3600) + (CAST(SUBSTRING(FF_TALK_TIME				,4,2) AS DECIMAL(10,2)) * 60) + CAST(RIGHT(FF_TALK_TIME					,2) AS DECIMAL(10,2))
,Q_TALK_TIME				=	(CAST(LEFT(FF_Q_TALK_TIME				,2) AS DECIMAL(10,2)) * 3600) + (CAST(SUBSTRING(FF_Q_TALK_TIME				,4,2) AS DECIMAL(10,2)) * 60) + CAST(RIGHT(FF_Q_TALK_TIME				,2) AS DECIMAL(10,2))
,HANDLE_TIME				=	(CAST(LEFT(FF_HANDLE_TIME				,2) AS DECIMAL(10,2)) * 3600) + (CAST(SUBSTRING(FF_HANDLE_TIME				,4,2) AS DECIMAL(10,2)) * 60) + CAST(RIGHT(FF_HANDLE_TIME				,2) AS DECIMAL(10,2))
,Q_HANDLE_TIME				=	(CAST(LEFT(FF_Q_HANDLE_TIME				,2) AS DECIMAL(10,2)) * 3600) + (CAST(SUBSTRING(FF_Q_HANDLE_TIME			,4,2) AS DECIMAL(10,2)) * 60) + CAST(RIGHT(FF_Q_HANDLE_TIME				,2) AS DECIMAL(10,2))
,TENANT_KEY					=	@TENANT_KEY

--===================================================================================================
-- UPDATE DATETIME KEY
--===================================================================================================
UPDATE WSOL_TB_IMPORTS_MONAT_INVOICING_1 SET
 STD_TENANT_START_DATE_TIME_KEY = DT.DATE_TIME_KEY
FROM		WSOL_TB_IMPORTS_MONAT_INVOICING_1	I
INNER JOIN	DATE_TIME						DT	ON DT.CAL_DATE = I.[DATETIME]

--	SELECT * FROM WSOL_TB_IMPORTS_MONAT_INVOICING_1
--===============================================
-- GENERATE ANY ENGINEERED VALUES																	<<<<----- MAY NEED TO UPDATE
--===============================================
--UPDATE WSOL_TB_IMPORTS_MONAT_INVOICING_1 SET

--	SELECT * FROM WSOL_TB_IMPORTS_MONAT_INVOICING_BAD
--===============================================
--REMOVE LOGGED OUT RECORDS:
--===============================================
INSERT INTO WSOL_TB_IMPORTS_MONAT_INVOICING_BAD
(
 BAD_IMPORTS_CODE
,BAD_IMPORTS_FILE_TYPE
,WS_ROW_CREATED_TIME
,FF_AGENT_NAME
,FF_DATE
,FF_TIME
,FF_BUSINESS_UNIT
,FF_TEAM
,FF_GROUPS
,FF_ANSWERED_SESSIONS
,FF_RONAS
,FF_DIDS
,FF_DODS
,FF_STARTED_IMS
,FF_STARTED_CALLS
,FF_ESCALATIONS
,FF_CONSULTS
,FF_TRANSFERS
,FF_SUPERVISOR_JOINS
,FF_AVAILABLE_TIME
,FF_RINGING_TIME1
,FF_CONNECT_IM_SESSION_TIME
,FF_CONNECT_PHONE_CALL_TIME
,FF_CONNECT_DID_CALL_TIME
,FF_CONNECT_DOD_CALL_TIME
,FF_NON_CONNECT_CALL_TIME
,FF_AFTERCALL_TIME
,FF_RONA_TIME
,FF_UNAVAILABLE_TIME
,FF_OFF_WORK_TIME
,FF_LOGGED_OUT_TIME
,FF_ON_PHONE_TIME
,FF_Q_ON_PHONE_TIME
,FF_TALK_TIME
,FF_Q_TALK_TIME
,FF_HANDLE_TIME
,FF_Q_HANDLE_TIME
,FF_OCC_PERCENT
,FF_Q_OCC_PERCENT
,FF_TALK_PERCENT
,FF_Q_TALK_PERCENT
,FF_ACW_PERCENT
,FF_IDLE_PERCENT
,FF_AVG_TALK_TIME_PERCENT
,FF_AVG_Q_TALK_TIME_PERCENT
,FF_AVG_ACW_TIME_PERCENT
,FF_AVG_Q_ACW_TIME_PERCENT
,FF_AVG_HANDLE_TIME_PERCENT
,FF_AVG_Q_HANDLE_TIME_PERCENT
,SEQNO_ADDED_TIME
,SEQNO
,FTP_FILE_NAME
,[DATETIME]
,HOUR_INTERVAL
,AGENT_NAME
,ANSWERED_SESSIONS
,RONA_CNT
,DID_CNT
,DOD_CNT
,STARTED_IMS
,STARTED_CALLS
,ESCALATIONS
,CONSULTS
,TRANSFERS
,SUPERVISOR_JOINS
,AVAILABLE_TIME
,RING_TIME
,CONNECT_IM_SESSION_TIME
,CONNECT_PHONE_CALL_TIME
,CONNECT_DID_CALL_TIME
,CONNECT_DOD_CALL_TIME
,NON_CONNECT_CALL_TIME
,ACW_TIME
,RONA_TIME
,UNAVAILABLE_TIME
,OFF_WORK_TIME
,LOGGED_OUT_TIME
,ON_PHONE_TIME
,Q_ON_PHONE_TIME
,TALK_TIME
,Q_TALK_TIME
,HANDLE_TIME
,Q_HANDLE_TIME
,CPROD
,MING
,AUT2
,[EMAIL]
,ID_EXT
,SCHEDULER_ACL_NAME
,STD_TENANT_START_DATE_TIME_KEY
,CAL_DATE
,TENANT_KEY
,AIR_DAY_TYPE
,AIR_ACW_FONT_COLOR
,MIN_GUARANTEE_MINUTES
,MIN_GUARANTEE_TYPE
,AUTHORIZED_TO_INVOICE_TYPE
,HAS_HOLIDAYS
,INCLUDE_IN_CAS
,READY_FOR_XML
,SHOW_ID_EXTS
,INVOICE_ID
,RESOURCE_NAME
,CATS_ID
,PAY_GROUP
)
SELECT
 'LOS'					--BAD_IMPORTS_CODE		--'Logged Out State'
,'ACT'                  --BAD_IMPORTS_FILE_TYPE	--'ACT'IVITY FILE
,@WS_ROW_CREATED_TIME	--WS_ROW_CREATED_TIME
,W1.FF_AGENT_NAME
,W1.FF_DATE
,W1.FF_TIME
,W1.FF_BUSINESS_UNIT
,W1.FF_TEAM
,W1.FF_GROUPS
,W1.FF_ANSWERED_SESSIONS
,W1.FF_RONAS
,W1.FF_DIDS
,W1.FF_DODS
,W1.FF_STARTED_IMS
,W1.FF_STARTED_CALLS
,W1.FF_ESCALATIONS
,W1.FF_CONSULTS
,W1.FF_TRANSFERS
,W1.FF_SUPERVISOR_JOINS
,W1.FF_AVAILABLE_TIME
,W1.FF_RINGING_TIME1
,W1.FF_CONNECT_IM_SESSION_TIME
,W1.FF_CONNECT_PHONE_CALL_TIME
,W1.FF_CONNECT_DID_CALL_TIME
,W1.FF_CONNECT_DOD_CALL_TIME
,W1.FF_NON_CONNECT_CALL_TIME
,W1.FF_AFTERCALL_TIME
,W1.FF_RONA_TIME
,W1.FF_UNAVAILABLE_TIME
,W1.FF_OFF_WORK_TIME
,W1.FF_LOGGED_OUT_TIME
,W1.FF_ON_PHONE_TIME
,W1.FF_Q_ON_PHONE_TIME
,W1.FF_TALK_TIME
,W1.FF_Q_TALK_TIME
,W1.FF_HANDLE_TIME
,W1.FF_Q_HANDLE_TIME
,W1.FF_OCC_PERCENT
,W1.FF_Q_OCC_PERCENT
,W1.FF_TALK_PERCENT
,W1.FF_Q_TALK_PERCENT
,W1.FF_ACW_PERCENT
,W1.FF_IDLE_PERCENT
,W1.FF_AVG_TALK_TIME_PERCENT
,W1.FF_AVG_Q_TALK_TIME_PERCENT
,W1.FF_AVG_ACW_TIME_PERCENT
,W1.FF_AVG_Q_ACW_TIME_PERCENT
,W1.FF_AVG_HANDLE_TIME_PERCENT
,W1.FF_AVG_Q_HANDLE_TIME_PERCENT
,W1.SEQNO_ADDED_TIME
,W1.SEQNO
,W1.FTP_FILE_NAME
,W1.[DATETIME]
,W1.HOUR_INTERVAL
,W1.AGENT_NAME
,W1.ANSWERED_SESSIONS
,W1.RONA_CNT
,W1.DID_CNT
,W1.DOD_CNT
,W1.STARTED_IMS
,W1.STARTED_CALLS
,W1.ESCALATIONS
,W1.CONSULTS
,W1.TRANSFERS
,W1.SUPERVISOR_JOINS
,W1.AVAILABLE_TIME
,W1.RING_TIME
,W1.CONNECT_IM_SESSION_TIME
,W1.CONNECT_PHONE_CALL_TIME
,W1.CONNECT_DID_CALL_TIME
,W1.CONNECT_DOD_CALL_TIME
,W1.NON_CONNECT_CALL_TIME
,W1.ACW_TIME
,W1.RONA_TIME
,W1.UNAVAILABLE_TIME
,W1.OFF_WORK_TIME
,W1.LOGGED_OUT_TIME
,W1.ON_PHONE_TIME
,W1.Q_ON_PHONE_TIME
,W1.TALK_TIME
,W1.Q_TALK_TIME
,W1.HANDLE_TIME
,W1.Q_HANDLE_TIME
,W1.CPROD
,W1.MING
,W1.AUT2
,W1.[EMAIL]
,W1.ID_EXT
,W1.SCHEDULER_ACL_NAME
,W1.STD_TENANT_START_DATE_TIME_KEY
,W1.CAL_DATE
,W1.TENANT_KEY
,W1.AIR_DAY_TYPE
,W1.AIR_ACW_FONT_COLOR
,W1.MIN_GUARANTEE_MINUTES
,W1.MIN_GUARANTEE_TYPE
,W1.AUTHORIZED_TO_INVOICE_TYPE
,W1.HAS_HOLIDAYS
,W1.INCLUDE_IN_CAS
,W1.READY_FOR_XML
,W1.SHOW_ID_EXTS
,W1.INVOICE_ID
,W1.RESOURCE_NAME
,W1.CATS_ID
,W1.PAY_GROUP
FROM           WSOL_TB_IMPORTS_MONAT_INVOICING_1    W1
WHERE (
	  LOGGED_OUT_TIME > 0.00
  AND AVAILABLE_TIME = 0.00
  AND RING_TIME = 0.00
  AND CONNECT_IM_SESSION_TIME = 0.00
  AND CONNECT_PHONE_CALL_TIME = 0.00
  AND CONNECT_DID_CALL_TIME = 0.00
  AND CONNECT_DOD_CALL_TIME = 0.00
  AND NON_CONNECT_CALL_TIME = 0.00
  AND ACW_TIME = 0.00
  AND RONA_TIME = 0.00
  AND UNAVAILABLE_TIME = 0.00
  AND OFF_WORK_TIME = 0.00
  AND ON_PHONE_TIME = 0.00
  AND Q_ON_PHONE_TIME = 0.00
  AND TALK_TIME = 0.00
  AND Q_TALK_TIME = 0.00
  AND HANDLE_TIME = 0.00
  AND Q_HANDLE_TIME = 0.00
  )

--======================================================================
--DELETE LOGGED OUT RECORDS;
--======================================================================
DELETE FROM WSOL_TB_IMPORTS_MONAT_INVOICING_1
WHERE (
	  LOGGED_OUT_TIME > 0.00
  AND AVAILABLE_TIME = 0.00
  AND RING_TIME = 0.00
  AND CONNECT_IM_SESSION_TIME = 0.00
  AND CONNECT_PHONE_CALL_TIME = 0.00
  AND CONNECT_DID_CALL_TIME = 0.00
  AND CONNECT_DOD_CALL_TIME = 0.00
  AND NON_CONNECT_CALL_TIME = 0.00
  AND ACW_TIME = 0.00
  AND RONA_TIME = 0.00
  AND UNAVAILABLE_TIME = 0.00
  AND OFF_WORK_TIME = 0.00
  AND ON_PHONE_TIME = 0.00
  AND Q_ON_PHONE_TIME = 0.00
  AND TALK_TIME = 0.00
  AND Q_TALK_TIME = 0.00
  AND HANDLE_TIME = 0.00
  AND Q_HANDLE_TIME = 0.00
  )
--======================================================================

--===============================================
--REMOVE ALL ZERO DURATION RECORDS:
--===============================================
INSERT INTO WSOL_TB_IMPORTS_MONAT_INVOICING_BAD
(
 BAD_IMPORTS_CODE
,BAD_IMPORTS_FILE_TYPE
,WS_ROW_CREATED_TIME
,FF_AGENT_NAME
,FF_DATE
,FF_TIME
,FF_BUSINESS_UNIT
,FF_TEAM
,FF_GROUPS
,FF_ANSWERED_SESSIONS
,FF_RONAS
,FF_DIDS
,FF_DODS
,FF_STARTED_IMS
,FF_STARTED_CALLS
,FF_ESCALATIONS
,FF_CONSULTS
,FF_TRANSFERS
,FF_SUPERVISOR_JOINS
,FF_AVAILABLE_TIME
,FF_RINGING_TIME1
,FF_CONNECT_IM_SESSION_TIME
,FF_CONNECT_PHONE_CALL_TIME
,FF_CONNECT_DID_CALL_TIME
,FF_CONNECT_DOD_CALL_TIME
,FF_NON_CONNECT_CALL_TIME
,FF_AFTERCALL_TIME
,FF_RONA_TIME
,FF_UNAVAILABLE_TIME
,FF_OFF_WORK_TIME
,FF_LOGGED_OUT_TIME
,FF_ON_PHONE_TIME
,FF_Q_ON_PHONE_TIME
,FF_TALK_TIME
,FF_Q_TALK_TIME
,FF_HANDLE_TIME
,FF_Q_HANDLE_TIME
,FF_OCC_PERCENT
,FF_Q_OCC_PERCENT
,FF_TALK_PERCENT
,FF_Q_TALK_PERCENT
,FF_ACW_PERCENT
,FF_IDLE_PERCENT
,FF_AVG_TALK_TIME_PERCENT
,FF_AVG_Q_TALK_TIME_PERCENT
,FF_AVG_ACW_TIME_PERCENT
,FF_AVG_Q_ACW_TIME_PERCENT
,FF_AVG_HANDLE_TIME_PERCENT
,FF_AVG_Q_HANDLE_TIME_PERCENT
,SEQNO_ADDED_TIME
,SEQNO
,FTP_FILE_NAME
,[DATETIME]
,HOUR_INTERVAL
,AGENT_NAME
,ANSWERED_SESSIONS
,RONA_CNT
,DID_CNT
,DOD_CNT
,STARTED_IMS
,STARTED_CALLS
,ESCALATIONS
,CONSULTS
,TRANSFERS
,SUPERVISOR_JOINS
,AVAILABLE_TIME
,RING_TIME
,CONNECT_IM_SESSION_TIME
,CONNECT_PHONE_CALL_TIME
,CONNECT_DID_CALL_TIME
,CONNECT_DOD_CALL_TIME
,NON_CONNECT_CALL_TIME
,ACW_TIME
,RONA_TIME
,UNAVAILABLE_TIME
,OFF_WORK_TIME
,LOGGED_OUT_TIME
,ON_PHONE_TIME
,Q_ON_PHONE_TIME
,TALK_TIME
,Q_TALK_TIME
,HANDLE_TIME
,Q_HANDLE_TIME
,CPROD
,MING
,AUT2
,[EMAIL]
,ID_EXT
,SCHEDULER_ACL_NAME
,STD_TENANT_START_DATE_TIME_KEY
,CAL_DATE
,TENANT_KEY
,AIR_DAY_TYPE
,AIR_ACW_FONT_COLOR
,MIN_GUARANTEE_MINUTES
,MIN_GUARANTEE_TYPE
,AUTHORIZED_TO_INVOICE_TYPE
,HAS_HOLIDAYS
,INCLUDE_IN_CAS
,READY_FOR_XML
,SHOW_ID_EXTS
,INVOICE_ID
,RESOURCE_NAME
,CATS_ID
,PAY_GROUP
)
SELECT
 'AZR'					--BAD_IMPORTS_CODE		--'All Zero Records'
,'ACT'                  --BAD_IMPORTS_FILE_TYPE	--'ACT'IVITY FILE
,@WS_ROW_CREATED_TIME	--WS_ROW_CREATED_TIME
,W1.FF_AGENT_NAME
,W1.FF_DATE
,W1.FF_TIME
,W1.FF_BUSINESS_UNIT
,W1.FF_TEAM
,W1.FF_GROUPS
,W1.FF_ANSWERED_SESSIONS
,W1.FF_RONAS
,W1.FF_DIDS
,W1.FF_DODS
,W1.FF_STARTED_IMS
,W1.FF_STARTED_CALLS
,W1.FF_ESCALATIONS
,W1.FF_CONSULTS
,W1.FF_TRANSFERS
,W1.FF_SUPERVISOR_JOINS
,W1.FF_AVAILABLE_TIME
,W1.FF_RINGING_TIME1
,W1.FF_CONNECT_IM_SESSION_TIME
,W1.FF_CONNECT_PHONE_CALL_TIME
,W1.FF_CONNECT_DID_CALL_TIME
,W1.FF_CONNECT_DOD_CALL_TIME
,W1.FF_NON_CONNECT_CALL_TIME
,W1.FF_AFTERCALL_TIME
,W1.FF_RONA_TIME
,W1.FF_UNAVAILABLE_TIME
,W1.FF_OFF_WORK_TIME
,W1.FF_LOGGED_OUT_TIME
,W1.FF_ON_PHONE_TIME
,W1.FF_Q_ON_PHONE_TIME
,W1.FF_TALK_TIME
,W1.FF_Q_TALK_TIME
,W1.FF_HANDLE_TIME
,W1.FF_Q_HANDLE_TIME
,W1.FF_OCC_PERCENT
,W1.FF_Q_OCC_PERCENT
,W1.FF_TALK_PERCENT
,W1.FF_Q_TALK_PERCENT
,W1.FF_ACW_PERCENT
,W1.FF_IDLE_PERCENT
,W1.FF_AVG_TALK_TIME_PERCENT
,W1.FF_AVG_Q_TALK_TIME_PERCENT
,W1.FF_AVG_ACW_TIME_PERCENT
,W1.FF_AVG_Q_ACW_TIME_PERCENT
,W1.FF_AVG_HANDLE_TIME_PERCENT
,W1.FF_AVG_Q_HANDLE_TIME_PERCENT
,W1.SEQNO_ADDED_TIME
,W1.SEQNO
,W1.FTP_FILE_NAME
,W1.[DATETIME]
,W1.HOUR_INTERVAL
,W1.AGENT_NAME
,W1.ANSWERED_SESSIONS
,W1.RONA_CNT
,W1.DID_CNT
,W1.DOD_CNT
,W1.STARTED_IMS
,W1.STARTED_CALLS
,W1.ESCALATIONS
,W1.CONSULTS
,W1.TRANSFERS
,W1.SUPERVISOR_JOINS
,W1.AVAILABLE_TIME
,W1.RING_TIME
,W1.CONNECT_IM_SESSION_TIME
,W1.CONNECT_PHONE_CALL_TIME
,W1.CONNECT_DID_CALL_TIME
,W1.CONNECT_DOD_CALL_TIME
,W1.NON_CONNECT_CALL_TIME
,W1.ACW_TIME
,W1.RONA_TIME
,W1.UNAVAILABLE_TIME
,W1.OFF_WORK_TIME
,W1.LOGGED_OUT_TIME
,W1.ON_PHONE_TIME
,W1.Q_ON_PHONE_TIME
,W1.TALK_TIME
,W1.Q_TALK_TIME
,W1.HANDLE_TIME
,W1.Q_HANDLE_TIME
,W1.CPROD
,W1.MING
,W1.AUT2
,W1.[EMAIL]
,W1.ID_EXT
,W1.SCHEDULER_ACL_NAME
,W1.STD_TENANT_START_DATE_TIME_KEY
,W1.CAL_DATE
,W1.TENANT_KEY
,W1.AIR_DAY_TYPE
,W1.AIR_ACW_FONT_COLOR
,W1.MIN_GUARANTEE_MINUTES
,W1.MIN_GUARANTEE_TYPE
,W1.AUTHORIZED_TO_INVOICE_TYPE
,W1.HAS_HOLIDAYS
,W1.INCLUDE_IN_CAS
,W1.READY_FOR_XML
,W1.SHOW_ID_EXTS
,W1.INVOICE_ID
,W1.RESOURCE_NAME
,W1.CATS_ID
,W1.PAY_GROUP
-- SELECT *
FROM           WSOL_TB_IMPORTS_MONAT_INVOICING_1    W1
WHERE (
	   AVAILABLE_TIME = 0.00
  AND  RING_TIME = 0.00
  AND  CONNECT_IM_SESSION_TIME = 0.00
  AND  CONNECT_PHONE_CALL_TIME = 0.00
  AND  CONNECT_DID_CALL_TIME = 0.00
  AND  CONNECT_DOD_CALL_TIME = 0.00
  AND  NON_CONNECT_CALL_TIME = 0.00
  AND  ACW_TIME = 0.00
  AND  RONA_TIME = 0.00
  AND  UNAVAILABLE_TIME = 0.00
  AND  OFF_WORK_TIME = 0.00
  AND  LOGGED_OUT_TIME = 0.00
  AND  ON_PHONE_TIME = 0.00
  AND  Q_ON_PHONE_TIME = 0.00
  AND  TALK_TIME = 0.00
  AND  Q_TALK_TIME = 0.00
  AND  HANDLE_TIME = 0.00
  AND  Q_HANDLE_TIME = 0.00
  )

--======================================================================
--DELETE ALL ZERO DURATION RECORDS:
--======================================================================
DELETE FROM WSOL_TB_IMPORTS_MONAT_INVOICING_1
WHERE (
	   AVAILABLE_TIME = 0.00
  AND  RING_TIME = 0.00
  AND  CONNECT_IM_SESSION_TIME = 0.00
  AND  CONNECT_PHONE_CALL_TIME = 0.00
  AND  CONNECT_DID_CALL_TIME = 0.00
  AND  CONNECT_DOD_CALL_TIME = 0.00
  AND  NON_CONNECT_CALL_TIME = 0.00
  AND  ACW_TIME = 0.00
  AND  RONA_TIME = 0.00
  AND  UNAVAILABLE_TIME = 0.00
  AND  OFF_WORK_TIME = 0.00
  AND  LOGGED_OUT_TIME = 0.00
  AND  ON_PHONE_TIME = 0.00
  AND  Q_ON_PHONE_TIME = 0.00
  AND  TALK_TIME = 0.00
  AND  Q_TALK_TIME = 0.00
  AND  HANDLE_TIME = 0.00
  AND  Q_HANDLE_TIME = 0.00
  )
--======================================================================

--===============================================
--HANDLE INVALID DATE/TIME RECORDS:
--===============================================
INSERT INTO WSOL_TB_IMPORTS_MONAT_INVOICING_BAD
(
 BAD_IMPORTS_CODE
,BAD_IMPORTS_FILE_TYPE
,WS_ROW_CREATED_TIME
,FF_AGENT_NAME
,FF_DATE
,FF_TIME
,FF_BUSINESS_UNIT
,FF_TEAM
,FF_GROUPS
,FF_ANSWERED_SESSIONS
,FF_RONAS
,FF_DIDS
,FF_DODS
,FF_STARTED_IMS
,FF_STARTED_CALLS
,FF_ESCALATIONS
,FF_CONSULTS
,FF_TRANSFERS
,FF_SUPERVISOR_JOINS
,FF_AVAILABLE_TIME
,FF_RINGING_TIME1
,FF_CONNECT_IM_SESSION_TIME
,FF_CONNECT_PHONE_CALL_TIME
,FF_CONNECT_DID_CALL_TIME
,FF_CONNECT_DOD_CALL_TIME
,FF_NON_CONNECT_CALL_TIME
,FF_AFTERCALL_TIME
,FF_RONA_TIME
,FF_UNAVAILABLE_TIME
,FF_OFF_WORK_TIME
,FF_LOGGED_OUT_TIME
,FF_ON_PHONE_TIME
,FF_Q_ON_PHONE_TIME
,FF_TALK_TIME
,FF_Q_TALK_TIME
,FF_HANDLE_TIME
,FF_Q_HANDLE_TIME
,FF_OCC_PERCENT
,FF_Q_OCC_PERCENT
,FF_TALK_PERCENT
,FF_Q_TALK_PERCENT
,FF_ACW_PERCENT
,FF_IDLE_PERCENT
,FF_AVG_TALK_TIME_PERCENT
,FF_AVG_Q_TALK_TIME_PERCENT
,FF_AVG_ACW_TIME_PERCENT
,FF_AVG_Q_ACW_TIME_PERCENT
,FF_AVG_HANDLE_TIME_PERCENT
,FF_AVG_Q_HANDLE_TIME_PERCENT
,SEQNO_ADDED_TIME
,SEQNO
,FTP_FILE_NAME
,[DATETIME]
,HOUR_INTERVAL
,AGENT_NAME
,ANSWERED_SESSIONS
,RONA_CNT
,DID_CNT
,DOD_CNT
,STARTED_IMS
,STARTED_CALLS
,ESCALATIONS
,CONSULTS
,TRANSFERS
,SUPERVISOR_JOINS
,AVAILABLE_TIME
,RING_TIME
,CONNECT_IM_SESSION_TIME
,CONNECT_PHONE_CALL_TIME
,CONNECT_DID_CALL_TIME
,CONNECT_DOD_CALL_TIME
,NON_CONNECT_CALL_TIME
,ACW_TIME
,RONA_TIME
,UNAVAILABLE_TIME
,OFF_WORK_TIME
,LOGGED_OUT_TIME
,ON_PHONE_TIME
,Q_ON_PHONE_TIME
,TALK_TIME
,Q_TALK_TIME
,HANDLE_TIME
,Q_HANDLE_TIME
,CPROD
,MING
,AUT2
,[EMAIL]
,ID_EXT
,SCHEDULER_ACL_NAME
,STD_TENANT_START_DATE_TIME_KEY
,CAL_DATE
,TENANT_KEY
,AIR_DAY_TYPE
,AIR_ACW_FONT_COLOR
,MIN_GUARANTEE_MINUTES
,MIN_GUARANTEE_TYPE
,AUTHORIZED_TO_INVOICE_TYPE
,HAS_HOLIDAYS
,INCLUDE_IN_CAS
,READY_FOR_XML
,SHOW_ID_EXTS
,INVOICE_ID
,RESOURCE_NAME
,CATS_ID
,PAY_GROUP
)
SELECT
 'DTM'					--BAD_IMPORTS_CODE		--'Invalid Datetime'
,'ACT'                  --BAD_IMPORTS_FILE_TYPE	--'ACT'IVITY FILE
,@WS_ROW_CREATED_TIME	--WS_ROW_CREATED_TIME
,W1.FF_AGENT_NAME
,W1.FF_DATE
,W1.FF_TIME
,W1.FF_BUSINESS_UNIT
,W1.FF_TEAM
,W1.FF_GROUPS
,W1.FF_ANSWERED_SESSIONS
,W1.FF_RONAS
,W1.FF_DIDS
,W1.FF_DODS
,W1.FF_STARTED_IMS
,W1.FF_STARTED_CALLS
,W1.FF_ESCALATIONS
,W1.FF_CONSULTS
,W1.FF_TRANSFERS
,W1.FF_SUPERVISOR_JOINS
,W1.FF_AVAILABLE_TIME
,W1.FF_RINGING_TIME1
,W1.FF_CONNECT_IM_SESSION_TIME
,W1.FF_CONNECT_PHONE_CALL_TIME
,W1.FF_CONNECT_DID_CALL_TIME
,W1.FF_CONNECT_DOD_CALL_TIME
,W1.FF_NON_CONNECT_CALL_TIME
,W1.FF_AFTERCALL_TIME
,W1.FF_RONA_TIME
,W1.FF_UNAVAILABLE_TIME
,W1.FF_OFF_WORK_TIME
,W1.FF_LOGGED_OUT_TIME
,W1.FF_ON_PHONE_TIME
,W1.FF_Q_ON_PHONE_TIME
,W1.FF_TALK_TIME
,W1.FF_Q_TALK_TIME
,W1.FF_HANDLE_TIME
,W1.FF_Q_HANDLE_TIME
,W1.FF_OCC_PERCENT
,W1.FF_Q_OCC_PERCENT
,W1.FF_TALK_PERCENT
,W1.FF_Q_TALK_PERCENT
,W1.FF_ACW_PERCENT
,W1.FF_IDLE_PERCENT
,W1.FF_AVG_TALK_TIME_PERCENT
,W1.FF_AVG_Q_TALK_TIME_PERCENT
,W1.FF_AVG_ACW_TIME_PERCENT
,W1.FF_AVG_Q_ACW_TIME_PERCENT
,W1.FF_AVG_HANDLE_TIME_PERCENT
,W1.FF_AVG_Q_HANDLE_TIME_PERCENT
,W1.SEQNO_ADDED_TIME
,W1.SEQNO
,W1.FTP_FILE_NAME
,W1.[DATETIME]
,W1.HOUR_INTERVAL
,W1.AGENT_NAME
,W1.ANSWERED_SESSIONS
,W1.RONA_CNT
,W1.DID_CNT
,W1.DOD_CNT
,W1.STARTED_IMS
,W1.STARTED_CALLS
,W1.ESCALATIONS
,W1.CONSULTS
,W1.TRANSFERS
,W1.SUPERVISOR_JOINS
,W1.AVAILABLE_TIME
,W1.RING_TIME
,W1.CONNECT_IM_SESSION_TIME
,W1.CONNECT_PHONE_CALL_TIME
,W1.CONNECT_DID_CALL_TIME
,W1.CONNECT_DOD_CALL_TIME
,W1.NON_CONNECT_CALL_TIME
,W1.ACW_TIME
,W1.RONA_TIME
,W1.UNAVAILABLE_TIME
,W1.OFF_WORK_TIME
,W1.LOGGED_OUT_TIME
,W1.ON_PHONE_TIME
,W1.Q_ON_PHONE_TIME
,W1.TALK_TIME
,W1.Q_TALK_TIME
,W1.HANDLE_TIME
,W1.Q_HANDLE_TIME
,W1.CPROD
,W1.MING
,W1.AUT2
,W1.[EMAIL]
,W1.ID_EXT
,W1.SCHEDULER_ACL_NAME
,W1.STD_TENANT_START_DATE_TIME_KEY
,W1.CAL_DATE
,W1.TENANT_KEY
,W1.AIR_DAY_TYPE
,W1.AIR_ACW_FONT_COLOR
,W1.MIN_GUARANTEE_MINUTES
,W1.MIN_GUARANTEE_TYPE
,W1.AUTHORIZED_TO_INVOICE_TYPE
,W1.HAS_HOLIDAYS
,W1.INCLUDE_IN_CAS
,W1.READY_FOR_XML
,W1.SHOW_ID_EXTS
,W1.INVOICE_ID
,W1.RESOURCE_NAME
,W1.CATS_ID
,W1.PAY_GROUP
FROM           WSOL_TB_IMPORTS_MONAT_INVOICING_1    W1
WHERE  ISNULL(W1.STD_TENANT_START_DATE_TIME_KEY,0) = 0

--======================================================================
--DELETE INVALID DATE/TIME RECORDS;
--======================================================================
DELETE FROM WSOL_TB_IMPORTS_MONAT_INVOICING_1
WHERE ISNULL(STD_TENANT_START_DATE_TIME_KEY,0) = 0
--======================================================================

--======================================================================
--REMOVE RECORDS OUTSIDE OF WORK HOURS																<<<<----- MAY NEED TO UPDATE
--======================================================================

--======================================================================
--DELETE RECORDS OUTSIDE OF WORK HOURS																<<<<----- MAY NEED TO UPDATE
--======================================================================

--===========================================================================================================
--HANDLE DUPLICATES:
--===========================================================================================================
INSERT INTO WSOL_TB_IMPORTS_MONAT_INVOICING_BAD
(
 BAD_IMPORTS_CODE
,BAD_IMPORTS_FILE_TYPE
,WS_ROW_CREATED_TIME
,FF_AGENT_NAME
,FF_DATE
,FF_TIME
,FF_BUSINESS_UNIT
,FF_TEAM
,FF_GROUPS
,FF_ANSWERED_SESSIONS
,FF_RONAS
,FF_DIDS
,FF_DODS
,FF_STARTED_IMS
,FF_STARTED_CALLS
,FF_ESCALATIONS
,FF_CONSULTS
,FF_TRANSFERS
,FF_SUPERVISOR_JOINS
,FF_AVAILABLE_TIME
,FF_RINGING_TIME1
,FF_CONNECT_IM_SESSION_TIME
,FF_CONNECT_PHONE_CALL_TIME
,FF_CONNECT_DID_CALL_TIME
,FF_CONNECT_DOD_CALL_TIME
,FF_NON_CONNECT_CALL_TIME
,FF_AFTERCALL_TIME
,FF_RONA_TIME
,FF_UNAVAILABLE_TIME
,FF_OFF_WORK_TIME
,FF_LOGGED_OUT_TIME
,FF_ON_PHONE_TIME
,FF_Q_ON_PHONE_TIME
,FF_TALK_TIME
,FF_Q_TALK_TIME
,FF_HANDLE_TIME
,FF_Q_HANDLE_TIME
,FF_OCC_PERCENT
,FF_Q_OCC_PERCENT
,FF_TALK_PERCENT
,FF_Q_TALK_PERCENT
,FF_ACW_PERCENT
,FF_IDLE_PERCENT
,FF_AVG_TALK_TIME_PERCENT
,FF_AVG_Q_TALK_TIME_PERCENT
,FF_AVG_ACW_TIME_PERCENT
,FF_AVG_Q_ACW_TIME_PERCENT
,FF_AVG_HANDLE_TIME_PERCENT
,FF_AVG_Q_HANDLE_TIME_PERCENT
,SEQNO_ADDED_TIME
,SEQNO
,FTP_FILE_NAME
,[DATETIME]
,HOUR_INTERVAL
,AGENT_NAME
,ANSWERED_SESSIONS
,RONA_CNT
,DID_CNT
,DOD_CNT
,STARTED_IMS
,STARTED_CALLS
,ESCALATIONS
,CONSULTS
,TRANSFERS
,SUPERVISOR_JOINS
,AVAILABLE_TIME
,RING_TIME
,CONNECT_IM_SESSION_TIME
,CONNECT_PHONE_CALL_TIME
,CONNECT_DID_CALL_TIME
,CONNECT_DOD_CALL_TIME
,NON_CONNECT_CALL_TIME
,ACW_TIME
,RONA_TIME
,UNAVAILABLE_TIME
,OFF_WORK_TIME
,LOGGED_OUT_TIME
,ON_PHONE_TIME
,Q_ON_PHONE_TIME
,TALK_TIME
,Q_TALK_TIME
,HANDLE_TIME
,Q_HANDLE_TIME
,CPROD
,MING
,AUT2
,[EMAIL]
,ID_EXT
,SCHEDULER_ACL_NAME
,STD_TENANT_START_DATE_TIME_KEY
,CAL_DATE
,TENANT_KEY
,AIR_DAY_TYPE
,AIR_ACW_FONT_COLOR
,MIN_GUARANTEE_MINUTES
,MIN_GUARANTEE_TYPE
,AUTHORIZED_TO_INVOICE_TYPE
,HAS_HOLIDAYS
,INCLUDE_IN_CAS
,READY_FOR_XML
,SHOW_ID_EXTS
,INVOICE_ID
,RESOURCE_NAME
,CATS_ID
,PAY_GROUP
)
SELECT
 'DUP'					--BAD_IMPORTS_CODE		--'DUPLICATE'
,'ACT'                  --BAD_IMPORTS_FILE_TYPE --'ACT'IVITY FILE
,@WS_ROW_CREATED_TIME	--WS_ROW_CREATED_TIME
,W1.FF_AGENT_NAME
,W1.FF_DATE
,W1.FF_TIME
,W1.FF_BUSINESS_UNIT
,W1.FF_TEAM
,W1.FF_GROUPS
,W1.FF_ANSWERED_SESSIONS
,W1.FF_RONAS
,W1.FF_DIDS
,W1.FF_DODS
,W1.FF_STARTED_IMS
,W1.FF_STARTED_CALLS
,W1.FF_ESCALATIONS
,W1.FF_CONSULTS
,W1.FF_TRANSFERS
,W1.FF_SUPERVISOR_JOINS
,W1.FF_AVAILABLE_TIME
,W1.FF_RINGING_TIME1
,W1.FF_CONNECT_IM_SESSION_TIME
,W1.FF_CONNECT_PHONE_CALL_TIME
,W1.FF_CONNECT_DID_CALL_TIME
,W1.FF_CONNECT_DOD_CALL_TIME
,W1.FF_NON_CONNECT_CALL_TIME
,W1.FF_AFTERCALL_TIME
,W1.FF_RONA_TIME
,W1.FF_UNAVAILABLE_TIME
,W1.FF_OFF_WORK_TIME
,W1.FF_LOGGED_OUT_TIME
,W1.FF_ON_PHONE_TIME
,W1.FF_Q_ON_PHONE_TIME
,W1.FF_TALK_TIME
,W1.FF_Q_TALK_TIME
,W1.FF_HANDLE_TIME
,W1.FF_Q_HANDLE_TIME
,W1.FF_OCC_PERCENT
,W1.FF_Q_OCC_PERCENT
,W1.FF_TALK_PERCENT
,W1.FF_Q_TALK_PERCENT
,W1.FF_ACW_PERCENT
,W1.FF_IDLE_PERCENT
,W1.FF_AVG_TALK_TIME_PERCENT
,W1.FF_AVG_Q_TALK_TIME_PERCENT
,W1.FF_AVG_ACW_TIME_PERCENT
,W1.FF_AVG_Q_ACW_TIME_PERCENT
,W1.FF_AVG_HANDLE_TIME_PERCENT
,W1.FF_AVG_Q_HANDLE_TIME_PERCENT
,W1.SEQNO_ADDED_TIME
,W1.SEQNO
,W1.FTP_FILE_NAME
,W1.[DATETIME]
,W1.HOUR_INTERVAL
,W1.AGENT_NAME
,W1.ANSWERED_SESSIONS
,W1.RONA_CNT
,W1.DID_CNT
,W1.DOD_CNT
,W1.STARTED_IMS
,W1.STARTED_CALLS
,W1.ESCALATIONS
,W1.CONSULTS
,W1.TRANSFERS
,W1.SUPERVISOR_JOINS
,W1.AVAILABLE_TIME
,W1.RING_TIME
,W1.CONNECT_IM_SESSION_TIME
,W1.CONNECT_PHONE_CALL_TIME
,W1.CONNECT_DID_CALL_TIME
,W1.CONNECT_DOD_CALL_TIME
,W1.NON_CONNECT_CALL_TIME
,W1.ACW_TIME
,W1.RONA_TIME
,W1.UNAVAILABLE_TIME
,W1.OFF_WORK_TIME
,W1.LOGGED_OUT_TIME
,W1.ON_PHONE_TIME
,W1.Q_ON_PHONE_TIME
,W1.TALK_TIME
,W1.Q_TALK_TIME
,W1.HANDLE_TIME
,W1.Q_HANDLE_TIME
,W1.CPROD
,W1.MING
,W1.AUT2
,W1.[EMAIL]
,W1.ID_EXT
,W1.SCHEDULER_ACL_NAME
,W1.STD_TENANT_START_DATE_TIME_KEY
,W1.CAL_DATE
,W1.TENANT_KEY
,W1.AIR_DAY_TYPE
,W1.AIR_ACW_FONT_COLOR
,W1.MIN_GUARANTEE_MINUTES
,W1.MIN_GUARANTEE_TYPE
,W1.AUTHORIZED_TO_INVOICE_TYPE
,W1.HAS_HOLIDAYS
,W1.INCLUDE_IN_CAS
,W1.READY_FOR_XML
,W1.SHOW_ID_EXTS
,W1.INVOICE_ID
,W1.RESOURCE_NAME
,W1.CATS_ID
,W1.PAY_GROUP

FROM
(	SELECT
	 [DATETIME]
	,FF_AGENT_NAME
	,FF_BUSINESS_UNIT
	,FF_TEAM
	,FF_GROUPS
	,ROW_NUMBER() over (partition by [DATETIME], FF_AGENT_NAME, FF_BUSINESS_UNIT, FF_TEAM, FF_GROUPS
                            order by [DATETIME], FF_AGENT_NAME, FF_BUSINESS_UNIT, FF_TEAM, FF_GROUPS, HANDLE_TIME DESC) ROWNO
	FROM WSOL_TB_IMPORTS_MONAT_INVOICING_1
) TNM
LEFT JOIN      WSOL_TB_IMPORTS_MONAT_INVOICING_1	W1   ON W1.[DATETIME]		= TNM.[DATETIME]
														AND W1.FF_AGENT_NAME	= TNM.FF_AGENT_NAME
														AND W1.FF_BUSINESS_UNIT	= TNM.FF_BUSINESS_UNIT
														AND W1.FF_TEAM			= TNM.FF_TEAM
														AND W1.FF_GROUPS		= TNM.FF_GROUPS
WHERE TNM.ROWNO > 1

--===========================================================================================================
--DELETE DUPLICATES:
--===========================================================================================================
DELETE FROM TNM
FROM
(	SELECT
	 [DATETIME]
	,FF_AGENT_NAME
	,FF_BUSINESS_UNIT
	,FF_TEAM
	,FF_GROUPS
	,ROW_NUMBER() over (partition by [DATETIME], FF_AGENT_NAME, FF_BUSINESS_UNIT, FF_TEAM, FF_GROUPS
                            order by [DATETIME], FF_AGENT_NAME, FF_BUSINESS_UNIT, FF_TEAM, FF_GROUPS, HANDLE_TIME DESC) ROWNO
	FROM WSOL_TB_IMPORTS_MONAT_INVOICING_1
) TNM
WHERE TNM.ROWNO > 1
--===========================================================================================================

-- SELECT * FROM WSOL_TB_IMPORTS_MONAT_INVOICING_1 ORDER BY SEQNO
--===========================================================================================================
--UPDATE FIELDS FROM MAPPING DATA AND ADDITIONAL INVOICE FIELDS
--===========================================================================================================
UPDATE WSOL_TB_IMPORTS_MONAT_INVOICING_1 SET
  EMAIL			= ISNULL(IAM.EMAIL,'')
 ,ID_EXT		= CASE WHEN IAM.INVOICE_GROUP = 'RES' THEN 'MRA'
					   WHEN IAM.INVOICE_GROUP = 'FC'  THEN 'MFC'
					   WHEN IAM.INVOICE_GROUP = ''	  THEN 'MSA'
					   ELSE '' END
 ,PAY_GROUP		= ISNULL(IAM.PAY_GROUP,0)
 ,RESOURCE_NAME	= ISNULL(IAM.RESOURCE_NAME,'')
 FROM            WSOL_TB_IMPORTS_MONAT_INVOICING_1			I
 LEFT JOIN       WSOL_TB_IMPORTS_MONAT_AIA_AGENT_MAPPING	IAM  ON IAM.INVOICE_MAP_KEY = I.FF_AGENT_NAME

--SELECT * FROM WSOL_TB_IMPORTS_MONAT_AIA_AGENT_MAPPING

--=================================================================================================
--UPDATE FOR WEEKEND RATES
--=================================================================================================
SET DATEFIRST 1  -- = Monday  

UPDATE WSOL_TB_IMPORTS_MONAT_INVOICING_1 SET
 ID_EXT = CASE WHEN (ID_EXT IN ('MFC','MSA') AND DATEPART(dw, [DATETIME]) IN (6, 7)) THEN
				CASE WHEN ID_EXT = 'MFC' THEN 'MFW'
				     WHEN ID_EXT = 'MSA' THEN 'MSW'
					 ELSE ID_EXT
				END
			   ELSE ID_EXT
		  END

--SELECT DISTINCT(ID_EXT) FROM WSOL_TB_IMPORTS_MONAT_INVOICING_1

--===================================================================================================================================================
--SET ADDITIONAL INVOICE FIELDS
--===================================================================================================================================================
UPDATE WSOL_TB_IMPORTS_MONAT_INVOICING_1 SET	-- SELECT
  AIR_DAY_TYPE = CASE WHEN IG.HAS_HOLIDAYS = 'Y' AND
						 (    ISNULL(IH.HOLIDAY_DATE,'1/1/1900') > CAST('1/1/1901' AS DATETIME) OR
						   ( ISNULL(IHA.HOLIDAY_DATE,'1/1/1900') > CAST('1/1/1901' AS DATETIME) AND ISNULL(IHA.ID_EXT,'') <> '' )
						 )
					  THEN 'H' ELSE 'S' END  --AS AIR_DAY_TYPE  --H=Holiday  --S=Standard
 FROM            WSOL_TB_IMPORTS_MONAT_INVOICING_1				I
 INNER JOIN      DATE_TIME										DT	ON DT.DATE_TIME_KEY       = I.STD_TENANT_START_DATE_TIME_KEY
 LEFT JOIN       WSOL_TB_IMPORTS_MONAT_SD_INVOICE_GROUPS		IG	ON IG.ID_EXT              = I.ID_EXT
 LEFT JOIN       WSOL_TB_IMPORTS_MONAT_SD_INVOICE_HOLIDAYS		IH	ON IH.HOLIDAY_DATE        = CAST(DT.CAL_DATE_STRING AS DATETIME)
 LEFT JOIN       WSOL_TB_IMPORTS_MONAT_SD_INVOICE_HOLIDAYS_ADDL	IHA ON IHA.HOLIDAY_DATE       = CAST(DT.CAL_DATE_STRING AS DATETIME)
																   AND IHA.ID_EXT             = I.ID_EXT

UPDATE WSOL_TB_IMPORTS_MONAT_INVOICING_1 SET
  AIR_ACW_FONT_COLOR             = 'Black'
 ,MIN_GUARANTEE_MINUTES          = ISNULL(IG.MIN_GUARANTEE_MINUTES,0)        --varies between scheduler acl names.
 ,MIN_GUARANTEE_TYPE             = ISNULL(IG.MIN_GUARANTEE_TYPE,'')          --varies between scheduler acl names.
 ,AUTHORIZED_TO_INVOICE_TYPE     = ISNULL(IG.AUTHORIZED_TO_INVOICE_TYPE,'')  --varies between scheduler acl names.

 ,HAS_HOLIDAYS    = IG.HAS_HOLIDAYS
 ,INCLUDE_IN_CAS  = IG.INCLUDE_IN_CAS
 ,READY_FOR_XML   = IG.READY_FOR_XML
 ,SHOW_ID_EXTS    = IG.SHOW_ID_EXTS
 FROM            WSOL_TB_IMPORTS_MONAT_INVOICING_1			I
 LEFT JOIN       WSOL_TB_IMPORTS_MONAT_SD_INVOICE_GROUPS	IG  ON IG.ID_EXT    = I.ID_EXT
												


UPDATE WSOL_TB_IMPORTS_MONAT_INVOICING_1 SET
   INVOICE_ID         = CASE WHEN AIA.AIR_DAY_TYPE = 'H' THEN AIASD.HOLIDAY_INVOICE_ID ELSE AIASD.INVOICE_SYSTEM_ID END
  ,SCHEDULER_ACL_NAME = CASE WHEN AIA.AIR_DAY_TYPE = 'H' THEN AIASD.HOLIDAY_INVOICE_ID ELSE AIASD.INVOICE_SYSTEM_ID END
 FROM            WSOL_TB_IMPORTS_MONAT_INVOICING_1				AIA 
 LEFT JOIN       WSOL_TB_IMPORTS_MONAT_SD_AIA_STATIC_DEFAULTS	AIASD ON AIASD.ACD_ID_EXTENSION = AIA.ID_EXT


--======================================================================
--CHECK FOR BAD DATA FOUND IN IMPORT .CSV FILES:
--======================================================================
--SELECT * FROM WSOL_TB_IMPORT_ERRORS_FOUND WHERE TENANT_KEY = 160
--======================================================================
DECLARE
 @ERR_CNT  INT
,@RCD_CNT  INT
,@MSG1     VARCHAR(2500)
SET @ERR_CNT  = 0 
SET @RCD_CNT  = 0 
SET @MSG1     = ''
--Check #1:  ===================================================================================================
	SET @RCD_CNT = (SELECT COUNT(*) FROM WSOL_TB_IMPORTS_MONAT_INVOICING_1)
	IF @RCD_CNT < 1 BEGIN
		SET @MSG1 = @MSG1 + 'ERROR!  File Import Failed.  No Records Were/Could Be Imported.   |   ' 
		SET @ERR_CNT = @ERR_CNT + 1
	END

--=============================== INSERT INTO PERMANENT TABLE (No errors) OR SKIP AND GO TO END (Errors):
IF @ERR_CNT > 0 BEGIN
INSERT INTO WSOL_TB_IMPORT_ERRORS_FOUND
(
 TENANT_KEY
,SUB_GROUP_NAME
,ERROR_MSG)
	SELECT 
	 @TENANT_KEY		--TENANT_KEY
	,'MONAT_INVOICING'	--SUB_GROUP_NAME
	,@MSG1				--ERROR_MSG
	--===========================
	GOTO EARLY_EXIT
	--===========================
END
ELSE BEGIN
	--MUST RETURN AT LEAST ONE RECORD TO SSIS
INSERT INTO WSOL_TB_IMPORT_ERRORS_FOUND
(TENANT_KEY
,SUB_GROUP_NAME
,ERROR_MSG)
	SELECT 
	 @TENANT_KEY		--TENANT_KEY
	,'MONAT_INVOICING'	--SUB_GROUP_NAME
	,''					--ERROR_MSG
END

--===============================================
-- CALCULATE PAYMENT VALUES
--===============================================
-- SELECT * FROM WSOL_TB_IMPORTS_MONAT_INVOICING_1
UPDATE WSOL_TB_IMPORTS_MONAT_INVOICING_1 SET
 CPROD = AVAILABLE_TIME + RING_TIME + CONNECT_PHONE_CALL_TIME + ACW_TIME

UPDATE WSOL_TB_IMPORTS_MONAT_INVOICING_1 SET
 MING	= CASE WHEN CPROD > 3600.00 THEN 3600.00 ELSE CPROD END
,AUT2	= CASE WHEN CPROD > 3600.00 THEN 3600.00 ELSE CPROD END	

--===============================================
SET DATEFIRST 1  -- = Monday  
--===============================================
DECLARE 
 @DTM_BEG  DATETIME
,@DTM_END  DATETIME
,@DTM_MAX  DATETIME

SET @DTM_BEG = DATEADD(hh,-2,(SELECT MIN([DATETIME]) FROM WSOL_TB_IMPORTS_MONAT_INVOICING_1))
SET @DTM_END = DATEADD(hh, 2,(SELECT MAX([DATETIME]) FROM WSOL_TB_IMPORTS_MONAT_INVOICING_1))
SET @DTM_MAX = DATEADD(hh, 0,(SELECT MAX([DATETIME]) FROM WSOL_TB_IMPORTS_MONAT_INVOICING_1))

--SELECT * FROM WSOL_TB_IMPORTS_MONAT_INVOICING
--=============================================
--UPDATE PERMANENT INVOICE TABLE
--=============================================
UPDATE WSOL_TB_IMPORTS_MONAT_INVOICING SET
-- FF_AGENT_NAME					= W1.FF_AGENT_NAME
 FF_DATE							= W1.FF_DATE
,FF_TIME							= W1.FF_TIME
,FF_BUSINESS_UNIT					= W1.FF_BUSINESS_UNIT
,FF_TEAM							= W1.FF_TEAM
,FF_GROUPS							= W1.FF_GROUPS
,FF_ANSWERED_SESSIONS				= W1.FF_ANSWERED_SESSIONS
,FF_RONAS							= W1.FF_RONAS
,FF_DIDS							= W1.FF_DIDS
,FF_DODS							= W1.FF_DODS
,FF_STARTED_IMS						= W1.FF_STARTED_IMS
,FF_STARTED_CALLS					= W1.FF_STARTED_CALLS
,FF_ESCALATIONS						= W1.FF_ESCALATIONS
,FF_CONSULTS						= W1.FF_CONSULTS
,FF_TRANSFERS						= W1.FF_TRANSFERS
,FF_SUPERVISOR_JOINS				= W1.FF_SUPERVISOR_JOINS
,FF_AVAILABLE_TIME					= W1.FF_AVAILABLE_TIME
,FF_RINGING_TIME1					= W1.FF_RINGING_TIME1
,FF_CONNECT_IM_SESSION_TIME			= W1.FF_CONNECT_IM_SESSION_TIME
,FF_CONNECT_PHONE_CALL_TIME			= W1.FF_CONNECT_PHONE_CALL_TIME
,FF_CONNECT_DID_CALL_TIME			= W1.FF_CONNECT_DID_CALL_TIME
,FF_CONNECT_DOD_CALL_TIME			= W1.FF_CONNECT_DOD_CALL_TIME
,FF_NON_CONNECT_CALL_TIME			= W1.FF_NON_CONNECT_CALL_TIME
,FF_AFTERCALL_TIME					= W1.FF_AFTERCALL_TIME
,FF_RONA_TIME						= W1.FF_RONA_TIME
,FF_UNAVAILABLE_TIME				= W1.FF_UNAVAILABLE_TIME
,FF_OFF_WORK_TIME					= W1.FF_OFF_WORK_TIME
,FF_LOGGED_OUT_TIME					= W1.FF_LOGGED_OUT_TIME
,FF_ON_PHONE_TIME					= W1.FF_ON_PHONE_TIME
,FF_Q_ON_PHONE_TIME					= W1.FF_Q_ON_PHONE_TIME
,FF_TALK_TIME						= W1.FF_TALK_TIME
,FF_Q_TALK_TIME						= W1.FF_Q_TALK_TIME
,FF_HANDLE_TIME						= W1.FF_HANDLE_TIME
,FF_Q_HANDLE_TIME					= W1.FF_Q_HANDLE_TIME
,FF_OCC_PERCENT						= W1.FF_OCC_PERCENT
,FF_Q_OCC_PERCENT					= W1.FF_Q_OCC_PERCENT
,FF_TALK_PERCENT					= W1.FF_TALK_PERCENT
,FF_Q_TALK_PERCENT					= W1.FF_Q_TALK_PERCENT
,FF_ACW_PERCENT						= W1.FF_ACW_PERCENT
,FF_IDLE_PERCENT					= W1.FF_IDLE_PERCENT
,FF_AVG_TALK_TIME_PERCENT			= W1.FF_AVG_TALK_TIME_PERCENT
,FF_AVG_Q_TALK_TIME_PERCENT			= W1.FF_AVG_Q_TALK_TIME_PERCENT
,FF_AVG_ACW_TIME_PERCENT			= W1.FF_AVG_ACW_TIME_PERCENT
,FF_AVG_Q_ACW_TIME_PERCENT			= W1.FF_AVG_Q_ACW_TIME_PERCENT
,FF_AVG_HANDLE_TIME_PERCENT			= W1.FF_AVG_HANDLE_TIME_PERCENT
,FF_AVG_Q_HANDLE_TIME_PERCENT		= W1.FF_AVG_Q_HANDLE_TIME_PERCENT

,SEQNO_ADDED_TIME					= W1.SEQNO_ADDED_TIME
,SEQNO								= W1.SEQNO
,FTP_FILE_NAME						= W1.FTP_FILE_NAME

,[DATETIME]							= W1.[DATETIME]
,HOUR_INTERVAL						= W1.HOUR_INTERVAL
,AGENT_NAME							= W1.AGENT_NAME
,ANSWERED_SESSIONS					= W1.ANSWERED_SESSIONS
,RONA_CNT							= W1.RONA_CNT
,DID_CNT							= W1.DID_CNT
,DOD_CNT							= W1.DOD_CNT
,STARTED_IMS						= W1.STARTED_IMS
,STARTED_CALLS						= W1.STARTED_CALLS
,ESCALATIONS						= W1.ESCALATIONS
,CONSULTS							= W1.CONSULTS
,TRANSFERS							= W1.TRANSFERS
,SUPERVISOR_JOINS					= W1.SUPERVISOR_JOINS
,AVAILABLE_TIME						= W1.AVAILABLE_TIME
,RING_TIME							= W1.RING_TIME
,CONNECT_IM_SESSION_TIME			= W1.CONNECT_IM_SESSION_TIME
,CONNECT_PHONE_CALL_TIME			= W1.CONNECT_PHONE_CALL_TIME
,CONNECT_DID_CALL_TIME				= W1.CONNECT_DID_CALL_TIME
,CONNECT_DOD_CALL_TIME				= W1.CONNECT_DOD_CALL_TIME
,NON_CONNECT_CALL_TIME				= W1.NON_CONNECT_CALL_TIME
,ACW_TIME							= W1.ACW_TIME
,RONA_TIME							= W1.RONA_TIME
,UNAVAILABLE_TIME					= W1.UNAVAILABLE_TIME
,OFF_WORK_TIME						= W1.OFF_WORK_TIME
,LOGGED_OUT_TIME					= W1.LOGGED_OUT_TIME
,ON_PHONE_TIME						= W1.ON_PHONE_TIME
,Q_ON_PHONE_TIME					= W1.Q_ON_PHONE_TIME
,TALK_TIME							= W1.TALK_TIME
,Q_TALK_TIME						= W1.Q_TALK_TIME
,HANDLE_TIME						= W1.HANDLE_TIME
,Q_HANDLE_TIME						= W1.Q_HANDLE_TIME

,CPROD								= W1.CPROD
,MING								= W1.MING
,AUT2								= W1.AUT2

,[EMAIL]							= W1.EMAIL
--,ID_EXT							= W1.ID_EXT
,SCHEDULER_ACL_NAME					= W1.SCHEDULER_ACL_NAME
--,STD_TENANT_START_DATE_TIME_KEY	= W1.STD_TENANT_START_DATE_TIME_KEY
,CAL_DATE							= W1.CAL_DATE
,TENANT_KEY							= W1.TENANT_KEY
,AIR_DAY_TYPE						= W1.AIR_DAY_TYPE
,AIR_ACW_FONT_COLOR					= W1.AIR_ACW_FONT_COLOR
,MIN_GUARANTEE_MINUTES				= W1.MIN_GUARANTEE_MINUTES
,MIN_GUARANTEE_TYPE					= W1.MIN_GUARANTEE_TYPE
,AUTHORIZED_TO_INVOICE_TYPE			= W1.AUTHORIZED_TO_INVOICE_TYPE
,HAS_HOLIDAYS						= W1.HAS_HOLIDAYS
,INCLUDE_IN_CAS						= W1.INCLUDE_IN_CAS
,READY_FOR_XML						= W1.READY_FOR_XML
,SHOW_ID_EXTS						= W1.SHOW_ID_EXTS
--,INVOICE_ID						= W1.INVOICE_ID
,RESOURCE_NAME						= W1.RESOURCE_NAME
,CATS_ID							= W1.CATS_ID
,PAY_GROUP							= W1.PAY_GROUP

--,WS_ROW_CREATED_TIME				= NULL
,WS_ROW_UPDATED_TIME				= @WS_ROW_CREATED_TIME

--  SELECT *
FROM            WSOL_TB_IMPORTS_MONAT_INVOICING_1  W1
INNER JOIN      WSOL_TB_IMPORTS_MONAT_INVOICING    G   ON G.STD_TENANT_START_DATE_TIME_KEY = W1.STD_TENANT_START_DATE_TIME_KEY
													  AND G.ID_EXT                         = W1.ID_EXT
													  AND G.FF_AGENT_NAME				   = W1.FF_AGENT_NAME
													  AND G.INVOICE_ID					   = W1.INVOICE_ID

----Where Permanent table key fields match Work table key fields - then we want to update non-key fields!!!:
WHERE G.STD_TENANT_START_DATE_TIME_KEY	= W1.STD_TENANT_START_DATE_TIME_KEY
  AND G.ID_EXT							= W1.ID_EXT
  AND G.FF_AGENT_NAME					= W1.FF_AGENT_NAME
  AND G.INVOICE_ID						= W1.INVOICE_ID

--=============================================
--INSERT INTO PERMANENT IMPORT TABLE:
--=============================================
INSERT INTO WSOL_TB_IMPORTS_MONAT_INVOICING
(FF_AGENT_NAME
,FF_DATE
,FF_TIME
,FF_BUSINESS_UNIT
,FF_TEAM
,FF_GROUPS
,FF_ANSWERED_SESSIONS
,FF_RONAS
,FF_DIDS
,FF_DODS
,FF_STARTED_IMS
,FF_STARTED_CALLS
,FF_ESCALATIONS
,FF_CONSULTS
,FF_TRANSFERS
,FF_SUPERVISOR_JOINS
,FF_AVAILABLE_TIME
,FF_RINGING_TIME1
,FF_CONNECT_IM_SESSION_TIME
,FF_CONNECT_PHONE_CALL_TIME
,FF_CONNECT_DID_CALL_TIME
,FF_CONNECT_DOD_CALL_TIME
,FF_NON_CONNECT_CALL_TIME
,FF_AFTERCALL_TIME
,FF_RONA_TIME
,FF_UNAVAILABLE_TIME
,FF_OFF_WORK_TIME
,FF_LOGGED_OUT_TIME
,FF_ON_PHONE_TIME
,FF_Q_ON_PHONE_TIME
,FF_TALK_TIME
,FF_Q_TALK_TIME
,FF_HANDLE_TIME
,FF_Q_HANDLE_TIME
,FF_OCC_PERCENT
,FF_Q_OCC_PERCENT
,FF_TALK_PERCENT
,FF_Q_TALK_PERCENT
,FF_ACW_PERCENT
,FF_IDLE_PERCENT
,FF_AVG_TALK_TIME_PERCENT
,FF_AVG_Q_TALK_TIME_PERCENT
,FF_AVG_ACW_TIME_PERCENT
,FF_AVG_Q_ACW_TIME_PERCENT
,FF_AVG_HANDLE_TIME_PERCENT
,FF_AVG_Q_HANDLE_TIME_PERCENT
,SEQNO_ADDED_TIME
,SEQNO
,FTP_FILE_NAME
,[DATETIME]
,HOUR_INTERVAL
,AGENT_NAME
,ANSWERED_SESSIONS
,RONA_CNT
,DID_CNT
,DOD_CNT
,STARTED_IMS
,STARTED_CALLS
,ESCALATIONS
,CONSULTS
,TRANSFERS
,SUPERVISOR_JOINS
,AVAILABLE_TIME
,RING_TIME
,CONNECT_IM_SESSION_TIME
,CONNECT_PHONE_CALL_TIME
,CONNECT_DID_CALL_TIME
,CONNECT_DOD_CALL_TIME
,NON_CONNECT_CALL_TIME
,ACW_TIME
,RONA_TIME
,UNAVAILABLE_TIME
,OFF_WORK_TIME
,LOGGED_OUT_TIME
,ON_PHONE_TIME
,Q_ON_PHONE_TIME
,TALK_TIME
,Q_TALK_TIME
,HANDLE_TIME
,Q_HANDLE_TIME
,CPROD
,MING
,AUT2
,[EMAIL]
,ID_EXT
,SCHEDULER_ACL_NAME
,STD_TENANT_START_DATE_TIME_KEY
,CAL_DATE
,TENANT_KEY
,AIR_DAY_TYPE
,AIR_ACW_FONT_COLOR
,MIN_GUARANTEE_MINUTES
,MIN_GUARANTEE_TYPE
,AUTHORIZED_TO_INVOICE_TYPE
,HAS_HOLIDAYS
,INCLUDE_IN_CAS
,READY_FOR_XML
,SHOW_ID_EXTS
,INVOICE_ID
,RESOURCE_NAME
,CATS_ID
,PAY_GROUP
,WS_ROW_CREATED_TIME
,WS_ROW_UPDATED_TIME
)
SELECT
 W1.FF_AGENT_NAME
,W1.FF_DATE
,W1.FF_TIME
,W1.FF_BUSINESS_UNIT
,W1.FF_TEAM
,W1.FF_GROUPS
,W1.FF_ANSWERED_SESSIONS
,W1.FF_RONAS
,W1.FF_DIDS
,W1.FF_DODS
,W1.FF_STARTED_IMS
,W1.FF_STARTED_CALLS
,W1.FF_ESCALATIONS
,W1.FF_CONSULTS
,W1.FF_TRANSFERS
,W1.FF_SUPERVISOR_JOINS
,W1.FF_AVAILABLE_TIME
,W1.FF_RINGING_TIME1
,W1.FF_CONNECT_IM_SESSION_TIME
,W1.FF_CONNECT_PHONE_CALL_TIME
,W1.FF_CONNECT_DID_CALL_TIME
,W1.FF_CONNECT_DOD_CALL_TIME
,W1.FF_NON_CONNECT_CALL_TIME
,W1.FF_AFTERCALL_TIME
,W1.FF_RONA_TIME
,W1.FF_UNAVAILABLE_TIME
,W1.FF_OFF_WORK_TIME
,W1.FF_LOGGED_OUT_TIME
,W1.FF_ON_PHONE_TIME
,W1.FF_Q_ON_PHONE_TIME
,W1.FF_TALK_TIME
,W1.FF_Q_TALK_TIME
,W1.FF_HANDLE_TIME
,W1.FF_Q_HANDLE_TIME
,W1.FF_OCC_PERCENT
,W1.FF_Q_OCC_PERCENT
,W1.FF_TALK_PERCENT
,W1.FF_Q_TALK_PERCENT
,W1.FF_ACW_PERCENT
,W1.FF_IDLE_PERCENT
,W1.FF_AVG_TALK_TIME_PERCENT
,W1.FF_AVG_Q_TALK_TIME_PERCENT
,W1.FF_AVG_ACW_TIME_PERCENT
,W1.FF_AVG_Q_ACW_TIME_PERCENT
,W1.FF_AVG_HANDLE_TIME_PERCENT
,W1.FF_AVG_Q_HANDLE_TIME_PERCENT

,W1.SEQNO_ADDED_TIME
,W1.SEQNO
,W1.FTP_FILE_NAME

,W1.[DATETIME]
,W1.HOUR_INTERVAL
,W1.AGENT_NAME
,W1.ANSWERED_SESSIONS
,W1.RONA_CNT
,W1.DID_CNT
,W1.DOD_CNT
,W1.STARTED_IMS
,W1.STARTED_CALLS
,W1.ESCALATIONS
,W1.CONSULTS
,W1.TRANSFERS
,W1.SUPERVISOR_JOINS
,W1.AVAILABLE_TIME
,W1.RING_TIME
,W1.CONNECT_IM_SESSION_TIME
,W1.CONNECT_PHONE_CALL_TIME
,W1.CONNECT_DID_CALL_TIME
,W1.CONNECT_DOD_CALL_TIME
,W1.NON_CONNECT_CALL_TIME
,W1.ACW_TIME
,W1.RONA_TIME
,W1.UNAVAILABLE_TIME
,W1.OFF_WORK_TIME
,W1.LOGGED_OUT_TIME
,W1.ON_PHONE_TIME
,W1.Q_ON_PHONE_TIME
,W1.TALK_TIME
,W1.Q_TALK_TIME
,W1.HANDLE_TIME
,W1.Q_HANDLE_TIME
,W1.CPROD
,W1.MING
,W1.AUT2
,W1.[EMAIL]
,W1.ID_EXT
,W1.SCHEDULER_ACL_NAME
,W1.STD_TENANT_START_DATE_TIME_KEY
,W1.CAL_DATE
,W1.TENANT_KEY
,W1.AIR_DAY_TYPE
,W1.AIR_ACW_FONT_COLOR
,W1.MIN_GUARANTEE_MINUTES
,W1.MIN_GUARANTEE_TYPE
,W1.AUTHORIZED_TO_INVOICE_TYPE
,W1.HAS_HOLIDAYS
,W1.INCLUDE_IN_CAS
,W1.READY_FOR_XML
,W1.SHOW_ID_EXTS
,W1.INVOICE_ID
,W1.RESOURCE_NAME
,W1.CATS_ID
,W1.PAY_GROUP
,@WS_ROW_CREATED_TIME    --[WS_ROW_CREATED_TIME] [datetime] NOT NULL,
,NULL                    --[WS_ROW_UPDATED_TIME] [datetime] NULL,

FROM            WSOL_TB_IMPORTS_MONAT_INVOICING_1  W1

LEFT JOIN       WSOL_TB_IMPORTS_MONAT_INVOICING    G   ON G.STD_TENANT_START_DATE_TIME_KEY = W1.STD_TENANT_START_DATE_TIME_KEY
													  AND G.ID_EXT                         = W1.ID_EXT
													  AND G.FF_AGENT_NAME				   = W1.FF_AGENT_NAME
													  AND G.INVOICE_ID					   = W1.INVOICE_ID

WHERE (G.FF_AGENT_NAME					IS NULL AND ISNULL(W1.FF_AGENT_NAME					,'') <> '' )
  AND (G.STD_TENANT_START_DATE_TIME_KEY	IS NULL AND ISNULL(W1.STD_TENANT_START_DATE_TIME_KEY, 0) <>  0 )
--AND (G.INVOICE_ID						IS NULL AND ISNULL(W4.INVOICE_ID					,'') <> '' )			
--AND (G.ID_EXT							IS NULL AND ISNULL(W4.ID_EXT						,'') <> '' )

--===============================================================
SET DATEFIRST 1  -- = Monday
--===============================================================

IF OBJECT_ID('TEMPDB..#DT_EASY_WEEKS') IS NOT NULL BEGIN
   DROP TABLE #DT_EASY_WEEKS
END
CREATE TABLE #DT_EASY_WEEKS
(CAL_DATE_STRING      VARCHAR(10)
,CAL_WEEK_START_DATE  DATETIME
,CAL_WEEK_END_DATE    DATETIME
,PAY_CYCLE_CLOSURE_DATE DATETIME
)
INSERT INTO #DT_EASY_WEEKS
SELECT
 DT.CAL_DATE_STRING
,CASE WHEN DATEPART(DW,CAST(DT.CAL_DATE_STRING AS DATETIME)) = 1 THEN CAST(DT.CAL_DATE_STRING AS DATETIME)
	  WHEN DATEPART(DW,CAST(DT.CAL_DATE_STRING AS DATETIME)) = 7 THEN DATEADD(DD,-6,CAST(DT.CAL_DATE_STRING AS DATETIME))
	  ELSE DATEADD(DD,1,DT.CAL_WEEK_START_DATE) END
,DT.CAL_DATE_STRING
,DT.CAL_DATE_STRING  --PAY_CYCLE_CLOSURE_DATE
FROM DATE_TIME DT
WHERE DT.CAL_DATE >= @DTM_BEG AND DT.CAL_DATE <  @DTM_END
GROUP BY 
 DT.CAL_DATE_STRING
,CASE WHEN DATEPART(DW,CAST(DT.CAL_DATE_STRING AS DATETIME)) = 1 THEN CAST(DT.CAL_DATE_STRING AS DATETIME)
	  WHEN DATEPART(DW,CAST(DT.CAL_DATE_STRING AS DATETIME)) = 7 THEN DATEADD(DD,-6,CAST(DT.CAL_DATE_STRING AS DATETIME))
	  ELSE DATEADD(DD,1,DT.CAL_WEEK_START_DATE) END
,DT.CAL_DATE_STRING
,DT.CAL_DATE_STRING  --PAY_CYCLE_CLOSURE_DATE
--===========================
UPDATE #DT_EASY_WEEKS SET CAL_WEEK_END_DATE = DATEADD(DD,6,CAL_WEEK_START_DATE)

UPDATE #DT_EASY_WEEKS SET
 PAY_CYCLE_CLOSURE_DATE = CASE WHEN DATEPART(DD,@DTM_MAX) >= 1 AND DATEPART(DD,@DTM_MAX) < 16 THEN
									CAST(CONVERT(VARCHAR(10), CONVERT(VARCHAR(2),MONTH(@DTM_MAX)) + CONVERT(VARCHAR(4),'/15/') + CONVERT(VARCHAR(4),YEAR(@DTM_MAX)),101) AS DATETIME)
							   WHEN DATEPART(DD,@DTM_MAX) > 15 THEN 
									DATEADD(D,-1,DATEADD(M,DATEDIFF(M,0,@DTM_MAX)+1,0))
							   END 
							   
 --SELECT * FROM #DT_EASY_WEEKS ORDER BY CAL_DATE_STRING
 /*
--==================================
--CREATE TMP TABLE:
--==================================
IF OBJECT_ID('TEMPDB..#WSOL_TB_IMPORTS_MONAT_UV_ANT_AIA') IS NOT NULL BEGIN
   DROP TABLE #WSOL_TB_IMPORTS_MONAT_UV_ANT_AIA
END
CREATE TABLE #WSOL_TB_IMPORTS_MONAT_UV_ANT_AIA
(	[PLATFORM] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[STATUS] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[INVOICE_MAP_KEY] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	[FIELD_NAME] [varchar](100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[SCHEDULER_PROJECT_ID] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[SCHEDULER_ACL_NAME] [varchar](100) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	[ACD_ID_EXTENSION] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	[OFFICIAL_WSOL_CLIENT_ID] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[OFFICIAL_WSOL_CLIENT_NAME] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[OFFICIAL_ACD_CLIENT_ID] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[OFFICIAL_ACD_CLIENT_NAME] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	[PRIMARY_PROJECT_MANAGER_ID] [varchar](500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[DIRECTOR_OF_PROJECT_MANAGEMENT_ID] [varchar](500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[AGENT_TECHNOLOGY_MANAGER_ID] [varchar](500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[CONTRACTOR_SUPPORT_PATHWAY] [varchar](500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[INVOICE_SYSTEM_ID] [varchar](100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[HOLIDAY_INVOICE_ID] [varchar](100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[HOLIDAY] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[FILE_FORMAT_OF_PUSH] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[AGENT_PREPARATION_INVOICE_ID] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[NEW_ACL] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[CURRENT_CATS] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[CATS_ID] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[PATS_ID] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[SMART_ELIGIBLE] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[SMART_TIER_1] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[SMART_TIER_2] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[SMART_TIER_3] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[INTERVAL] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[DATE] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[HOD_INTERVAL] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[AU_DK_LOGGED_IN_DURATION] [decimal](10, 2) NULL,
	[AU_DK_AVAILABLE_DURATION] [decimal](10, 2) NULL,
	[AU_DK_TALK_DURATION] [decimal](10, 2) NULL,
	[AU_DK_IB_TALK_DURATION] [decimal](10, 2) NULL,
	[AU_DK_OB_TALK_DURATION] [decimal](10, 2) NULL,
	[AU_DK_CONVENTIONAL_ACW] [decimal](10, 2) NULL,
	[AU_DK_NR_DURATION] [decimal](10, 2) NULL,
	[AU_DK_PSEUDO_PRODUCTIVE_DURATION] [decimal](10, 2) NULL,
	[AU_DK_ADJUSTED_NR_DURATION] [decimal](10, 2) NULL,
	[AU_DK_TOTAL_PRODUCTIVE_DURATION] [decimal](10, 2) NULL,
	[AU_DK_WPSEUDO_PRODUCTIVE_DURATIONS] [decimal](10, 2) NULL,
	[AU_DK_XFER_COUNT] [int] NULL,
	[AU_DK_HOLD_COUNT] [int] NULL,
	[AU_DK_CONFERENCE_COUNT] [int] NULL,
	[AU_DK_CONSULT_COUNT] [int] NULL,
	[AU_DK_PUP_COUNT] [int] NULL,
	[AU_DK_OFFERED_COUNT] [int] NULL,
	[AU_DK_HANDLED_COUNT] [int] NULL,
	[AU_DK_IB_HANDLE_COUNT] [int] NULL,
	[AU_DK_OB_HANDLE_COUNT] [int] NULL,
	[AU_DK_RONA_COUNT] [int] NULL,
	[AU_DK_AWR_COUNT] [int] NULL,
	[MINIMUM_GUARANTEE] [decimal](10, 2) NULL,
	[AUTHORIZED_TO_INVOICE] [decimal](10, 2) NULL,
	[WEEK_ENDING_DATE] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[PAY_CYCLE_CLOSURE_DATE] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,

	[FTP_FILE_NAME] [varchar](100) NOT NULL,
	[EMAIL] [varchar](100)  NULL,
	[STD_TENANT_START_DATE_TIME_KEY] [int] NOT NULL,
	[CAL_DATE] [datetime] NULL,
	[TENANT_KEY] [int] NOT NULL,
	[AIR_DAY_TYPE] [varchar](1) NOT NULL,
	[AIR_ACW_FONT_COLOR] [varchar](50) NULL,
	[MIN_GUARANTEE_RATE] [decimal](6, 3) NULL,
	[MIN_GUARANTEE_TYPE] [varchar](50) NULL,
	[AUTHORIZED_TO_INVOICE_TYPE] [varchar](50) NULL,
	[HAS_HOLIDAYS] [varchar](1) NULL,
	[INCLUDE_IN_CAS] [varchar](1) NULL,
	[READY_FOR_XML] [varchar](1) NULL,
	[SHOW_ID_EXTS] [varchar](1) NULL,
	[INVOICE_ID] [varchar](100) NULL,
	[RESOURCE_NAME] [varchar](100) NULL,
	[AIRITKDUR] [decimal](10, 2) NULL,
	[AIRIACDUR] [decimal](10, 2) NULL,
	[WS_ROW_CREATED_TIME] [datetime] NULL,
	[WS_ROW_UPDATED_TIME] [datetime] NULL

)
INSERT INTO #WSOL_TB_IMPORTS_MONAT_UV_ANT_AIA
SELECT 
 AIASD.[PLATFORM]
,AIASD.[STATUS]    
,AIA.FF_AGENT_NAME  --INVOICE_MAP_KEY
,AIASD.FIELD_NAME
,AIASD.SCHEDULER_PROJECT_ID
,AIASD.SCHEDULER_ACL_NAME
,AIASD.ACD_ID_EXTENSION
,AIASD.OFFICIAL_WSOL_CLIENT_ID
,AIASD.OFFICIAL_WSOL_CLIENT_NAME
,AIASD.OFFICIAL_ACD_CLIENT_ID
,AIASD.OFFICIAL_ACD_CLIENT_NAME
,AIASD.PRIMARY_PROJECT_MANAGER_ID
,AIASD.DIRECTOR_OF_PROJECT_MANAGEMENT_ID
,AIASD.AGENT_TECHNOLOGY_MANAGER_ID
,AIASD.CONTRACTOR_SUPPORT_PATHWAY
,AIASD.INVOICE_SYSTEM_ID
,AIASD.HOLIDAY_INVOICE_ID
,CASE WHEN AIA.AIR_DAY_TYPE = 'H' THEN 'Yes' ELSE 'No' END  AS HOLIDAY   --AIR_DAY_TYPE:  'H'=Holiday  'S'=Standard (not holiday)
,AIASD.FILE_FORMAT_OF_PUSH
,AIASD.AGENT_PREPARATION_INVOICE_ID
,AIASD.NEW_ACL
,AIASD.CURRENT_CATS
,AIASD.CATS_ID
,AIASD.PATS_ID
,AIASD.SMART_ELIGIBLE
,AIASD.SMART_TIER_1
,AIASD.SMART_TIER_2
,AIASD.SMART_TIER_3
,AIASD.INTERVAL
,DT.CAL_DATE_STRING				--[DATE]             
,DT.LABEL_HH24 + ':00'			--HOD_INTERVAL

,AIA.AVAILABLE_TIME + AIA.NON_CONNECT_CALL_TIME + AIA.RONA_TIME + AIA.UNAVAILABLE_TIME + AIA.HANDLE_TIME	--AU_DK_LOGGED_IN_DURATION
,AIA.AVAILABLE_TIME								--AU_DK_AVAILABLE_DURATION

,AIA.RING_TIME + AIA.CONNECT_PHONE_CALL_TIME	--AU_DK_TALK_DURATION
,0												--AU_DK_IB_TALK_DURATION
,0												--AU_DK_OB_TALK_DURATION

,AIA.ACW_TIME									--AU_DK_CONVENTIONAL_ACW
,AIA.UNAVAILABLE_TIME					        --AU_DK_NR_DURATION
,0												--AIA.AU_DK_PSEUDO_PRODUCTIVE_DURATION
,0												--AU_DK_ADJUSTED_NR_DURATION
,AIA.CPROD										--AU_DK_TOTAL_PRODUCTIVE_DURATION
,AIA.CPROD										--AU_DK_WPSEUDO_PRODUCTIVE_DURATIONS  

,0		--AU_DK_XFER_COUNT
,0		--AU_DK_HOLD_COUNT
,0		--AU_DK_CONFERENCE_COUNT
,0		--AU_DK_CONSULT_COUNT
,0		--AU_DK_PUP_COUNT

,0		--AU_DK_OFFERED_COUNT
,0		--AU_DK_HANDLED_COUNT
,0		--AU_DK_IB_HANDLE_COUNT
,0		--AU_DK_OB_HANDLE_COUNT
													
,0		--AU_DK_RONA_COUNT
,0		--AU_DK_AWR_COUNT

,AIA.MING	--MINIMUM_GUARANTEE
,AIA.AUT2	--AUTHORIZED_TO_INVOICE

,CONVERT(VARCHAR(10),DEW.CAL_WEEK_END_DATE,101)      --AS WEEK_ENDING_DATE       --EVERY SUNDAY.--,AIA.WEEK_ENDING_DATE             --HAVE TO CALCULATE !!!!!!!!!!!
,CONVERT(VARCHAR(10),DEW.PAY_CYCLE_CLOSURE_DATE,101) --AS PAY_CYCLE_CLOSURE_DATE --EVERY OTHER SUNDAY, FROM A STARTING SUNDAY OF 10/31/11.--,AIA.PAY_CYCLE_CLOSURE_DATE       --HAVE TO CALCULATE !!!!!!!!!!!

,AIA.FTP_FILE_NAME
,AIA.EMAIL
,AIA.STD_TENANT_START_DATE_TIME_KEY
,DT.CAL_DATE
,AIA.TENANT_KEY
,AIA.AIR_DAY_TYPE
,AIA.AIR_ACW_FONT_COLOR
,AIA.MIN_GUARANTEE_MINUTES
,AIA.MIN_GUARANTEE_TYPE
,AIA.AUTHORIZED_TO_INVOICE_TYPE
,AIA.HAS_HOLIDAYS
,AIA.INCLUDE_IN_CAS
,AIA.READY_FOR_XML
,AIA.SHOW_ID_EXTS
,AIA.INVOICE_ID  --CASE WHEN AIA.AIR_DAY_TYPE = 'H' THEN AIASD.HOLIDAY_INVOICE_ID ELSE AIASD.INVOICE_SYSTEM_ID END  --AS INVOICE_ID 
,AIA.RESOURCE_NAME
,NULL			--AIA.AIRITKDUR
,NULL			--AIA.AIRIACDUR
,dbo.GETDATE()  --	[WS_ROW_CREATED_TIME] [datetime] NULL,
,NULL			--	[WS_ROW_UPDATED_TIME] [datetime] NULL
	
--SELECT TOP 1000 *
FROM            WSOL_TB_IMPORTS_MONAT_INVOICING_1            AIA 
INNER JOIN      WSOL_TB_IMPORTS_MONAT_SD_AIA_STATIC_DEFAULTS AIASD ON AIASD.ACD_ID_EXTENSION = AIA.ID_EXT
INNER JOIN      WSOL_TB_IMPORTS_MONAT_SD_INVOICE_GROUPS      CASG  ON CASG.ID_EXT            = AIASD.ACD_ID_EXTENSION	

INNER JOIN      DATE_TIME									 DT    ON DT.DATE_TIME_KEY       = AIA.STD_TENANT_START_DATE_TIME_KEY

LEFT JOIN       #DT_EASY_WEEKS								DEW   ON DEW.CAL_DATE_STRING    = DT.CAL_DATE_STRING

WHERE DT.CAL_DATE >= @DTM_BEG AND DT.CAL_DATE <  @DTM_END
  AND (ISNULL(AIASD.ACD_ID_EXTENSION,'') <> '')
  AND (ISNULL(AIA.RESOURCE_NAME,'') <> '')
  AND AIA.AUT2 <> 0.00											--<<<<<---- FILTER OUT RECORDS WHERE AUTHORIZED TIME = 0.00


--==========================================================================
--UPDATE WSOL_TB_...UV_ANT_AIA TABLE:
--==========================================================================
UPDATE WSOL_TB_IMPORTS_MONAT_UV_ANT_AIA SET
 [PLATFORM]							= W1.[PLATFORM]
,[STATUS]							= W1.[STATUS]
--,INVOICE_MAP_KEY					= W1.INVOICE_MAP_KEY
,FIELD_NAME							= W1.FIELD_NAME
,SCHEDULER_PROJECT_ID				= W1.SCHEDULER_PROJECT_ID
,SCHEDULER_ACL_NAME					= W1.SCHEDULER_ACL_NAME
--,ACD_ID_EXTENSION					= W1.ACD_ID_EXTENSION
,OFFICIAL_WSOL_CLIENT_ID			= W1.OFFICIAL_WSOL_CLIENT_ID
,OFFICIAL_WSOL_CLIENT_NAME			= W1.OFFICIAL_WSOL_CLIENT_NAME
,OFFICIAL_ACD_CLIENT_ID				= W1.OFFICIAL_ACD_CLIENT_ID
,OFFICIAL_ACD_CLIENT_NAME			= W1.OFFICIAL_ACD_CLIENT_NAME
,PRIMARY_PROJECT_MANAGER_ID			= W1.PRIMARY_PROJECT_MANAGER_ID
,DIRECTOR_OF_PROJECT_MANAGEMENT_ID	= W1.DIRECTOR_OF_PROJECT_MANAGEMENT_ID
,AGENT_TECHNOLOGY_MANAGER_ID		= W1.AGENT_TECHNOLOGY_MANAGER_ID
,CONTRACTOR_SUPPORT_PATHWAY			= W1.CONTRACTOR_SUPPORT_PATHWAY
,INVOICE_SYSTEM_ID					= W1.INVOICE_SYSTEM_ID
,HOLIDAY_INVOICE_ID					= W1.HOLIDAY_INVOICE_ID
,HOLIDAY							= W1.HOLIDAY
,FILE_FORMAT_OF_PUSH				= W1.FILE_FORMAT_OF_PUSH
,AGENT_PREPARATION_INVOICE_ID		= W1.AGENT_PREPARATION_INVOICE_ID
,NEW_ACL							= W1.NEW_ACL
,CURRENT_CATS						= W1.CURRENT_CATS
,CATS_ID							= W1.CATS_ID
,PATS_ID							= W1.PATS_ID
,SMART_ELIGIBLE						= W1.SMART_ELIGIBLE
,SMART_TIER_1						= W1.SMART_TIER_1
,SMART_TIER_2						= W1.SMART_TIER_2
,SMART_TIER_3						= W1.SMART_TIER_3
,INTERVAL							= W1.INTERVAL
,[DATE]								= W1.[DATE]
,HOD_INTERVAL						= W1.HOD_INTERVAL
,AU_DK_LOGGED_IN_DURATION			= W1.AU_DK_LOGGED_IN_DURATION
,AU_DK_AVAILABLE_DURATION			= W1.AU_DK_AVAILABLE_DURATION
,AU_DK_TALK_DURATION				= W1.AU_DK_TALK_DURATION
,AU_DK_IB_TALK_DURATION				= W1.AU_DK_IB_TALK_DURATION
,AU_DK_OB_TALK_DURATION				= W1.AU_DK_OB_TALK_DURATION
,AU_DK_CONVENTIONAL_ACW				= W1.AU_DK_CONVENTIONAL_ACW
,AU_DK_NR_DURATION					= W1.AU_DK_NR_DURATION
,AU_DK_PSEUDO_PRODUCTIVE_DURATION   = W1.AU_DK_PSEUDO_PRODUCTIVE_DURATION
,AU_DK_ADJUSTED_NR_DURATION         = W1.AU_DK_ADJUSTED_NR_DURATION
,AU_DK_TOTAL_PRODUCTIVE_DURATION    = W1.AU_DK_TOTAL_PRODUCTIVE_DURATION
,AU_DK_WPSEUDO_PRODUCTIVE_DURATIONS = W1.AU_DK_WPSEUDO_PRODUCTIVE_DURATIONS
,AU_DK_XFER_COUNT					= W1.AU_DK_XFER_COUNT
,AU_DK_HOLD_COUNT					= W1.AU_DK_HOLD_COUNT
,AU_DK_CONFERENCE_COUNT				= W1.AU_DK_CONFERENCE_COUNT
,AU_DK_CONSULT_COUNT				= W1.AU_DK_CONSULT_COUNT
,AU_DK_PUP_COUNT					= W1.AU_DK_PUP_COUNT
,AU_DK_OFFERED_COUNT				= W1.AU_DK_OFFERED_COUNT
,AU_DK_HANDLED_COUNT				= W1.AU_DK_HANDLED_COUNT
,AU_DK_IB_HANDLE_COUNT				= W1.AU_DK_IB_HANDLE_COUNT
,AU_DK_OB_HANDLE_COUNT				= W1.AU_DK_OB_HANDLE_COUNT
,AU_DK_RONA_COUNT					= W1.AU_DK_RONA_COUNT
,AU_DK_AWR_COUNT					= W1.AU_DK_AWR_COUNT
,MINIMUM_GUARANTEE					= W1.MINIMUM_GUARANTEE
,AUTHORIZED_TO_INVOICE				= W1.AUTHORIZED_TO_INVOICE
,WEEK_ENDING_DATE					= W1.WEEK_ENDING_DATE
,PAY_CYCLE_CLOSURE_DATE				= W1.PAY_CYCLE_CLOSURE_DATE

--FIELDS ABOVE ARE IN XML FILE.   FIELDS BELOW ARE NOT IN XML FILE!!!:
,FTP_FILE_NAME						= W1.FTP_FILE_NAME
,EMAIL								= W1.EMAIL

--,STD_TENANT_START_DATE_TIME_KEY = W1.STD_TENANT_START_DATE_TIME_KEY
,CAL_DATE							= W1.CAL_DATE
,TENANT_KEY							= W1.TENANT_KEY
,AIR_DAY_TYPE						= W1.AIR_DAY_TYPE
,AIR_ACW_FONT_COLOR					= W1.AIR_ACW_FONT_COLOR
,MIN_GUARANTEE_RATE					= W1.MIN_GUARANTEE_RATE
,MIN_GUARANTEE_TYPE					= W1.MIN_GUARANTEE_TYPE
,AUTHORIZED_TO_INVOICE_TYPE			= W1.AUTHORIZED_TO_INVOICE_TYPE
,HAS_HOLIDAYS						= W1.HAS_HOLIDAYS
,INCLUDE_IN_CAS						= W1.INCLUDE_IN_CAS
,READY_FOR_XML						= W1.READY_FOR_XML
,SHOW_ID_EXTS						= W1.SHOW_ID_EXTS
,INVOICE_ID							= W1.INVOICE_ID
,RESOURCE_NAME						= W1.RESOURCE_NAME

,AIRITKDUR							= W1.AIRITKDUR
,AIRIACDUR							= W1.AIRIACDUR

--,WS_ROW_CREATED_TIME
,WS_ROW_UPDATED_TIME				= @WS_ROW_CREATED_TIME

FROM            #WSOL_TB_IMPORTS_MONAT_UV_ANT_AIA   W1

INNER JOIN      WSOL_TB_IMPORTS_MONAT_UV_ANT_AIA    UV  ON UV.STD_TENANT_START_DATE_TIME_KEY = W1.STD_TENANT_START_DATE_TIME_KEY
													   AND UV.ACD_ID_EXTENSION               = W1.ACD_ID_EXTENSION
													   AND UV.INVOICE_MAP_KEY                = W1.INVOICE_MAP_KEY

WHERE ( UV.STD_TENANT_START_DATE_TIME_KEY = W1.STD_TENANT_START_DATE_TIME_KEY )
  AND ( UV.ACD_ID_EXTENSION               = W1.ACD_ID_EXTENSION )
  AND ( UV.INVOICE_MAP_KEY                = W1.INVOICE_MAP_KEY )


--=====================================================
--INSERT TMP TABLE FIELDS INTO WSOL_TB_... TABLE:
--=====================================================
INSERT INTO [WSOL_TB_IMPORTS_MONAT_UV_ANT_AIA]
SELECT 
 AIA.[PLATFORM]
,AIA.[STATUS]
,AIA.INVOICE_MAP_KEY
,AIA.FIELD_NAME
,AIA.SCHEDULER_PROJECT_ID
,AIA.SCHEDULER_ACL_NAME
,AIA.ACD_ID_EXTENSION
,AIA.OFFICIAL_WSOL_CLIENT_ID
,AIA.OFFICIAL_WSOL_CLIENT_NAME
,AIA.OFFICIAL_ACD_CLIENT_ID
,AIA.OFFICIAL_ACD_CLIENT_NAME
,AIA.PRIMARY_PROJECT_MANAGER_ID
,AIA.DIRECTOR_OF_PROJECT_MANAGEMENT_ID
,AIA.AGENT_TECHNOLOGY_MANAGER_ID
,AIA.CONTRACTOR_SUPPORT_PATHWAY
,AIA.INVOICE_SYSTEM_ID
,AIA.HOLIDAY_INVOICE_ID
,AIA.HOLIDAY
,AIA.FILE_FORMAT_OF_PUSH
,AIA.AGENT_PREPARATION_INVOICE_ID
,AIA.NEW_ACL
,AIA.CURRENT_CATS
,AIA.CATS_ID
,AIA.PATS_ID
,AIA.SMART_ELIGIBLE
,AIA.SMART_TIER_1
,AIA.SMART_TIER_2
,AIA.SMART_TIER_3
,AIA.INTERVAL
,AIA.[DATE]
,AIA.HOD_INTERVAL
,AIA.AU_DK_LOGGED_IN_DURATION
,AIA.AU_DK_AVAILABLE_DURATION
,AIA.AU_DK_TALK_DURATION
,AIA.AU_DK_IB_TALK_DURATION
,AIA.AU_DK_OB_TALK_DURATION
,AIA.AU_DK_CONVENTIONAL_ACW
,AIA.AU_DK_NR_DURATION
,AIA.AU_DK_PSEUDO_PRODUCTIVE_DURATION
,AIA.AU_DK_ADJUSTED_NR_DURATION
,AIA.AU_DK_TOTAL_PRODUCTIVE_DURATION
,AIA.AU_DK_WPSEUDO_PRODUCTIVE_DURATIONS
,AIA.AU_DK_XFER_COUNT
,AIA.AU_DK_HOLD_COUNT
,AIA.AU_DK_CONFERENCE_COUNT
,AIA.AU_DK_CONSULT_COUNT
,AIA.AU_DK_PUP_COUNT
,AIA.AU_DK_OFFERED_COUNT
,AIA.AU_DK_HANDLED_COUNT
,AIA.AU_DK_IB_HANDLE_COUNT
,AIA.AU_DK_OB_HANDLE_COUNT
,AIA.AU_DK_RONA_COUNT
,AIA.AU_DK_AWR_COUNT
,AIA.MINIMUM_GUARANTEE
,AIA.AUTHORIZED_TO_INVOICE
,AIA.WEEK_ENDING_DATE
,AIA.PAY_CYCLE_CLOSURE_DATE

,AIA.FTP_FILE_NAME
,AIA.EMAIL
,AIA.STD_TENANT_START_DATE_TIME_KEY
,AIA.CAL_DATE
,AIA.TENANT_KEY
,AIA.AIR_DAY_TYPE
,AIA.AIR_ACW_FONT_COLOR
,AIA.MIN_GUARANTEE_RATE
,AIA.MIN_GUARANTEE_TYPE
,AIA.AUTHORIZED_TO_INVOICE_TYPE
,AIA.HAS_HOLIDAYS
,AIA.INCLUDE_IN_CAS
,AIA.READY_FOR_XML
,AIA.SHOW_ID_EXTS
,AIA.INVOICE_ID
,AIA.RESOURCE_NAME
,AIA.AIRITKDUR
,AIA.AIRIACDUR
,AIA.WS_ROW_CREATED_TIME
,AIA.WS_ROW_UPDATED_TIME

--Where Permanent table is Null and Work table is not Null - then we want to add the data!!!:

FROM            #WSOL_TB_IMPORTS_MONAT_UV_ANT_AIA   AIA
LEFT JOIN       WSOL_TB_IMPORTS_MONAT_UV_ANT_AIA    UV  ON UV.STD_TENANT_START_DATE_TIME_KEY = AIA.STD_TENANT_START_DATE_TIME_KEY
													   AND UV.ACD_ID_EXTENSION               = AIA.ACD_ID_EXTENSION
												       AND UV.INVOICE_MAP_KEY                = AIA.INVOICE_MAP_KEY

WHERE ( UV.STD_TENANT_START_DATE_TIME_KEY IS NULL AND ISNULL(AIA.STD_TENANT_START_DATE_TIME_KEY,0) <> 0 )
  AND ( UV.ACD_ID_EXTENSION               IS NULL AND ISNULL(AIA.ACD_ID_EXTENSION,'') <> '' )
  AND ( UV.INVOICE_MAP_KEY                IS NULL AND ISNULL(AIA.INVOICE_MAP_KEY,'') <> '' )

*/
--=============================================
EARLY_EXIT:
--=============================================