
CREATE PROCEDURE [dbo].[uspIMPORTS_HUMACH_AGENT_INVOICING_REPORTS]
 @DATE_BEG           DATETIME
,@DATE_END           DATETIME
,@TENANT_KEY         VARCHAR(150) --No multiples even though filter below is setup for multiples.
,@CUSTOMER_ID		 VARCHAR(150) --
,@INVOICE_GROUP      VARCHAR(150) --Hid. Def=' '
,@ID_EXT             VARCHAR(300) --Hid. Def=' '
,@RESOURCE_KEY       VARCHAR(10)  --Hid. Def='0'
,@TIME_INTERVAL      VARCHAR(10)  --Hid. Def='HR'  HR,DY,DR   FOR SUB: MD(Month by Day),MR(Month Range)  15 and 30 not possible !!!!
,@SHOW_RESOURCE      VARCHAR(1)   --Hid. Def='Y'
,@DUR_IN             VARCHAR(2)   --Hid. Def='MM' 
,@RESOURCE_FORMAT    VARCHAR(2)   --Hid. Def='NM' --'NM'=NAME + (employee id),  'ID'=ID
,@SHOW_HOLIDAY       VARCHAR(1)   --Hid. Def='N'
,@PSW                VARCHAR(10)  --Hid. Def='NONE'
,@EXECUTIONER        VARCHAR(3)   --Hid. Def='MAN'  MANual,SUBscription
,@RPT_TYPE_GRP       VARCHAR(3)   --Hid. Def='INV'
,@RPT_TYPE           VARCHAR(3)   --Hid. Def='INV'  
AS
SET NOCOUNT ON    

--  EXECUTE [dbo].[uspIMPORTS_HUMACH_AGENT_INVOICING_REPORTS] '03/16/2016','03/31/2016','0','0','0','0','0','HR','Y','SS','NM','Y','4','MAN','INV','INV'

--  @TIME_INTERVAL:  Can only show invoicing report at hour level or higher !!!

--  Durations in data feed are in seconds.

--  SELECT * FROM WSOL_TB_IMPORTS_HUMACH_SD_INVOICE_GROUPS
--  SELECT * FROM WSOL_TB_IMPORTS_HUMACH_UV_ANT_AIA
    
--TMP:  FOR RUNNING SQL JOBS FOR PREVIOUS DAYS:  
--SET @DATE_BEG = '05/23/2014'
--SET @DATE_END = '06/05/2014'

--==================================--SET DATEFIRST 1  --1=MONDAY  7=SUNDAY  --DW = M,T,W,T,F,S,S
DECLARE
 @DTM_BEG AS DATETIME
,@DTM_END AS DATETIME
IF @DATE_BEG < '01/01/1901' BEGIN     
    SET @DTM_BEG = CAST(CONVERT(VARCHAR(10),dbo.getdate() - 1,101) AS DATETIME) 
	SET @DTM_END = CAST(CONVERT(VARCHAR(10),dbo.getdate() - 1,101) AS DATETIME) -- + 1
END
ELSE BEGIN
    SET @DTM_BEG = CAST(CONVERT(VARCHAR(10),@DATE_BEG,101) AS DATETIME) 
    SET @DTM_END = CAST(CONVERT(VARCHAR(10),@DATE_END,101) AS DATETIME) -- + 1
END
SET @DTM_END    = @DTM_END + 1  --EVERYTHING ABOVE, @DTM_END IS FOR EXACT DATE RANGE NEEDED. ONE IS ADDED SO WHERE CLAUSE " < @DTM_END" WORKS.

DECLARE
 @MTD_BEG AS DATETIME
,@MTD_END AS DATETIME  --,@YTD_BEG AS DATETIME--,@YTD_END AS DATETIME
SET @MTD_BEG = CAST(CAST(DATEPART(mm,@DTM_BEG) AS VARCHAR(2)) + '/01/' + CAST(DATEPART(yyyy,@DTM_BEG) AS VARCHAR(4)) AS DATETIME)
SET @MTD_END = @DTM_END  --SET @YTD_BEG = CAST('01/01/' + CAST(DATEPART(yyyy,@DTM_BEG) AS VARCHAR(4)) AS DATETIME)  

IF @TIME_INTERVAL IN ('MR','MD') BEGIN  --MONTH DETERMINED BY @DTM_BEG.
	SET @DTM_BEG = @MTD_BEG
	SET @DTM_END = @MTD_END
END

--========================================================
--SET ID EXTENSIONS
--========================================================
SET @CUSTOMER_ID	= ',' + LTRIM(RTRIM(@CUSTOMER_ID)) + ','
SET @INVOICE_GROUP	= ',' + LTRIM(RTRIM(REPLACE(@INVOICE_GROUP,'NO INVOICE GROUP',''))) + ','


--==================================
--SET AMOUNT TO DIVIDE BY:
--==================================
DECLARE @DS DECIMAL(10,2)  -- SECONDS TO DIVIDE BY.
IF @DUR_IN = 'SS' BEGIN
    SET @DS = 1.00			--DIVIDE SECONDS BY 1 TO GET SECONDS.
END
IF @DUR_IN = 'MM' BEGIN
    SET @DS = 60.00			--DIVIDE SECONDS BY 60 TO GET MINUTES.
END
IF @DUR_IN = 'HH' BEGIN
    SET @DS = 3600.00		--DIVIDE SECONDS BY 3600 TO GET HOURS.
END

--==================================
--CREATE TMP TABLE:
--==================================
IF OBJECT_ID('TEMPDB..#IMPORTS_HUMACH_AGENT_INVOICING_REPORTS') IS NOT NULL BEGIN
   DROP TABLE #IMPORTS_HUMACH_AGENT_INVOICING_REPORTS
END
CREATE TABLE #IMPORTS_HUMACH_AGENT_INVOICING_REPORTS
(TENANT_NAME            VARCHAR(50)
,ID_EXT                 VARCHAR(3)
,SCHEDULER_ACL_NAME     VARCHAR(100)  
,EMPLOYEE_ID            VARCHAR(50)   
,STD_TENANT_START_DATE_TIME_KEY INT
,RESOURCE_NAME          VARCHAR(100)

,AIR_DAY_TYPE           varchar(1)
,AIR_ACW_FONT_COLOR     varchar(50)
,MIN_GUARANTEE_MINUTES  decimal(6,3)
,MIN_GUARANTEE_TYPE     varchar(50)
,AUTHORIZED_TO_INVOICE_TYPE varchar(50)
,HAS_HOLIDAYS           varchar(1)
,INCLUDE_IN_CAS         varchar(1)
,READY_FOR_XML          varchar(1)
,SHOW_ID_EXTS           varchar(1)
,
[LOGGED_IN_SECS] [decimal](10, 2) NULL,
[READY_SECS] [decimal](10, 2) NULL,
[ASSIGNED_SECS] [decimal](10, 2) NULL,
[BUSY_SECS] [decimal](10, 2) NULL,
[NOT_READY_SECS] [decimal](10, 2) NULL,
[AGENT_UNRESPONSIVE_SECS] [decimal](10, 2) NULL,
[POST_LOGIN_SECS] [decimal](10, 2) NULL,
[BREAK_SECS] [decimal](10, 2) NULL,
[WRAP_SECS] [decimal](10, 2) NULL,
[NR_05_SECS] [decimal](10, 2) NULL,
[NR_06_SECS] [decimal](10, 2) NULL,
[NR_07_SECS] [decimal](10, 2) NULL,
[DIAL_PENDING_SECS] [decimal](10, 2) NULL,
[STATE_UNKNOWN_SECS] [decimal](10, 2) NULL,
[Q_IN_CALLS_IN_AGT_ASSIGNED_SECS] [decimal](10, 2) NULL,
[Q_IN_CALLS_IN_AGT_ASSIGNED_FAILED_SECS] [decimal](10, 2) NULL,
[Q_IN_CALLS_IN_AGT_ANS_SECS] [decimal](10, 2) NULL,
[Q_IN_CALLS_AGT_CALLS_TRANS_SECS] [decimal](10, 2) NULL,
[Q_IN_CALLS_IN_AGT_COMPLETED_CALL_TALK_SECS] [decimal](10, 2) NULL,
[Q_IN_CALLS_IN_AGT_COMPLETED_CALL_TIME_SECS] [decimal](10, 2) NULL,
[Q_IN_CALLS_AGT_CALLS_HOLD_SECS] [decimal](10, 2) NULL,
[Q_IN_CALLS_IN_AGT_COMPLETED_CALL_CONNECTED_SECS] [decimal](10, 2) NULL,
[Q_IN_CALLS_IN_AGT_CALLS_HANDLE_SECS] [decimal](10, 2) NULL,
[NON_Q_CALLS_OUT_AGT_CALL_ANS_CALL_TALK_SECS] [decimal](10, 2) NULL,
[NON_Q_CALLS_OUT_AGT_CALL_ANS_CALL_TIME_SECS] [decimal](10, 2) NULL,
[NON_Q_CALLS_OUT_AGT_CALL_ANS_CALL_CONNECTED_SECS] [decimal](10, 2) NULL,
[Q_IN_CALLS_IN_AGT_ASSIGNED_CT] [decimal](10, 2) NULL,
[Q_IN_CALLS_IN_AGT_ASSIGNED_FAILED_CT] [decimal](10, 2) NULL,
[Q_IN_CALLS_IN_AGT_ANS_CT] [decimal](10, 2) NULL,
[Q_IN_CALLS_AGT_CALLS_HOLD_CT] [decimal](10, 2) NULL,
[Q_IN_CALLS_AGT_CALLS_ON_HOLD_CT] [decimal](10, 2) NULL,
[Q_IN_CALLS_AGT_CALLS_TRANS_CT] [decimal](10, 2) NULL,
[Q_IN_CALLS_IN_AGT_CALLS_HANDLE_CT] [decimal](10, 2) NULL,
[Q_IN_CALLS_IN_AGT_COMPLETED_CT] [decimal](10, 2) NULL,
[NON_Q_CALLS_OUT_AGT_CALL_ANS_CT] [decimal](10, 2) NULL,
[NON_Q_CALLS_OUT_AGT_CALL_ATTEMPT_CT] [decimal](10, 2) NULL,
[TOTAL_CALLS] [decimal] (10, 2) NULL,
[AUTHORIZED_WRAP] [decimal] (10, 2) NULL,
[CPROD] [decimal](10, 2) NULL,
[MINIMUM_GUARANTEE] [decimal](10, 2) NULL,
[AUTHORIZED_MINUTES] [decimal](10, 2) NULL,
)

INSERT INTO #IMPORTS_HUMACH_AGENT_INVOICING_REPORTS
SELECT
 UAA.TENANT_NAME
,UAA.ID_EXT
,UAA.SCHEDULER_ACL_NAME
,UAA.EMPLOYEE_ID 
,UAA.STD_TENANT_START_DATE_TIME_KEY
,UAA.RESOURCE_NAME

,(ISNULL(UAA.AIR_DAY_TYPE,''))				--AS AIR_DAY_TYPE
,(ISNULL(UAA.AIR_ACW_FONT_COLOR,''))		--AS AIR_ACW_FONT_COLOR
,(ISNULL(UAA.MIN_GUARANTEE_MINUTES,0.000))	--AS MIN_GUARANTEE_MINUTES
,(ISNULL(UAA.MIN_GUARANTEE_TYPE,''))		--AS MIN_GUARANTEE_TYPE
,(ISNULL(UAA.AUTHORIZED_TO_INVOICE_TYPE,''))--AS AUTHORIZED_TO_INVOICE_TYPE
,(ISNULL(UAA.HAS_HOLIDAYS,''))				--AS HAS_HOLIDAYS
,(ISNULL(UAA.INCLUDE_IN_CAS,''))			--AS INCLUDE_IN_CAS
,(ISNULL(UAA.READY_FOR_XML,''))				--AS READY_FOR_XML
,(ISNULL(UAA.SHOW_ID_EXTS,''))				--AS SHOW_ID_EXTS

,(ISNULL(UAA.LOGGED_IN_SECS,0))
,(ISNULL(UAA.READY_SECS,0))
,(ISNULL(UAA.ASSIGNED_SECS,0))
,(ISNULL(UAA.BUSY_SECS,0))
,(ISNULL(UAA.NOT_READY_SECS,0))
,(ISNULL(UAA.AGENT_UNRESPONSIVE_SECS,0))
,(ISNULL(UAA.POST_LOGIN_SECS,0))
,(ISNULL(UAA.BREAK_SECS,0))
,(ISNULL(UAA.WRAP_SECS,0))
,(ISNULL(UAA.NR_05_SECS,0))
,(ISNULL(UAA.NR_06_SECS,0))
,(ISNULL(UAA.NR_07_SECS,0))
,(ISNULL(UAA.DIAL_PENDING_SECS,0))
,(ISNULL(UAA.STATE_UNKNOWN_SECS,0))
,(ISNULL(UAA.Q_IN_CALLS_IN_AGT_ASSIGNED_SECS,0))
,(ISNULL(UAA.Q_IN_CALLS_IN_AGT_ASSIGNED_FAILED_SECS,0))
,(ISNULL(UAA.Q_IN_CALLS_IN_AGT_ANS_SECS,0))
,(ISNULL(UAA.Q_IN_CALLS_AGT_CALLS_TRANS_SECS,0))
,(ISNULL(UAA.Q_IN_CALLS_IN_AGT_COMPLETED_CALL_TALK_SECS,0))
,(ISNULL(UAA.Q_IN_CALLS_IN_AGT_COMPLETED_CALL_TIME_SECS,0))
,(ISNULL(UAA.Q_IN_CALLS_AGT_CALLS_HOLD_SECS,0))
,(ISNULL(UAA.Q_IN_CALLS_IN_AGT_COMPLETED_CALL_CONNECTED_SECS,0))
,(ISNULL(UAA.Q_IN_CALLS_IN_AGT_CALLS_HANDLE_SECS,0))
,(ISNULL(UAA.NON_Q_CALLS_OUT_AGT_CALL_ANS_CALL_TALK_SECS,0))
,(ISNULL(UAA.NON_Q_CALLS_OUT_AGT_CALL_ANS_CALL_TIME_SECS,0))
,(ISNULL(UAA.NON_Q_CALLS_OUT_AGT_CALL_ANS_CALL_CONNECTED_SECS,0))
,(ISNULL(UAA.Q_IN_CALLS_IN_AGT_ASSIGNED_CT,0))
,(ISNULL(UAA.Q_IN_CALLS_IN_AGT_ASSIGNED_FAILED_CT,0))
,(ISNULL(UAA.Q_IN_CALLS_IN_AGT_ANS_CT,0))
,(ISNULL(UAA.Q_IN_CALLS_AGT_CALLS_HOLD_CT,0))
,(ISNULL(UAA.Q_IN_CALLS_AGT_CALLS_ON_HOLD_CT,0))
,(ISNULL(UAA.Q_IN_CALLS_AGT_CALLS_TRANS_CT,0))
,(ISNULL(UAA.Q_IN_CALLS_IN_AGT_CALLS_HANDLE_CT,0))
,(ISNULL(UAA.Q_IN_CALLS_IN_AGT_COMPLETED_CT,0))
,(ISNULL(UAA.NON_Q_CALLS_OUT_AGT_CALL_ANS_CT,0))
,(ISNULL(UAA.NON_Q_CALLS_OUT_AGT_CALL_ATTEMPT_CT,0))
,(ISNULL(UAA.TOTAL_CALLS,0))
,(ISNULL(UAA.AUTHORIZED_WRAP,0))
,(ISNULL(UAA.CPROD,0))
,(ISNULL(UAA.MINIMUM_GUARANTEE,0))
,(ISNULL(UAA.AUTHORIZED_MINUTES,0))

--DATASOURCES FOR DURATION FIELDS, IN SECONDS, IN HOUR INTERVALS:
--    GROUPED JUST ENOUGH TO BE ABLE TO JOIN DATASOURCES TOGETHER, AND AT MOST BASIC INTERVAL!
FROM
(	SELECT	
	 UA.FF_CUSTOMER_NAME				AS TENANT_NAME
	,UA.ID_EXT							AS ID_EXT
	,UA.INVOICE_ID					    AS SCHEDULER_ACL_NAME
	,CASE WHEN CHARINDEX('_',UA.FF_AGENT_LAST_NAME) > 0 THEN
		LOWER(LEFT(UA.FF_AGENT_FIRST_NAME,1)) + LOWER(LEFT(UA.FF_AGENT_LAST_NAME,CHARINDEX('_',UA.FF_AGENT_LAST_NAME) - 1)) + RIGHT(UA.FF_AGENT_LAST_NAME,3)
	  ELSE
		LOWER(LEFT(UA.FF_AGENT_FIRST_NAME,1)) + LOWER(UA.FF_AGENT_LAST_NAME) END  AS EMPLOYEE_ID 
	,UA.STD_TENANT_START_DATE_TIME_KEY
	,MAX(UA.RESOURCE_NAME)              AS RESOURCE_NAME
	,MAX(UA.AIR_DAY_TYPE)               AS AIR_DAY_TYPE
	,'BLACK'                            AS AIR_ACW_FONT_COLOR
	,0									AS MIN_GUARANTEE_MINUTES
	,''									AS MIN_GUARANTEE_TYPE
	,''									AS AUTHORIZED_TO_INVOICE_TYPE
	,'Y'								AS HAS_HOLIDAYS
	,''									AS INCLUDE_IN_CAS
	,''									AS READY_FOR_XML
	,''									AS SHOW_ID_EXTS

	,SUM(ISNULL(UA.LOGGED_IN_SECS,0))									AS LOGGED_IN_SECS
	,SUM(ISNULL(UA.READY_SECS,0))										AS READY_SECS
	,SUM(ISNULL(UA.ASSIGNED_SECS,0))									AS ASSIGNED_SECS
	,SUM(ISNULL(UA.BUSY_SECS,0))										AS BUSY_SECS
	,SUM(ISNULL(UA.NOT_READY_SECS,0))									AS NOT_READY_SECS
	,SUM(ISNULL(UA.AGENT_UNRESPONSIVE_SECS,0))							AS AGENT_UNRESPONSIVE_SECS
	,SUM(ISNULL(UA.POST_LOGIN_SECS,0))									AS POST_LOGIN_SECS
	,SUM(ISNULL(UA.BREAK_SECS,0))										AS BREAK_SECS
	,SUM(ISNULL(UA.WRAP_SECS,0))										AS WRAP_SECS
	,SUM(ISNULL(UA.NR_05_SECS,0))										AS NR_05_SECS
	,SUM(ISNULL(UA.NR_06_SECS,0))										AS NR_06_SECS
	,SUM(ISNULL(UA.NR_07_SECS,0))										AS NR_07_SECS
	,SUM(ISNULL(UA.DIAL_PENDING_SECS,0))								AS DIAL_PENDING_SECS
	,SUM(ISNULL(UA.STATE_UNKNOWN_SECS,0))								AS STATE_UNKNOWN_SECS
	,SUM(ISNULL(UA.Q_IN_CALLS_IN_AGT_ASSIGNED_SECS,0))					AS Q_IN_CALLS_IN_AGT_ASSIGNED_SECS
	,SUM(ISNULL(UA.Q_IN_CALLS_IN_AGT_ASSIGNED_FAILED_SECS,0))			AS Q_IN_CALLS_IN_AGT_ASSIGNED_FAILED_SECS
	,SUM(ISNULL(UA.Q_IN_CALLS_IN_AGT_ANS_SECS,0))						AS Q_IN_CALLS_IN_AGT_ANS_SECS
	,SUM(ISNULL(UA.Q_IN_CALLS_AGT_CALLS_TRANS_SECS,0))					AS Q_IN_CALLS_AGT_CALLS_TRANS_SECS
	,SUM(ISNULL(UA.Q_IN_CALLS_IN_AGT_COMPLETED_CALL_TALK_SECS,0))		AS Q_IN_CALLS_IN_AGT_COMPLETED_CALL_TALK_SECS
	,SUM(ISNULL(UA.Q_IN_CALLS_IN_AGT_COMPLETED_CALL_TIME_SECS,0))		AS Q_IN_CALLS_IN_AGT_COMPLETED_CALL_TIME_SECS
	,SUM(ISNULL(UA.Q_IN_CALLS_AGT_CALLS_HOLD_SECS,0))					AS Q_IN_CALLS_AGT_CALLS_HOLD_SECS
	,SUM(ISNULL(UA.Q_IN_CALLS_IN_AGT_COMPLETED_CALL_CONNECTED_SECS,0))	AS Q_IN_CALLS_IN_AGT_COMPLETED_CALL_CONNECTED_SECS
	,SUM(ISNULL(UA.Q_IN_CALLS_IN_AGT_CALLS_HANDLE_SECS,0))				AS Q_IN_CALLS_IN_AGT_CALLS_HANDLE_SECS
	,SUM(ISNULL(UA.NON_Q_CALLS_OUT_AGT_CALL_ANS_CALL_TALK_SECS,0))		AS NON_Q_CALLS_OUT_AGT_CALL_ANS_CALL_TALK_SECS
	,SUM(ISNULL(UA.NON_Q_CALLS_OUT_AGT_CALL_ANS_CALL_TIME_SECS,0))		AS NON_Q_CALLS_OUT_AGT_CALL_ANS_CALL_TIME_SECS
	,SUM(ISNULL(UA.NON_Q_CALLS_OUT_AGT_CALL_ANS_CALL_CONNECTED_SECS,0))	AS NON_Q_CALLS_OUT_AGT_CALL_ANS_CALL_CONNECTED_SECS
	,SUM(ISNULL(UA.Q_IN_CALLS_IN_AGT_ASSIGNED_CT,0))					AS Q_IN_CALLS_IN_AGT_ASSIGNED_CT
	,SUM(ISNULL(UA.Q_IN_CALLS_IN_AGT_ASSIGNED_FAILED_CT,0))				AS Q_IN_CALLS_IN_AGT_ASSIGNED_FAILED_CT
	,SUM(ISNULL(UA.Q_IN_CALLS_IN_AGT_ANS_CT,0))							AS Q_IN_CALLS_IN_AGT_ANS_CT
	,SUM(ISNULL(UA.Q_IN_CALLS_AGT_CALLS_HOLD_CT,0))						AS Q_IN_CALLS_AGT_CALLS_HOLD_CT
	,SUM(ISNULL(UA.Q_IN_CALLS_AGT_CALLS_ON_HOLD_CT,0))					AS Q_IN_CALLS_AGT_CALLS_ON_HOLD_CT
	,SUM(ISNULL(UA.Q_IN_CALLS_AGT_CALLS_TRANS_CT,0))					AS Q_IN_CALLS_AGT_CALLS_TRANS_CT
	,SUM(ISNULL(UA.Q_IN_CALLS_IN_AGT_CALLS_HANDLE_CT,0))				AS Q_IN_CALLS_IN_AGT_CALLS_HANDLE_CT
	,SUM(ISNULL(UA.Q_IN_CALLS_IN_AGT_COMPLETED_CT,0))					AS Q_IN_CALLS_IN_AGT_COMPLETED_CT
	,SUM(ISNULL(UA.NON_Q_CALLS_OUT_AGT_CALL_ANS_CT,0))					AS NON_Q_CALLS_OUT_AGT_CALL_ANS_CT
	,SUM(ISNULL(UA.NON_Q_CALLS_OUT_AGT_CALL_ATTEMPT_CT,0))				AS NON_Q_CALLS_OUT_AGT_CALL_ATTEMPT_CT
	,SUM(ISNULL(UA.TOTAL_CALLS,0))										AS TOTAL_CALLS
	,SUM(ISNULL(UA.AUTHORIZED_WRAP,0))									AS AUTHORIZED_WRAP
	,SUM(ISNULL(UA.CPROD,0))											AS CPROD
	,SUM(ISNULL(UA.MINIMUM_GUARANTEE,0))								AS MINIMUM_GUARANTEE
	,SUM(ISNULL(UA.AUTHORIZED_MINUTES,0))								AS AUTHORIZED_MINUTES

	--  SELECT *
	FROM			WSOL_TB_IMPORTS_HUMACH_INVOICING	UA
	INNER JOIN		DATE_TIME							DT    ON DT.DATE_TIME_KEY = UA.STD_TENANT_START_DATE_TIME_KEY

	WHERE DT.CAL_DATE >= @DTM_BEG AND DT.CAL_DATE <  @DTM_END
	  -- AND ISNULL(UA.ID_EXT,'') IN ('NWA','NPS','NWS','NWR')
	  --AND ( @ID_EXT IN (',0,',',,') OR CHARINDEX(',' + RTRIM(UA.ID_EXT) + ',',@ID_EXT) > 0 )
	  AND (@CUSTOMER_ID	  IN (',0,',',,') OR CHARINDEX(',' + RTRIM(UA.FF_CUSTOMER_ID) + ',',@CUSTOMER_ID) > 0)
	  AND (@INVOICE_GROUP IN (',0,') OR CHARINDEX(',' + RTRIM(UA.INVOICE_ID) + ',',@INVOICE_GROUP) > 0) 
		
	GROUP BY
	 UA.ID_EXT 
	,UA.FF_CUSTOMER_NAME
	,UA.INVOICE_ID
	,UA.STD_TENANT_START_DATE_TIME_KEY
	,CASE WHEN CHARINDEX('_',UA.FF_AGENT_LAST_NAME) > 0 THEN
		LOWER(LEFT(UA.FF_AGENT_FIRST_NAME,1)) + LOWER(LEFT(UA.FF_AGENT_LAST_NAME,CHARINDEX('_',UA.FF_AGENT_LAST_NAME) - 1)) + RIGHT(UA.FF_AGENT_LAST_NAME,3)
	  ELSE
		LOWER(LEFT(UA.FF_AGENT_FIRST_NAME,1)) + LOWER(UA.FF_AGENT_LAST_NAME) END
) UAA

--==============================================================
--==============================================================
IF OBJECT_ID('TEMPDB..#IMPORTS_HUMACH_AGENT_INVOICING_REPORTS_RTN') IS NOT NULL BEGIN
   DROP TABLE #IMPORTS_HUMACH_AGENT_INVOICING_REPORTS_RTN
END
CREATE TABLE #IMPORTS_HUMACH_AGENT_INVOICING_REPORTS_RTN
(GRPNO                 INT
,TENANT_NAME           VARCHAR(50)
,ID_EXT                VARCHAR(3)
,SCHEDULER_ACL_NAME    VARCHAR(100)
,EMPLOYEE_ID           VARCHAR(50)
,RESOURCE_NAME         VARCHAR(100)
,CAL_YEAR_MONTH_NUM    VARCHAR(10)
,DATE_INTERVAL         VARCHAR(50)
,TIME_INTERVAL         VARCHAR(10)

,AIR_DAY_TYPE          varchar(1)
,AIR_ACW_FONT_COLOR    varchar(50)
,MIN_GUARANTEE_MINUTES decimal(6,3)
,MIN_GUARANTEE_TYPE    varchar(50)
,AUTHORIZED_TO_INVOICE_TYPE varchar(50)
,HAS_HOLIDAYS          varchar(1)
,INCLUDE_IN_CAS        varchar(1)
,READY_FOR_XML         varchar(1)
,SHOW_ID_EXTS          varchar(1)

,AIR_HOLIDAY_IN        VARCHAR(1)
,ALL_AUTHORIZED_TIME   DECIMAL(10,2)

,
[LOGGED_IN_SECS] [decimal](10, 2) NULL,
[READY_SECS] [decimal](10, 2) NULL,
[ASSIGNED_SECS] [decimal](10, 2) NULL,
[BUSY_SECS] [decimal](10, 2) NULL,
[NOT_READY_SECS] [decimal](10, 2) NULL,
[AGENT_UNRESPONSIVE_SECS] [decimal](10, 2) NULL,
[POST_LOGIN_SECS] [decimal](10, 2) NULL,
[BREAK_SECS] [decimal](10, 2) NULL,
[WRAP_SECS] [decimal](10, 2) NULL,
[NR_05_SECS] [decimal](10, 2) NULL,
[NR_06_SECS] [decimal](10, 2) NULL,
[NR_07_SECS] [decimal](10, 2) NULL,
[DIAL_PENDING_SECS] [decimal](10, 2) NULL,
[STATE_UNKNOWN_SECS] [decimal](10, 2) NULL,
[Q_IN_CALLS_IN_AGT_ASSIGNED_SECS] [decimal](10, 2) NULL,
[Q_IN_CALLS_IN_AGT_ASSIGNED_FAILED_SECS] [decimal](10, 2) NULL,
[Q_IN_CALLS_IN_AGT_ANS_SECS] [decimal](10, 2) NULL,
[Q_IN_CALLS_AGT_CALLS_TRANS_SECS] [decimal](10, 2) NULL,
[Q_IN_CALLS_IN_AGT_COMPLETED_CALL_TALK_SECS] [decimal](10, 2) NULL,
[Q_IN_CALLS_IN_AGT_COMPLETED_CALL_TIME_SECS] [decimal](10, 2) NULL,
[Q_IN_CALLS_AGT_CALLS_HOLD_SECS] [decimal](10, 2) NULL,
[Q_IN_CALLS_IN_AGT_COMPLETED_CALL_CONNECTED_SECS] [decimal](10, 2) NULL,
[Q_IN_CALLS_IN_AGT_CALLS_HANDLE_SECS] [decimal](10, 2) NULL,
[NON_Q_CALLS_OUT_AGT_CALL_ANS_CALL_TALK_SECS] [decimal](10, 2) NULL,
[NON_Q_CALLS_OUT_AGT_CALL_ANS_CALL_TIME_SECS] [decimal](10, 2) NULL,
[NON_Q_CALLS_OUT_AGT_CALL_ANS_CALL_CONNECTED_SECS] [decimal](10, 2) NULL,
[Q_IN_CALLS_IN_AGT_ASSIGNED_CT] [decimal](10, 2) NULL,
[Q_IN_CALLS_IN_AGT_ASSIGNED_FAILED_CT] [decimal](10, 2) NULL,
[Q_IN_CALLS_IN_AGT_ANS_CT] [decimal](10, 2) NULL,
[Q_IN_CALLS_AGT_CALLS_HOLD_CT] [decimal](10, 2) NULL,
[Q_IN_CALLS_AGT_CALLS_ON_HOLD_CT] [decimal](10, 2) NULL,
[Q_IN_CALLS_AGT_CALLS_TRANS_CT] [decimal](10, 2) NULL,
[Q_IN_CALLS_IN_AGT_CALLS_HANDLE_CT] [decimal](10, 2) NULL,
[Q_IN_CALLS_IN_AGT_COMPLETED_CT] [decimal](10, 2) NULL,
[NON_Q_CALLS_OUT_AGT_CALL_ANS_CT] [decimal](10, 2) NULL,
[NON_Q_CALLS_OUT_AGT_CALL_ATTEMPT_CT] [decimal](10, 2) NULL,
[TOTAL_CALLS] [decimal](10, 2) NULL,
[AUTHORIZED_WRAP] [decimal](10, 2) NULL,
[CPROD] [decimal](10, 2) NULL,
[MINIMUM_GUARANTEE] [decimal](10, 2) NULL,
[AUTHORIZED_MINUTES] [decimal](10, 2) NULL,
)
--==================================


--==================================
INSERT INTO #IMPORTS_HUMACH_AGENT_INVOICING_REPORTS_RTN
SELECT
 20								--AS GRPNO  
,ISNULL(GG.TENANT_NAME       ,'') AS TENANT_NAME
,ISNULL(GG.ID_EXT            ,'') AS ID_EXT
,ISNULL(GG.SCHEDULER_ACL_NAME,'') AS SCHEDULER_ACL_NAME
,ISNULL(GG.EMPLOYEE_ID       ,'') AS EMPLOYEE_ID
,ISNULL(GG.RESOURCE_NAME     ,'') AS RESOURCE_NAME
,ISNULL(GG.CAL_YEAR_MONTH_NUM,'') AS CAL_YEAR_MONTH_NUM
,ISNULL(GG.DI                ,'') AS DI
,ISNULL(GG.TI                ,'') AS TI

,(GG.AIR_DAY_TYPE)                AS AIR_DAY_TYPE
,(GG.AIR_ACW_FONT_COLOR)          AS AIR_ACW_FONT_COLOR
,(GG.MIN_GUARANTEE_MINUTES)       AS MIN_GUARANTEE_MINUTES
,(GG.MIN_GUARANTEE_TYPE)          AS MIN_GUARANTEE_TYPE
,(GG.AUTHORIZED_TO_INVOICE_TYPE)  AS AUTHORIZED_TO_INVOICE_TYPE
,(GG.HAS_HOLIDAYS)                AS HAS_HOLIDAYS
,(GG.INCLUDE_IN_CAS)              AS INCLUDE_IN_CAS
,(GG.READY_FOR_XML)               AS READY_FOR_XML
,(GG.SHOW_ID_EXTS)                AS SHOW_ID_EXTS

,'' --AS AIR_HOLIDAY_IN
,0  --AS ALL_AUTHORIZED_TIME

,CAST((ISNULL(GG.LOGGED_IN_SECS										,0)) / @DS AS DECIMAL(10,2)) AS LOGGED_IN_SECS
,CAST((ISNULL(GG.READY_SECS											,0)) / @DS AS DECIMAL(10,2)) AS READY_SECS
,CAST((ISNULL(GG.ASSIGNED_SECS										,0)) / @DS AS DECIMAL(10,2)) AS ASSIGNED_SECS
,CAST((ISNULL(GG.BUSY_SECS											,0)) / @DS AS DECIMAL(10,2)) AS BUSY_SECS
,CAST((ISNULL(GG.NOT_READY_SECS										,0)) / @DS AS DECIMAL(10,2)) AS NOT_READY_SECS
,CAST((ISNULL(GG.AGENT_UNRESPONSIVE_SECS							,0)) / @DS AS DECIMAL(10,2)) AS AGENT_UNRESPONSIVE_SECS
,CAST((ISNULL(GG.POST_LOGIN_SECS									,0)) / @DS AS DECIMAL(10,2)) AS POST_LOGIN_SECS
,CAST((ISNULL(GG.BREAK_SECS											,0)) / @DS AS DECIMAL(10,2)) AS BREAK_SECS
,CAST((ISNULL(GG.WRAP_SECS											,0)) / @DS AS DECIMAL(10,2)) AS WRAP_SECS
,CAST((ISNULL(GG.NR_05_SECS											,0)) / @DS AS DECIMAL(10,2)) AS NR_05_SECS
,CAST((ISNULL(GG.NR_06_SECS											,0)) / @DS AS DECIMAL(10,2)) AS NR_06_SECS
,CAST((ISNULL(GG.NR_07_SECS											,0)) / @DS AS DECIMAL(10,2)) AS NR_07_SECS
,CAST((ISNULL(GG.DIAL_PENDING_SECS									,0)) / @DS AS DECIMAL(10,2)) AS DIAL_PENDING_SECS
,CAST((ISNULL(GG.STATE_UNKNOWN_SECS									,0)) / @DS AS DECIMAL(10,2)) AS STATE_UNKNOWN_SECS
,CAST((ISNULL(GG.Q_IN_CALLS_IN_AGT_ASSIGNED_SECS					,0)) / @DS AS DECIMAL(10,2)) AS Q_IN_CALLS_IN_AGT_ASSIGNED_SECS
,CAST((ISNULL(GG.Q_IN_CALLS_IN_AGT_ASSIGNED_FAILED_SECS				,0)) / @DS AS DECIMAL(10,2)) AS Q_IN_CALLS_IN_AGT_ASSIGNED_FAILED_SECS
,CAST((ISNULL(GG.Q_IN_CALLS_IN_AGT_ANS_SECS							,0)) / @DS AS DECIMAL(10,2)) AS Q_IN_CALLS_IN_AGT_ANS_SECS
,CAST((ISNULL(GG.Q_IN_CALLS_AGT_CALLS_TRANS_SECS					,0)) / @DS AS DECIMAL(10,2)) AS Q_IN_CALLS_AGT_CALLS_TRANS_SECS
,CAST((ISNULL(GG.Q_IN_CALLS_IN_AGT_COMPLETED_CALL_TALK_SECS			,0)) / @DS AS DECIMAL(10,2)) AS Q_IN_CALLS_IN_AGT_COMPLETED_CALL_TALK_SECS
,CAST((ISNULL(GG.Q_IN_CALLS_IN_AGT_COMPLETED_CALL_TIME_SECS			,0)) / @DS AS DECIMAL(10,2)) AS Q_IN_CALLS_IN_AGT_COMPLETED_CALL_TIME_SECS
,CAST((ISNULL(GG.Q_IN_CALLS_AGT_CALLS_HOLD_SECS						,0)) / @DS AS DECIMAL(10,2)) AS Q_IN_CALLS_AGT_CALLS_HOLD_SECS
,CAST((ISNULL(GG.Q_IN_CALLS_IN_AGT_COMPLETED_CALL_CONNECTED_SECS	,0)) / @DS AS DECIMAL(10,2)) AS Q_IN_CALLS_IN_AGT_COMPLETED_CALL_CONNECTED_SECS
,CAST((ISNULL(GG.Q_IN_CALLS_IN_AGT_CALLS_HANDLE_SECS				,0)) / @DS AS DECIMAL(10,2)) AS Q_IN_CALLS_IN_AGT_CALLS_HANDLE_SECS
,CAST((ISNULL(GG.NON_Q_CALLS_OUT_AGT_CALL_ANS_CALL_TALK_SECS		,0)) / @DS AS DECIMAL(10,2)) AS NON_Q_CALLS_OUT_AGT_CALL_ANS_CALL_TALK_SECS
,CAST((ISNULL(GG.NON_Q_CALLS_OUT_AGT_CALL_ANS_CALL_TIME_SECS		,0)) / @DS AS DECIMAL(10,2)) AS NON_Q_CALLS_OUT_AGT_CALL_ANS_CALL_TIME_SECS
,CAST((ISNULL(GG.NON_Q_CALLS_OUT_AGT_CALL_ANS_CALL_CONNECTED_SECS	,0)) / @DS AS DECIMAL(10,2)) AS NON_Q_CALLS_OUT_AGT_CALL_ANS_CALL_CONNECTED_SECS
,CAST((ISNULL(GG.Q_IN_CALLS_IN_AGT_ASSIGNED_CT						,0))	   AS DECIMAL(10,2)) AS Q_IN_CALLS_IN_AGT_ASSIGNED_CT
,CAST((ISNULL(GG.Q_IN_CALLS_IN_AGT_ASSIGNED_FAILED_CT				,0))	   AS DECIMAL(10,2)) AS Q_IN_CALLS_IN_AGT_ASSIGNED_FAILED_CT
,CAST((ISNULL(GG.Q_IN_CALLS_IN_AGT_ANS_CT							,0))	   AS DECIMAL(10,2)) AS Q_IN_CALLS_IN_AGT_ANS_CT
,CAST((ISNULL(GG.Q_IN_CALLS_AGT_CALLS_HOLD_CT						,0))	   AS DECIMAL(10,2)) AS Q_IN_CALLS_AGT_CALLS_HOLD_CT
,CAST((ISNULL(GG.Q_IN_CALLS_AGT_CALLS_ON_HOLD_CT					,0))	   AS DECIMAL(10,2)) AS Q_IN_CALLS_AGT_CALLS_ON_HOLD_CT
,CAST((ISNULL(GG.Q_IN_CALLS_AGT_CALLS_TRANS_CT						,0))	   AS DECIMAL(10,2)) AS Q_IN_CALLS_AGT_CALLS_TRANS_CT
,CAST((ISNULL(GG.Q_IN_CALLS_IN_AGT_CALLS_HANDLE_CT					,0))	   AS DECIMAL(10,2)) AS Q_IN_CALLS_IN_AGT_CALLS_HANDLE_CT
,CAST((ISNULL(GG.Q_IN_CALLS_IN_AGT_COMPLETED_CT						,0))	   AS DECIMAL(10,2)) AS Q_IN_CALLS_IN_AGT_COMPLETED_CT
,CAST((ISNULL(GG.NON_Q_CALLS_OUT_AGT_CALL_ANS_CT					,0))	   AS DECIMAL(10,2)) AS NON_Q_CALLS_OUT_AGT_CALL_ANS_CT
,CAST((ISNULL(GG.NON_Q_CALLS_OUT_AGT_CALL_ATTEMPT_CT				,0))	   AS DECIMAL(10,2)) AS NON_Q_CALLS_OUT_AGT_CALL_ATTEMPT_CT
,CAST((ISNULL(GG.TOTAL_CALLS										,0))	   AS DECIMAL(10,2)) AS TOTAL_CALLS
,CAST((ISNULL(GG.AUTHORIZED_WRAP									,0)) / @DS AS DECIMAL(10,2)) AS AUTHORIZED_WRAP
,CAST((ISNULL(GG.CPROD												,0)) / @DS AS DECIMAL(10,2)) AS CPROD
,CAST((ISNULL(GG.MINIMUM_GUARANTEE									,0)) / @DS AS DECIMAL(10,2)) AS MINIMUM_GUARANTEE
,CAST((ISNULL(GG.AUTHORIZED_MINUTES									,0)) / @DS AS DECIMAL(10,2)) AS AUTHORIZED_MINUTES

FROM  -- GG STARTS HERE:
(	SELECT
	 ISNULL(SW.TENANT_NAME,'')        AS TENANT_NAME
	,ISNULL(SW.ID_EXT,'')             AS ID_EXT
	,ISNULL(SW.SCHEDULER_ACL_NAME,'') AS SCHEDULER_ACL_NAME
	,ISNULL(SW.EMPLOYEE_ID,'')		  AS EMPLOYEE_ID
	,MAX(RESOURCE_NAME)               AS RESOURCE_NAME

	,(CASE WHEN @TIME_INTERVAL IN ('MR') THEN DT.CAL_YEAR_MONTH_NUM ELSE '' END ) AS CAL_YEAR_MONTH_NUM
	,(CASE WHEN @TIME_INTERVAL IN ('MR') THEN LEFT(DT.CAL_MONTH_NAME,3) + ' ' + DT.CAL_YEAR_STRING
		   WHEN @TIME_INTERVAL IN ('DR') THEN ''  ELSE DT.CAL_DATE_STRING END ) AS DI
	,(CASE --WHEN @TIME_INTERVAL = '15' THEN DT.LABEL_HH24 + ':' + DT.LABEL_MI
		   --WHEN @TIME_INTERVAL = '30' THEN DT.LABEL_HH24 + ':' + DT.LABEL_30MI
		   WHEN @TIME_INTERVAL = 'HR' THEN DT.LABEL_HH24 ELSE '' END ) AS TI

	,MAX(SW.AIR_DAY_TYPE)					AS AIR_DAY_TYPE
	,MAX(SW.AIR_ACW_FONT_COLOR)				AS AIR_ACW_FONT_COLOR
	,MAX(SW.MIN_GUARANTEE_MINUTES)			AS MIN_GUARANTEE_MINUTES
	,MAX(SW.MIN_GUARANTEE_TYPE)				AS MIN_GUARANTEE_TYPE
	,MAX(SW.AUTHORIZED_TO_INVOICE_TYPE)		AS AUTHORIZED_TO_INVOICE_TYPE
	,MAX(SW.HAS_HOLIDAYS)					AS HAS_HOLIDAYS
	,MAX(SW.INCLUDE_IN_CAS)					AS INCLUDE_IN_CAS
	,MAX(SW.READY_FOR_XML)					AS READY_FOR_XML
	,MAX(SW.SHOW_ID_EXTS)					AS SHOW_ID_EXTS
	
	,SUM(ISNULL(SW.LOGGED_IN_SECS									,0)) AS LOGGED_IN_SECS
	,SUM(ISNULL(SW.READY_SECS										,0)) AS READY_SECS
	,SUM(ISNULL(SW.ASSIGNED_SECS									,0)) AS ASSIGNED_SECS
	,SUM(ISNULL(SW.BUSY_SECS										,0)) AS BUSY_SECS
	,SUM(ISNULL(SW.NOT_READY_SECS									,0)) AS NOT_READY_SECS
	,SUM(ISNULL(SW.AGENT_UNRESPONSIVE_SECS							,0)) AS AGENT_UNRESPONSIVE_SECS
	,SUM(ISNULL(SW.POST_LOGIN_SECS									,0)) AS POST_LOGIN_SECS
	,SUM(ISNULL(SW.BREAK_SECS										,0)) AS BREAK_SECS
	,SUM(ISNULL(SW.WRAP_SECS										,0)) AS WRAP_SECS
	,SUM(ISNULL(SW.NR_05_SECS										,0)) AS NR_05_SECS
	,SUM(ISNULL(SW.NR_06_SECS										,0)) AS NR_06_SECS
	,SUM(ISNULL(SW.NR_07_SECS										,0)) AS NR_07_SECS
	,SUM(ISNULL(SW.DIAL_PENDING_SECS								,0)) AS DIAL_PENDING_SECS
	,SUM(ISNULL(SW.STATE_UNKNOWN_SECS								,0)) AS STATE_UNKNOWN_SECS
	,SUM(ISNULL(SW.Q_IN_CALLS_IN_AGT_ASSIGNED_SECS					,0)) AS Q_IN_CALLS_IN_AGT_ASSIGNED_SECS
	,SUM(ISNULL(SW.Q_IN_CALLS_IN_AGT_ASSIGNED_FAILED_SECS			,0)) AS Q_IN_CALLS_IN_AGT_ASSIGNED_FAILED_SECS
	,SUM(ISNULL(SW.Q_IN_CALLS_IN_AGT_ANS_SECS						,0)) AS Q_IN_CALLS_IN_AGT_ANS_SECS
	,SUM(ISNULL(SW.Q_IN_CALLS_AGT_CALLS_TRANS_SECS					,0)) AS Q_IN_CALLS_AGT_CALLS_TRANS_SECS
	,SUM(ISNULL(SW.Q_IN_CALLS_IN_AGT_COMPLETED_CALL_TALK_SECS		,0)) AS Q_IN_CALLS_IN_AGT_COMPLETED_CALL_TALK_SECS
	,SUM(ISNULL(SW.Q_IN_CALLS_IN_AGT_COMPLETED_CALL_TIME_SECS		,0)) AS Q_IN_CALLS_IN_AGT_COMPLETED_CALL_TIME_SECS
	,SUM(ISNULL(SW.Q_IN_CALLS_AGT_CALLS_HOLD_SECS					,0)) AS Q_IN_CALLS_AGT_CALLS_HOLD_SECS
	,SUM(ISNULL(SW.Q_IN_CALLS_IN_AGT_COMPLETED_CALL_CONNECTED_SECS	,0)) AS Q_IN_CALLS_IN_AGT_COMPLETED_CALL_CONNECTED_SECS
	,SUM(ISNULL(SW.Q_IN_CALLS_IN_AGT_CALLS_HANDLE_SECS				,0)) AS Q_IN_CALLS_IN_AGT_CALLS_HANDLE_SECS
	,SUM(ISNULL(SW.NON_Q_CALLS_OUT_AGT_CALL_ANS_CALL_TALK_SECS		,0)) AS NON_Q_CALLS_OUT_AGT_CALL_ANS_CALL_TALK_SECS
	,SUM(ISNULL(SW.NON_Q_CALLS_OUT_AGT_CALL_ANS_CALL_TIME_SECS		,0)) AS NON_Q_CALLS_OUT_AGT_CALL_ANS_CALL_TIME_SECS
	,SUM(ISNULL(SW.NON_Q_CALLS_OUT_AGT_CALL_ANS_CALL_CONNECTED_SECS	,0)) AS NON_Q_CALLS_OUT_AGT_CALL_ANS_CALL_CONNECTED_SECS
	,SUM(ISNULL(SW.Q_IN_CALLS_IN_AGT_ASSIGNED_CT					,0)) AS Q_IN_CALLS_IN_AGT_ASSIGNED_CT
	,SUM(ISNULL(SW.Q_IN_CALLS_IN_AGT_ASSIGNED_FAILED_CT				,0)) AS Q_IN_CALLS_IN_AGT_ASSIGNED_FAILED_CT
	,SUM(ISNULL(SW.Q_IN_CALLS_IN_AGT_ANS_CT							,0)) AS Q_IN_CALLS_IN_AGT_ANS_CT
	,SUM(ISNULL(SW.Q_IN_CALLS_AGT_CALLS_HOLD_CT						,0)) AS Q_IN_CALLS_AGT_CALLS_HOLD_CT
	,SUM(ISNULL(SW.Q_IN_CALLS_AGT_CALLS_ON_HOLD_CT					,0)) AS Q_IN_CALLS_AGT_CALLS_ON_HOLD_CT
	,SUM(ISNULL(SW.Q_IN_CALLS_AGT_CALLS_TRANS_CT					,0)) AS Q_IN_CALLS_AGT_CALLS_TRANS_CT
	,SUM(ISNULL(SW.Q_IN_CALLS_IN_AGT_CALLS_HANDLE_CT				,0)) AS Q_IN_CALLS_IN_AGT_CALLS_HANDLE_CT
	,SUM(ISNULL(SW.Q_IN_CALLS_IN_AGT_COMPLETED_CT					,0)) AS Q_IN_CALLS_IN_AGT_COMPLETED_CT
	,SUM(ISNULL(SW.NON_Q_CALLS_OUT_AGT_CALL_ANS_CT					,0)) AS NON_Q_CALLS_OUT_AGT_CALL_ANS_CT
	,SUM(ISNULL(SW.NON_Q_CALLS_OUT_AGT_CALL_ATTEMPT_CT				,0)) AS NON_Q_CALLS_OUT_AGT_CALL_ATTEMPT_CT
	,SUM(ISNULL(SW.TOTAL_CALLS										,0)) AS TOTAL_CALLS
	,SUM(ISNULL(SW.AUTHORIZED_WRAP									,0)) AS AUTHORIZED_WRAP
	,SUM(ISNULL(SW.CPROD											,0)) AS CPROD
	,SUM(ISNULL(SW.MINIMUM_GUARANTEE								,0)) AS MINIMUM_GUARANTEE
	,SUM(ISNULL(SW.AUTHORIZED_MINUTES								,0)) AS AUTHORIZED_MINUTES
	
	FROM			#IMPORTS_HUMACH_AGENT_INVOICING_REPORTS		SW
	INNER JOIN		DATE_TIME									DT	ON DT.DATE_TIME_KEY = SW.STD_TENANT_START_DATE_TIME_KEY
													 
	--WHERE DT.CAL_DATE >= @DTM_BEG AND DT.CAL_DATE <  @DTM_END		  --AND (@TENANT_KEY   IN ('0','') OR SW.TENANT_KEY   = CAST(@TENANT_KEY AS INT) )

	GROUP BY 
	 ISNULL(SW.TENANT_NAME,'')        --AS TENANT_NAME
	,ISNULL(SW.ID_EXT,'')             --AS ID_EXT
	,ISNULL(SW.SCHEDULER_ACL_NAME,'') --AS SCHEDULER_ACL_NAME
	,ISNULL(SW.EMPLOYEE_ID,'')		  --AS EMPLOYEE_ID

	,(CASE WHEN @TIME_INTERVAL IN ('MR') THEN DT.CAL_YEAR_MONTH_NUM ELSE '' END ) --AS CAL_YEAR_MONTH_NUM
	,(CASE WHEN @TIME_INTERVAL IN ('MR') THEN LEFT(DT.CAL_MONTH_NAME,3) + ' ' + DT.CAL_YEAR_STRING
		   WHEN @TIME_INTERVAL IN ('DR') THEN ''  ELSE DT.CAL_DATE_STRING END ) --AS DI
	,(CASE --WHEN @TIME_INTERVAL = '15' THEN DT.LABEL_HH24 + ':' + DT.LABEL_MI
		   --WHEN @TIME_INTERVAL = '30' THEN DT.LABEL_HH24 + ':' + DT.LABEL_30MI
		   WHEN @TIME_INTERVAL = 'HR' THEN DT.LABEL_HH24 ELSE '' END ) --AS TI
) GG

--==================================
--IS A HOLIDAY DATE IN THE MIX:
--==================================
DECLARE @HOLIDAY_IN VARCHAR(1)
SET @HOLIDAY_IN = 'N'
DECLARE @I INT
SET @I = (SELECT COUNT(*) FROM #IMPORTS_HUMACH_AGENT_INVOICING_REPORTS_RTN WHERE AIR_DAY_TYPE = 'H')  --  AND INCLUDE_IN_CAS = 'Y')
IF @I > 0 BEGIN
	SET @HOLIDAY_IN = 'Y'
END
--==================================
UPDATE #IMPORTS_HUMACH_AGENT_INVOICING_REPORTS_RTN SET
 AIR_HOLIDAY_IN = @HOLIDAY_IN

--=========================================================
--UPDATE TOTALS LINE ON REPORT FOR STANDARD AND HOLIDAY:
--=========================================================
UPDATE #IMPORTS_HUMACH_AGENT_INVOICING_REPORTS_RTN SET
 ALL_AUTHORIZED_TIME = ISNULL(LOJ.ALL_AUTHORIZED_TIME,0.0)
FROM #IMPORTS_HUMACH_AGENT_INVOICING_REPORTS_RTN TA
LEFT OUTER JOIN
(	SELECT
	 SCHEDULER_ACL_NAME
	,EMPLOYEE_ID
	,AIR_DAY_TYPE
	,SUM(AUTHORIZED_MINUTES) AS ALL_AUTHORIZED_TIME
	FROM #IMPORTS_HUMACH_AGENT_INVOICING_REPORTS_RTN 
	GROUP BY 
	 SCHEDULER_ACL_NAME
	,EMPLOYEE_ID
	,AIR_DAY_TYPE
) LOJ ON LOJ.SCHEDULER_ACL_NAME = TA.SCHEDULER_ACL_NAME
	 AND LOJ.EMPLOYEE_ID        = TA.EMPLOYEE_ID
	 AND LOJ.AIR_DAY_TYPE       = TA.AIR_DAY_TYPE

--==================================
--RETURN DATA
--==================================
--=======================================================================================
--POPULATE TABLE READ BY SSIS TO GET END DATE OF DATA REPORT/FILE HAS BEEN RUN FOR:
--=======================================================================================
INSERT INTO WSOL_TB_FILENAMES_FOR_SSIS
(SQL_JOB_NAME
,FILENM
,CST_ROW_CREATED_TIME)
SELECT
 'uspIMPORTS_HUMACH_AGENT_INVOICING_REPORTS'			--SQL_JOB_NAME
,REPLACE(CONVERT(VARCHAR(10),@DTM_END - 1,111),'/','')	--FILENM   YYYYMMDD_...
,dbo.getdate()  --CST_ROW_CREATED_TIME

--=====================================
--RETURN DATASET:
--=====================================
SELECT 
 CASE WHEN @DUR_IN = 'SS' THEN '' ELSE 'F' END AS DUR_FORMAT
,CONVERT(VARCHAR(10),@DTM_BEG,101) + '-' + CONVERT(VARCHAR(10),@DTM_END - 1,101)  AS DATE_RANGE
,V.*

FROM      #IMPORTS_HUMACH_AGENT_INVOICING_REPORTS_RTN  V

ORDER BY 
 V.GRPNO
,V.SCHEDULER_ACL_NAME
,V.EMPLOYEE_ID
,V.CAL_YEAR_MONTH_NUM
,V.DATE_INTERVAL
,V.TIME_INTERVAL  --SINCE IN MILITARY TIME!

--===============================
EARLY_EXIT:
--===============================
--IMPOSSIBLE:  SELECT 1/0    POSSIBLE:  SELECT 0/1