
CREATE PROCEDURE [dbo].[uspIMPORTS_MONAT_AGENT_INVOICING_REPORTS_01]
 @DATE_BEG           DATETIME
,@DATE_END           DATETIME
,@TENANT_KEY         VARCHAR(150) --No multiples even though filter below is setup for multiples.
,@SCHEDULER_GROUP    VARCHAR(150) --Hid. Def=' '
,@ID_EXT             VARCHAR(300) --Hid. Def=' '
,@RESOURCE_KEY       VARCHAR(10)  --Hid. Def='0'
,@TIME_INTERVAL      VARCHAR(10)  --Hid. Def='HR'  HR,DY,DR   FOR SUB: MD(Month by Day),MR(Month Range)  15 and 30 not possible !!!!
,@SHOW_RESOURCE      VARCHAR(1)   --Hid. Def='Y'
,@SHOW_DETAILS		 BIT		  --	 DEF='TRUE'
,@DUR_IN             VARCHAR(2)   --Hid. Def='MM' 
,@RESOURCE_FORMAT    VARCHAR(2)   --Hid. Def='NM' --'NM'=NAME + (employee id),  'ID'=ID
,@SHOW_HOLIDAY       VARCHAR(1)   --Hid. Def='N'
,@PSW                VARCHAR(10)  --Hid. Def='NONE'
,@EXECUTIONER        VARCHAR(3)   --Hid. Def='MAN'  MANual,SUBscription
,@RPT_TYPE_GRP       VARCHAR(3)   --Hid. Def='INV'
,@RPT_TYPE           VARCHAR(3)   --Hid. Def='INV'  
AS
SET NOCOUNT ON    

--  EXECUTE [dbo].[uspIMPORTS_MONAT_AGENT_INVOICING_REPORTS_01] '08/01/2017','08/15/2017','0','0','0','0','HR','Y','SS','NM','Y','4','MAN','INV','INV'

--	@TIME_INTERVAL:  Can show invoicing report at hourly level or higher !!!

--	Durations in FTP FILE are in HH:MM:SS but converted to seconds.  Therefore, reporting may be in seconds, minutes, or hours.

--  SELECT * FROM WSOL_TB_IMPORTS_MONAT_SD_INVOICE_GROUPS
--  SELECT * FROM WSOL_TB_IMPORTS_MONAT_UV_ANT_AIA


--========================================================================================================
DECLARE
 @DTM_BEG AS DATETIME
,@DTM_END AS DATETIME
IF @DATE_BEG < '01/01/1901' BEGIN     
    SET @DTM_BEG = CAST(CONVERT(VARCHAR(10),dbo.getdate() - 1,101) AS DATETIME) 
	SET @DTM_END = CAST(CONVERT(VARCHAR(10),dbo.getdate() - 1,101) AS DATETIME) -- + 1
END
ELSE BEGIN
    SET @DTM_BEG = CAST(CONVERT(VARCHAR(10),@DATE_BEG,101) AS DATETIME) 
    SET @DTM_END = CAST(CONVERT(VARCHAR(10),@DATE_END,101) AS DATETIME) -- + 1
END
SET @DTM_END    = @DTM_END + 1  --EVERYTHING ABOVE, @DTM_END IS FOR EXACT DATE RANGE NEEDED. ONE IS ADDED SO WHERE CLAUSE " < @DTM_END" WORKS.

DECLARE
 @MTD_BEG AS DATETIME
,@MTD_END AS DATETIME  --,@YTD_BEG AS DATETIME--,@YTD_END AS DATETIME
SET @MTD_BEG = CAST(CAST(DATEPART(mm,@DTM_BEG) AS VARCHAR(2)) + '/01/' + CAST(DATEPART(yyyy,@DTM_BEG) AS VARCHAR(4)) AS DATETIME)
SET @MTD_END = @DTM_END  

IF @TIME_INTERVAL IN ('MR','MD') BEGIN  --MONTH DETERMINED BY @DTM_BEG.
	SET @DTM_BEG = @MTD_BEG
	SET @DTM_END = @MTD_END
END

IF @EXECUTIONER = 'DLY' BEGIN
	IF DATEPART(DW,dbo.getdate()) = 2 BEGIN
		SET @DTM_BEG = CAST(CONVERT(VARCHAR(10),dbo.getdate() - 3,101) AS DATETIME)
	END
	ELSE BEGIN
		SET @DTM_BEG = CAST(CONVERT(VARCHAR(10),dbo.getdate() - 1,101) AS DATETIME)
	END
	SET @DTM_END = @DTM_BEG + 1
END

IF @EXECUTIONER = 'WKY' BEGIN
	SET @DTM_BEG = CAST(CONVERT(VARCHAR(10),dbo.getdate() - 7,101) AS DATETIME)
	SET @DTM_END = CAST(CONVERT(VARCHAR(10),dbo.getdate()	 ,101) AS DATETIME)
END

IF @EXECUTIONER = 'MTH' BEGIN
	IF MONTH(dbo.getdate()) = 1
		BEGIN
			SET @DTM_BEG = CONVERT(DATETIME,CONVERT(VARCHAR(6),'12/01/') + CONVERT(VARCHAR(4),YEAR(dbo.getdate())-1))
		END
	ELSE
		BEGIN
			SET @DTM_BEG = CAST(CONVERT(VARCHAR(10), (CONVERT(VARCHAR(2),MONTH(dbo.getdate())-1) + CONVERT(VARCHAR(4),'/01/') + CONVERT(VARCHAR(4),YEAR(dbo.getdate()))),101) AS DATETIME)
		END
	SET @DTM_END = CAST(CONVERT(VARCHAR(10),dbo.getdate(),101) AS DATETIME)
END



--========================================================================
--	SET AMOUNT TO DIVIDE BY:
--========================================================================
DECLARE @DS DECIMAL(10,2)  --SECONDS TO DIVIDE BY.
IF @DUR_IN = 'SS' BEGIN
    SET @DS = 1.00     --DIVIDE SECONDS BY 1  TO GET SAME, SECONDS.
END
IF @DUR_IN = 'MM' BEGIN
    SET @DS = 60.00    --DIVIDE SECONDS BY 60 TO GET MINUTES.
END
IF @DUR_IN = 'HH' BEGIN
    SET @DS = 3600.00  --DIVIDE SECONDS BY 3600 TO GET HOURS.
END

--==================================
--	CREATE TMP TABLE:
--==================================
IF OBJECT_ID('TEMPDB..#IMPORTS_MONAT_AGENT_INVOICING_REPORTS_01') IS NOT NULL BEGIN
   DROP TABLE #IMPORTS_MONAT_AGENT_INVOICING_REPORTS_01
END
CREATE TABLE #IMPORTS_MONAT_AGENT_INVOICING_REPORTS_01
(TENANT_NAME					VARCHAR(50)
,ID_EXT							VARCHAR(3)
,SCHEDULER_ACL_NAME				VARCHAR(100)  
,EMPLOYEE_ID					VARCHAR(50)
,STD_TENANT_START_DATE_TIME_KEY INT
,RESOURCE_NAME					VARCHAR(100)

,AIR_DAY_TYPE					VARCHAR(1)
,AIR_ACW_FONT_COLOR				VARCHAR(50)
,MIN_GUARANTEE_MINUTES			DECIMAL(6,3)
,MIN_GUARANTEE_TYPE				VARCHAR(50)
,AUTHORIZED_TO_INVOICE_TYPE		VARCHAR(50)
,HAS_HOLIDAYS					VARCHAR(1)
,INCLUDE_IN_CAS					VARCHAR(1)
,READY_FOR_XML					VARCHAR(1)
,SHOW_ID_EXTS					VARCHAR(1)
,
[INBOUND_CALLS] [int] NULL,
[OUTBOUND_CALLS] [int] NULL,
[TOTAL_CALLS] [int] NULL,
[LOGGED_IN_DUR] [decimal](10, 2) NULL,
[AVAILABLE_DUR] [decimal](10, 2) NULL,
[BUSY_DUR] [decimal](10, 2) NULL,
[DIRECT_CALL_DUR] [decimal](10, 2) NULL,
[DIRECT_OB_DIAL_DUR] [decimal](10, 2) NULL,
[OFF_WORK_DUR] [decimal](10, 2) NULL,
[UNKNOWN_DUR] [decimal](10, 2) NULL,
[RONA_DUR] [decimal](10, 2) NULL,
[RONA_SPECIAL_PROJECT_DUR] [decimal](10, 2) NULL,
[RONA_SYSTEM_ISSUES_IT_DUR] [decimal](10, 2) NULL,
[RONA_IDLE_DUR] [decimal](10, 2) NULL,
[RONA_CALL_BACK_DUR] [decimal](10, 2) NULL,
[INCALL_DUR] [decimal](10, 2) NULL,
[INCALL_IDLE_DUR] [decimal](10, 2) NULL,
[INCALL_CALL_BACK_DUR] [decimal](10, 2) NULL,
[INCALL_SPECIAL_PROJECT_DUR] [decimal](10, 2) NULL,
[INCALL_ON_BREAK_DUR] [decimal](10, 2) NULL,
[ACW_DUR] [decimal](10, 2) NULL,
[AUTHORIZED_ACW_DUR] [decimal](10, 2) NULL,
[ACW_ON_BREAK_DUR] [decimal](10, 2) NULL,
[ACW_CALL_BACK_DUR] [decimal](10, 2) NULL,
[ACW_IDLE_DUR] [decimal](10, 2) NULL,
[ACW_SPECIAL_PROJECT_DUR] [decimal](10, 2) NULL,
[ACW_FLOOR_SUPPORT_DUR] [decimal](10, 2) NULL,
[ACW_SYSTEM_ISSUES_IT_DUR] [decimal](10, 2) NULL,
[RING_DUR] [decimal](10, 2) NULL,
[RING_BREAK_DUR] [decimal](10, 2) NULL,
[RING_SPECIAL_PROJECT_DUR] [decimal](10, 2) NULL,
[RING_IDLE_DUR] [decimal](10, 2) NULL,
[RING_SYSTEM_ISSUES_IT_DUR] [decimal](10, 2) NULL,
[RING_CALL_BACK_DUR] [decimal](10, 2) NULL,
[UNAVAILABLE_DUR] [decimal](10, 2) NULL,
[UNAVAILABLE_ON_BREAK_DUR] [decimal](10, 2) NULL,
[UNAVAILABLE_CALL_BACK_DUR] [decimal](10, 2) NULL,
[UNAVAILABLE_IDLE_DUR] [decimal](10, 2) NULL,
[UNAVAILABLE_PERSONAL_TIME_DUR] [decimal](10, 2) NULL,
[UNAVAILABLE_RR_DUR] [decimal](10, 2) NULL,
[UNAVAILABLE_SPECIAL_PROJECT_DUR] [decimal](10, 2) NULL,
[UNAVAILABLE_FLOOR_SUPPORT_DUR] [decimal](10, 2) NULL,
[UNAVAILABLE_SYSTEM_ISSUES_IT_DUR] [decimal](10, 2) NULL,
[UNAVAILABLE_EMAIL_DUR] [decimal](10, 2) NULL,
[TOTAL_AVAILABLE] [decimal](10, 2) NULL,
[TOTAL_RING] [decimal](10, 2) NULL,
[TOTAL_TALK] [decimal](10, 2) NULL,
[TOTAL_ACW] [decimal](10, 2) NULL,
[TOTAL_UNAVAILABLE] [decimal](10, 2) NULL,
[TOTAL_RONA] [decimal](10, 2) NULL,
[HANDLE_TIME] [decimal](10, 2) NULL,
[CPROD] [decimal](10, 2) NULL,
[AUTHORIZED] [decimal](10, 2) NULL,
)

INSERT INTO #IMPORTS_MONAT_AGENT_INVOICING_REPORTS_01
SELECT
 'MONAT GLOBAL'	--T.TENANT_NAME
,''					--UAA.ACD_ID_EXTENSION
,UAA.SCHEDULER_ACL_NAME
,UAA.EMPLOYEE_ID
,UAA.STD_TENANT_START_DATE_TIME_KEY
,UAA.RESOURCE_NAME

,(ISNULL(UAA.AIR_DAY_TYPE,''))					--AS AIR_DAY_TYPE
,(ISNULL(UAA.AIR_ACW_FONT_COLOR,''))			--AS AIR_ACW_FONT_COLOR
,(ISNULL(UAA.MIN_GUARANTEE_MINUTES,0.000))		--AS MIN_GUARANTEE_MINUTES
,(ISNULL(UAA.MIN_GUARANTEE_TYPE,''))			--AS MIN_GUARANTEE_TYPE
,(ISNULL(UAA.AUTHORIZED_TO_INVOICE_TYPE,''))	--AS AUTHORIZED_TO_INVOICE_TYPE
,(ISNULL(UAA.HAS_HOLIDAYS,''))					--AS HAS_HOLIDAYS
,(ISNULL(UAA.INCLUDE_IN_CAS,''))				--AS INCLUDE_IN_CAS
,(ISNULL(UAA.READY_FOR_XML,''))					--AS READY_FOR_XML
,(ISNULL(UAA.SHOW_ID_EXTS,''))					--AS SHOW_ID_EXTS

,(ISNULL(UAA.INBOUND_CALLS						,0))
,(ISNULL(UAA.OUTBOUND_CALLS						,0))
,(ISNULL(UAA.TOTAL_CALLS						,0))

,(ISNULL(UAA.LOGGED_IN_DUR						,0.00))
,(ISNULL(UAA.AVAILABLE_DUR						,0.00))
,(ISNULL(UAA.BUSY_DUR							,0.00))
,(ISNULL(UAA.DIRECT_CALL_DUR					,0.00))
,(ISNULL(UAA.DIRECT_OB_DIAL_DUR					,0.00))
,(ISNULL(UAA.OFF_WORK_DUR						,0.00))
,(ISNULL(UAA.UNKNOWN_DUR						,0.00))
,(ISNULL(UAA.RONA_DUR							,0.00))
,(ISNULL(UAA.RONA_SPECIAL_PROJECT_DUR			,0.00))
,(ISNULL(UAA.RONA_SYSTEM_ISSUES_IT_DUR			,0.00))
,(ISNULL(UAA.RONA_IDLE_DUR						,0.00))
,(ISNULL(UAA.RONA_CALL_BACK_DUR					,0.00))
,(ISNULL(UAA.INCALL_DUR							,0.00))
,(ISNULL(UAA.INCALL_IDLE_DUR					,0.00))
,(ISNULL(UAA.INCALL_CALL_BACK_DUR				,0.00))
,(ISNULL(UAA.INCALL_SPECIAL_PROJECT_DUR			,0.00))
,(ISNULL(UAA.INCALL_ON_BREAK_DUR				,0.00))
,(ISNULL(UAA.ACW_DUR							,0.00))
,(ISNULL(UAA.AUTHORIZED_ACW_DUR					,0.00))
,(ISNULL(UAA.ACW_ON_BREAK_DUR					,0.00))
,(ISNULL(UAA.ACW_CALL_BACK_DUR					,0.00))
,(ISNULL(UAA.ACW_IDLE_DUR						,0.00))
,(ISNULL(UAA.ACW_SPECIAL_PROJECT_DUR			,0.00))
,(ISNULL(UAA.ACW_FLOOR_SUPPORT_DUR				,0.00))
,(ISNULL(UAA.ACW_SYSTEM_ISSUES_IT_DUR			,0.00))
,(ISNULL(UAA.RING_DUR							,0.00))
,(ISNULL(UAA.RING_BREAK_DUR						,0.00))
,(ISNULL(UAA.RING_SPECIAL_PROJECT_DUR			,0.00))
,(ISNULL(UAA.RING_IDLE_DUR						,0.00))
,(ISNULL(UAA.RING_SYSTEM_ISSUES_IT_DUR			,0.00))
,(ISNULL(UAA.RING_CALL_BACK_DUR					,0.00))
,(ISNULL(UAA.UNAVAILABLE_DUR					,0.00))
,(ISNULL(UAA.UNAVAILABLE_ON_BREAK_DUR			,0.00))
,(ISNULL(UAA.UNAVAILABLE_CALL_BACK_DUR			,0.00))
,(ISNULL(UAA.UNAVAILABLE_IDLE_DUR				,0.00))
,(ISNULL(UAA.UNAVAILABLE_PERSONAL_TIME_DUR		,0.00))
,(ISNULL(UAA.UNAVAILABLE_RR_DUR					,0.00))
,(ISNULL(UAA.UNAVAILABLE_SPECIAL_PROJECT_DUR	,0.00))
,(ISNULL(UAA.UNAVAILABLE_FLOOR_SUPPORT_DUR		,0.00))
,(ISNULL(UAA.UNAVAILABLE_SYSTEM_ISSUES_IT_DUR	,0.00))
,(ISNULL(UAA.UNAVAILABLE_EMAIL_DUR				,0.00))
,(ISNULL(UAA.TOTAL_AVAILABLE					,0.00))
,(ISNULL(UAA.TOTAL_RING							,0.00))
,(ISNULL(UAA.TOTAL_TALK							,0.00))
,(ISNULL(UAA.TOTAL_ACW							,0.00))
,(ISNULL(UAA.TOTAL_UNAVAILABLE					,0.00))
,(ISNULL(UAA.TOTAL_RONA							,0.00))
,(ISNULL(UAA.HANDLE_TIME						,0.00))
,(ISNULL(UAA.CPROD								,0.00))
,(ISNULL(UAA.AUTHORIZED							,0.00))

--SELECT * FROM WSOL_TB_IMPORTS_MONAT_INVOICING_NEW

FROM
(	SELECT	
	-- UA.TENANT_KEY
	 ''									AS ACD_ID_EXTENSION
	,UA.INVOICE_ID					    AS SCHEDULER_ACL_NAME
	,UA.FF_AGENT						AS EMPLOYEE_ID 
	,UA.STD_TENANT_START_DATE_TIME_KEY
	,MAX(UA.RESOURCE_NAME)              AS RESOURCE_NAME
	,MAX(UA.AIR_DAY_TYPE)               AS AIR_DAY_TYPE
	,'BLACK'                            AS AIR_ACW_FONT_COLOR
	,0									AS MIN_GUARANTEE_MINUTES
	,''									AS MIN_GUARANTEE_TYPE
	,''									AS AUTHORIZED_TO_INVOICE_TYPE
	,'Y'								AS HAS_HOLIDAYS
	,''									AS INCLUDE_IN_CAS
	,''									AS READY_FOR_XML
	,''									AS SHOW_ID_EXTS

	,SUM(ISNULL(UA.INBOUND_CALLS					,0))	AS INBOUND_CALLS
	,SUM(ISNULL(UA.OUTBOUND_CALLS					,0))	AS OUTBOUND_CALLS
	,SUM(ISNULL(UA.TOTAL_CALLS						,0))	AS TOTAL_CALLS

	,SUM(ISNULL(UA.LOGGED_IN_DUR					,0.00))	AS LOGGED_IN_DUR
	,SUM(ISNULL(UA.AVAILABLE_DUR					,0.00))	AS AVAILABLE_DUR
	,SUM(ISNULL(UA.BUSY_DUR							,0.00))	AS BUSY_DUR
	,SUM(ISNULL(UA.DIRECT_CALL_DUR					,0.00))	AS DIRECT_CALL_DUR
	,SUM(ISNULL(UA.DIRECT_OB_DIAL_DUR				,0.00))	AS DIRECT_OB_DIAL_DUR
	,SUM(ISNULL(UA.OFF_WORK_DUR						,0.00))	AS OFF_WORK_DUR
	,SUM(ISNULL(UA.UNKNOWN_DUR						,0.00))	AS UNKNOWN_DUR
	,SUM(ISNULL(UA.RONA_DUR							,0.00))	AS RONA_DUR
	,SUM(ISNULL(UA.RONA_SPECIAL_PROJECT_DUR			,0.00))	AS RONA_SPECIAL_PROJECT_DUR
	,SUM(ISNULL(UA.RONA_SYSTEM_ISSUES_IT_DUR		,0.00))	AS RONA_SYSTEM_ISSUES_IT_DUR
	,SUM(ISNULL(UA.RONA_IDLE_DUR					,0.00))	AS RONA_IDLE_DUR
	,SUM(ISNULL(UA.RONA_CALL_BACK_DUR				,0.00))	AS RONA_CALL_BACK_DUR
	,SUM(ISNULL(UA.INCALL_DUR						,0.00))	AS INCALL_DUR
	,SUM(ISNULL(UA.INCALL_IDLE_DUR					,0.00))	AS INCALL_IDLE_DUR
	,SUM(ISNULL(UA.INCALL_CALL_BACK_DUR				,0.00)) AS INCALL_CALL_BACK_DUR
	,SUM(ISNULL(UA.INCALL_SPECIAL_PROJECT_DUR		,0.00)) AS INCALL_SPECIAL_PROJECT_DUR
	,SUM(ISNULL(UA.INCALL_ON_BREAK_DUR				,0.00)) AS INCALL_ON_BREAK_DUR
	,SUM(ISNULL(UA.ACW_DUR							,0.00)) AS ACW_DUR
	,SUM(ISNULL(UA.AUTHORIZED_ACW_DUR				,0.00)) AS AUTHORIZED_ACW_DUR
	,SUM(ISNULL(UA.ACW_ON_BREAK_DUR					,0.00)) AS ACW_ON_BREAK_DUR
	,SUM(ISNULL(UA.ACW_CALL_BACK_DUR				,0.00)) AS ACW_CALL_BACK_DUR
	,SUM(ISNULL(UA.ACW_IDLE_DUR						,0.00)) AS ACW_IDLE_DUR
	,SUM(ISNULL(UA.ACW_SPECIAL_PROJECT_DUR			,0.00)) AS ACW_SPECIAL_PROJECT_DUR
	,SUM(ISNULL(UA.ACW_FLOOR_SUPPORT_DUR			,0.00)) AS ACW_FLOOR_SUPPORT_DUR
	,SUM(ISNULL(UA.ACW_SYSTEM_ISSUES_IT_DUR			,0.00)) AS ACW_SYSTEM_ISSUES_IT_DUR
	,SUM(ISNULL(UA.RING_DUR							,0.00)) AS RING_DUR
	,SUM(ISNULL(UA.RING_BREAK_DUR					,0.00)) AS RING_BREAK_DUR
	,SUM(ISNULL(UA.RING_SPECIAL_PROJECT_DUR			,0.00)) AS RING_SPECIAL_PROJECT_DUR
	,SUM(ISNULL(UA.RING_IDLE_DUR					,0.00)) AS RING_IDLE_DUR
	,SUM(ISNULL(UA.RING_SYSTEM_ISSUES_IT_DUR		,0.00)) AS RING_SYSTEM_ISSUES_IT_DUR
	,SUM(ISNULL(UA.RING_CALL_BACK_DUR				,0.00)) AS RING_CALL_BACK_DUR
	,SUM(ISNULL(UA.UNAVAILABLE_DUR					,0.00)) AS UNAVAILABLE_DUR
	,SUM(ISNULL(UA.UNAVAILABLE_ON_BREAK_DUR			,0.00)) AS UNAVAILABLE_ON_BREAK_DUR
	,SUM(ISNULL(UA.UNAVAILABLE_CALL_BACK_DUR		,0.00)) AS UNAVAILABLE_CALL_BACK_DUR
	,SUM(ISNULL(UA.UNAVAILABLE_IDLE_DUR				,0.00)) AS UNAVAILABLE_IDLE_DUR
	,SUM(ISNULL(UA.UNAVAILABLE_PERSONAL_TIME_DUR	,0.00)) AS UNAVAILABLE_PERSONAL_TIME_DUR
	,SUM(ISNULL(UA.UNAVAILABLE_RR_DUR				,0.00)) AS UNAVAILABLE_RR_DUR
	,SUM(ISNULL(UA.UNAVAILABLE_SPECIAL_PROJECT_DUR	,0.00)) AS UNAVAILABLE_SPECIAL_PROJECT_DUR
	,SUM(ISNULL(UA.UNAVAILABLE_FLOOR_SUPPORT_DUR	,0.00)) AS UNAVAILABLE_FLOOR_SUPPORT_DUR
	,SUM(ISNULL(UA.UNAVAILABLE_SYSTEM_ISSUES_IT_DUR	,0.00)) AS UNAVAILABLE_SYSTEM_ISSUES_IT_DUR
	,SUM(ISNULL(UA.UNAVAILABLE_EMAIL_DUR			,0.00)) AS UNAVAILABLE_EMAIL_DUR
	,SUM(ISNULL(UA.TOTAL_AVAILABLE					,0.00)) AS TOTAL_AVAILABLE
	,SUM(ISNULL(UA.TOTAL_RING						,0.00)) AS TOTAL_RING
	,SUM(ISNULL(UA.TOTAL_TALK						,0.00)) AS TOTAL_TALK
	,SUM(ISNULL(UA.TOTAL_ACW						,0.00)) AS TOTAL_ACW
	,SUM(ISNULL(UA.TOTAL_UNAVAILABLE				,0.00)) AS TOTAL_UNAVAILABLE
	,SUM(ISNULL(UA.TOTAL_RONA						,0.00)) AS TOTAL_RONA
	,SUM(ISNULL(UA.HANDLE_TIME						,0.00)) AS HANDLE_TIME
	,SUM(ISNULL(UA.CPROD							,0.00))	AS CPROD
	,SUM(ISNULL(UA.AUTHORIZED						,0.00))	AS AUTHORIZED
	
	--  SELECT *
	FROM            WSOL_TB_IMPORTS_MONAT_INVOICING_NEW	UA
	INNER JOIN      DATE_TIME							DT	ON DT.DATE_TIME_KEY = UA.STD_TENANT_START_DATE_TIME_KEY

	WHERE DT.CAL_DATE >= @DTM_BEG AND DT.CAL_DATE <  @DTM_END
		
	GROUP BY 
	 UA.INVOICE_ID
	,UA.FF_AGENT
	,UA.STD_TENANT_START_DATE_TIME_KEY
) UAA

--==============================================================
-- CREATE TEMPORARY TABLE TO RETURN RESULTS
--==============================================================
IF OBJECT_ID('TEMPDB..#IMPORTS_MONAT_AGENT_INVOICING_REPORTS_RTN_01') IS NOT NULL BEGIN
   DROP TABLE #IMPORTS_MONAT_AGENT_INVOICING_REPORTS_RTN_01
END
CREATE TABLE #IMPORTS_MONAT_AGENT_INVOICING_REPORTS_RTN_01
(GRPNO                 INT
,TENANT_NAME           VARCHAR(50)
,ID_EXT                VARCHAR(3)
,SCHEDULER_ACL_NAME    VARCHAR(100)
,EMPLOYEE_ID           VARCHAR(50)
,RESOURCE_NAME         VARCHAR(100)
,CAL_YEAR_MONTH_NUM    VARCHAR(10)
,DATE_INTERVAL         VARCHAR(50)
,TIME_INTERVAL         VARCHAR(10)

,AIR_DAY_TYPE				varchar(1)
,AIR_ACW_FONT_COLOR			varchar(50)
,MIN_GUARANTEE_MINUTES		decimal(6,3)
,MIN_GUARANTEE_TYPE			varchar(50)
,AUTHORIZED_TO_INVOICE_TYPE	varchar(50)
,HAS_HOLIDAYS				varchar(1)
,INCLUDE_IN_CAS				varchar(1)
,READY_FOR_XML				varchar(1)
,SHOW_ID_EXTS				varchar(1)

,AIR_HOLIDAY_IN				VARCHAR(1)
,ALL_AUTHORIZED_TIME		DECIMAL(10,2)

,
[INBOUND_CALLS] [int] NULL,
[OUTBOUND_CALLS] [int] NULL,
[TOTAL_CALLS] [int] NULL,
[LOGGED_IN_DUR] [decimal](10, 2) NULL,
[AVAILABLE_DUR] [decimal](10, 2) NULL,
[BUSY_DUR] [decimal](10, 2) NULL,
[DIRECT_CALL_DUR] [decimal](10, 2) NULL,
[DIRECT_OB_DIAL_DUR] [decimal](10, 2) NULL,
[OFF_WORK_DUR] [decimal](10, 2) NULL,
[UNKNOWN_DUR] [decimal](10, 2) NULL,
[RONA_DUR] [decimal](10, 2) NULL,
[RONA_SPECIAL_PROJECT_DUR] [decimal](10, 2) NULL,
[RONA_SYSTEM_ISSUES_IT_DUR] [decimal](10, 2) NULL,
[RONA_IDLE_DUR] [decimal](10, 2) NULL,
[RONA_CALL_BACK_DUR] [decimal](10, 2) NULL,
[INCALL_DUR] [decimal](10, 2) NULL,
[INCALL_IDLE_DUR] [decimal](10, 2) NULL,
[INCALL_CALL_BACK_DUR] [decimal](10, 2) NULL,
[INCALL_SPECIAL_PROJECT_DUR] [decimal](10, 2) NULL,
[INCALL_ON_BREAK_DUR] [decimal](10, 2) NULL,
[ACW_DUR] [decimal](10, 2) NULL,
[AUTHORIZED_ACW_DUR] [decimal](10, 2) NULL,
[ACW_ON_BREAK_DUR] [decimal](10, 2) NULL,
[ACW_CALL_BACK_DUR] [decimal](10, 2) NULL,
[ACW_IDLE_DUR] [decimal](10, 2) NULL,
[ACW_SPECIAL_PROJECT_DUR] [decimal](10, 2) NULL,
[ACW_FLOOR_SUPPORT_DUR] [decimal](10, 2) NULL,
[ACW_SYSTEM_ISSUES_IT_DUR] [decimal](10, 2) NULL,
[RING_DUR] [decimal](10, 2) NULL,
[RING_BREAK_DUR] [decimal](10, 2) NULL,
[RING_SPECIAL_PROJECT_DUR] [decimal](10, 2) NULL,
[RING_IDLE_DUR] [decimal](10, 2) NULL,
[RING_SYSTEM_ISSUES_IT_DUR] [decimal](10, 2) NULL,
[RING_CALL_BACK_DUR] [decimal](10, 2) NULL,
[UNAVAILABLE_DUR] [decimal](10, 2) NULL,
[UNAVAILABLE_ON_BREAK_DUR] [decimal](10, 2) NULL,
[UNAVAILABLE_CALL_BACK_DUR] [decimal](10, 2) NULL,
[UNAVAILABLE_IDLE_DUR] [decimal](10, 2) NULL,
[UNAVAILABLE_PERSONAL_TIME_DUR] [decimal](10, 2) NULL,
[UNAVAILABLE_RR_DUR] [decimal](10, 2) NULL,
[UNAVAILABLE_SPECIAL_PROJECT_DUR] [decimal](10, 2) NULL,
[UNAVAILABLE_FLOOR_SUPPORT_DUR] [decimal](10, 2) NULL,
[UNAVAILABLE_SYSTEM_ISSUES_IT_DUR] [decimal](10, 2) NULL,
[UNAVAILABLE_EMAIL_DUR] [decimal](10, 2) NULL,
[TOTAL_AVAILABLE] [decimal](10, 2) NULL,
[TOTAL_RING] [decimal](10, 2) NULL,
[TOTAL_TALK] [decimal](10, 2) NULL,
[TOTAL_ACW] [decimal](10, 2) NULL,
[TOTAL_UNAVAILABLE] [decimal](10, 2) NULL,
[TOTAL_RONA] [decimal](10, 2) NULL,
[HANDLE_TIME] [decimal](10, 2) NULL,
[CPROD] [decimal](10, 2) NULL,
[AUTHORIZED] [decimal](10, 2) NULL,
)

--==================================
-- POPULATE TEMPORARY TABLE
--==================================
INSERT INTO #IMPORTS_MONAT_AGENT_INVOICING_REPORTS_RTN_01
SELECT
 20								--AS GRPNO  
,ISNULL(GG.TENANT_NAME       ,'') AS TENANT_NAME
,ISNULL(GG.ID_EXT            ,'') AS ID_EXT
,ISNULL(GG.SCHEDULER_ACL_NAME,'') AS SCHEDULER_ACL_NAME
,ISNULL(GG.EMPLOYEE_ID       ,'') AS EMPLOYEE_ID
,ISNULL(GG.RESOURCE_NAME     ,'') AS RESOURCE_NAME
,ISNULL(GG.CAL_YEAR_MONTH_NUM,'') AS CAL_YEAR_MONTH_NUM
,ISNULL(GG.DI                ,'') AS DI
,ISNULL(GG.TI                ,'') AS TI

,(GG.AIR_DAY_TYPE)                AS AIR_DAY_TYPE
,(GG.AIR_ACW_FONT_COLOR)          AS AIR_ACW_FONT_COLOR
,(GG.MIN_GUARANTEE_MINUTES)       AS MIN_GUARANTEE_MINUTES
,(GG.MIN_GUARANTEE_TYPE)          AS MIN_GUARANTEE_TYPE
,(GG.AUTHORIZED_TO_INVOICE_TYPE)  AS AUTHORIZED_TO_INVOICE_TYPE
,(GG.HAS_HOLIDAYS)                AS HAS_HOLIDAYS
,(GG.INCLUDE_IN_CAS)              AS INCLUDE_IN_CAS
,(GG.READY_FOR_XML)               AS READY_FOR_XML
,(GG.SHOW_ID_EXTS)                AS SHOW_ID_EXTS

,'' --AS AIR_HOLIDAY_IN
,0  --AS ALL_AUTHORIZED_TIME

,ISNULL(GG.INBOUND_CALLS							,0)								AS INBOUND_CALLS
,ISNULL(GG.OUTBOUND_CALLS							,0)								AS OUTBOUND_CALLS
,ISNULL(GG.TOTAL_CALLS								,0)								AS TOTAL_CALLS

,CAST((ISNULL(GG.LOGGED_IN_DUR						,0.00)) / @DS AS DECIMAL(10,2))	AS LOGGED_IN_DUR
,CAST((ISNULL(GG.AVAILABLE_DUR						,0.00)) / @DS AS DECIMAL(10,2))	AS AVAILABLE_DUR
,CAST((ISNULL(GG.BUSY_DUR							,0.00)) / @DS AS DECIMAL(10,2))	AS BUSY_DUR
,CAST((ISNULL(GG.DIRECT_CALL_DUR					,0.00)) / @DS AS DECIMAL(10,2))	AS DIRECT_CALL_DUR
,CAST((ISNULL(GG.DIRECT_OB_DIAL_DUR					,0.00)) / @DS AS DECIMAL(10,2)) AS DIRECT_OB_DIAL_DUR
,CAST((ISNULL(GG.OFF_WORK_DUR						,0.00)) / @DS AS DECIMAL(10,2))	AS OFF_WORK_DUR
,CAST((ISNULL(GG.UNKNOWN_DUR						,0.00)) / @DS AS DECIMAL(10,2))	AS UNKNOWN_DUR
,CAST((ISNULL(GG.RONA_DUR							,0.00)) / @DS AS DECIMAL(10,2))	AS RONA_DUR
,CAST((ISNULL(GG.RONA_SPECIAL_PROJECT_DUR			,0.00)) / @DS AS DECIMAL(10,2))	AS RONA_SPECIAL_PROJECT_DUR
,CAST((ISNULL(GG.RONA_SYSTEM_ISSUES_IT_DUR			,0.00)) / @DS AS DECIMAL(10,2)) AS RONA_SYSTEM_ISSUES_IT_DUR
,CAST((ISNULL(GG.RONA_IDLE_DUR						,0.00)) / @DS AS DECIMAL(10,2)) AS RONA_IDLE_DUR
,CAST((ISNULL(GG.RONA_CALL_BACK_DUR					,0.00)) / @DS AS DECIMAL(10,2)) AS RONA_CALL_BACK_DUR
,CAST((ISNULL(GG.INCALL_DUR							,0.00)) / @DS AS DECIMAL(10,2)) AS INCALL_DUR
,CAST((ISNULL(GG.INCALL_IDLE_DUR					,0.00)) / @DS AS DECIMAL(10,2)) AS INCALL_IDLE_DUR
,CAST((ISNULL(GG.INCALL_CALL_BACK_DUR				,0.00)) / @DS AS DECIMAL(10,2)) AS INCALL_CALL_BACK_DUR
,CAST((ISNULL(GG.INCALL_SPECIAL_PROJECT_DUR			,0.00)) / @DS AS DECIMAL(10,2)) AS INCALL_SPECIAL_PROJECT_DUR
,CAST((ISNULL(GG.INCALL_ON_BREAK_DUR				,0.00)) / @DS AS DECIMAL(10,2)) AS INCALL_ON_BREAK_DUR
,CAST((ISNULL(GG.ACW_DUR							,0.00)) / @DS AS DECIMAL(10,2)) AS ACW_DUR
,CAST((ISNULL(GG.AUTHORIZED_ACW_DUR					,0.00)) / @DS AS DECIMAL(10,2)) AS AUTHORIZED_ACW_DUR
,CAST((ISNULL(GG.ACW_ON_BREAK_DUR					,0.00)) / @DS AS DECIMAL(10,2)) AS ACW_ON_BREAK_DUR
,CAST((ISNULL(GG.ACW_CALL_BACK_DUR					,0.00)) / @DS AS DECIMAL(10,2)) AS ACW_CALL_BACK_DUR
,CAST((ISNULL(GG.ACW_IDLE_DUR						,0.00)) / @DS AS DECIMAL(10,2)) AS ACW_IDLE_DUR
,CAST((ISNULL(GG.ACW_SPECIAL_PROJECT_DUR			,0.00)) / @DS AS DECIMAL(10,2)) AS ACW_SPECIAL_PROJECT_DUR
,CAST((ISNULL(GG.ACW_FLOOR_SUPPORT_DUR				,0.00)) / @DS AS DECIMAL(10,2)) AS ACW_FLOOR_SUPPORT_DUR
,CAST((ISNULL(GG.ACW_SYSTEM_ISSUES_IT_DUR			,0.00)) / @DS AS DECIMAL(10,2)) AS ACW_SYSTEM_ISSUES_IT_DUR
,CAST((ISNULL(GG.RING_DUR							,0.00)) / @DS AS DECIMAL(10,2)) AS RING_DUR
,CAST((ISNULL(GG.RING_BREAK_DUR						,0.00)) / @DS AS DECIMAL(10,2)) AS RING_BREAK_DUR
,CAST((ISNULL(GG.RING_SPECIAL_PROJECT_DUR			,0.00)) / @DS AS DECIMAL(10,2)) AS RING_SPECIAL_PROJECT_DUR
,CAST((ISNULL(GG.RING_IDLE_DUR						,0.00)) / @DS AS DECIMAL(10,2)) AS RING_IDLE_DUR
,CAST((ISNULL(GG.RING_SYSTEM_ISSUES_IT_DUR			,0.00)) / @DS AS DECIMAL(10,2)) AS RING_SYSTEM_ISSUES_IT_DUR
,CAST((ISNULL(GG.RING_CALL_BACK_DUR					,0.00)) / @DS AS DECIMAL(10,2)) AS RING_CALL_BACK_DUR
,CAST((ISNULL(GG.UNAVAILABLE_DUR					,0.00)) / @DS AS DECIMAL(10,2)) AS UNAVAILABLE_DUR
,CAST((ISNULL(GG.UNAVAILABLE_ON_BREAK_DUR			,0.00)) / @DS AS DECIMAL(10,2)) AS UNAVAILABLE_ON_BREAK_DUR
,CAST((ISNULL(GG.UNAVAILABLE_CALL_BACK_DUR			,0.00)) / @DS AS DECIMAL(10,2)) AS UNAVAILABLE_CALL_BACK_DUR
,CAST((ISNULL(GG.UNAVAILABLE_IDLE_DUR				,0.00)) / @DS AS DECIMAL(10,2)) AS UNAVAILABLE_IDLE_DUR
,CAST((ISNULL(GG.UNAVAILABLE_PERSONAL_TIME_DUR		,0.00)) / @DS AS DECIMAL(10,2)) AS UNAVAILABLE_PERSONAL_TIME_DUR
,CAST((ISNULL(GG.UNAVAILABLE_RR_DUR					,0.00)) / @DS AS DECIMAL(10,2)) AS UNAVAILABLE_RR_DUR
,CAST((ISNULL(GG.UNAVAILABLE_SPECIAL_PROJECT_DUR	,0.00)) / @DS AS DECIMAL(10,2)) AS UNAVAILABLE_SPECIAL_PROJECT_DUR
,CAST((ISNULL(GG.UNAVAILABLE_FLOOR_SUPPORT_DUR		,0.00)) / @DS AS DECIMAL(10,2)) AS UNAVAILABLE_FLOOR_SUPPORT_DUR
,CAST((ISNULL(GG.UNAVAILABLE_SYSTEM_ISSUES_IT_DUR	,0.00)) / @DS AS DECIMAL(10,2)) AS UNAVAILABLE_SYSTEM_ISSUES_IT_DUR
,CAST((ISNULL(GG.UNAVAILABLE_EMAIL_DUR				,0.00)) / @DS AS DECIMAL(10,2)) AS UNAVAILABLE_EMAIL_DUR
,CAST((ISNULL(GG.TOTAL_AVAILABLE					,0.00)) / @DS AS DECIMAL(10,2)) AS TOTAL_AVAILABLE
,CAST((ISNULL(GG.TOTAL_RING							,0.00)) / @DS AS DECIMAL(10,2)) AS TOTAL_RING
,CAST((ISNULL(GG.TOTAL_TALK							,0.00)) / @DS AS DECIMAL(10,2)) AS TOTAL_TALK
,CAST((ISNULL(GG.TOTAL_ACW							,0.00)) / @DS AS DECIMAL(10,2)) AS TOTAL_ACW
,CAST((ISNULL(GG.TOTAL_UNAVAILABLE					,0.00)) / @DS AS DECIMAL(10,2)) AS TOTAL_UNAVAILABLE
,CAST((ISNULL(GG.TOTAL_RONA							,0.00)) / @DS AS DECIMAL(10,2)) AS TOTAL_RONA
,CAST((ISNULL(GG.HANDLE_TIME						,0.00)) / @DS AS DECIMAL(10,2)) AS HANDLE_TIME
,CAST((ISNULL(GG.CPROD								,0.00)) / @DS AS DECIMAL(10,2))	AS CPROD
,CAST((ISNULL(GG.AUTHORIZED							,0.00)) / @DS AS DECIMAL(10,2))	AS AUTHORIZED


FROM  -- GG STARTS HERE:
(	SELECT
	 ISNULL(SW.TENANT_NAME,'')        AS TENANT_NAME
	,ISNULL(SW.ID_EXT,'')             AS ID_EXT
	,ISNULL(SW.SCHEDULER_ACL_NAME,'') AS SCHEDULER_ACL_NAME
	,ISNULL(SW.EMPLOYEE_ID,'')		  AS EMPLOYEE_ID
	,MAX(RESOURCE_NAME)               AS RESOURCE_NAME

	,(CASE WHEN @TIME_INTERVAL IN ('MR') THEN DT.CAL_YEAR_MONTH_NUM ELSE '' END ) AS CAL_YEAR_MONTH_NUM
	,(CASE WHEN @TIME_INTERVAL IN ('MR') THEN LEFT(DT.CAL_MONTH_NAME,3) + ' ' + DT.CAL_YEAR_STRING
		   WHEN @TIME_INTERVAL IN ('DR') THEN ''  ELSE DT.CAL_DATE_STRING END ) AS DI
	,(CASE --WHEN @TIME_INTERVAL = '15' THEN DT.LABEL_HH24 + ':' + DT.LABEL_MI
		   --WHEN @TIME_INTERVAL = '30' THEN DT.LABEL_HH24 + ':' + DT.LABEL_30MI
		   WHEN @TIME_INTERVAL = 'HR' THEN DT.LABEL_HH24 ELSE '' END ) AS TI

	,MAX(SW.AIR_DAY_TYPE)               AS AIR_DAY_TYPE
	,MAX(SW.AIR_ACW_FONT_COLOR)         AS AIR_ACW_FONT_COLOR
	,MAX(SW.MIN_GUARANTEE_MINUTES)      AS MIN_GUARANTEE_MINUTES
	,MAX(SW.MIN_GUARANTEE_TYPE)         AS MIN_GUARANTEE_TYPE
	,MAX(SW.AUTHORIZED_TO_INVOICE_TYPE) AS AUTHORIZED_TO_INVOICE_TYPE
	,MAX(SW.HAS_HOLIDAYS)               AS HAS_HOLIDAYS
	,MAX(SW.INCLUDE_IN_CAS)             AS INCLUDE_IN_CAS
	,MAX(SW.READY_FOR_XML)              AS READY_FOR_XML
	,MAX(SW.SHOW_ID_EXTS)               AS SHOW_ID_EXTS

	,SUM(ISNULL(SW.INBOUND_CALLS					,0))	AS INBOUND_CALLS
	,SUM(ISNULL(SW.OUTBOUND_CALLS					,0))	AS OUTBOUND_CALLS
	,SUM(ISNULL(SW.TOTAL_CALLS						,0))	AS TOTAL_CALLS

	,SUM(ISNULL(SW.LOGGED_IN_DUR					,0.00))	AS LOGGED_IN_DUR
	,SUM(ISNULL(SW.AVAILABLE_DUR					,0.00))	AS AVAILABLE_DUR
	,SUM(ISNULL(SW.BUSY_DUR							,0.00))	AS BUSY_DUR
	,SUM(ISNULL(SW.DIRECT_CALL_DUR					,0.00))	AS DIRECT_CALL_DUR
	,SUM(ISNULL(SW.DIRECT_OB_DIAL_DUR				,0.00)) AS DIRECT_OB_DIAL_DUR
	,SUM(ISNULL(SW.OFF_WORK_DUR						,0.00))	AS OFF_WORK_DUR
	,SUM(ISNULL(SW.UNKNOWN_DUR						,0.00))	AS UNKNOWN_DUR
	,SUM(ISNULL(SW.RONA_DUR							,0.00))	AS RONA_DUR
	,SUM(ISNULL(SW.RONA_SPECIAL_PROJECT_DUR			,0.00))	AS RONA_SPECIAL_PROJECT_DUR
	,SUM(ISNULL(SW.RONA_SYSTEM_ISSUES_IT_DUR		,0.00))	AS RONA_SYSTEM_ISSUES_IT_DUR
	,SUM(ISNULL(SW.RONA_IDLE_DUR					,0.00))	AS RONA_IDLE_DUR
	,SUM(ISNULL(SW.RONA_CALL_BACK_DUR				,0.00))	AS RONA_CALL_BACK_DUR
	,SUM(ISNULL(SW.INCALL_DUR						,0.00))	AS INCALL_DUR
	,SUM(ISNULL(SW.INCALL_IDLE_DUR					,0.00))	AS INCALL_IDLE_DUR
	,SUM(ISNULL(SW.INCALL_CALL_BACK_DUR				,0.00))	AS INCALL_CALL_BACK_DUR
	,SUM(ISNULL(SW.INCALL_SPECIAL_PROJECT_DUR		,0.00))	AS INCALL_SPECIAL_PROJECT_DUR
	,SUM(ISNULL(SW.INCALL_ON_BREAK_DUR				,0.00))	AS INCALL_ON_BREAK_DUR
	,SUM(ISNULL(SW.ACW_DUR							,0.00))	AS ACW_DUR
	,SUM(ISNULL(SW.AUTHORIZED_ACW_DUR				,0.00)) AS AUTHORIZED_ACW_DUR
	,SUM(ISNULL(SW.ACW_ON_BREAK_DUR					,0.00))	AS ACW_ON_BREAK_DUR
	,SUM(ISNULL(SW.ACW_CALL_BACK_DUR				,0.00))	AS ACW_CALL_BACK_DUR
	,SUM(ISNULL(SW.ACW_IDLE_DUR						,0.00))	AS ACW_IDLE_DUR
	,SUM(ISNULL(SW.ACW_SPECIAL_PROJECT_DUR			,0.00))	AS ACW_SPECIAL_PROJECT_DUR
	,SUM(ISNULL(SW.ACW_FLOOR_SUPPORT_DUR			,0.00))	AS ACW_FLOOR_SUPPORT_DUR
	,SUM(ISNULL(SW.ACW_SYSTEM_ISSUES_IT_DUR			,0.00))	AS ACW_SYSTEM_ISSUES_IT_DUR
	,SUM(ISNULL(SW.RING_DUR							,0.00))	AS RING_DUR
	,SUM(ISNULL(SW.RING_BREAK_DUR					,0.00))	AS RING_BREAK_DUR
	,SUM(ISNULL(SW.RING_SPECIAL_PROJECT_DUR			,0.00))	AS RING_SPECIAL_PROJECT_DUR
	,SUM(ISNULL(SW.RING_IDLE_DUR					,0.00))	AS RING_IDLE_DUR
	,SUM(ISNULL(SW.RING_SYSTEM_ISSUES_IT_DUR		,0.00))	AS RING_SYSTEM_ISSUES_IT_DUR
	,SUM(ISNULL(SW.RING_CALL_BACK_DUR				,0.00))	AS RING_CALL_BACK_DUR
	,SUM(ISNULL(SW.UNAVAILABLE_DUR					,0.00))	AS UNAVAILABLE_DUR
	,SUM(ISNULL(SW.UNAVAILABLE_ON_BREAK_DUR			,0.00))	AS UNAVAILABLE_ON_BREAK_DUR
	,SUM(ISNULL(SW.UNAVAILABLE_CALL_BACK_DUR		,0.00))	AS UNAVAILABLE_CALL_BACK_DUR
	,SUM(ISNULL(SW.UNAVAILABLE_IDLE_DUR				,0.00))	AS UNAVAILABLE_IDLE_DUR
	,SUM(ISNULL(SW.UNAVAILABLE_PERSONAL_TIME_DUR	,0.00))	AS UNAVAILABLE_PERSONAL_TIME_DUR
	,SUM(ISNULL(SW.UNAVAILABLE_RR_DUR				,0.00))	AS UNAVAILABLE_RR_DUR
	,SUM(ISNULL(SW.UNAVAILABLE_SPECIAL_PROJECT_DUR	,0.00))	AS UNAVAILABLE_SPECIAL_PROJECT_DUR
	,SUM(ISNULL(SW.UNAVAILABLE_FLOOR_SUPPORT_DUR	,0.00))	AS UNAVAILABLE_FLOOR_SUPPORT_DUR
	,SUM(ISNULL(SW.UNAVAILABLE_SYSTEM_ISSUES_IT_DUR	,0.00))	AS UNAVAILABLE_SYSTEM_ISSUES_IT_DUR
	,SUM(ISNULL(SW.UNAVAILABLE_EMAIL_DUR			,0.00))	AS UNAVAILABLE_EMAIL_DUR
	,SUM(ISNULL(SW.TOTAL_AVAILABLE					,0.00))	AS TOTAL_AVAILABLE
	,SUM(ISNULL(SW.TOTAL_RING						,0.00))	AS TOTAL_RING
	,SUM(ISNULL(SW.TOTAL_TALK						,0.00))	AS TOTAL_TALK
	,SUM(ISNULL(SW.TOTAL_ACW						,0.00))	AS TOTAL_ACW
	,SUM(ISNULL(SW.TOTAL_UNAVAILABLE				,0.00))	AS TOTAL_UNAVAILABLE
	,SUM(ISNULL(SW.TOTAL_RONA						,0.00))	AS TOTAL_RONA
	,SUM(ISNULL(SW.HANDLE_TIME						,0.00)) AS HANDLE_TIME
	,SUM(ISNULL(SW.CPROD							,0.00))	AS CPROD
	,SUM(ISNULL(SW.AUTHORIZED						,0.00))	AS AUTHORIZED
	
	FROM            #IMPORTS_MONAT_AGENT_INVOICING_REPORTS_01	SW
	INNER JOIN      DATE_TIME									DT   ON DT.DATE_TIME_KEY	=	SW.STD_TENANT_START_DATE_TIME_KEY

	GROUP BY 
	 ISNULL(SW.TENANT_NAME,'')        --AS TENANT_NAME
	,ISNULL(SW.ID_EXT,'')             --AS ID_EXT
	,ISNULL(SW.SCHEDULER_ACL_NAME,'') --AS SCHEDULER_ACL_NAME
	,ISNULL(SW.EMPLOYEE_ID,'')		  --AS EMPLOYEE_ID

	,(CASE WHEN @TIME_INTERVAL IN ('MR') THEN DT.CAL_YEAR_MONTH_NUM ELSE '' END ) --AS CAL_YEAR_MONTH_NUM
	,(CASE WHEN @TIME_INTERVAL IN ('MR') THEN LEFT(DT.CAL_MONTH_NAME,3) + ' ' + DT.CAL_YEAR_STRING
		   WHEN @TIME_INTERVAL IN ('DR') THEN ''  ELSE DT.CAL_DATE_STRING END ) --AS DI
	,(CASE --WHEN @TIME_INTERVAL = '15' THEN DT.LABEL_HH24 + ':' + DT.LABEL_MI
		   --WHEN @TIME_INTERVAL = '30' THEN DT.LABEL_HH24 + ':' + DT.LABEL_30MI
		   WHEN @TIME_INTERVAL = 'HR' THEN DT.LABEL_HH24 ELSE '' END ) --AS TI

) GG

--==================================
--IS A HOLIDAY DATE IN THE MIX:
--==================================
DECLARE @HOLIDAY_IN VARCHAR(1)
SET @HOLIDAY_IN = 'N'
DECLARE @I INT
SET @I = (SELECT COUNT(*) FROM #IMPORTS_MONAT_AGENT_INVOICING_REPORTS_RTN_01 WHERE AIR_DAY_TYPE = 'H')  --  AND INCLUDE_IN_CAS = 'Y')
IF @I > 0 BEGIN
	SET @HOLIDAY_IN = 'Y'
END
--==================================
UPDATE #IMPORTS_MONAT_AGENT_INVOICING_REPORTS_RTN_01 SET
 AIR_HOLIDAY_IN = @HOLIDAY_IN

--======================================================
--UPDATE TOTALS LINE ON REPORT FOR STANDARD AND HOLIDAY:
--======================================================
UPDATE #IMPORTS_MONAT_AGENT_INVOICING_REPORTS_RTN_01 SET
 ALL_AUTHORIZED_TIME = ISNULL(LOJ.ALL_AUTHORIZED_TIME,0.0)
FROM #IMPORTS_MONAT_AGENT_INVOICING_REPORTS_RTN_01 TA
LEFT OUTER JOIN
(	SELECT
	 SCHEDULER_ACL_NAME
	,EMPLOYEE_ID
	,AIR_DAY_TYPE
	,SUM(AUTHORIZED) AS ALL_AUTHORIZED_TIME
	FROM #IMPORTS_MONAT_AGENT_INVOICING_REPORTS_RTN_01
	GROUP BY 
	 SCHEDULER_ACL_NAME
	,EMPLOYEE_ID
	,AIR_DAY_TYPE
) LOJ ON LOJ.SCHEDULER_ACL_NAME = TA.SCHEDULER_ACL_NAME
	 AND LOJ.EMPLOYEE_ID        = TA.EMPLOYEE_ID
	 AND LOJ.AIR_DAY_TYPE       = TA.AIR_DAY_TYPE

--==================================
--RETURN DATA
--==================================
--==================================
--POPULATE TABLE READ BY SSIS TO GET END DATE OF DATA REPORT/FILE HAS BEEN RUN FOR:
--==================================
INSERT INTO WSOL_TB_FILENAMES_FOR_SSIS
(SQL_JOB_NAME
,FILENM
,CST_ROW_CREATED_TIME)
SELECT
 'uspIMPORTS_MONAT_AGENT_INVOICING_REPORTS_01'			--SQL_JOB_NAME
,REPLACE(CONVERT(VARCHAR(10),@DTM_END - 1,111),'/','')  --FILENM   YYYYMMDD_...
,dbo.GETDATE()											--CST_ROW_CREATED_TIME

--=====================================
--RETURN DATASET:
--=====================================
SELECT 
 CASE WHEN @DUR_IN = 'SS' THEN '' ELSE 'F' END AS DUR_FORMAT
,CONVERT(VARCHAR(10),@DTM_BEG,101) + '-' + CONVERT(VARCHAR(10),@DTM_END - 1,101)  AS DATE_RANGE
,V.*

FROM      #IMPORTS_MONAT_AGENT_INVOICING_REPORTS_RTN_01  V

ORDER BY 
 V.GRPNO
,V.SCHEDULER_ACL_NAME
,V.RESOURCE_NAME
,V.EMPLOYEE_ID
,V.CAL_YEAR_MONTH_NUM
,V.DATE_INTERVAL
,V.TIME_INTERVAL  --SINCE IN MILITARY TIME!




--===============================
EARLY_EXIT:
--===============================
--IMPOSSIBLE:  SELECT 1/0    POSSIBLE:  SELECT 0/1