
CREATE PROCEDURE [dbo].[uspIMPORTS_EGENCIA_AGENT_INVOICING_REPORTS]
 @DATE_BEG           DATETIME
,@DATE_END           DATETIME
,@TENANT_KEY         VARCHAR(150) --No multiples even though filter below is setup for multiples.
,@SCHEDULER_GROUP    VARCHAR(150) --Hid. Def=' '
,@ID_EXT             VARCHAR(300) --Hid. Def=' '
,@RESOURCE_KEY       VARCHAR(10)  --Hid. Def='0'
,@TIME_INTERVAL      VARCHAR(10)  --Hid. Def='HR'  HR,DY,DR   FOR SUB: MD(Month by Day),MR(Month Range)  15 and 30 not possible !!!!
,@SHOW_RESOURCE      VARCHAR(1)   --Hid. Def='Y'
--,@SHOW_DETAILS		 BIT		  --	 DEF='TRUE'
,@DUR_IN             VARCHAR(2)   --Hid. Def='MM' 
,@RESOURCE_FORMAT    VARCHAR(2)   --Hid. Def='NM' --'NM'=NAME + (employee id),  'ID'=ID
,@SHOW_HOLIDAY       VARCHAR(1)   --Hid. Def='N'
,@PSW                VARCHAR(10)  --Hid. Def='NONE'
,@EXECUTIONER        VARCHAR(3)   --Hid. Def='MAN'  MANual,SUBscription
,@RPT_TYPE_GRP       VARCHAR(3)   --Hid. Def='INV'
,@RPT_TYPE           VARCHAR(3)   --Hid. Def='INV'  
AS
SET NOCOUNT ON    

--  EXECUTE [dbo].[uspIMPORTS_EGENCIA_AGENT_INVOICING_REPORTS] '10/01/2017','10/15/2017','0','0','0','0','HR','Y','SS','NM','Y','4','MAN','INV','INV'

--	@TIME_INTERVAL:  Can show invoicing report at hourly level or higher !!!

--	Durations in SFTP FILE are in seconds.  Therefore, reporting may be in seconds, minutes, or hours.

--  SELECT * FROM WSOL_TB_IMPORTS_EGENCIA_SD_INVOICE_GROUPS
--  SELECT * FROM WSOL_TB_IMPORTS_EGENCIA_UV_ANT_AIA


--========================================================================================================
DECLARE
 @DTM_BEG AS DATETIME
,@DTM_END AS DATETIME
IF @DATE_BEG < '01/01/1901' BEGIN     
    SET @DTM_BEG = CAST(CONVERT(VARCHAR(10),dbo.getdate() - 1,101) AS DATETIME) 
	SET @DTM_END = CAST(CONVERT(VARCHAR(10),dbo.getdate() - 1,101) AS DATETIME) -- + 1
END
ELSE BEGIN
    SET @DTM_BEG = CAST(CONVERT(VARCHAR(10),@DATE_BEG,101) AS DATETIME) 
    SET @DTM_END = CAST(CONVERT(VARCHAR(10),@DATE_END,101) AS DATETIME) -- + 1
END
SET @DTM_END    = @DTM_END + 1  --EVERYTHING ABOVE, @DTM_END IS FOR EXACT DATE RANGE NEEDED. ONE IS ADDED SO WHERE CLAUSE " < @DTM_END" WORKS.

DECLARE
 @MTD_BEG AS DATETIME
,@MTD_END AS DATETIME  --,@YTD_BEG AS DATETIME--,@YTD_END AS DATETIME
SET @MTD_BEG = CAST(CAST(DATEPART(mm,@DTM_BEG) AS VARCHAR(2)) + '/01/' + CAST(DATEPART(yyyy,@DTM_BEG) AS VARCHAR(4)) AS DATETIME)
SET @MTD_END = @DTM_END  

IF @TIME_INTERVAL IN ('MR','MD') BEGIN  --MONTH DETERMINED BY @DTM_BEG.
	SET @DTM_BEG = @MTD_BEG
	SET @DTM_END = @MTD_END
END

IF @EXECUTIONER = 'DLY' BEGIN
	IF DATEPART(DW,dbo.getdate()) = 2 BEGIN
		SET @DTM_BEG = CAST(CONVERT(VARCHAR(10),dbo.getdate() - 3,101) AS DATETIME)
	END
	ELSE BEGIN
		SET @DTM_BEG = CAST(CONVERT(VARCHAR(10),dbo.getdate() - 1,101) AS DATETIME)
	END
	SET @DTM_END = @DTM_BEG + 1
END

IF @EXECUTIONER = 'WKY' BEGIN
	SET @DTM_BEG = CAST(CONVERT(VARCHAR(10),dbo.getdate() - 7,101) AS DATETIME)
	SET @DTM_END = CAST(CONVERT(VARCHAR(10),dbo.getdate()	 ,101) AS DATETIME)
END

IF @EXECUTIONER = 'MTH' BEGIN
	IF MONTH(dbo.getdate()) = 1
		BEGIN
			SET @DTM_BEG = CONVERT(DATETIME,CONVERT(VARCHAR(6),'12/01/') + CONVERT(VARCHAR(4),YEAR(dbo.getdate())-1))
		END
	ELSE
		BEGIN
			SET @DTM_BEG = CAST(CONVERT(VARCHAR(10), (CONVERT(VARCHAR(2),MONTH(dbo.getdate())-1) + CONVERT(VARCHAR(4),'/01/') + CONVERT(VARCHAR(4),YEAR(dbo.getdate()))),101) AS DATETIME)
		END
	SET @DTM_END = CAST(CONVERT(VARCHAR(10),dbo.getdate(),101) AS DATETIME)
END



--========================================================================
--	SET AMOUNT TO DIVIDE BY:
--========================================================================
DECLARE @DS DECIMAL(10,2)  --SECONDS TO DIVIDE BY.
IF @DUR_IN = 'SS' BEGIN
    SET @DS = 1.00     --DIVIDE SECONDS BY 1  TO GET SAME, SECONDS.
END
IF @DUR_IN = 'MM' BEGIN
    SET @DS = 60.00    --DIVIDE SECONDS BY 60 TO GET MINUTES.
END
IF @DUR_IN = 'HH' BEGIN
    SET @DS = 3600.00  --DIVIDE SECONDS BY 3600 TO GET HOURS.
END

--==================================
--	CREATE TMP TABLE:
--==================================
IF OBJECT_ID('TEMPDB..#IMPORTS_EGENCIA_AGENT_INVOICING_REPORTS') IS NOT NULL BEGIN
   DROP TABLE #IMPORTS_EGENCIA_AGENT_INVOICING_REPORTS
END
CREATE TABLE #IMPORTS_EGENCIA_AGENT_INVOICING_REPORTS
(TENANT_NAME					VARCHAR(50)
,ID_EXT							VARCHAR(3)
,SCHEDULER_ACL_NAME				VARCHAR(100)  
,EMPLOYEE_ID					VARCHAR(50)
,STD_TENANT_START_DATE_TIME_KEY INT
,RESOURCE_NAME					VARCHAR(100)

,AIR_DAY_TYPE					VARCHAR(1)
,AIR_ACW_FONT_COLOR				VARCHAR(50)
,MIN_GUARANTEE_MINUTES			DECIMAL(6,3)
,MIN_GUARANTEE_TYPE				VARCHAR(50)
,AUTHORIZED_TO_INVOICE_TYPE		VARCHAR(50)
,HAS_HOLIDAYS					VARCHAR(1)
,INCLUDE_IN_CAS					VARCHAR(1)
,READY_FOR_XML					VARCHAR(1)
,SHOW_ID_EXTS					VARCHAR(1)
,
[STAFFED_SECS] [decimal](10, 2) NULL,
[AVAILABLE_SECS] [decimal](10, 2) NULL,
[ACD_SECS] [decimal](10, 2) NULL,
[OTHER_SECS] [decimal](10, 2) NULL,
[ACW_SECS] [decimal](10, 2) NULL,
[RING_SECS] [decimal](10, 2) NULL,
[AUX_0_DEFAULT_SECS] [decimal](10, 2) NULL,
[AUX_1_BREAK_SECS] [decimal](10, 2) NULL,
[AUX_2_COACHING_SECS] [decimal](10, 2) NULL,
[AUX_3_MEETING_SECS] [decimal](10, 2) NULL,
[AUX_4_PROJECT_SECS] [decimal](10, 2) NULL,
[AUX_5_EGE_TRAINING_SECS] [decimal](10, 2) NULL,
[AUX_6_OUTBOUND_SECS] [decimal](10, 2) NULL,
[AUX_7_EMAIL_SECS] [decimal](10, 2) NULL,
[AUX_8_QUEUE_WORK_SECS] [decimal](10, 2) NULL,
[AUX_9_SYSTEM_DOWN_SECS] [decimal](10, 2) NULL,
[AUX_10_EXCHANGE_SECS] [decimal](10, 2) NULL,
[AUX_11_PERSONAL_SECS] [decimal](10, 2) NULL,
[AUX_34_SECS] [decimal](10, 2) NULL,
[AUX_35_SECS] [decimal](10, 2) NULL,
[AUX_37_SECS] [decimal](10, 2) NULL,
[AUX_40_SECS] [decimal](10, 2) NULL,
[OUTBOUND_SECS] [decimal](10, 2) NULL,
[EMAIL_SECS] [decimal](10, 2) NULL,
[PROJECT_SECS] [decimal](10, 2) NULL,
[MEETING_SECS] [decimal](10, 2) NULL,
[TOTAL_AUX_SECS] [decimal](10, 2) NULL,
[PROD_BILLING_SECS] [decimal](10, 2) NULL,
[AUTHORIZED_CSAT_SAT_KEY_SECS] [decimal](10, 2) NULL,
[AUTHORIZED_RESOURCE_SECS] [decimal](10, 2) NULL,
[LINE_OF_BUSINESS] [varchar](100) NULL,
[WEEKEND] [char](1) NULL,
[CPROD] [decimal](10, 2) NULL,
[MINIMUM_GUARANTEE] [decimal](10, 2) NULL,
[AUTHORIZED_MINUTES] [decimal](10, 2) NULL,
)

INSERT INTO #IMPORTS_EGENCIA_AGENT_INVOICING_REPORTS
SELECT
 'EGENCIA'	--T.TENANT_NAME
,''			--UAA.ACD_ID_EXTENSION
,UAA.SCHEDULER_ACL_NAME
,UAA.EMPLOYEE_ID
,UAA.STD_TENANT_START_DATE_TIME_KEY
,UAA.RESOURCE_NAME

,(ISNULL(UAA.AIR_DAY_TYPE,''))					--AS AIR_DAY_TYPE
,(ISNULL(UAA.AIR_ACW_FONT_COLOR,''))			--AS AIR_ACW_FONT_COLOR
,(ISNULL(UAA.MIN_GUARANTEE_MINUTES,0.000))		--AS MIN_GUARANTEE_MINUTES
,(ISNULL(UAA.MIN_GUARANTEE_TYPE,''))			--AS MIN_GUARANTEE_TYPE
,(ISNULL(UAA.AUTHORIZED_TO_INVOICE_TYPE,''))	--AS AUTHORIZED_TO_INVOICE_TYPE
,(ISNULL(UAA.HAS_HOLIDAYS,''))					--AS HAS_HOLIDAYS
,(ISNULL(UAA.INCLUDE_IN_CAS,''))				--AS INCLUDE_IN_CAS
,(ISNULL(UAA.READY_FOR_XML,''))					--AS READY_FOR_XML
,(ISNULL(UAA.SHOW_ID_EXTS,''))					--AS SHOW_ID_EXTS

,(ISNULL(UAA.STAFFED_SECS					,0.00))
,(ISNULL(UAA.AVAILABLE_SECS					,0.00))
,(ISNULL(UAA.ACD_SECS						,0.00))
,(ISNULL(UAA.OTHER_SECS						,0.00))
,(ISNULL(UAA.ACW_SECS						,0.00))
,(ISNULL(UAA.RING_SECS						,0.00))
,(ISNULL(UAA.AUX_0_DEFAULT_SECS				,0.00))
,(ISNULL(UAA.AUX_1_BREAK_SECS				,0.00))
,(ISNULL(UAA.AUX_2_COACHING_SECS			,0.00))
,(ISNULL(UAA.AUX_3_MEETING_SECS				,0.00))
,(ISNULL(UAA.AUX_4_PROJECT_SECS				,0.00))
,(ISNULL(UAA.AUX_5_EGE_TRAINING_SECS		,0.00))
,(ISNULL(UAA.AUX_6_OUTBOUND_SECS			,0.00))
,(ISNULL(UAA.AUX_7_EMAIL_SECS				,0.00))
,(ISNULL(UAA.AUX_8_QUEUE_WORK_SECS			,0.00))
,(ISNULL(UAA.AUX_9_SYSTEM_DOWN_SECS			,0.00))
,(ISNULL(UAA.AUX_10_EXCHANGE_SECS			,0.00))
,(ISNULL(UAA.AUX_11_PERSONAL_SECS			,0.00))
,(ISNULL(UAA.AUX_34_SECS					,0.00))
,(ISNULL(UAA.AUX_35_SECS					,0.00))
,(ISNULL(UAA.AUX_37_SECS					,0.00))
,(ISNULL(UAA.AUX_40_SECS					,0.00))
,(ISNULL(UAA.OUTBOUND_SECS					,0.00))
,(ISNULL(UAA.EMAIL_SECS						,0.00))
,(ISNULL(UAA.PROJECT_SECS					,0.00))
,(ISNULL(UAA.MEETING_SECS					,0.00))
,(ISNULL(UAA.TOTAL_AUX_SECS					,0.00))
,(ISNULL(UAA.PROD_BILLING_SECS				,0.00))
,(ISNULL(UAA.AUTHORIZED_CSAT_SAT_KEY_SECS	,0.00))
,(ISNULL(UAA.AUTHORIZED_RESOURCE_SECS		,0.00))

,(ISNULL(UAA.LINE_OF_BUSINESS,''))				--AS LINE_OF_BUSINESS
,(ISNULL(UAA.WEEKEND,''))						--AS WEEKEND

,(ISNULL(UAA.CPROD							,0.00))
,(ISNULL(UAA.MINIMUM_GUARANTEE				,0.00))
,(ISNULL(UAA.AUTHORIZED_MINUTES				,0.00))

--SELECT * FROM WSOL_TB_IMPORTS_EGENCIA_INVOICING

FROM
(	SELECT	
	-- UA.TENANT_KEY
	 ''									AS ACD_ID_EXTENSION
	,UA.INVOICE_ID					    AS SCHEDULER_ACL_NAME
	,UA.FF_LOGIN_ID						AS EMPLOYEE_ID 
	,UA.STD_TENANT_START_DATE_TIME_KEY
	,MAX(UA.RESOURCE_NAME)              AS RESOURCE_NAME
	,MAX(UA.AIR_DAY_TYPE)               AS AIR_DAY_TYPE
	,'BLACK'                            AS AIR_ACW_FONT_COLOR
	,0									AS MIN_GUARANTEE_MINUTES
	,''									AS MIN_GUARANTEE_TYPE
	,''									AS AUTHORIZED_TO_INVOICE_TYPE
	,'Y'								AS HAS_HOLIDAYS
	,''									AS INCLUDE_IN_CAS
	,''									AS READY_FOR_XML
	,''									AS SHOW_ID_EXTS

	,SUM(ISNULL(UA.STAFFED_SECS					,0.00))	AS STAFFED_SECS
	,SUM(ISNULL(UA.AVAILABLE_SECS				,0.00))	AS AVAILABLE_SECS
	,SUM(ISNULL(UA.ACD_SECS						,0.00))	AS ACD_SECS
	,SUM(ISNULL(UA.OTHER_SECS					,0.00))	AS OTHER_SECS
	,SUM(ISNULL(UA.ACW_SECS						,0.00))	AS ACW_SECS
	,SUM(ISNULL(UA.RING_SECS					,0.00))	AS RING_SECS
	,SUM(ISNULL(UA.AUX_0_DEFAULT_SECS			,0.00))	AS AUX_0_DEFAULT_SECS
	,SUM(ISNULL(UA.AUX_1_BREAK_SECS				,0.00))	AS AUX_1_BREAK_SECS
	,SUM(ISNULL(UA.AUX_2_COACHING_SECS			,0.00))	AS AUX_2_COACHING_SECS
	,SUM(ISNULL(UA.AUX_3_MEETING_SECS			,0.00))	AS AUX_3_MEETING_SECS
	,SUM(ISNULL(UA.AUX_4_PROJECT_SECS			,0.00))	AS AUX_4_PROJECT_SECS
	,SUM(ISNULL(UA.AUX_5_EGE_TRAINING_SECS		,0.00))	AS AUX_5_EGE_TRAINING_SECS
	,SUM(ISNULL(UA.AUX_6_OUTBOUND_SECS			,0.00))	AS AUX_6_OUTBOUND_SECS
	,SUM(ISNULL(UA.AUX_7_EMAIL_SECS				,0.00)) AS AUX_7_EMAIL_SECS
	,SUM(ISNULL(UA.AUX_8_QUEUE_WORK_SECS		,0.00)) AS AUX_8_QUEUE_WORK_SECS
	,SUM(ISNULL(UA.AUX_9_SYSTEM_DOWN_SECS		,0.00)) AS AUX_9_SYSTEM_DOWN_SECS
	,SUM(ISNULL(UA.AUX_10_EXCHANGE_SECS			,0.00)) AS AUX_10_EXCHANGE_SECS
	,SUM(ISNULL(UA.AUX_11_PERSONAL_SECS			,0.00)) AS AUX_11_PERSONAL_SECS
	,SUM(ISNULL(UA.AUX_34_SECS					,0.00)) AS AUX_34_SECS
	,SUM(ISNULL(UA.AUX_35_SECS					,0.00)) AS AUX_35_SECS
	,SUM(ISNULL(UA.AUX_37_SECS					,0.00)) AS AUX_37_SECS
	,SUM(ISNULL(UA.AUX_40_SECS					,0.00)) AS AUX_40_SECS
	,SUM(ISNULL(UA.OUTBOUND_SECS				,0.00)) AS OUTBOUND_SECS
	,SUM(ISNULL(UA.EMAIL_SECS					,0.00)) AS EMAIL_SECS
	,SUM(ISNULL(UA.PROJECT_SECS					,0.00)) AS PROJECT_SECS
	,SUM(ISNULL(UA.MEETING_SECS					,0.00)) AS MEETING_SECS
	,SUM(ISNULL(UA.TOTAL_AUX_SECS				,0.00)) AS TOTAL_AUX_SECS
	,SUM(ISNULL(UA.PROD_BILLING_SECS			,0.00)) AS PROD_BILLING_SECS
	,SUM(ISNULL(UA.AUTHORIZED_CSAT_SAT_KEY_SECS	,0.00)) AS AUTHORIZED_CSAT_SAT_KEY_SECS
	,SUM(ISNULL(UA.AUTHORIZED_RESOURCE_SECS		,0.00)) AS AUTHORIZED_RESOURCE_SECS

	,ISNULL(UA.LINE_OF_BUSINESS	,''  ) AS LINE_OF_BUSINESS
	,ISNULL(UA.WEEKEND			,''  ) AS WEEKEND

	,SUM(ISNULL(UA.CPROD						,0.00))	AS CPROD
	,SUM(ISNULL(UA.MINIMUM_GUARANTEE			,0.00))	AS MINIMUM_GUARANTEE
	,SUM(ISNULL(UA.AUTHORIZED_MINUTES			,0.00))	AS AUTHORIZED_MINUTES
	
	--  SELECT *
	FROM            WSOL_TB_IMPORTS_EGENCIA_INVOICING	UA
	INNER JOIN      DATE_TIME							DT	ON DT.DATE_TIME_KEY = UA.STD_TENANT_START_DATE_TIME_KEY

	WHERE DT.CAL_DATE >= @DTM_BEG AND DT.CAL_DATE <  @DTM_END
		
	GROUP BY 
	 UA.INVOICE_ID
	,UA.FF_LOGIN_ID
	,UA.STD_TENANT_START_DATE_TIME_KEY
	,UA.LINE_OF_BUSINESS
	,UA.WEEKEND
) UAA

--==============================================================
-- CREATE TEMPORARY TABLE TO RETURN RESULTS
--==============================================================
IF OBJECT_ID('TEMPDB..#IMPORTS_EGENCIA_AGENT_INVOICING_REPORTS_RTN') IS NOT NULL BEGIN
   DROP TABLE #IMPORTS_EGENCIA_AGENT_INVOICING_REPORTS_RTN
END
CREATE TABLE #IMPORTS_EGENCIA_AGENT_INVOICING_REPORTS_RTN
(GRPNO                 INT
,TENANT_NAME           VARCHAR(50)
,ID_EXT                VARCHAR(3)
,SCHEDULER_ACL_NAME    VARCHAR(100)
,EMPLOYEE_ID           VARCHAR(50)
,RESOURCE_NAME         VARCHAR(100)
,CAL_YEAR_MONTH_NUM    VARCHAR(10)
,DATE_INTERVAL         VARCHAR(50)
,TIME_INTERVAL         VARCHAR(10)

,AIR_DAY_TYPE				varchar(1)
,AIR_ACW_FONT_COLOR			varchar(50)
,MIN_GUARANTEE_MINUTES		decimal(6,3)
,MIN_GUARANTEE_TYPE			varchar(50)
,AUTHORIZED_TO_INVOICE_TYPE	varchar(50)
,HAS_HOLIDAYS				varchar(1)
,INCLUDE_IN_CAS				varchar(1)
,READY_FOR_XML				varchar(1)
,SHOW_ID_EXTS				varchar(1)

,AIR_HOLIDAY_IN				VARCHAR(1)
,ALL_AUTHORIZED_TIME		DECIMAL(10,2)
,ALL_AUTHORIZED_WE_TIME		DECIMAL(10,2)

,
[STAFFED_SECS] [decimal](10, 2) NULL,
[AVAILABLE_SECS] [decimal](10, 2) NULL,
[ACD_SECS] [decimal](10, 2) NULL,
[OTHER_SECS] [decimal](10, 2) NULL,
[ACW_SECS] [decimal](10, 2) NULL,
[RING_SECS] [decimal](10, 2) NULL,
[AUX_0_DEFAULT_SECS] [decimal](10, 2) NULL,
[AUX_1_BREAK_SECS] [decimal](10, 2) NULL,
[AUX_2_COACHING_SECS] [decimal](10, 2) NULL,
[AUX_3_MEETING_SECS] [decimal](10, 2) NULL,
[AUX_4_PROJECT_SECS] [decimal](10, 2) NULL,
[AUX_5_EGE_TRAINING_SECS] [decimal](10, 2) NULL,
[AUX_6_OUTBOUND_SECS] [decimal](10, 2) NULL,
[AUX_7_EMAIL_SECS] [decimal](10, 2) NULL,
[AUX_8_QUEUE_WORK_SECS] [decimal](10, 2) NULL,
[AUX_9_SYSTEM_DOWN_SECS] [decimal](10, 2) NULL,
[AUX_10_EXCHANGE_SECS] [decimal](10, 2) NULL,
[AUX_11_PERSONAL_SECS] [decimal](10, 2) NULL,
[AUX_34_SECS] [decimal](10, 2) NULL,
[AUX_35_SECS] [decimal](10, 2) NULL,
[AUX_37_SECS] [decimal](10, 2) NULL,
[AUX_40_SECS] [decimal](10, 2) NULL,
[OUTBOUND_SECS] [decimal](10, 2) NULL,
[EMAIL_SECS] [decimal](10, 2) NULL,
[PROJECT_SECS] [decimal](10, 2) NULL,
[MEETING_SECS] [decimal](10, 2) NULL,
[TOTAL_AUX_SECS] [decimal](10, 2) NULL,
[PROD_BILLING_SECS] [decimal](10, 2) NULL,
[AUTHORIZED_CSAT_SAT_KEY_SECS] [decimal](10, 2) NULL,
[AUTHORIZED_RESOURCE_SECS] [decimal](10, 2) NULL,
[LINE_OF_BUSINESS] [varchar](100) NULL,
[WEEKEND] [char](1) NULL,
[CPROD] [decimal](10, 2) NULL,
[MINIMUM_GUARANTEE] [decimal](10, 2) NULL,
[AUTHORIZED_MINUTES] [decimal](10, 2) NULL,
)

--==================================
-- POPULATE TEMPORARY TABLE
--==================================
INSERT INTO #IMPORTS_EGENCIA_AGENT_INVOICING_REPORTS_RTN
SELECT
 20								--AS GRPNO  
,ISNULL(GG.TENANT_NAME       ,'') AS TENANT_NAME
,ISNULL(GG.ID_EXT            ,'') AS ID_EXT
,ISNULL(GG.SCHEDULER_ACL_NAME,'') AS SCHEDULER_ACL_NAME
,ISNULL(GG.EMPLOYEE_ID       ,'') AS EMPLOYEE_ID
,ISNULL(GG.RESOURCE_NAME     ,'') AS RESOURCE_NAME
,ISNULL(GG.CAL_YEAR_MONTH_NUM,'') AS CAL_YEAR_MONTH_NUM
,ISNULL(GG.DI                ,'') AS DI
,ISNULL(GG.TI                ,'') AS TI

,(GG.AIR_DAY_TYPE)                AS AIR_DAY_TYPE
,(GG.AIR_ACW_FONT_COLOR)          AS AIR_ACW_FONT_COLOR
,(GG.MIN_GUARANTEE_MINUTES)       AS MIN_GUARANTEE_MINUTES
,(GG.MIN_GUARANTEE_TYPE)          AS MIN_GUARANTEE_TYPE
,(GG.AUTHORIZED_TO_INVOICE_TYPE)  AS AUTHORIZED_TO_INVOICE_TYPE
,(GG.HAS_HOLIDAYS)                AS HAS_HOLIDAYS
,(GG.INCLUDE_IN_CAS)              AS INCLUDE_IN_CAS
,(GG.READY_FOR_XML)               AS READY_FOR_XML
,(GG.SHOW_ID_EXTS)                AS SHOW_ID_EXTS

,'' --AS AIR_HOLIDAY_IN
,0  --AS ALL_AUTHORIZED_TIME
,0	--AS ALL_AUTHORIZED_WE_TIME

,CAST((ISNULL(GG.STAFFED_SECS					,0.00)) / @DS AS DECIMAL(10,2))	AS STAFFED_SECS
,CAST((ISNULL(GG.AVAILABLE_SECS					,0.00)) / @DS AS DECIMAL(10,2))	AS AVAILABLE_SECS
,CAST((ISNULL(GG.ACD_SECS						,0.00)) / @DS AS DECIMAL(10,2))	AS ACD_SECS
,CAST((ISNULL(GG.OTHER_SECS						,0.00)) / @DS AS DECIMAL(10,2))	AS OTHER_SECS
,CAST((ISNULL(GG.ACW_SECS						,0.00)) / @DS AS DECIMAL(10,2))	AS ACW_SECS
,CAST((ISNULL(GG.RING_SECS						,0.00)) / @DS AS DECIMAL(10,2))	AS RING_SECS
,CAST((ISNULL(GG.AUX_0_DEFAULT_SECS				,0.00)) / @DS AS DECIMAL(10,2))	AS AUX_0_DEFAULT_SECS
,CAST((ISNULL(GG.AUX_1_BREAK_SECS				,0.00)) / @DS AS DECIMAL(10,2))	AS AUX_1_BREAK_SECS
,CAST((ISNULL(GG.AUX_2_COACHING_SECS			,0.00)) / @DS AS DECIMAL(10,2)) AS AUX_2_COACHING_SECS
,CAST((ISNULL(GG.AUX_3_MEETING_SECS				,0.00)) / @DS AS DECIMAL(10,2)) AS AUX_3_MEETING_SECS
,CAST((ISNULL(GG.AUX_4_PROJECT_SECS				,0.00)) / @DS AS DECIMAL(10,2)) AS AUX_4_PROJECT_SECS
,CAST((ISNULL(GG.AUX_5_EGE_TRAINING_SECS		,0.00)) / @DS AS DECIMAL(10,2)) AS AUX_5_EGE_TRAINING_SECS
,CAST((ISNULL(GG.AUX_6_OUTBOUND_SECS			,0.00)) / @DS AS DECIMAL(10,2)) AS AUX_6_OUTBOUND_SECS
,CAST((ISNULL(GG.AUX_7_EMAIL_SECS				,0.00)) / @DS AS DECIMAL(10,2)) AS AUX_7_EMAIL_SECS
,CAST((ISNULL(GG.AUX_8_QUEUE_WORK_SECS			,0.00)) / @DS AS DECIMAL(10,2)) AS AUX_8_QUEUE_WORK_SECS
,CAST((ISNULL(GG.AUX_9_SYSTEM_DOWN_SECS			,0.00)) / @DS AS DECIMAL(10,2)) AS AUX_9_SYSTEM_DOWN_SECS
,CAST((ISNULL(GG.AUX_10_EXCHANGE_SECS			,0.00)) / @DS AS DECIMAL(10,2)) AS AUX_10_EXCHANGE_SECS
,CAST((ISNULL(GG.AUX_11_PERSONAL_SECS			,0.00)) / @DS AS DECIMAL(10,2)) AS AUX_11_PERSONAL_SECS
,CAST((ISNULL(GG.AUX_34_SECS					,0.00)) / @DS AS DECIMAL(10,2)) AS AUX_34_SECS
,CAST((ISNULL(GG.AUX_35_SECS					,0.00)) / @DS AS DECIMAL(10,2)) AS AUX_35_SECS
,CAST((ISNULL(GG.AUX_37_SECS					,0.00)) / @DS AS DECIMAL(10,2)) AS AUX_37_SECS
,CAST((ISNULL(GG.AUX_40_SECS					,0.00)) / @DS AS DECIMAL(10,2)) AS AUX_40_SECS
,CAST((ISNULL(GG.OUTBOUND_SECS					,0.00)) / @DS AS DECIMAL(10,2)) AS OUTBOUND_SECS
,CAST((ISNULL(GG.EMAIL_SECS						,0.00)) / @DS AS DECIMAL(10,2)) AS EMAIL_SECS
,CAST((ISNULL(GG.PROJECT_SECS					,0.00)) / @DS AS DECIMAL(10,2)) AS PROJECT_SECS
,CAST((ISNULL(GG.MEETING_SECS					,0.00)) / @DS AS DECIMAL(10,2)) AS MEETING_SECS
,CAST((ISNULL(GG.TOTAL_AUX_SECS					,0.00)) / @DS AS DECIMAL(10,2)) AS TOTAL_AUX_SECS
,CAST((ISNULL(GG.PROD_BILLING_SECS				,0.00)) / @DS AS DECIMAL(10,2)) AS PROD_BILLING_SECS
,CAST((ISNULL(GG.AUTHORIZED_CSAT_SAT_KEY_SECS	,0.00)) / @DS AS DECIMAL(10,2)) AS AUTHORIZED_CSAT_SAT_KEY_SECS
,CAST((ISNULL(GG.AUTHORIZED_RESOURCE_SECS		,0.00)) / @DS AS DECIMAL(10,2)) AS AUTHORIZED_RESOURCE_SECS

,ISNULL(GG.LINE_OF_BUSINESS	,'') AS LINE_OF_BUSINESS
,ISNULL(GG.WEEKEND			,'') AS WEEKEND

,CAST((ISNULL(GG.CPROD							,0.00)) / @DS AS DECIMAL(10,2))	AS CPROD
,CAST((ISNULL(GG.MINIMUM_GUARANTEE				,0.00)) / @DS AS DECIMAL(10,2))	AS MINIMUM_GUARANTEE
,CAST((ISNULL(GG.AUTHORIZED_MINUTES				,0.00)) / @DS AS DECIMAL(10,2))	AS AUTHORIZED_MINUTES


FROM  -- GG STARTS HERE:
(	SELECT
	 ISNULL(SW.TENANT_NAME,'')        AS TENANT_NAME
	,ISNULL(SW.ID_EXT,'')             AS ID_EXT
	,ISNULL(SW.SCHEDULER_ACL_NAME,'') AS SCHEDULER_ACL_NAME
	,ISNULL(SW.EMPLOYEE_ID,'')		  AS EMPLOYEE_ID
	,MAX(RESOURCE_NAME)               AS RESOURCE_NAME

	,(CASE WHEN @TIME_INTERVAL IN ('MR') THEN DT.CAL_YEAR_MONTH_NUM ELSE '' END ) AS CAL_YEAR_MONTH_NUM
	,(CASE WHEN @TIME_INTERVAL IN ('MR') THEN LEFT(DT.CAL_MONTH_NAME,3) + ' ' + DT.CAL_YEAR_STRING
		   WHEN @TIME_INTERVAL IN ('DR') THEN ''  ELSE DT.CAL_DATE_STRING END ) AS DI
	,(CASE --WHEN @TIME_INTERVAL = '15' THEN DT.LABEL_HH24 + ':' + DT.LABEL_MI
		   --WHEN @TIME_INTERVAL = '30' THEN DT.LABEL_HH24 + ':' + DT.LABEL_30MI
		   WHEN @TIME_INTERVAL = 'HR' THEN DT.LABEL_HH24 ELSE '' END ) AS TI

	,MAX(SW.AIR_DAY_TYPE)               AS AIR_DAY_TYPE
	,MAX(SW.AIR_ACW_FONT_COLOR)         AS AIR_ACW_FONT_COLOR
	,MAX(SW.MIN_GUARANTEE_MINUTES)      AS MIN_GUARANTEE_MINUTES
	,MAX(SW.MIN_GUARANTEE_TYPE)         AS MIN_GUARANTEE_TYPE
	,MAX(SW.AUTHORIZED_TO_INVOICE_TYPE) AS AUTHORIZED_TO_INVOICE_TYPE
	,MAX(SW.HAS_HOLIDAYS)               AS HAS_HOLIDAYS
	,MAX(SW.INCLUDE_IN_CAS)             AS INCLUDE_IN_CAS
	,MAX(SW.READY_FOR_XML)              AS READY_FOR_XML
	,MAX(SW.SHOW_ID_EXTS)               AS SHOW_ID_EXTS

	,SUM(ISNULL(SW.STAFFED_SECS					,0.00))	AS STAFFED_SECS
	,SUM(ISNULL(SW.AVAILABLE_SECS				,0.00))	AS AVAILABLE_SECS
	,SUM(ISNULL(SW.ACD_SECS						,0.00))	AS ACD_SECS
	,SUM(ISNULL(SW.OTHER_SECS					,0.00))	AS OTHER_SECS
	,SUM(ISNULL(SW.ACW_SECS						,0.00))	AS ACW_SECS
	,SUM(ISNULL(SW.RING_SECS					,0.00))	AS RING_SECS
	,SUM(ISNULL(SW.AUX_0_DEFAULT_SECS			,0.00))	AS AUX_0_DEFAULT_SECS
	,SUM(ISNULL(SW.AUX_1_BREAK_SECS				,0.00))	AS AUX_1_BREAK_SECS
	,SUM(ISNULL(SW.AUX_2_COACHING_SECS			,0.00))	AS AUX_2_COACHING_SECS
	,SUM(ISNULL(SW.AUX_3_MEETING_SECS			,0.00))	AS AUX_3_MEETING_SECS
	,SUM(ISNULL(SW.AUX_4_PROJECT_SECS			,0.00))	AS AUX_4_PROJECT_SECS
	,SUM(ISNULL(SW.AUX_5_EGE_TRAINING_SECS		,0.00))	AS AUX_5_EGE_TRAINING_SECS
	,SUM(ISNULL(SW.AUX_6_OUTBOUND_SECS			,0.00))	AS AUX_6_OUTBOUND_SECS
	,SUM(ISNULL(SW.AUX_7_EMAIL_SECS				,0.00))	AS AUX_7_EMAIL_SECS
	,SUM(ISNULL(SW.AUX_8_QUEUE_WORK_SECS		,0.00))	AS AUX_8_QUEUE_WORK_SECS
	,SUM(ISNULL(SW.AUX_9_SYSTEM_DOWN_SECS		,0.00))	AS AUX_9_SYSTEM_DOWN_SECS
	,SUM(ISNULL(SW.AUX_10_EXCHANGE_SECS			,0.00))	AS AUX_10_EXCHANGE_SECS
	,SUM(ISNULL(SW.AUX_11_PERSONAL_SECS			,0.00))	AS AUX_11_PERSONAL_SECS
	,SUM(ISNULL(SW.AUX_34_SECS					,0.00)) AS AUX_34_SECS
	,SUM(ISNULL(SW.AUX_35_SECS					,0.00)) AS AUX_35_SECS
	,SUM(ISNULL(SW.AUX_37_SECS					,0.00)) AS AUX_37_SECS
	,SUM(ISNULL(SW.AUX_40_SECS					,0.00)) AS AUX_40_SECS
	,SUM(ISNULL(SW.OUTBOUND_SECS				,0.00)) AS OUTBOUND_SECS
	,SUM(ISNULL(SW.EMAIL_SECS					,0.00)) AS EMAIL_SECS
	,SUM(ISNULL(SW.PROJECT_SECS					,0.00)) AS PROJECT_SECS
	,SUM(ISNULL(SW.MEETING_SECS					,0.00)) AS MEETING_SECS
	,SUM(ISNULL(SW.TOTAL_AUX_SECS				,0.00)) AS TOTAL_AUX_SECS
	,SUM(ISNULL(SW.PROD_BILLING_SECS			,0.00)) AS PROD_BILLING_SECS
	,SUM(ISNULL(SW.AUTHORIZED_CSAT_SAT_KEY_SECS	,0.00)) AS AUTHORIZED_CSAT_SAT_KEY_SECS
	,SUM(ISNULL(SW.AUTHORIZED_RESOURCE_SECS		,0.00)) AS AUTHORIZED_RESOURCE_SECS

	,ISNULL(SW.LINE_OF_BUSINESS	,'')	AS LINE_OF_BUSINESS
	,ISNULL(SW.WEEKEND			,'')	AS WEEKEND

	,SUM(ISNULL(SW.CPROD						,0.00))	AS CPROD
	,SUM(ISNULL(SW.MINIMUM_GUARANTEE			,0.00))	AS MINIMUM_GUARANTEE
	,SUM(ISNULL(SW.AUTHORIZED_MINUTES			,0.00))	AS AUTHORIZED_MINUTES
	
	FROM            #IMPORTS_EGENCIA_AGENT_INVOICING_REPORTS	SW
	INNER JOIN      DATE_TIME									DT   ON DT.DATE_TIME_KEY	=	SW.STD_TENANT_START_DATE_TIME_KEY

	GROUP BY 
	 ISNULL(SW.TENANT_NAME,'')			--AS TENANT_NAME
	,ISNULL(SW.ID_EXT,'')				--AS ID_EXT
	,ISNULL(SW.SCHEDULER_ACL_NAME,'')	--AS SCHEDULER_ACL_NAME
	,ISNULL(SW.EMPLOYEE_ID,'')			--AS EMPLOYEE_ID
	,ISNULL(SW.LINE_OF_BUSINESS,'')		--AS LINE_OF_BUSINESS
	,ISNULL(SW.WEEKEND,'')				--AS WEEKEND

	,(CASE WHEN @TIME_INTERVAL IN ('MR') THEN DT.CAL_YEAR_MONTH_NUM ELSE '' END ) --AS CAL_YEAR_MONTH_NUM
	,(CASE WHEN @TIME_INTERVAL IN ('MR') THEN LEFT(DT.CAL_MONTH_NAME,3) + ' ' + DT.CAL_YEAR_STRING
		   WHEN @TIME_INTERVAL IN ('DR') THEN ''  ELSE DT.CAL_DATE_STRING END ) --AS DI
	,(CASE --WHEN @TIME_INTERVAL = '15' THEN DT.LABEL_HH24 + ':' + DT.LABEL_MI
		   --WHEN @TIME_INTERVAL = '30' THEN DT.LABEL_HH24 + ':' + DT.LABEL_30MI
		   WHEN @TIME_INTERVAL = 'HR' THEN DT.LABEL_HH24 ELSE '' END ) --AS TI

) GG

--==================================
--IS A HOLIDAY DATE IN THE MIX:
--==================================
DECLARE @HOLIDAY_IN VARCHAR(1)
SET @HOLIDAY_IN = 'N'
DECLARE @I INT
SET @I = (SELECT COUNT(*) FROM #IMPORTS_EGENCIA_AGENT_INVOICING_REPORTS_RTN WHERE AIR_DAY_TYPE = 'H')  --  AND INCLUDE_IN_CAS = 'Y')
IF @I > 0 BEGIN
	SET @HOLIDAY_IN = 'Y'
END
--==================================
UPDATE #IMPORTS_EGENCIA_AGENT_INVOICING_REPORTS_RTN SET
 AIR_HOLIDAY_IN = @HOLIDAY_IN

--======================================================
--UPDATE TOTALS LINE ON REPORT FOR STANDARD AND HOLIDAY:
--======================================================
UPDATE #IMPORTS_EGENCIA_AGENT_INVOICING_REPORTS_RTN SET
 ALL_AUTHORIZED_TIME = ISNULL(LOJ.ALL_AUTHORIZED_TIME,0.0)
FROM #IMPORTS_EGENCIA_AGENT_INVOICING_REPORTS_RTN TA
LEFT OUTER JOIN
(	SELECT
	 SCHEDULER_ACL_NAME
	,EMPLOYEE_ID
	,AIR_DAY_TYPE
	,SUM(AUTHORIZED_MINUTES) AS ALL_AUTHORIZED_TIME
	FROM #IMPORTS_EGENCIA_AGENT_INVOICING_REPORTS_RTN 
	GROUP BY 
	 SCHEDULER_ACL_NAME
	,EMPLOYEE_ID
	,AIR_DAY_TYPE
) LOJ ON LOJ.SCHEDULER_ACL_NAME = TA.SCHEDULER_ACL_NAME
	 AND LOJ.EMPLOYEE_ID        = TA.EMPLOYEE_ID
	 AND LOJ.AIR_DAY_TYPE       = TA.AIR_DAY_TYPE

--======================================================
--UPDATE TOTALS LINE ON REPORT FOR WEEKEND:
--======================================================
UPDATE #IMPORTS_EGENCIA_AGENT_INVOICING_REPORTS_RTN SET
 ALL_AUTHORIZED_WE_TIME = ISNULL(LOJ.ALL_AUTHORIZED_WE_TIME,0.0)
FROM #IMPORTS_EGENCIA_AGENT_INVOICING_REPORTS_RTN TA
LEFT OUTER JOIN
(	SELECT
	 SCHEDULER_ACL_NAME
	,EMPLOYEE_ID
	,AIR_DAY_TYPE
	,WEEKEND
	,SUM(AUTHORIZED_MINUTES) AS ALL_AUTHORIZED_WE_TIME
	FROM #IMPORTS_EGENCIA_AGENT_INVOICING_REPORTS_RTN
	WHERE WEEKEND = 'Y'
	GROUP BY 
	 SCHEDULER_ACL_NAME
	,EMPLOYEE_ID
	,AIR_DAY_TYPE
	,WEEKEND
) LOJ ON LOJ.SCHEDULER_ACL_NAME = TA.SCHEDULER_ACL_NAME
	 AND LOJ.EMPLOYEE_ID        = TA.EMPLOYEE_ID
	 AND LOJ.AIR_DAY_TYPE       = TA.AIR_DAY_TYPE

--==================================
--RETURN DATA
--==================================
--==================================
--POPULATE TABLE READ BY SSIS TO GET END DATE OF DATA REPORT/FILE HAS BEEN RUN FOR:
--==================================
INSERT INTO WSOL_TB_FILENAMES_FOR_SSIS
(SQL_JOB_NAME
,FILENM
,CST_ROW_CREATED_TIME)
SELECT
 'uspIMPORTS_EGENCIA_AGENT_INVOICING_REPORTS'			--SQL_JOB_NAME
,REPLACE(CONVERT(VARCHAR(10),@DTM_END - 1,111),'/','')  --FILENM   YYYYMMDD_...
,dbo.GETDATE()											--CST_ROW_CREATED_TIME

--=====================================
--RETURN DATASET:
--=====================================
SELECT 
 CASE WHEN @DUR_IN = 'SS' THEN '' ELSE 'F' END AS DUR_FORMAT
,CONVERT(VARCHAR(10),@DTM_BEG,101) + '-' + CONVERT(VARCHAR(10),@DTM_END - 1,101)  AS DATE_RANGE
,V.*

FROM      #IMPORTS_EGENCIA_AGENT_INVOICING_REPORTS_RTN  V

ORDER BY 
 V.GRPNO
,V.SCHEDULER_ACL_NAME
,V.RESOURCE_NAME
,V.EMPLOYEE_ID
,V.LINE_OF_BUSINESS
,V.WEEKEND
,V.CAL_YEAR_MONTH_NUM
,V.DATE_INTERVAL
,V.TIME_INTERVAL  --SINCE IN MILITARY TIME!




--===============================
EARLY_EXIT:
--===============================
--IMPOSSIBLE:  SELECT 1/0    POSSIBLE:  SELECT 0/1