CREATE PROCEDURE [dbo].[uspIMPORTS_STUBHUB_AGENT_INVOICING]
 @DATE_BEG           DATETIME
,@DATE_END           DATETIME
,@TENANT_KEY         VARCHAR(150) --No multiples even though filter below is setup for multiples.
,@SCHEDULER_GROUP    VARCHAR(150) --Hid. Def=' '
,@ID_EXT             VARCHAR(300) --Hid. Def=' '
,@RESOURCE_KEY       VARCHAR(10)  --Hid. Def='0'
,@TIME_INTERVAL      VARCHAR(10)  --Hid. Def='HR'  HR,DY,DR   FOR SUB: MD(Month by Day),MR(Month Range)  15 and 30 not possible !!!!
,@SHOW_RESOURCE      VARCHAR(1)   --Hid. Def='Y'
,@DUR_IN             VARCHAR(2)   --Hid. Def='MM' 
,@RESOURCE_FORMAT    VARCHAR(2)   --Hid. Def='NM' --'NM'=NAME + (employee id),  'ID'=ID
,@SHOW_HOLIDAY       VARCHAR(1)   --Hid. Def='N'
,@PSW                VARCHAR(10)  --Hid. Def='NONE'
,@EXECUTIONER        VARCHAR(3)   --Hid. Def='MAN'  MANual,SUBscription
,@RPT_TYPE_GRP       VARCHAR(3)   --Hid. Def='INV'
,@RPT_TYPE           VARCHAR(3)   --Hid. Def='INV'  
AS
SET NOCOUNT ON    

--  EXECUTE [dbo].[uspIMPORTS_STUBHUB_AGENT_INVOICING] '05/23/2014','06/05/2014','0','0','0','0','HR','Y','SS','NM','Y','4','MAN','INV','INV'

--@TIME_INTERVAL:  Can only show invoicing report at hour level or higher !!!

--Durations in FTP FILE are in seconds.  So, this report can pull by secs, mins, and hrs now.

--  SELECT * FROM YZ_TB_IMPORTS_STUBHUB_SD_INVOICE_GROUPS
--  SELECT * FROM YZ_TB_IMPORTS_STUBHUB_UV_ANT_AIA
    
--TMP:  FOR RUNNING SQL JOBS FOR PREVIOUS DAYS:  
--SET @DATE_BEG = '05/23/2014'
--SET @DATE_END = '06/05/2014'

--==================================--SET DATEFIRST 1  --1=MONDAY  7=SUNDAY  --DW = M,T,W,T,F,S,S
DECLARE
 @DTM_BEG AS DATETIME
,@DTM_END AS DATETIME
IF @DATE_BEG < '01/01/1901' BEGIN     
    SET @DTM_BEG = CAST(CONVERT(VARCHAR(10),dbo.getdate() - 1,101) AS DATETIME) 
	SET @DTM_END = CAST(CONVERT(VARCHAR(10),dbo.getdate() - 1,101) AS DATETIME) -- + 1
END
ELSE BEGIN
    SET @DTM_BEG = CAST(CONVERT(VARCHAR(10),@DATE_BEG,101) AS DATETIME) 
    SET @DTM_END = CAST(CONVERT(VARCHAR(10),@DATE_END,101) AS DATETIME) -- + 1
END
SET @DTM_END    = @DTM_END + 1  --EVERYTHING ABOVE, @DTM_END IS FOR EXACT DATE RANGE NEEDED. ONE IS ADDED SO WHERE CLAUSE " < @DTM_END" WORKS.

DECLARE
 @MTD_BEG AS DATETIME
,@MTD_END AS DATETIME  --,@YTD_BEG AS DATETIME--,@YTD_END AS DATETIME
SET @MTD_BEG = CAST(CAST(DATEPART(mm,@DTM_BEG) AS VARCHAR(2)) + '/01/' + CAST(DATEPART(yyyy,@DTM_BEG) AS VARCHAR(4)) AS DATETIME)
SET @MTD_END = @DTM_END  --SET @YTD_BEG = CAST('01/01/' + CAST(DATEPART(yyyy,@DTM_BEG) AS VARCHAR(4)) AS DATETIME)  --THINK _BEG MAKES MORE SENSE THAN _END.--SET @YTD_END = @DTM_END
--==================================
	--                                                         MD=Month with daily totals.   MR=Month, NO Daily totals.
	--                                                         DR=Date Range, NO daily totals.  
	--                                                           The 'M' in MD,MR needed, to know that month is wanted, so @MTD_BEG and @MTD_END can be set correctly...
	--     @DLY_ AND @MTD_ ARE USED TO DETERMINE WHAT DAYS TO SHOW IN THE DIFFERENT ROWS OF DATA.

--@EXECUTIONER FROM SUBSCRIPTION WILL PASS IN 'MR' OR 'MD'.  OTHERWISE WILL BE 'DY' OR 'DR' WHEN MANUAL.

IF @TIME_INTERVAL IN ('MR','MD') BEGIN  --MONTH DETERMINED BY @DTM_BEG.
	SET @DTM_BEG = @MTD_BEG
	SET @DTM_END = @MTD_END
END

--==================================
--SET AMOUNT TO DIVIDE BY:
--==================================
DECLARE @DS DECIMAL(10,2)  --SECONDS TO DIVIDE BY.
IF @DUR_IN = 'SS' BEGIN
    SET @DS = 1.00     --DIVIDE SECONDS BY 1  TO GET SAME, SECONDS.
END
IF @DUR_IN = 'MM' BEGIN
    SET @DS = 60.00    --DIVIDE SECONDS BY 60 TO GET MINUTES.
END
IF @DUR_IN = 'HH' BEGIN
    SET @DS = 3600.00  --DIVIDE SECONDS BY 3600 TO GET HOURS.
END

--==================================
--CREATE TMP TABLE:
--==================================
IF OBJECT_ID('TEMPDB..#IMPORTS_STUBHUB_AGENT_INVOICING') IS NOT NULL BEGIN
   DROP TABLE #IMPORTS_STUBHUB_AGENT_INVOICING
END
CREATE TABLE #IMPORTS_STUBHUB_AGENT_INVOICING
(TENANT_NAME            VARCHAR(50)
,ID_EXT                 VARCHAR(3)
,SCHEDULER_ACL_NAME     VARCHAR(100)  
,EMPLOYEE_ID            VARCHAR(50)   
,STD_TENANT_START_DATE_TIME_KEY INT
,RESOURCE_NAME          VARCHAR(100)

,AIR_DAY_TYPE           varchar(1)
,AIR_ACW_FONT_COLOR     varchar(50)
,MIN_GUARANTEE_RATE     decimal(6,3)
,MIN_GUARANTEE_TYPE     varchar(50)
,AUTHORIZED_TO_INVOICE_TYPE varchar(50)
,HAS_HOLIDAYS           varchar(1)
,INCLUDE_IN_CAS         varchar(1)
,READY_FOR_XML          varchar(1)
,SHOW_ID_EXTS           varchar(1)
,
[LOGGED_IN_TIME] [int] NULL,
[READY_TIME] [int] NULL,
[NOT_READY_TIME] [int] NULL,
[CALLS_ACCEPTED] [int] NULL,
[RING_TIME] [int] NULL,
[TALK_TIME] [int] NULL,
[HOLD_TIME] [int] NULL,
[WRAP_TIME] [int] NULL,
[CONSULT_TIME] [int] NULL,
[HANDLE_TIME] [int] NULL,
[TOTAL_TALK] [decimal](10, 2) NULL,
[CPROD] [decimal](10, 2) NULL,
[MING] [decimal](10, 2) NULL,
[AUT2] [decimal](10, 2) NULL,
)

INSERT INTO #IMPORTS_STUBHUB_AGENT_INVOICING
SELECT
 'STUBHUB'  --T.TENANT_NAME
,''  --UAA.ACD_ID_EXTENSION
,UAA.SCHEDULER_ACL_NAME
,UAA.EMPLOYEE_ID 
,UAA.STD_TENANT_START_DATE_TIME_KEY
,UAA.RESOURCE_NAME

,(ISNULL(UAA.AIR_DAY_TYPE,''))           --AS AIR_DAY_TYPE
,(ISNULL(UAA.AIR_ACW_FONT_COLOR,''))     --AS AIR_ACW_FONT_COLOR
,(ISNULL(UAA.MIN_GUARANTEE_RATE,0.000))  --AS MIN_GUARANTEE_RATE
,(ISNULL(UAA.MIN_GUARANTEE_TYPE,''))     --AS MIN_GUARANTEE_TYPE
,(ISNULL(UAA.AUTHORIZED_TO_INVOICE_TYPE,'')) --AS AUTHORIZED_TO_INVOICE_TYPE
,(ISNULL(UAA.HAS_HOLIDAYS,''))           --AS HAS_HOLIDAYS
,(ISNULL(UAA.INCLUDE_IN_CAS,''))         --AS INCLUDE_IN_CAS
,(ISNULL(UAA.READY_FOR_XML,''))          --AS READY_FOR_XML
,(ISNULL(UAA.SHOW_ID_EXTS,''))           --AS SHOW_ID_EXTS

,(ISNULL(UAA.LOGGED_IN_TIME,0))
,(ISNULL(UAA.READY_TIME,0))
,(ISNULL(UAA.NOT_READY_TIME,0))
,(ISNULL(UAA.CALLS_ACCEPTED,0))
,(ISNULL(UAA.RING_TIME,0))
,(ISNULL(UAA.TALK_TIME,0))
,(ISNULL(UAA.HOLD_TIME,0))
,(ISNULL(UAA.WRAP_TIME,0))
,(ISNULL(UAA.CONSULT_TIME,0))
,(ISNULL(UAA.HANDLE_TIME,0))
,(ISNULL(UAA.TOTAL_TALK,0))
,(ISNULL(UAA.CPROD,0))
,(ISNULL(UAA.MING,0))
,(ISNULL(UAA.AUT2,0))

--DATASOURCES FOR DURATION FIELDS, IN SECONDS, IN HOUR INTERVALS:
--    GROUPED JUST ENOUGH TO BE ABLE TO JOIN DATASOURCES TOGETHER, AND AT MOST BASIC INTERVAL!
FROM
(	SELECT	
	-- UA.TENANT_KEY
	 ''									AS ACD_ID_EXTENSION
	,UA.INVOICE_ID					    AS SCHEDULER_ACL_NAME
	,UA.FF_USER_NAME					AS EMPLOYEE_ID 
	,UA.STD_TENANT_START_DATE_TIME_KEY
	--,MAX(UA.FF_AGENT_NAME)				AS RESOURCE_NAME  -- USED TO PULL AGENTS THAT ARE NOT MAPPED
	,UA.RESOURCE_NAME	                AS RESOURCE_NAME
	,MAX(UA.AIR_DAY_TYPE)               AS AIR_DAY_TYPE
	,'BLACK'                            AS AIR_ACW_FONT_COLOR
	,0									AS MIN_GUARANTEE_RATE
	,''									AS MIN_GUARANTEE_TYPE
	,''									AS AUTHORIZED_TO_INVOICE_TYPE
	,'Y'								AS HAS_HOLIDAYS
	,''									AS INCLUDE_IN_CAS
	,''									AS READY_FOR_XML
	,''									AS SHOW_ID_EXTS

	,SUM(ISNULL(UA.LOGGED_IN_TIME,0))	AS LOGGED_IN_TIME
	,SUM(ISNULL(UA.READY_TIME,0))		AS READY_TIME
	,SUM(ISNULL(UA.NOT_READY_TIME,0))	AS NOT_READY_TIME
	,SUM(ISNULL(UA.CALLS_ACCEPTED,0))	AS CALLS_ACCEPTED
	,SUM(ISNULL(UA.RING_TIME,0))		AS RING_TIME
	,SUM(ISNULL(UA.TALK_TIME,0))		AS TALK_TIME
	,SUM(ISNULL(UA.HOLD_TIME,0))		AS HOLD_TIME
	,SUM(ISNULL(UA.WRAP_TIME,0))		AS WRAP_TIME
	,SUM(ISNULL(UA.CONSULT_TIME,0))		AS CONSULT_TIME
	,SUM(ISNULL(UA.HANDLE_TIME,0))		AS HANDLE_TIME
	,SUM(ISNULL(UA.TOTAL_TALK,0))		AS TOTAL_TALK
	,SUM(ISNULL(UA.CPROD,0))			AS CPROD
	,SUM(ISNULL(UA.MING,0))				AS MING
	,SUM(ISNULL(UA.AUT2,0))				AS AUT2
	
	--  SELECT *
	FROM            YZ_TB_IMPORTS_STUBHUB_INVOICING      UA
	INNER JOIN      DATE_TIME                            DT    ON DT.DATE_TIME_KEY                   = UA.STD_TENANT_START_DATE_TIME_KEY

	WHERE DT.CAL_DATE >= @DTM_BEG AND DT.CAL_DATE <  @DTM_END
	  -- AND ISNULL(UA.RESOURCE_NAME,'') <> ''	-- FILTER OUT AGENTS WITH NO AIA AGENT MAPPING
	  -- AND ISNULL(UA.RESOURCE_NAME,'') = ''	--USED TO PULL AGENTS THAT ARE NOT MAPPED
	GROUP BY 
	 UA.INVOICE_ID
	,UA.FF_USER_NAME
	,UA.RESOURCE_NAME
	,UA.STD_TENANT_START_DATE_TIME_KEY
) UAA

--==============================================================
-- CREATE TEMPORARY TABLE TO RETURN RESULTS
--==============================================================
IF OBJECT_ID('TEMPDB..#IMPORTS_STUBHUB_AGENT_INVOICING_RTN') IS NOT NULL BEGIN
   DROP TABLE #IMPORTS_STUBHUB_AGENT_INVOICING_RTN
END
CREATE TABLE #IMPORTS_STUBHUB_AGENT_INVOICING_RTN
(GRPNO                 INT
,TENANT_NAME           VARCHAR(50)
,ID_EXT                VARCHAR(3)
,SCHEDULER_ACL_NAME    VARCHAR(100)
,EMPLOYEE_ID           VARCHAR(50)
,RESOURCE_NAME         VARCHAR(100)
,CAL_YEAR_MONTH_NUM    VARCHAR(10)
,DATE_INTERVAL         VARCHAR(50)
,TIME_INTERVAL         VARCHAR(10)

,AIR_DAY_TYPE          varchar(1)
,AIR_ACW_FONT_COLOR    varchar(50)
,MIN_GUARANTEE_RATE    decimal(6,3)
,MIN_GUARANTEE_TYPE    varchar(50)
,AUTHORIZED_TO_INVOICE_TYPE varchar(50)
,HAS_HOLIDAYS          varchar(1)
,INCLUDE_IN_CAS        varchar(1)
,READY_FOR_XML         varchar(1)
,SHOW_ID_EXTS          varchar(1)

,AIR_HOLIDAY_IN        VARCHAR(1)
,ALL_AUTHORIZED_TIME   DECIMAL(10,2)

,
[LOGGED_IN_TIME] [decimal](10, 2) NULL,
[READY_TIME] [decimal](10, 2) NULL,
[NOT_READY_TIME] [decimal](10, 2) NULL,
[CALLS_ACCEPTED] [int] NULL,
[RING_TIME] [decimal](10, 2) NULL,
[TALK_TIME] [decimal](10, 2) NULL,
[HOLD_TIME] [decimal](10, 2) NULL,
[WRAP_TIME] [decimal](10, 2) NULL,
[CONSULT_TIME] [decimal](10, 2) NULL,
[HANDLE_TIME] [decimal](10, 2) NULL,
[TOTAL_TALK] [decimal](10, 2) NULL,
[CPROD] [decimal](10, 2) NULL,
[MING] [decimal](10, 2) NULL,
[AUT2] [decimal](10, 2) NULL,
)

--==================================
-- POPULATE TEMPORARY TABLE
--==================================
INSERT INTO #IMPORTS_STUBHUB_AGENT_INVOICING_RTN
SELECT
 20								--AS GRPNO  
,ISNULL(GG.TENANT_NAME       ,'') AS TENANT_NAME
,ISNULL(GG.ID_EXT            ,'') AS ID_EXT
,ISNULL(GG.SCHEDULER_ACL_NAME,'') AS SCHEDULER_ACL_NAME
,ISNULL(GG.EMPLOYEE_ID       ,'') AS EMPLOYEE_ID
,ISNULL(GG.RESOURCE_NAME     ,'') AS RESOURCE_NAME
,ISNULL(GG.CAL_YEAR_MONTH_NUM,'') AS CAL_YEAR_MONTH_NUM
,ISNULL(GG.DI                ,'') AS DI
,ISNULL(GG.TI                ,'') AS TI

,(GG.AIR_DAY_TYPE)                AS AIR_DAY_TYPE
,(GG.AIR_ACW_FONT_COLOR)          AS AIR_ACW_FONT_COLOR
,(GG.MIN_GUARANTEE_RATE)          AS MIN_GUARANTEE_RATE
,(GG.MIN_GUARANTEE_TYPE)          AS MIN_GUARANTEE_TYPE
,(GG.AUTHORIZED_TO_INVOICE_TYPE)  AS AUTHORIZED_TO_INVOICE_TYPE
,(GG.HAS_HOLIDAYS)                AS HAS_HOLIDAYS
,(GG.INCLUDE_IN_CAS)              AS INCLUDE_IN_CAS
,(GG.READY_FOR_XML)               AS READY_FOR_XML
,(GG.SHOW_ID_EXTS)                AS SHOW_ID_EXTS

,'' --AS AIR_HOLIDAY_IN
,0  --AS ALL_AUTHORIZED_TIME

,CAST((ISNULL(GG.LOGGED_IN_TIME	,0)) / @DS AS DECIMAL(10,2))		AS LOGGED_IN_TIME
,CAST((ISNULL(GG.READY_TIME		,0)) / @DS AS DECIMAL(10,2))		AS READY_TIME
,CAST((ISNULL(GG.NOT_READY_TIME	,0)) / @DS AS DECIMAL(10,2))		AS NOT_READY_TIME

,(ISNULL(GG.CALLS_ACCEPTED		,0))								AS CALLS_ACCEPTED

,CAST((ISNULL(GG.RING_TIME		,0)) / @DS AS DECIMAL(10,2))		AS RING_TIME
,CAST((ISNULL(GG.TALK_TIME		,0)) / @DS AS DECIMAL(10,2))		AS TALK_TIME
,CAST((ISNULL(GG.HOLD_TIME		,0)) / @DS AS DECIMAL(10,2))		AS HOLD_TIME
,CAST((ISNULL(GG.WRAP_TIME		,0)) / @DS AS DECIMAL(10,2))		AS WRAP_TIME
,CAST((ISNULL(GG.CONSULT_TIME	,0)) / @DS AS DECIMAL(10,2))		AS CONSULT_TIME
,CAST((ISNULL(GG.HANDLE_TIME	,0)) / @DS AS DECIMAL(10,2))		AS HANDLE_TIME
,CAST((ISNULL(GG.TOTAL_TALK		,0)) / @DS AS DECIMAL(10,2))		AS TOTAL_TALK
,CAST((ISNULL(GG.CPROD			,0)) / @DS AS DECIMAL(10,2))		AS CPROD
,CAST((ISNULL(GG.MING			,0)) / @DS AS DECIMAL(10,2))		AS MING
,CAST((ISNULL(GG.AUT2			,0)) / @DS AS DECIMAL(10,2))		AS AUT2


FROM  -- GG STARTS HERE:
(	SELECT
	 ISNULL(SW.TENANT_NAME,'')        AS TENANT_NAME
	,ISNULL(SW.ID_EXT,'')             AS ID_EXT
	,ISNULL(SW.SCHEDULER_ACL_NAME,'') AS SCHEDULER_ACL_NAME
	,ISNULL(SW.EMPLOYEE_ID,'')		  AS EMPLOYEE_ID
	,ISNULL(SW.RESOURCE_NAME,'')      AS RESOURCE_NAME

	,(CASE WHEN @TIME_INTERVAL IN ('MR') THEN DT.CAL_YEAR_MONTH_NUM ELSE '' END ) AS CAL_YEAR_MONTH_NUM
	,(CASE WHEN @TIME_INTERVAL IN ('MR') THEN LEFT(DT.CAL_MONTH_NAME,3) + ' ' + DT.CAL_YEAR_STRING
		   WHEN @TIME_INTERVAL IN ('DR') THEN ''  ELSE DT.CAL_DATE_STRING END ) AS DI
	,(CASE --WHEN @TIME_INTERVAL = '15' THEN DT.LABEL_HH24 + ':' + DT.LABEL_MI
		   --WHEN @TIME_INTERVAL = '30' THEN DT.LABEL_HH24 + ':' + DT.LABEL_30MI
		   WHEN @TIME_INTERVAL = 'HR' THEN DT.LABEL_HH24 ELSE '' END ) AS TI

	,MAX(SW.AIR_DAY_TYPE)               AS AIR_DAY_TYPE
	,MAX(SW.AIR_ACW_FONT_COLOR)         AS AIR_ACW_FONT_COLOR
	,MAX(SW.MIN_GUARANTEE_RATE)         AS MIN_GUARANTEE_RATE
	,MAX(SW.MIN_GUARANTEE_TYPE)         AS MIN_GUARANTEE_TYPE
	,MAX(SW.AUTHORIZED_TO_INVOICE_TYPE) AS AUTHORIZED_TO_INVOICE_TYPE
	,MAX(SW.HAS_HOLIDAYS)               AS HAS_HOLIDAYS
	,MAX(SW.INCLUDE_IN_CAS)             AS INCLUDE_IN_CAS
	,MAX(SW.READY_FOR_XML)              AS READY_FOR_XML
	,MAX(SW.SHOW_ID_EXTS)               AS SHOW_ID_EXTS

	,SUM(ISNULL(SW.LOGGED_IN_TIME	,0))	AS LOGGED_IN_TIME
	,SUM(ISNULL(SW.READY_TIME		,0))	AS READY_TIME
	,SUM(ISNULL(SW.NOT_READY_TIME	,0))	AS NOT_READY_TIME
	,SUM(ISNULL(SW.CALLS_ACCEPTED	,0))	AS CALLS_ACCEPTED
	,SUM(ISNULL(SW.RING_TIME		,0))	AS RING_TIME
	,SUM(ISNULL(SW.TALK_TIME		,0))	AS TALK_TIME
	,SUM(ISNULL(SW.HOLD_TIME		,0))	AS HOLD_TIME
	,SUM(ISNULL(SW.WRAP_TIME		,0))	AS WRAP_TIME
	,SUM(ISNULL(SW.CONSULT_TIME		,0))	AS CONSULT_TIME
	,SUM(ISNULL(SW.HANDLE_TIME		,0))	AS HANDLE_TIME
	,SUM(ISNULL(SW.TOTAL_TALK		,0))	AS TOTAL_TALK
	,SUM(ISNULL(SW.CPROD			,0))	AS CPROD
	,SUM(ISNULL(SW.MING				,0))	AS MING
	,SUM(ISNULL(SW.AUT2				,0))	AS AUT2
	
	FROM            #IMPORTS_STUBHUB_AGENT_INVOICING	SW
	INNER JOIN      DATE_TIME							DT   ON DT.DATE_TIME_KEY              = SW.STD_TENANT_START_DATE_TIME_KEY
													 
	--WHERE DT.CAL_DATE >= @DTM_BEG AND DT.CAL_DATE <  @DTM_END		  --AND (@TENANT_KEY   IN ('0','') OR SW.TENANT_KEY   = CAST(@TENANT_KEY AS INT) )

	GROUP BY 
	 ISNULL(SW.TENANT_NAME,'')        --AS TENANT_NAME
	,ISNULL(SW.ID_EXT,'')             --AS ID_EXT
	,ISNULL(SW.SCHEDULER_ACL_NAME,'') --AS SCHEDULER_ACL_NAME
	,ISNULL(SW.EMPLOYEE_ID,'')		  --AS EMPLOYEE_ID
	,ISNULL(SW.RESOURCE_NAME,'')	  --AS RESOURCE_NAME

	,(CASE WHEN @TIME_INTERVAL IN ('MR') THEN DT.CAL_YEAR_MONTH_NUM ELSE '' END ) --AS CAL_YEAR_MONTH_NUM
	,(CASE WHEN @TIME_INTERVAL IN ('MR') THEN LEFT(DT.CAL_MONTH_NAME,3) + ' ' + DT.CAL_YEAR_STRING
		   WHEN @TIME_INTERVAL IN ('DR') THEN ''  ELSE DT.CAL_DATE_STRING END ) --AS DI
	,(CASE --WHEN @TIME_INTERVAL = '15' THEN DT.LABEL_HH24 + ':' + DT.LABEL_MI
		   --WHEN @TIME_INTERVAL = '30' THEN DT.LABEL_HH24 + ':' + DT.LABEL_30MI
		   WHEN @TIME_INTERVAL = 'HR' THEN DT.LABEL_HH24 ELSE '' END ) --AS TI

	--,(ISNULL(SW.FF_AGENT_NAME,''))         --AS FF_AGENT_NAME
	--,(ISNULL(SW.FF_USER_NAME,''))          --AS FF_USER_NAME

) GG

--==================================
--IS A HOLIDAY DATE IN THE MIX:
--==================================
DECLARE @HOLIDAY_IN VARCHAR(1)
SET @HOLIDAY_IN = 'N'
DECLARE @I INT
SET @I = (SELECT COUNT(*) FROM #IMPORTS_STUBHUB_AGENT_INVOICING_RTN WHERE AIR_DAY_TYPE = 'H')  --  AND INCLUDE_IN_CAS = 'Y')
IF @I > 0 BEGIN
	SET @HOLIDAY_IN = 'Y'
END
--==================================
UPDATE #IMPORTS_STUBHUB_AGENT_INVOICING_RTN SET
 AIR_HOLIDAY_IN = @HOLIDAY_IN

--======================================================
--UPDATE TOTALS LINE ON REPORT FOR STANDARD AND HOLIDAY:
--======================================================
UPDATE #IMPORTS_STUBHUB_AGENT_INVOICING_RTN SET
 ALL_AUTHORIZED_TIME = ISNULL(LOJ.ALL_AUTHORIZED_TIME,0.0)
FROM #IMPORTS_STUBHUB_AGENT_INVOICING_RTN TA
LEFT OUTER JOIN
(	SELECT
	 SCHEDULER_ACL_NAME
	,EMPLOYEE_ID
	,RESOURCE_NAME
	,AIR_DAY_TYPE
	,SUM(AUT2) AS ALL_AUTHORIZED_TIME
	FROM #IMPORTS_STUBHUB_AGENT_INVOICING_RTN 
	GROUP BY 
	 SCHEDULER_ACL_NAME
	,EMPLOYEE_ID
	,RESOURCE_NAME --EMPLOYEE_ID
	,AIR_DAY_TYPE
) LOJ ON LOJ.SCHEDULER_ACL_NAME = TA.SCHEDULER_ACL_NAME
	 AND LOJ.EMPLOYEE_ID        = TA.EMPLOYEE_ID
	 AND LOJ.RESOURCE_NAME		= TA.RESOURCE_NAME
	 AND LOJ.AIR_DAY_TYPE       = TA.AIR_DAY_TYPE

--==================================
--RETURN DATA
--==================================
--==================================
--POPULATE TABLE READ BY SSIS TO GET END DATE OF DATA REPORT/FILE HAS BEEN RUN FOR:
--==================================
INSERT INTO YZ_TB_FILENAMES_FOR_SSIS
(SQL_JOB_NAME
,FILENM
,CST_ROW_CREATED_TIME)
SELECT
 'uspIMPORTS_STUBHUB_AGENT_INVOICING'  --SQL_JOB_NAME
,REPLACE(CONVERT(VARCHAR(10),@DTM_END - 1,111),'/','')   --FILENM   YYYYMMDD_...
,dbo.getdate()  --CST_ROW_CREATED_TIME

--=====================================
--RETURN DATASET:
--=====================================
SELECT 
 CASE WHEN @DUR_IN = 'SS' THEN '' ELSE 'F' END AS DUR_FORMAT
,CONVERT(VARCHAR(10),@DTM_BEG,101) + '-' + CONVERT(VARCHAR(10),@DTM_END - 1,101)  AS DATE_RANGE
,V.*

FROM      #IMPORTS_STUBHUB_AGENT_INVOICING_RTN  V

ORDER BY 
 V.GRPNO
,V.SCHEDULER_ACL_NAME
,V.RESOURCE_NAME
,V.EMPLOYEE_ID
,V.CAL_YEAR_MONTH_NUM
,V.DATE_INTERVAL
,V.TIME_INTERVAL  --SINCE IN MILITARY TIME!




--===============================
EARLY_EXIT:
--===============================
--IMPOSSIBLE:  SELECT 1/0    POSSIBLE:  SELECT 0/1