

CREATE PROCEDURE [dbo].[uspIMPORTS_BRIGHT_PATTERN_DEFAULT_INVOICE_GROUPS]
 @DATE_BEG           DATETIME
,@DATE_END           DATETIME
,@TENANT_KEY         VARCHAR(150)
,@CUSTOMER_ID		 VARCHAR(150)
AS
SET NOCOUNT ON

--  EXECUTE [dbo].[uspIMPORTS_BRIGHT_PATTERN_DEFAULT_INVOICE_GROUPS] '10/16/2017','10/31/2017','0','0'

--~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
DECLARE
 @DTM_BEG AS DATETIME
,@DTM_END AS DATETIME
SET @DTM_BEG = CAST(CONVERT(VARCHAR(10),@DATE_BEG,101) AS DATETIME) 
SET @DTM_END = CAST(CONVERT(VARCHAR(10),@DATE_END,101) AS DATETIME) + 1
--~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
SET @TENANT_KEY = 900905 -- BRIGHT_PATTERN
SET @CUSTOMER_ID = ',' + LTRIM(RTRIM(@CUSTOMER_ID)) + ','

--~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
SELECT
 UA.INVOICE_ID
,UA.INVOICE_ID_DISPLAY
FROM 
(	SELECT
	 CASE WHEN ISNULL(YT.INVOICE_ID,'') = '' THEN 'NO INVOICE GROUP' ELSE YT.INVOICE_ID END AS INVOICE_ID
	,CASE WHEN ISNULL(YT.INVOICE_ID,'') = '' THEN 'NO INVOICE GROUP' ELSE YT.INVOICE_ID END AS INVOICE_ID_DISPLAY
	-- SELECT *
	FROM WSOL_TB_IMPORTS_BRIGHT_PATTERN_INVOICING YT

	WHERE ( YT.[DATETIME] >= @DTM_BEG AND YT.[DATETIME] <  @DTM_END )
	  AND ( @CUSTOMER_ID IN (',,',',0,') OR CHARINDEX(',' + CAST(YT.TENANT_KEY AS VARCHAR(10)) + ',',@CUSTOMER_ID) > 0 )

	GROUP BY
	 CASE WHEN ISNULL(YT.INVOICE_ID,'') = '' THEN 'NO INVOICE GROUP' ELSE YT.INVOICE_ID END
) UA
ORDER BY UA.INVOICE_ID DESC

--~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~