

CREATE PROCEDURE [dbo].[uspIMPORTS_HUMACH_DEFAULT_CUSTOMERS]
 @DATE_BEG           DATETIME
,@DATE_END           DATETIME
AS
SET NOCOUNT ON

--  EXECUTE [dbo].[uspIMPORTS_HUMACH_DEFAULT_CUSTOMERS] '04/01/2016','04/15/2016'

--~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
DECLARE
 @DTM_BEG AS DATETIME
,@DTM_END AS DATETIME
SET @DTM_BEG = CAST(CONVERT(VARCHAR(10),@DATE_BEG,101) AS DATETIME) 
SET @DTM_END = CAST(CONVERT(VARCHAR(10),@DATE_END,101) AS DATETIME) + 1
--~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
SELECT
 UA.FF_CUSTOMER_ID
,UA.FF_CUSTOMER_NAME
FROM 
(	SELECT
	 YT.FF_CUSTOMER_ID
	,YT.FF_CUSTOMER_NAME
	--  SELECT *
	FROM WSOL_TB_IMPORTS_HUMACH_INVOICING YT

	--WHERE YT.[DATETIME] >= @DTM_BEG AND YT.[DATETIME] <  @DTM_END

	GROUP BY
	 YT.FF_CUSTOMER_ID
	,YT.FF_CUSTOMER_NAME
) UA
ORDER BY UA.FF_CUSTOMER_NAME

--~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~