
CREATE PROCEDURE [dbo].[uspIMPORTS_DAILY_SCHEDULE_OFFICIAL_ACL_NAMES]
 @DATE_BEG           DATETIME
,@DATE_END           DATETIME
,@TENANT_NAME        VARCHAR(50)
AS
SET NOCOUNT ON

--  EXECUTE [dbo].[uspIMPORTS_DAILY_SCHEDULE_OFFICIAL_ACL_NAMES] '07/01/2016','07/10/2016','0'
--  EXECUTE [dbo].[uspIMPORTS_DAILY_SCHEDULE_OFFICIAL_ACL_NAMES] '07/01/2016','07/10/2016','ASO,SABRE'
--~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
DECLARE
 @DTM_BEG AS DATETIME
,@DTM_END AS DATETIME
SET @DTM_BEG = CAST(CONVERT(VARCHAR(10),@DATE_BEG,101) AS DATETIME) 
SET @DTM_END = CAST(CONVERT(VARCHAR(10),@DATE_END,101) AS DATETIME) + 1
--~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
SET @TENANT_NAME = ',' + LTRIM(RTRIM(@TENANT_NAME)) + ','
--~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
SELECT
	ISNULL(SC.OFFICIAL_ACL_NAME, WK.OFFICIAL_ACL_NAME) AS OFFICIAL_ACL_NAME
	--  SELECT *
	FROM WSOL_TB_IMPORTS_WORK_HOURS_ALL	WK
	FULL OUTER JOIN	WSOL_TB_IMPORTS_DAILY_SCHEDULE	SC
	
	 ON WK.OFFICIAL_ACL_NAME				= SC.OFFICIAL_ACL_NAME
	AND WK.FIELD_MAP_ID						= SC.FIELD_MAP_ID
	AND WK.STD_TENANT_START_DATE_TIME_KEY	= SC.STD_TENANT_START_DATE_TIME_KEY

	WHERE ( ISNULL(WK.DATETIME,SC.DATETIME) >= @DTM_BEG AND ISNULL(WK.DATETIME,SC.DATETIME) <  @DTM_END )
	  AND ( @TENANT_NAME IN (',,',',0,') OR CHARINDEX(',' + RTRIM(ISNULL(WK.TENANT_NAME,SC.TENANT_NAME)) + ',', @TENANT_NAME) > 0 )

	GROUP BY
	 ISNULL(SC.OFFICIAL_ACL_NAME, WK.OFFICIAL_ACL_NAME)

	ORDER BY
	 ISNULL(SC.OFFICIAL_ACL_NAME, WK.OFFICIAL_ACL_NAME)
--~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~