CREATE PROCEDURE [dbo].[uspIMPORTS_SALESFORCE_INFORMATICA_WFM_IMPORT]
AS
SET NOCOUNT ON

--  EXECUTE [dbo].[uspIMPORTS_SALESFORCE_INFORMATICA_WFM_IMPORT]

--  SELECT * FROM WSOL_TB_IMPORTS_SALESFORCE_INFORMATICA_WFM_1 ORDER BY [DATETIME] DESC

--=============================================
DECLARE @TENANT_KEY INT
SET @TENANT_KEY =       900999  --SALESFORCE
--=============================================
DELETE FROM YZ_TB_ERRORS_FOUND 
WHERE TENANT_KEY = @TENANT_KEY
  AND SUB_GROUP_NAME = 'SALESFORCE_INFORMATICA_WFM'    --  SELECT * FROM YZ_TB_ERRORS_FOUND WHERE TENANT_KEY = 900999
--=============================================

--===================================================================================
--USING @WS_ROW_CREATED_TIME FOR ALL INSERTS WILL ALLOW ME TO DELETE SPECIFIC INSERT PROCESSES/FILES.  MOST IMPORTANT!!!  FOR ALL TABLES.
--  IN CASE OF EMERGENCY, CRACK GLASS.
--===================================================================================
DECLARE @WS_ROW_CREATED_TIME AS DATETIME
SET @WS_ROW_CREATED_TIME = dbo.getdate()  --CLOSE ENOUGH TO ACTUAL INSERT TIME!
--===================================================================================

--======================================================================
--HANDLE COLUMN HEADER:
--======================================================================
INSERT INTO WSOL_TB_IMPORTS_SALESFORCE_INFORMATICA_WFM_BAD
(BAD_IMPORTS_NO
,BAD_IMPORTS_FILE_TYPE
,WS_ROW_CREATED_TIME
,FF_SCHEDULER_ACL
,FF_FIELD_MAP_NAME
,FF_PROGRAM_ID
,FF_COMMON_TEAM_NAME
,FF_FIELD_MAP_ID
,FF_CLIENT_NAME
,FF_CLIENT_ID
,FF_JOBCOST_ID
,FF_SCHEDULED_TIME
,FF_CANCELLED_TIME
,FF_CONFIRMED_TIME
,FF_SCHEDULED_TIME_7
,FF_CANCELLED_TIME_7
,FF_CONFIRMED_TIME_7
,FF_SCHEDULED_TIME_30
,FF_CANCELLED_TIME_30
,FF_CONFIRMED_TIME_30
,FF_RECORD_FILE_DATE
,FF_AGENT_ID
,FF_FIRST_NAME
,FF_LAST_NAME
,FF_CORPORATE_NAME
,FF_EMAIL_ADDRESS
,FF_PASSWORD
,FF_CATS_STATUS
,FF_PRIMARY_PHONE
,FF_ALTERNATE_PHONE
,FF_MOBILE_PHONE
,FF_STREET_ADDRESS
,FF_CITY
,FF_STATE_PROVINCE
,FF_ZIP_POSTAL
,FF_MOBILE_TERMS
,FF_APPLICATION_DATE
,FF_LAST_APP_UPDATE
,FF_BIRTH_MONTH_DAY
,FF_L4_SSN
,FF_AIM_NAME
,FF_ID_AGENT
,FF_OS
,FF_DOWNLOAD_SPEED
,FF_UPLOAD_SPEED
,FF_INDIVIDUAL_W9
,FF_CORPORATE_W9
,FF_MARKETING_CODE
,FF_C_NAME
,[DATETIME]
,STD_TENANT_START_DATE_TIME_KEY
,APPLICATION_DATE
,NICKNAME
,SEQNO_ADDED_TIME
,SEQNO
,FTP_FILE_NAME)

SELECT
 24                     --BAD_IMPORTS_NO  --'Junk Record'
,'WFM'                  --BAD_IMPORTS_FILE_TYPE  --'WFM' FILE.
,@WS_ROW_CREATED_TIME   --WS_ROW_CREATED_TIME--TEST:,dbo.getdate()  --,TNM.*
,W1.FF_SCHEDULER_ACL
,W1.FF_FIELD_MAP_NAME
,W1.FF_PROGRAM_ID
,W1.FF_COMMON_TEAM_NAME
,W1.FF_FIELD_MAP_ID
,W1.FF_CLIENT_NAME
,W1.FF_CLIENT_ID
,W1.FF_JOBCOST_ID
,W1.FF_SCHEDULED_TIME
,W1.FF_CANCELLED_TIME
,W1.FF_CONFIRMED_TIME
,W1.FF_SCHEDULED_TIME_7
,W1.FF_CANCELLED_TIME_7
,W1.FF_CONFIRMED_TIME_7
,W1.FF_SCHEDULED_TIME_30
,W1.FF_CANCELLED_TIME_30
,W1.FF_CONFIRMED_TIME_30
,W1.FF_RECORD_FILE_DATE
,W1.FF_AGENT_ID
,W1.FF_FIRST_NAME
,W1.FF_LAST_NAME
,W1.FF_CORPORATE_NAME
,W1.FF_EMAIL_ADDRESS
,W1.FF_PASSWORD
,W1.FF_CATS_STATUS
,W1.FF_PRIMARY_PHONE
,W1.FF_ALTERNATE_PHONE
,W1.FF_MOBILE_PHONE
,W1.FF_STREET_ADDRESS
,W1.FF_CITY
,W1.FF_STATE_PROVINCE
,W1.FF_ZIP_POSTAL
,W1.FF_MOBILE_TERMS
,W1.FF_APPLICATION_DATE
,W1.FF_LAST_APP_UPDATE
,W1.FF_BIRTH_MONTH_DAY
,W1.FF_L4_SSN
,W1.FF_AIM_NAME
,W1.FF_ID_AGENT
,W1.FF_OS
,W1.FF_DOWNLOAD_SPEED
,W1.FF_UPLOAD_SPEED
,W1.FF_INDIVIDUAL_W9
,W1.FF_CORPORATE_W9
,W1.FF_MARKETING_CODE
,W1.FF_C_NAME
,W1.[DATETIME]
,W1.STD_TENANT_START_DATE_TIME_KEY
,W1.APPLICATION_DATE
,W1.NICKNAME
,W1.SEQNO_ADDED_TIME
,W1.SEQNO
,W1.FTP_FILE_NAME

FROM           WSOL_TB_IMPORTS_SALESFORCE_INFORMATICA_WFM_1    W1
WHERE ISNULL(W1.FF_AGENT_ID,'') = 'Agent ID'

--======================================================================
--DELETE COLUMN HEADER AND JUNK RECORDS;
--======================================================================
DELETE FROM WSOL_TB_IMPORTS_SALESFORCE_INFORMATICA_WFM_1
WHERE ISNULL(FF_AGENT_ID,'') = 'Agent ID'
--======================================================================

--=============================================
--UPDATE DATETIME
--=============================================
UPDATE WSOL_TB_IMPORTS_SALESFORCE_INFORMATICA_WFM_1 SET
 [DATETIME]			= CAST(LEFT(FF_RECORD_FILE_DATE, 10) AS DATETIME)
,APPLICATION_DATE	= CAST(LEFT(FF_APPLICATION_DATE, 10) AS DATETIME)

--======================================================================
UPDATE WSOL_TB_IMPORTS_SALESFORCE_INFORMATICA_WFM_1 SET
 STD_TENANT_START_DATE_TIME_KEY = DT.DATE_TIME_KEY
FROM            WSOL_TB_IMPORTS_SALESFORCE_INFORMATICA_WFM_1    I
INNER JOIN      DATE_TIME										DT   ON DT.CAL_DATE = I.[DATETIME]

--==============================================
--CREATE NICKNAME
--==============================================
UPDATE WSOL_TB_IMPORTS_SALESFORCE_INFORMATICA_WFM_1 SET
 NICKNAME = FF_FIRST_NAME + ' ' + LEFT(FF_LAST_NAME,1) + '. - WS Agent Since ' + CONVERT(CHAR(3), APPLICATION_DATE, 0) + '. ' + CONVERT(VARCHAR(4),DATEPART(YEAR,APPLICATION_DATE))

--======================================================================
--HANDLE INVALID RECORDS:
--======================================================================
INSERT INTO WSOL_TB_IMPORTS_SALESFORCE_INFORMATICA_WFM_BAD
(BAD_IMPORTS_NO
,BAD_IMPORTS_FILE_TYPE
,WS_ROW_CREATED_TIME
,FF_SCHEDULER_ACL
,FF_FIELD_MAP_NAME
,FF_PROGRAM_ID
,FF_COMMON_TEAM_NAME
,FF_FIELD_MAP_ID
,FF_CLIENT_NAME
,FF_CLIENT_ID
,FF_JOBCOST_ID
,FF_SCHEDULED_TIME
,FF_CANCELLED_TIME
,FF_CONFIRMED_TIME
,FF_SCHEDULED_TIME_7
,FF_CANCELLED_TIME_7
,FF_CONFIRMED_TIME_7
,FF_SCHEDULED_TIME_30
,FF_CANCELLED_TIME_30
,FF_CONFIRMED_TIME_30
,FF_RECORD_FILE_DATE
,FF_AGENT_ID
,FF_FIRST_NAME
,FF_LAST_NAME
,FF_CORPORATE_NAME
,FF_EMAIL_ADDRESS
,FF_PASSWORD
,FF_CATS_STATUS
,FF_PRIMARY_PHONE
,FF_ALTERNATE_PHONE
,FF_MOBILE_PHONE
,FF_STREET_ADDRESS
,FF_CITY
,FF_STATE_PROVINCE
,FF_ZIP_POSTAL
,FF_MOBILE_TERMS
,FF_APPLICATION_DATE
,FF_LAST_APP_UPDATE
,FF_BIRTH_MONTH_DAY
,FF_L4_SSN
,FF_AIM_NAME
,FF_ID_AGENT
,FF_OS
,FF_DOWNLOAD_SPEED
,FF_UPLOAD_SPEED
,FF_INDIVIDUAL_W9
,FF_CORPORATE_W9
,FF_MARKETING_CODE
,FF_C_NAME
,[DATETIME]
,STD_TENANT_START_DATE_TIME_KEY
,APPLICATION_DATE
,NICKNAME
,SEQNO_ADDED_TIME
,SEQNO
,FTP_FILE_NAME)
SELECT
 24                     --BAD_IMPORTS_NO  --'Junk Record'
,'WFM'                  --BAD_IMPORTS_FILE_TYPE  --'WFM' FILE.
,@WS_ROW_CREATED_TIME   --WS_ROW_CREATED_TIME--TEST:,dbo.getdate()  --,TNM.*
,W1.FF_SCHEDULER_ACL
,W1.FF_FIELD_MAP_NAME
,W1.FF_PROGRAM_ID
,W1.FF_COMMON_TEAM_NAME
,W1.FF_FIELD_MAP_ID
,W1.FF_CLIENT_NAME
,W1.FF_CLIENT_ID
,W1.FF_JOBCOST_ID
,W1.FF_SCHEDULED_TIME
,W1.FF_CANCELLED_TIME
,W1.FF_CONFIRMED_TIME
,W1.FF_SCHEDULED_TIME_7
,W1.FF_CANCELLED_TIME_7
,W1.FF_CONFIRMED_TIME_7
,W1.FF_SCHEDULED_TIME_30
,W1.FF_CANCELLED_TIME_30
,W1.FF_CONFIRMED_TIME_30
,W1.FF_RECORD_FILE_DATE
,W1.FF_AGENT_ID
,W1.FF_FIRST_NAME
,W1.FF_LAST_NAME
,W1.FF_CORPORATE_NAME
,W1.FF_EMAIL_ADDRESS
,W1.FF_PASSWORD
,W1.FF_CATS_STATUS
,W1.FF_PRIMARY_PHONE
,W1.FF_ALTERNATE_PHONE
,W1.FF_MOBILE_PHONE
,W1.FF_STREET_ADDRESS
,W1.FF_CITY
,W1.FF_STATE_PROVINCE
,W1.FF_ZIP_POSTAL
,W1.FF_MOBILE_TERMS
,W1.FF_APPLICATION_DATE
,W1.FF_LAST_APP_UPDATE
,W1.FF_BIRTH_MONTH_DAY
,W1.FF_L4_SSN
,W1.FF_AIM_NAME
,W1.FF_ID_AGENT
,W1.FF_OS
,W1.FF_DOWNLOAD_SPEED
,W1.FF_UPLOAD_SPEED
,W1.FF_INDIVIDUAL_W9
,W1.FF_CORPORATE_W9
,W1.FF_MARKETING_CODE
,W1.FF_C_NAME
,W1.[DATETIME]
,W1.STD_TENANT_START_DATE_TIME_KEY
,W1.APPLICATION_DATE
,W1.NICKNAME
,W1.SEQNO_ADDED_TIME
,W1.SEQNO
,W1.FTP_FILE_NAME
FROM           WSOL_TB_IMPORTS_SALESFORCE_INFORMATICA_WFM_1    W1
WHERE ISNULL(W1.FF_AGENT_ID,'') = ''

--======================================================================
--DELETE COLUMN HEADER AND JUNK RECORDS;
--======================================================================
DELETE FROM WSOL_TB_IMPORTS_SALESFORCE_INFORMATICA_WFM_1
WHERE ISNULL(FF_AGENT_ID,'') = ''
--======================================================================

--======================================================================
--HANDLE INVALID DATE/TIME RECORDS:  ( [DATETIME] is joined with DATE_TIME table by cal_date.  If [DATETIME] is not an exact 15 minute interval, issue.)
--======================================================================
INSERT INTO WSOL_TB_IMPORTS_SALESFORCE_INFORMATICA_WFM_BAD
(BAD_IMPORTS_NO
,BAD_IMPORTS_FILE_TYPE
,WS_ROW_CREATED_TIME
,FF_SCHEDULER_ACL
,FF_FIELD_MAP_NAME
,FF_PROGRAM_ID
,FF_COMMON_TEAM_NAME
,FF_FIELD_MAP_ID
,FF_CLIENT_NAME
,FF_CLIENT_ID
,FF_JOBCOST_ID
,FF_SCHEDULED_TIME
,FF_CANCELLED_TIME
,FF_CONFIRMED_TIME
,FF_SCHEDULED_TIME_7
,FF_CANCELLED_TIME_7
,FF_CONFIRMED_TIME_7
,FF_SCHEDULED_TIME_30
,FF_CANCELLED_TIME_30
,FF_CONFIRMED_TIME_30
,FF_RECORD_FILE_DATE
,FF_AGENT_ID
,FF_FIRST_NAME
,FF_LAST_NAME
,FF_CORPORATE_NAME
,FF_EMAIL_ADDRESS
,FF_PASSWORD
,FF_CATS_STATUS
,FF_PRIMARY_PHONE
,FF_ALTERNATE_PHONE
,FF_MOBILE_PHONE
,FF_STREET_ADDRESS
,FF_CITY
,FF_STATE_PROVINCE
,FF_ZIP_POSTAL
,FF_MOBILE_TERMS
,FF_APPLICATION_DATE
,FF_LAST_APP_UPDATE
,FF_BIRTH_MONTH_DAY
,FF_L4_SSN
,FF_AIM_NAME
,FF_ID_AGENT
,FF_OS
,FF_DOWNLOAD_SPEED
,FF_UPLOAD_SPEED
,FF_INDIVIDUAL_W9
,FF_CORPORATE_W9
,FF_MARKETING_CODE
,FF_C_NAME
,[DATETIME]
,STD_TENANT_START_DATE_TIME_KEY
,APPLICATION_DATE
,NICKNAME
,SEQNO_ADDED_TIME
,SEQNO
,FTP_FILE_NAME)
SELECT
 26                     --BAD_IMPORTS_NO  --'Invalid Date/Time'
,'WFM'                  --BAD_IMPORTS_FILE_TYPE  --'WFM' FILE
,@WS_ROW_CREATED_TIME   --WS_ROW_CREATED_TIME--TEST:,dbo.getdate()  --,TNM.*
,W1.FF_SCHEDULER_ACL
,W1.FF_FIELD_MAP_NAME
,W1.FF_PROGRAM_ID
,W1.FF_COMMON_TEAM_NAME
,W1.FF_FIELD_MAP_ID
,W1.FF_CLIENT_NAME
,W1.FF_CLIENT_ID
,W1.FF_JOBCOST_ID
,W1.FF_SCHEDULED_TIME
,W1.FF_CANCELLED_TIME
,W1.FF_CONFIRMED_TIME
,W1.FF_SCHEDULED_TIME_7
,W1.FF_CANCELLED_TIME_7
,W1.FF_CONFIRMED_TIME_7
,W1.FF_SCHEDULED_TIME_30
,W1.FF_CANCELLED_TIME_30
,W1.FF_CONFIRMED_TIME_30
,W1.FF_RECORD_FILE_DATE
,W1.FF_AGENT_ID
,W1.FF_FIRST_NAME
,W1.FF_LAST_NAME
,W1.FF_CORPORATE_NAME
,W1.FF_EMAIL_ADDRESS
,W1.FF_PASSWORD
,W1.FF_CATS_STATUS
,W1.FF_PRIMARY_PHONE
,W1.FF_ALTERNATE_PHONE
,W1.FF_MOBILE_PHONE
,W1.FF_STREET_ADDRESS
,W1.FF_CITY
,W1.FF_STATE_PROVINCE
,W1.FF_ZIP_POSTAL
,W1.FF_MOBILE_TERMS
,W1.FF_APPLICATION_DATE
,W1.FF_LAST_APP_UPDATE
,W1.FF_BIRTH_MONTH_DAY
,W1.FF_L4_SSN
,W1.FF_AIM_NAME
,W1.FF_ID_AGENT
,W1.FF_OS
,W1.FF_DOWNLOAD_SPEED
,W1.FF_UPLOAD_SPEED
,W1.FF_INDIVIDUAL_W9
,W1.FF_CORPORATE_W9
,W1.FF_MARKETING_CODE
,W1.FF_C_NAME
,W1.[DATETIME]
,W1.STD_TENANT_START_DATE_TIME_KEY
,W1.APPLICATION_DATE
,W1.NICKNAME
,W1.SEQNO_ADDED_TIME
,W1.SEQNO
,W1.FTP_FILE_NAME
FROM           WSOL_TB_IMPORTS_SALESFORCE_INFORMATICA_WFM_1    W1
WHERE ISNULL(W1.STD_TENANT_START_DATE_TIME_KEY,0) = 0
--======================================================================
--DELETE INVALID DATE/TIME RECORDS;
--======================================================================
DELETE FROM WSOL_TB_IMPORTS_SALESFORCE_INFORMATICA_WFM_1
WHERE ISNULL(STD_TENANT_START_DATE_TIME_KEY,0) = 0
--======================================================================

--======================================================================
--HANDLE DUPLICATES:
--======================================================================
INSERT INTO WSOL_TB_IMPORTS_SALESFORCE_INFORMATICA_WFM_BAD
(BAD_IMPORTS_NO
,BAD_IMPORTS_FILE_TYPE
,WS_ROW_CREATED_TIME
,FF_SCHEDULER_ACL
,FF_FIELD_MAP_NAME
,FF_PROGRAM_ID
,FF_COMMON_TEAM_NAME
,FF_FIELD_MAP_ID
,FF_CLIENT_NAME
,FF_CLIENT_ID
,FF_JOBCOST_ID
,FF_SCHEDULED_TIME
,FF_CANCELLED_TIME
,FF_CONFIRMED_TIME
,FF_SCHEDULED_TIME_7
,FF_CANCELLED_TIME_7
,FF_CONFIRMED_TIME_7
,FF_SCHEDULED_TIME_30
,FF_CANCELLED_TIME_30
,FF_CONFIRMED_TIME_30
,FF_RECORD_FILE_DATE
,FF_AGENT_ID
,FF_FIRST_NAME
,FF_LAST_NAME
,FF_CORPORATE_NAME
,FF_EMAIL_ADDRESS
,FF_PASSWORD
,FF_CATS_STATUS
,FF_PRIMARY_PHONE
,FF_ALTERNATE_PHONE
,FF_MOBILE_PHONE
,FF_STREET_ADDRESS
,FF_CITY
,FF_STATE_PROVINCE
,FF_ZIP_POSTAL
,FF_MOBILE_TERMS
,FF_APPLICATION_DATE
,FF_LAST_APP_UPDATE
,FF_BIRTH_MONTH_DAY
,FF_L4_SSN
,FF_AIM_NAME
,FF_ID_AGENT
,FF_OS
,FF_DOWNLOAD_SPEED
,FF_UPLOAD_SPEED
,FF_INDIVIDUAL_W9
,FF_CORPORATE_W9
,FF_MARKETING_CODE
,FF_C_NAME
,[DATETIME]
,STD_TENANT_START_DATE_TIME_KEY
,APPLICATION_DATE
,NICKNAME
,SEQNO_ADDED_TIME
,SEQNO
,FTP_FILE_NAME)
SELECT
 21                     --BAD_IMPORTS_NO  --'DUPLICATE'
,'WFM'                  --BAD_IMPORTS_FILE_TYPE  --'WFM' FILE
,@WS_ROW_CREATED_TIME   --WS_ROW_CREATED_TIME--TEST:,dbo.getdate()  --,TNM.*
,W1.FF_SCHEDULER_ACL
,W1.FF_FIELD_MAP_NAME
,W1.FF_PROGRAM_ID
,W1.FF_COMMON_TEAM_NAME
,W1.FF_FIELD_MAP_ID
,W1.FF_CLIENT_NAME
,W1.FF_CLIENT_ID
,W1.FF_JOBCOST_ID
,W1.FF_SCHEDULED_TIME
,W1.FF_CANCELLED_TIME
,W1.FF_CONFIRMED_TIME
,W1.FF_SCHEDULED_TIME_7
,W1.FF_CANCELLED_TIME_7
,W1.FF_CONFIRMED_TIME_7
,W1.FF_SCHEDULED_TIME_30
,W1.FF_CANCELLED_TIME_30
,W1.FF_CONFIRMED_TIME_30
,W1.FF_RECORD_FILE_DATE
,W1.FF_AGENT_ID
,W1.FF_FIRST_NAME
,W1.FF_LAST_NAME
,W1.FF_CORPORATE_NAME
,W1.FF_EMAIL_ADDRESS
,W1.FF_PASSWORD
,W1.FF_CATS_STATUS
,W1.FF_PRIMARY_PHONE
,W1.FF_ALTERNATE_PHONE
,W1.FF_MOBILE_PHONE
,W1.FF_STREET_ADDRESS
,W1.FF_CITY
,W1.FF_STATE_PROVINCE
,W1.FF_ZIP_POSTAL
,W1.FF_MOBILE_TERMS
,W1.FF_APPLICATION_DATE
,W1.FF_LAST_APP_UPDATE
,W1.FF_BIRTH_MONTH_DAY
,W1.FF_L4_SSN
,W1.FF_AIM_NAME
,W1.FF_ID_AGENT
,W1.FF_OS
,W1.FF_DOWNLOAD_SPEED
,W1.FF_UPLOAD_SPEED
,W1.FF_INDIVIDUAL_W9
,W1.FF_CORPORATE_W9
,W1.FF_MARKETING_CODE
,W1.FF_C_NAME
,W1.[DATETIME]
,W1.STD_TENANT_START_DATE_TIME_KEY
,W1.APPLICATION_DATE
,W1.NICKNAME
,W1.SEQNO_ADDED_TIME
,W1.SEQNO
,W1.FTP_FILE_NAME
FROM
(	SELECT
	 [DATETIME]
	,FF_SCHEDULER_ACL
	,FF_FIELD_MAP_NAME
	,FF_PROGRAM_ID
	,FF_COMMON_TEAM_NAME
	,FF_FIELD_MAP_ID
	,FF_CLIENT_ID
	,FF_AGENT_ID
	,ROW_NUMBER() over (partition by [DATETIME], FF_SCHEDULER_ACL, FF_FIELD_MAP_NAME, FF_PROGRAM_ID, FF_COMMON_TEAM_NAME, FF_FIELD_MAP_ID, FF_CLIENT_ID, FF_AGENT_ID
                            order by [DATETIME], FF_AGENT_ID, FF_PROGRAM_ID DESC) ROWNO
	FROM WSOL_TB_IMPORTS_SALESFORCE_INFORMATICA_WFM_1
) TNM
LEFT JOIN      WSOL_TB_IMPORTS_SALESFORCE_INFORMATICA_WFM_1    W1	ON	W1.[DATETIME]			=	TNM.[DATETIME]
																	AND W1.FF_SCHEDULER_ACL		=	TNM.FF_SCHEDULER_ACL
																	AND W1.FF_FIELD_MAP_NAME	=	TNM.FF_FIELD_MAP_NAME
																	AND W1.FF_PROGRAM_ID		=	TNM.FF_PROGRAM_ID
																	AND W1.FF_COMMON_TEAM_NAME	=	TNM.FF_COMMON_TEAM_NAME
																	AND W1.FF_FIELD_MAP_ID		=	TNM.FF_FIELD_MAP_ID
																	AND W1.FF_CLIENT_ID			=	TNM.FF_CLIENT_ID
																	AND W1.FF_AGENT_ID			=	TNM.FF_AGENT_ID
WHERE TNM.ROWNO > 1

--======================================================================
--DELETE DUPLICATES:
--======================================================================
DELETE FROM TNM  
FROM
(	SELECT
	 [DATETIME]
	,FF_SCHEDULER_ACL
	,FF_FIELD_MAP_NAME
	,FF_PROGRAM_ID
	,FF_COMMON_TEAM_NAME
	,FF_FIELD_MAP_ID
	,FF_CLIENT_ID
	,FF_AGENT_ID
	,ROW_NUMBER() over (partition by [DATETIME], FF_SCHEDULER_ACL, FF_FIELD_MAP_NAME, FF_PROGRAM_ID, FF_COMMON_TEAM_NAME, FF_FIELD_MAP_ID, FF_CLIENT_ID, FF_AGENT_ID
                            order by [DATETIME], FF_AGENT_ID, FF_PROGRAM_ID DESC) ROWNO
	FROM WSOL_TB_IMPORTS_SALESFORCE_INFORMATICA_WFM_1
) TNM
WHERE TNM.ROWNO > 1
--======================================================================

--=============================================	--Hopefully generic enough for all Tenant SSIS to use!
--CHECK FOR BAD DATA FOUND IN IMPORT .TXT FILES:
--=============================================
DECLARE
 @ERR_CNT  INT
,@RCD_CNT  INT
,@MSG1     VARCHAR(2500)
SET @ERR_CNT  = 0 
SET @RCD_CNT  = 0 
SET @MSG1     = ''
--SQL won't insert special characters!!!  + CHAR(9)  --CHAR(10) + CHAR(13)
--Check #1:  ===================================================================================================I DON'T THINK THEY ARE PUTTING DUD FILES ON FTP.
	SET @RCD_CNT = (	SELECT COUNT(*) FROM WSOL_TB_IMPORTS_SALESFORCE_INFORMATICA_WFM_1 )
	IF @RCD_CNT < 1 BEGIN
		SET @MSG1 = @MSG1 + '1) File Import Failed.  No Records Were/Could Be Imported.   |   ' 
		SET @ERR_CNT = @ERR_CNT + 1
	END

--=============================== INSERT INTO PERMANENT TABLE (No errors) OR SKIP AND GO TO END (Errors):
IF @ERR_CNT > 0 BEGIN
	--SSIS reads yz_tb_errors_found table where tenant_key = 900543, and if record exists, outputs results/error_msg field in an email.
	INSERT INTO YZ_TB_ERRORS_FOUND
	(TENANT_KEY
,SUB_GROUP_NAME
,ERROR_MSG)
	SELECT 
	 @TENANT_KEY					--TENANT_KEY
	,'SALESFORCE-INFORMATICA-WFM'	--SUB_GROUP_NAME
	,@MSG1							--ERROR_MSG
	--===========================
	GOTO EARLY_EXIT
	--===========================
END
ELSE BEGIN
	
	--=============================================
	--Have to return a record for SSIS, no matter what, otherwise the f thing needs it's mommy:  Can't figure out how to get SSIS to work otherwise!!!

	INSERT INTO YZ_TB_ERRORS_FOUND
		(TENANT_KEY
,SUB_GROUP_NAME
,ERROR_MSG)
	SELECT 
	 @TENANT_KEY					--TENANT_KEY
	,'SALESFORCE-INFORMATICA-WFM'	--SUB_GROUP_NAME
	,''								--ERROR_MSG  --Never make this @MSG1 !!!  Must stay as ''.
	--Do NOT want to got to early exit here because data was good, according to 'checks'!  We want to import data into permanent table.
END

--=============================================
--INSERT INTO PERMANENT IMPORT TABLE: 
--=============================================
INSERT INTO WSOL_TB_IMPORTS_SALESFORCE_INFORMATICA_WFM
(SCHEDULER_ACL
,FIELD_MAP_NAME
,PROGRAM_ID
,COMMON_TEAM_NAME
,FIELD_MAP_ID
,CLIENT_NAME
,CLIENT_ID
,JOBCOST_ID
,SCHEDULED_TIME
,CANCELLED_TIME
,CONFIRMED_TIME
,SCHEDULED_TIME_7
,CANCELLED_TIME_7
,CONFIRMED_TIME_7
,SCHEDULED_TIME_30
,CANCELLED_TIME_30
,CONFIRMED_TIME_30
,RECORD_FILE_DATE
,AGENT_ID
,FIRST_NAME
,LAST_NAME
,CORPORATE_NAME
,EMAIL_ADDRESS
,[PASSWORD]
,CATS_STATUS
,PRIMARY_PHONE
,ALTERNATE_PHONE
,MOBILE_PHONE
,STREET_ADDRESS
,CITY
,STATE_PROVINCE
,ZIP_POSTAL
,MOBILE_TERMS
,APPLICATION_DATE
,LAST_APP_UPDATE
,BIRTH_MONTH_DAY
,L4_SSN
,AIM_NAME
,ID_AGENT
,OS
,DOWNLOAD_SPEED
,UPLOAD_SPEED
,INDIVIDUAL_W9
,CORPORATE_W9
,MARKETING_CODE
,CATS_PROFILE_NAME
,NICKNAME
,STD_TENANT_START_DATE_TIME_KEY
,SEQNO_ADDED_TIME
,SEQNO
,FTP_FILE_NAME
,WS_ROW_CREATED_TIME
,WS_ROW_UPDATED_TIME
)
SELECT
 ISNULL(W1.FF_SCHEDULER_ACL,'')					AS SCHEDULER_ACL
,ISNULL(W1.FF_FIELD_MAP_NAME,'')				AS FIELD_MAP_NAME
,ISNULL(CAST(W1.FF_PROGRAM_ID AS INT),0)		AS PROGRAM_ID
,ISNULL(W1.FF_COMMON_TEAM_NAME,'')				AS COMMON_TEAM_NAME
,ISNULL(W1.FF_FIELD_MAP_ID,'')					AS FIELD_MAP_ID
,ISNULL(W1.FF_CLIENT_NAME,'')					AS CLIENT_NAME
,ISNULL(CAST(W1.FF_CLIENT_ID AS INT),0)			AS CLIENT_ID
,ISNULL(W1.FF_JOBCOST_ID,'')					AS JOBCOST_ID
,ISNULL(CAST(W1.FF_SCHEDULED_TIME AS INT),0)	AS SCHEDULED_TIME
,ISNULL(CAST(W1.FF_CANCELLED_TIME AS INT),0)	AS CANCELLED_TIME
,ISNULL(CAST(W1.FF_CONFIRMED_TIME AS INT),0)	AS CONFIRMED_TIME
,ISNULL(CAST(W1.FF_SCHEDULED_TIME_7 AS INT),0)	AS SCHEDULED_TIME_7
,ISNULL(CAST(W1.FF_CANCELLED_TIME_7 AS INT),0)	AS CANCELLED_TIME_7
,ISNULL(CAST(W1.FF_CONFIRMED_TIME_7 AS INT),0)	AS CONFIRMED_TIME_7
,ISNULL(CAST(W1.FF_SCHEDULED_TIME_30 AS INT),0)	AS SCHEDULED_TIME_30
,ISNULL(CAST(W1.FF_CANCELLED_TIME_30 AS INT),0)	AS CANCELLED_TIME_30
,ISNULL(CAST(W1.FF_CONFIRMED_TIME_30 AS INT),0) AS CONFIRMED_TIME_30
,[DATETIME]										AS RECORD_FILE_DATE
,ISNULL(W1.FF_AGENT_ID,'')						AS AGENT_ID
,ISNULL(W1.FF_FIRST_NAME,'')					AS FIRST_NAME
,ISNULL(W1.FF_LAST_NAME,'')						AS LAST_NAME
,NULLIF(W1.FF_CORPORATE_NAME,'0')				AS CORPORATE_NAME
,ISNULL(W1.FF_EMAIL_ADDRESS,'')					AS EMAIL_ADDRESS
,ISNULL(W1.FF_PASSWORD,'')						AS [PASSWORD]
,ISNULL(W1.FF_CATS_STATUS,'')					AS CATS_STATUS
,ISNULL(W1.FF_PRIMARY_PHONE,'')					AS PRIMARY_PHONE
,ISNULL(W1.FF_ALTERNATE_PHONE,'')				AS ALTERNATE_PHONE
,ISNULL(W1.FF_MOBILE_PHONE,'')					AS MOBILE_PHONE
,ISNULL(W1.FF_STREET_ADDRESS,'')				AS STREET_ADDRESS
,ISNULL(W1.FF_CITY,'')							AS CITY
,ISNULL(W1.FF_STATE_PROVINCE,'')				AS STATE_PROVINCE
,ISNULL(W1.FF_ZIP_POSTAL,'')					AS ZIP_POSTAL
,ISNULL(CAST(W1.FF_MOBILE_TERMS AS INT),0)		AS MOBILE_TERMS
,W1.APPLICATION_DATE							AS APPLICATION_DATE
,CAST(LEFT(FF_LAST_APP_UPDATE, 10) AS DATETIME)	AS LAST_APP_UPDATE
,ISNULL(W1.FF_BIRTH_MONTH_DAY,'00/00')			AS BIRHT_MONTH_DAY
,ISNULL(W1.FF_L4_SSN,'0000')					AS L4_SSN
,ISNULL(W1.FF_AIM_NAME,'')						AS AIM_NAME
,ISNULL(W1.FF_ID_AGENT,'')						AS ID_AGENT
,ISNULL(W1.FF_OS,'')							AS OS
,ISNULL(CAST(W1.FF_DOWNLOAD_SPEED AS INT),0)	AS DOWNLOAD_SPEED
,ISNULL(CAST(W1.FF_UPLOAD_SPEED   AS INT),0)	AS UPLOAD_SPEED
,ISNULL(CAST(W1.FF_INDIVIDUAL_W9  AS INT),0)	AS INDIVIDUAL_W9
,ISNULL(CAST(W1.FF_CORPORATE_W9	  AS INT),0)	AS CORPORATE_W9
,ISNULL(CAST(W1.FF_MARKETING_CODE AS INT),0)	AS MARKETING_CODE
,ISNULL(W1.FF_C_NAME,'')						AS CATS_PROFILE_NAME
,W1.NICKNAME									AS NICKNAME

,W1.STD_TENANT_START_DATE_TIME_KEY				AS STD_TENANT_START_DATE_TIME_KEY
,W1.SEQNO_ADDED_TIME							AS SEQNO_ADDED_TIME
,W1.SEQNO										AS SEQNO
,W1.FTP_FILE_NAME								AS FTP_FILE_NAME

,@WS_ROW_CREATED_TIME							AS WS_ROW_CREATED_TIME
,NULL											AS WS_ROW_UPDATED_TIME

FROM            WSOL_TB_IMPORTS_SALESFORCE_INFORMATICA_WFM_1  W1

LEFT JOIN       WSOL_TB_IMPORTS_SALESFORCE_INFORMATICA_WFM    G		 ON G.STD_TENANT_START_DATE_TIME_KEY = W1.STD_TENANT_START_DATE_TIME_KEY
																	AND G.PROGRAM_ID                     = W1.FF_PROGRAM_ID
																	AND G.AGENT_ID						 = W1.FF_AGENT_ID

WHERE (G.AGENT_ID						 IS NULL AND ISNULL(W1.FF_AGENT_ID,'') <> '' )
  AND (G.PROGRAM_ID                      IS NULL AND ISNULL(W1.FF_PROGRAM_ID,'') <> '' )
  AND (G.STD_TENANT_START_DATE_TIME_KEY  IS NULL AND ISNULL(W1.STD_TENANT_START_DATE_TIME_KEY,0) <> 0 )

--=============================================
EARLY_EXIT:
--===========================================