
CREATE PROCEDURE [dbo].[uspIMPORTS_APFM_AIA_REPORTING]
 @DATE_BEG           DATETIME
,@DATE_END           DATETIME
,@TENANT_KEY         VARCHAR(150) --No multiples even though filter below is setup for multiples.
,@SCHEDULER_GROUP    VARCHAR(150) --Hid. Def=' '
,@ID_EXT             VARCHAR(300) --Hid. Def=' '
,@RESOURCE_KEY       VARCHAR(10)  --Hid. Def='0'
,@TIME_INTERVAL      VARCHAR(10)  --Hid. Def='HR'  HR,DY,DR   FOR SUB: MD(Month by Day),MR(Month Range)  15 and 30 not possible !!!!
,@SHOW_RESOURCE      VARCHAR(1)   --Hid. Def='Y'
,@DUR_IN             VARCHAR(2)   --Hid. Def='MM' 
,@RESOURCE_FORMAT    VARCHAR(2)   --Hid. Def='NM' --'NM'=NAME + (employee id),  'ID'=ID
,@SHOW_HOLIDAY       VARCHAR(1)   --Hid. Def='N'
,@PSW                VARCHAR(10)  --Hid. Def='NONE'
,@EXECUTIONER        VARCHAR(3)   --Hid. Def='MAN'  MANual,SUBscription
,@RPT_TYPE_GRP       VARCHAR(3)   --Hid. Def='INV'
,@RPT_TYPE           VARCHAR(3)   --Hid. Def='INV'
,@GROUP_BY_SKILL	 VARCHAR(5)	  --Vis. Def='Y'
AS
SET NOCOUNT ON    

--EXECUTE [dbo].[uspIMPORTS_APFM_AIA_REPORTING] '07/16/2016','07/31/2016','0','0','0','0','HR','Y','MM','NM','Y','4','MAN','INV','INV','True'

--@TIME_INTERVAL:  Can only show invoicing report at hour level or higher !!!

--  SELECT * FROM YZ_TB_IMPORTS_APFM_SD_INVOICE_GROUPS
--  SELECT * FROM WSOL_TB_IMPORTS_APFM_UV_ANT_AIA
    
--TMP:  FOR RUNNING SQL JOBS FOR PREVIOUS DAYS:  
--SET @DATE_BEG = '05/23/2014'
--SET @DATE_END = '06/05/2014'

--==================================--SET DATEFIRST 1  --1=MONDAY  7=SUNDAY  --DW = M,T,W,T,F,S,S
DECLARE
 @DTM_BEG AS DATETIME
,@DTM_END AS DATETIME
IF @DATE_BEG < '01/01/1901' BEGIN     
    SET @DTM_BEG = CAST(CONVERT(VARCHAR(10),dbo.getdate() - 1,101) AS DATETIME) 
	SET @DTM_END = CAST(CONVERT(VARCHAR(10),dbo.getdate() - 1,101) AS DATETIME) -- + 1
END
ELSE BEGIN
    SET @DTM_BEG = CAST(CONVERT(VARCHAR(10),@DATE_BEG,101) AS DATETIME) 
    SET @DTM_END = CAST(CONVERT(VARCHAR(10),@DATE_END,101) AS DATETIME) -- + 1
END
SET @DTM_END    = @DTM_END + 1  --EVERYTHING ABOVE, @DTM_END IS FOR EXACT DATE RANGE NEEDED. ONE IS ADDED SO WHERE CLAUSE " < @DTM_END" WORKS.

DECLARE
 @MTD_BEG AS DATETIME
,@MTD_END AS DATETIME  --,@YTD_BEG AS DATETIME--,@YTD_END AS DATETIME
SET @MTD_BEG = CAST(CAST(DATEPART(mm,@DTM_BEG) AS VARCHAR(2)) + '/01/' + CAST(DATEPART(yyyy,@DTM_BEG) AS VARCHAR(4)) AS DATETIME)
SET @MTD_END = @DTM_END

IF @TIME_INTERVAL IN ('MR','MD') BEGIN  --MONTH DETERMINED BY @DTM_BEG.
	SET @DTM_BEG = @MTD_BEG
	SET @DTM_END = @MTD_END
END


--==================================
--SET @TENANT_KEY      = ',' + LTRIM(RTRIM(@TENANT_KEY))      + ','
SET @SCHEDULER_GROUP = ',' + LTRIM(RTRIM(REPLACE(@SCHEDULER_GROUP,'NO SCHEDULER GROUP',''))) + ','
--SET @ID_EXT          = ',' + LTRIM(RTRIM(@ID_EXT))          + ','


--==================================
--SET AMOUNT TO DIVIDE BY:
--==================================
DECLARE @DS DECIMAL(10,2)  --SECONDS TO DIVIDE BY.
IF @DUR_IN = 'SS' BEGIN
    SET @DS = 1.00     --DIVIDE SECONDS BY 1  TO GET SAME, SECONDS.
END
IF @DUR_IN = 'MM' BEGIN
    SET @DS = 60.00    --DIVIDE SECONDS BY 60 TO GET MINUTES.
END
IF @DUR_IN = 'HH' BEGIN
    SET @DS = 3600.00  --DIVIDE SECONDS BY 3600 TO GET HOURS.
END

--SELECT * FROM WSOL_TB_IMPORTS_APFM_INVOICING
--==================================
--CREATE TMP TABLE:
--==================================
IF OBJECT_ID('TEMPDB..#IMPORTS_APFM_AIA_REPORTING') IS NOT NULL BEGIN
   DROP TABLE #IMPORTS_APFM_AIA_REPORTING
END
CREATE TABLE #IMPORTS_APFM_AIA_REPORTING
(TENANT_NAME            VARCHAR(50)
,ID_EXT                 VARCHAR(3)
,SCHEDULER_ACL_NAME     VARCHAR(100)
,FF_SKILL_AVAILABILITY	VARCHAR(500)  
,EMPLOYEE_ID            VARCHAR(50)   
,STD_TENANT_START_DATE_TIME_KEY INT
,RESOURCE_NAME          VARCHAR(100)

,AIR_DAY_TYPE           varchar(1)
,AIR_ACW_FONT_COLOR     varchar(50)
,MIN_GUARANTEE_RATE     decimal(6,3)
,MIN_GUARANTEE_TYPE     varchar(50)
,AUTHORIZED_TO_INVOICE_TYPE varchar(50)
,HAS_HOLIDAYS           varchar(1)
,INCLUDE_IN_CAS         varchar(1)
,READY_FOR_XML          varchar(1)
,SHOW_ID_EXTS           varchar(1)
,
[LOGGED_IN_DUR] [decimal] (10,2) NULL,
[READY_DUR] [decimal] (10,2) NULL,
[RING_DUR] [decimal] (10,2) NULL,
[ON_CALL_DUR] [decimal] (10,2) NULL,
[ON_CALL_SILENT_DUR] [decimal] (10,2) NULL,
[ACW_DUR] [decimal] (10,2) NULL,
[ON_PARK_DUR] [decimal] (10,2) NULL,
[ON_VOICEMAIL_DUR] [decimal] (10,2) NULL,
[ON_PREVIEW_DUR] [decimal] (10,2) NULL,
[NRD_ACW_DUR] [decimal] (10,2) NULL,
[NRD_TASK_COMP_DUR] [decimal] (10,2) NULL,
[NRD_SYSTEM_OBC_DUR] [decimal] (10,2) NULL,
[ON_HOLD_DUR] [decimal] (10,2) NULL,
[NRD_TRAINING_DUR] [decimal] (10,2) NULL,
[NRD_MEETING_DUR] [decimal] (10,2) NULL,
[NRD_MANDATORY_REPORTING_DUR] [decimal] (10,2) NULL,
[NRD_MANUAL_OBC_DUR] [decimal] (10,2) NULL,
[NRD_ACW_AGENT_DUR] [decimal] (10,2) NULL,
[NRD_OFFLINE_VENDOR_UNPAID_DUR] [decimal] (10,2) NULL,
[NRD_REASON_4_DUR] [decimal] (10,2) NULL,
[NOT_READY_BILLABLE] [decimal] (10,2) NULL,
[NOT_READY_NON_BILLABLE] [decimal] (10,2) NULL,
[NON_BILLABLE_SKILL_DUR] [decimal] (10,2) NULL,
[NON_BILLABLE_STATE_REASON_DUR] [decimal] (10,2) NULL,
[BILLABLE_CLIENT] [decimal] (10,2) NULL,
[TOTAL_TALK] [decimal] (10,2) NULL,
[TOTAL_ACW] [decimal] (10,2) NULL,
[AUTHORIZED] [decimal](10, 2) NULL,
)

INSERT INTO #IMPORTS_APFM_AIA_REPORTING
SELECT
 'APFM' --T.TENANT_NAME
,''		--UAA.ACD_ID_EXTENSION
,UAA.SCHEDULER_ACL_NAME
,UAA.FF_SKILL_AVAILABILITY
,UAA.EMPLOYEE_ID 
,UAA.STD_TENANT_START_DATE_TIME_KEY
,UAA.RESOURCE_NAME

,(ISNULL(UAA.AIR_DAY_TYPE,''))           --AS AIR_DAY_TYPE
,(ISNULL(UAA.AIR_ACW_FONT_COLOR,''))     --AS AIR_ACW_FONT_COLOR
,(ISNULL(UAA.MIN_GUARANTEE_RATE,0.000))  --AS MIN_GUARANTEE_RATE
,(ISNULL(UAA.MIN_GUARANTEE_TYPE,''))     --AS MIN_GUARANTEE_TYPE
,(ISNULL(UAA.AUTHORIZED_TO_INVOICE_TYPE,'')) --AS AUTHORIZED_TO_INVOICE_TYPE
,(ISNULL(UAA.HAS_HOLIDAYS,''))           --AS HAS_HOLIDAYS
,(ISNULL(UAA.INCLUDE_IN_CAS,''))         --AS INCLUDE_IN_CAS
,(ISNULL(UAA.READY_FOR_XML,''))          --AS READY_FOR_XML
,(ISNULL(UAA.SHOW_ID_EXTS,''))           --AS SHOW_ID_EXTS

,(ISNULL(UAA.LOGGED_IN_DUR,0))
,(ISNULL(UAA.READY_DUR,0))
,(ISNULL(UAA.RING_DUR,0))
,(ISNULL(UAA.ON_CALL_DUR,0))
,(ISNULL(UAA.ON_CALL_SILENT_DUR,0))
,(ISNULL(UAA.ACW_DUR,0))
,(ISNULL(UAA.ON_PARK_DUR,0))
,(ISNULL(UAA.ON_VOICEMAIL_DUR,0))
,(ISNULL(UAA.ON_PREVIEW_DUR,0))
,(ISNULL(UAA.NRD_ACW_DUR,0))
,(ISNULL(UAA.NRD_TASK_COMP_DUR,0))
,(ISNULL(UAA.NRD_SYSTEM_OBC_DUR,0))
,(ISNULL(UAA.ON_HOLD_DUR,0))
,(ISNULL(UAA.NRD_TRAINING_DUR,0))
,(ISNULL(UAA.NRD_MEETING_DUR,0))
,(ISNULL(UAA.NRD_MANDATORY_REPORTING_DUR,0))
,(ISNULL(UAA.NRD_MANUAL_OBC_DUR,0))
,(ISNULL(UAA.NRD_ACW_AGENT_DUR,0))
,(ISNULL(UAA.NRD_OFFLINE_VENDOR_UNPAID_DUR,0))
,(ISNULL(UAA.NRD_REASON_4_DUR,0))
,(ISNULL(UAA.NOT_READY_BILLABLE,0))
,(ISNULL(UAA.NOT_READY_NON_BILLABLE,0))
,(ISNULL(UAA.NON_BILLABLE_SKILL_DUR,0))
,(ISNULL(UAA.NON_BILLABLE_STATE_REASON_DUR,0))
,(ISNULL(UAA.BILLABLE_CLIENT,0))
,(ISNULL(UAA.TOTAL_TALK,0))
,(ISNULL(UAA.TOTAL_ACW,0))
,(ISNULL(UAA.AUTHORIZED,0))

FROM
(	SELECT	
	-- UA.TENANT_KEY
	 ''  AS ACD_ID_EXTENSION
	,UA.INVOICE_ID					    AS SCHEDULER_ACL_NAME
	,CASE WHEN @GROUP_BY_SKILL = 'True' THEN
			   UA.FF_SKILL_AVAILABILITY
		  ELSE UA.FF_AGENT_NAME  END	AS FF_SKILL_AVAILABILITY
	,UA.FF_AGENT_NAME                   AS EMPLOYEE_ID 
	,UA.STD_TENANT_START_DATE_TIME_KEY
	,MAX(UA.RESOURCE_NAME)              AS RESOURCE_NAME
	,MAX(UA.AIR_DAY_TYPE)               AS AIR_DAY_TYPE
	,'BLACK'                            AS AIR_ACW_FONT_COLOR
	,0									AS MIN_GUARANTEE_RATE
	,''									AS MIN_GUARANTEE_TYPE
	,''									AS AUTHORIZED_TO_INVOICE_TYPE
	,'Y'								AS HAS_HOLIDAYS
	,''									AS INCLUDE_IN_CAS
	,''									AS READY_FOR_XML
	,''									AS SHOW_ID_EXTS

	,SUM(ISNULL(UA.LOGGED_IN_DUR				,0.00))	AS LOGGED_IN_DUR
	,SUM(ISNULL(UA.READY_DUR					,0.00))	AS READY_DUR
	,SUM(ISNULL(UA.RING_DUR						,0.00))	AS RING_DUR
	,SUM(ISNULL(UA.ON_CALL_DUR					,0.00))	AS ON_CALL_DUR
	,SUM(ISNULL(UA.ON_CALL_SILENT_DUR			,0.00))	AS ON_CALL_SILENT_DUR
	,SUM(ISNULL(UA.ACW_DUR						,0.00))	AS ACW_DUR
	,SUM(ISNULL(UA.ON_PARK_DUR					,0.00))	AS ON_PARK_DUR
	,SUM(ISNULL(UA.ON_VOICEMAIL_DUR				,0.00))	AS ON_VOICEMAIL_DUR
	,SUM(ISNULL(UA.ON_PREVIEW_DUR				,0.00))	AS ON_PREVIEW_DUR
	,SUM(ISNULL(UA.NRD_ACW_DUR					,0.00))	AS NRD_ACW_DUR
	,SUM(ISNULL(UA.NRD_TASK_COMP_DUR			,0.00))	AS NRD_TASK_COMP_DUR
	,SUM(ISNULL(UA.NRD_SYSTEM_OBC_DUR			,0.00))	AS NRD_SYSTEM_OBC_DUR
	,SUM(ISNULL(UA.ON_HOLD_DUR					,0.00))	AS ON_HOLD_DUR
	,SUM(ISNULL(UA.NRD_TRAINING_DUR				,0.00))	AS NRD_TRAINING_DUR
	,SUM(ISNULL(UA.NRD_MEETING_DUR				,0.00))	AS NRD_MEETING_DUR
	,SUM(ISNULL(UA.NRD_MANDATORY_REPORTING_DUR	,0.00))	AS NRD_MANDATORY_REPORTING_DUR
	,SUM(ISNULL(UA.NRD_MANUAL_OBC_DUR			,0.00))	AS NRD_MANUAL_OBC_DUR
	,SUM(ISNULL(UA.NRD_ACW_AGENT_DUR			,0.00))	AS NRD_ACW_AGENT_DUR
	,SUM(ISNULL(UA.NRD_OFFLINE_VENDOR_UNPAID_DUR,0.00))	AS NRD_OFFLINE_VENDOR_UNPAID_DUR
	,SUM(ISNULL(UA.NRD_REASON_4_DUR				,0.00))	AS NRD_REASON_4_DUR
	,SUM(ISNULL(UA.NOT_READY_BILLABLE			,0.00))	AS NOT_READY_BILLABLE
	,SUM(ISNULL(UA.NOT_READY_NON_BILLABLE		,0.00))	AS NOT_READY_NON_BILLABLE
	,SUM(ISNULL(UA.NON_BILLABLE_SKILL_DUR		,0.00)) AS NON_BILLABLE_SKILL_DUR
	,SUM(ISNULL(UA.NON_BILLABLE_STATE_REASON_DUR,0.00)) AS NON_BILLABLE_STATE_REASON_DUR
	,SUM(ISNULL(UA.BILLABLE_CLIENT				,0.00))	AS BILLABLE_CLIENT
	,SUM(ISNULL(UA.TOTAL_TALK					,0.00))	AS TOTAL_TALK
	,SUM(ISNULL(UA.TOTAL_ACW					,0.00))	AS TOTAL_ACW
	,SUM(ISNULL(UA.AUTHORIZED					,0.00))	AS AUTHORIZED
	
	--  SELECT *
	FROM            WSOL_TB_IMPORTS_APFM_INVOICING       UA
	INNER JOIN      DATE_TIME                            DT    ON DT.DATE_TIME_KEY                   = UA.STD_TENANT_START_DATE_TIME_KEY

	WHERE DT.CAL_DATE >= @DTM_BEG AND DT.CAL_DATE <  @DTM_END
	  AND (ISNULL(UA.FF_AGENT_NAME,'') NOT IN ('Joshua Miller','Lynne Rochel','Jessica Sharp','Karen Ritter'))	-- FILTER OUT APFM EMPLOYEES
	  AND (@SCHEDULER_GROUP IN (',0,') OR CHARINDEX(',' + RTRIM(UA.INVOICE_ID) + ',',@SCHEDULER_GROUP) > 0) 
--	  AND ISNULL(UA.RESOURCE_NAME,'') <> ''
		
	GROUP BY
	 UA.INVOICE_ID
	,CASE WHEN @GROUP_BY_SKILL = 'True' THEN 
			UA.FF_SKILL_AVAILABILITY
		  ELSE
			UA.FF_AGENT_NAME END
	,UA.FF_AGENT_NAME
	,UA.STD_TENANT_START_DATE_TIME_KEY
) UAA
--SELECT * FROM WSOL_TB_IMPORTS_APFM_INVOICING

--==============================================================
--==============================================================
IF OBJECT_ID('TEMPDB..#IMPORTS_APFM_AIA_REPORTING_RTN') IS NOT NULL BEGIN
   DROP TABLE #IMPORTS_APFM_AIA_REPORTING_RTN
END
CREATE TABLE #IMPORTS_APFM_AIA_REPORTING_RTN
(GRPNO                 INT
,TENANT_NAME           VARCHAR(50)
,ID_EXT                VARCHAR(3)
,SCHEDULER_ACL_NAME    VARCHAR(100)
,FF_SKILL_AVAILABILITY VARCHAR(500)
,EMPLOYEE_ID           VARCHAR(50)
,RESOURCE_NAME         VARCHAR(100)
,CAL_YEAR_MONTH_NUM    VARCHAR(10)
,DATE_INTERVAL         VARCHAR(50)
,TIME_INTERVAL         VARCHAR(10)

,AIR_DAY_TYPE          varchar(1)
,AIR_ACW_FONT_COLOR    varchar(50)
,MIN_GUARANTEE_RATE    decimal(6,3)
,MIN_GUARANTEE_TYPE    varchar(50)
,AUTHORIZED_TO_INVOICE_TYPE varchar(50)
,HAS_HOLIDAYS          varchar(1)
,INCLUDE_IN_CAS        varchar(1)
,READY_FOR_XML         varchar(1)
,SHOW_ID_EXTS          varchar(1)

,AIR_HOLIDAY_IN        VARCHAR(1)
,ALL_AUTHORIZED_TIME   DECIMAL(10,2)

,
[LOGGED_IN_DUR] [decimal] (10,2) NULL,
[READY_DUR] [decimal] (10,2) NULL,
[RING_DUR] [decimal] (10,2) NULL,
[ON_CALL_DUR] [decimal] (10,2) NULL,
[ON_CALL_SILENT_DUR] [decimal] (10,2) NULL,
[ACW_DUR] [decimal] (10,2) NULL,
[ON_PARK_DUR] [decimal] (10,2) NULL,
[ON_VOICEMAIL_DUR] [decimal] (10,2) NULL,
[ON_PREVIEW_DUR] [decimal] (10,2) NULL,
[NRD_ACW_DUR] [decimal] (10,2) NULL,
[NRD_TASK_COMP_DUR] [decimal] (10,2) NULL,
[NRD_SYSTEM_OBC_DUR] [decimal] (10,2) NULL,
[ON_HOLD_DUR] [decimal] (10,2) NULL,
[NRD_TRAINING_DUR] [decimal] (10,2) NULL,
[NRD_MEETING_DUR] [decimal] (10,2) NULL,
[NRD_MANDATORY_REPORTING_DUR] [decimal] (10,2) NULL,
[NRD_MANUAL_OBC_DUR] [decimal] (10,2) NULL,
[NRD_ACW_AGENT_DUR] [decimal] (10,2) NULL,
[NRD_OFFLINE_VENDOR_UNPAID_DUR] [decimal] (10,2) NULL,
[NRD_REASON_4_DUR] [decimal] (10,2) NULL,
[NOT_READY_BILLABLE] [decimal] (10,2) NULL,
[NOT_READY_NON_BILLABLE] [decimal] (10,2) NULL,
[NON_BILLABLE_SKILL_DUR] [decimal] (10,2) NULL,
[NON_BILLABLE_STATE_REASON_DUR] [decimal] (10,2) NULL,
[BILLABLE_CLIENT] [decimal] (10,2) NULL,
[TOTAL_TALK] [decimal] (10,2) NULL,
[TOTAL_ACW] [decimal] (10,2) NULL,
[AUTHORIZED] [decimal](10, 2) NULL,
)
INSERT INTO #IMPORTS_APFM_AIA_REPORTING_RTN
SELECT
 20								--AS GRPNO  
,ISNULL(GG.TENANT_NAME			,'') AS TENANT_NAME
,ISNULL(GG.ID_EXT				,'') AS ID_EXT
,ISNULL(GG.SCHEDULER_ACL_NAME	,'') AS SCHEDULER_ACL_NAME
,ISNULL(GG.FF_SKILL_AVAILABILITY,'') AS FF_SKILL_AVAILABILITY
,ISNULL(GG.EMPLOYEE_ID			,'') AS EMPLOYEE_ID
,ISNULL(GG.RESOURCE_NAME		,'') AS RESOURCE_NAME
,ISNULL(GG.CAL_YEAR_MONTH_NUM	,'') AS CAL_YEAR_MONTH_NUM
,ISNULL(GG.DI					,'') AS DI
,ISNULL(GG.TI					,'') AS TI

,(GG.AIR_DAY_TYPE)                AS AIR_DAY_TYPE
,(GG.AIR_ACW_FONT_COLOR)          AS AIR_ACW_FONT_COLOR
,(GG.MIN_GUARANTEE_RATE)          AS MIN_GUARANTEE_RATE
,(GG.MIN_GUARANTEE_TYPE)          AS MIN_GUARANTEE_TYPE
,(GG.AUTHORIZED_TO_INVOICE_TYPE)  AS AUTHORIZED_TO_INVOICE_TYPE
,(GG.HAS_HOLIDAYS)                AS HAS_HOLIDAYS
,(GG.INCLUDE_IN_CAS)              AS INCLUDE_IN_CAS
,(GG.READY_FOR_XML)               AS READY_FOR_XML
,(GG.SHOW_ID_EXTS)                AS SHOW_ID_EXTS

,'' --AS AIR_HOLIDAY_IN
,0  --AS ALL_AUTHORIZED_TIME

,CAST((ISNULL(GG.LOGGED_IN_DUR					,0)) / @DS AS DECIMAL(10,2)) AS LOGGED_IN_DUR
,CAST((ISNULL(GG.READY_DUR						,0)) / @DS AS DECIMAL(10,2)) AS READY_DUR
,CAST((ISNULL(GG.RING_DUR						,0)) / @DS AS DECIMAL(10,2)) AS RING_DUR
,CAST((ISNULL(GG.ON_CALL_DUR					,0)) / @DS AS DECIMAL(10,2)) AS ON_CALL_DUR
,CAST((ISNULL(GG.ON_CALL_SILENT_DUR				,0)) / @DS AS DECIMAL(10,2)) AS ON_CALL_SILENT_DUR
,CAST((ISNULL(GG.ACW_DUR						,0)) / @DS AS DECIMAL(10,2)) AS ACW_DUR
,CAST((ISNULL(GG.ON_PARK_DUR					,0)) / @DS AS DECIMAL(10,2)) AS ON_PARK_DUR
,CAST((ISNULL(GG.ON_VOICEMAIL_DUR				,0)) / @DS AS DECIMAL(10,2)) AS ON_VOICEMAIL_DUR
,CAST((ISNULL(GG.ON_PREVIEW_DUR					,0)) / @DS AS DECIMAL(10,2)) AS ON_PREVIEW_DUR
,CAST((ISNULL(GG.NRD_ACW_DUR					,0)) / @DS AS DECIMAL(10,2)) AS NRD_ACW_DUR
,CAST((ISNULL(GG.NRD_TASK_COMP_DUR				,0)) / @DS AS DECIMAL(10,2)) AS NRD_TASK_COMP_DUR
,CAST((ISNULL(GG.NRD_SYSTEM_OBC_DUR				,0)) / @DS AS DECIMAL(10,2)) AS NRD_SYSTEM_OBC_DUR
,CAST((ISNULL(GG.ON_HOLD_DUR					,0)) / @DS AS DECIMAL(10,2)) AS ON_HOLD_DUR
,CAST((ISNULL(GG.NRD_TRAINING_DUR				,0)) / @DS AS DECIMAL(10,2)) AS NRD_TRAINING_DUR
,CAST((ISNULL(GG.NRD_MEETING_DUR				,0)) / @DS AS DECIMAL(10,2)) AS NRD_MEETING_DUR
,CAST((ISNULL(GG.NRD_MANDATORY_REPORTING_DUR	,0)) / @DS AS DECIMAL(10,2)) AS NRD_MANDATORY_REPORTING_DUR
,CAST((ISNULL(GG.NRD_MANUAL_OBC_DUR				,0)) / @DS AS DECIMAL(10,2)) AS NRD_MANUAL_OBC_DUR
,CAST((ISNULL(GG.NRD_ACW_AGENT_DUR				,0)) / @DS AS DECIMAL(10,2)) AS NRD_ACW_AGENT_DUR
,CAST((ISNULL(GG.NRD_OFFLINE_VENDOR_UNPAID_DUR	,0)) / @DS AS DECIMAL(10,2)) AS NRD_OFFLINE_VENDOR_UNPAID_DUR
,CAST((ISNULL(GG.NRD_REASON_4_DUR				,0)) / @DS AS DECIMAL(10,2)) AS NRD_REASON_4_DUR
,CAST((ISNULL(GG.NOT_READY_BILLABLE				,0)) / @DS AS DECIMAL(10,2)) AS NOT_READY_BILLABLE
,CAST((ISNULL(GG.NOT_READY_NON_BILLABLE			,0)) / @DS AS DECIMAL(10,2)) AS NOT_READY_NON_BILLABLE
,CAST((ISNULL(GG.NON_BILLABLE_SKILL_DUR			,0)) / @DS AS DECIMAL(10,2)) AS NON_BILLABLE_SKILL_DUR
,CAST((ISNULL(GG.NON_BILLABLE_STATE_REASON_DUR	,0)) / @DS AS DECIMAL(10,2)) AS NON_BILLABLE_STATE_REASON_DUR
,CAST((ISNULL(GG.BILLABLE_CLIENT				,0)) / @DS AS DECIMAL(10,2)) AS BILLABLE_CLIENT
,CAST((ISNULL(GG.TOTAL_TALK						,0)) / @DS AS DECIMAL(10,2)) AS TOTAL_TALK
,CAST((ISNULL(GG.TOTAL_ACW						,0)) / @DS AS DECIMAL(10,2)) AS TOTAL_ACW
,CAST((ISNULL(GG.AUTHORIZED						,0)) / @DS AS DECIMAL(10,2)) AS AUTHORIZED

FROM  -- GG STARTS HERE:
(	SELECT
	 ISNULL(SW.TENANT_NAME			,'') AS TENANT_NAME
	,ISNULL(SW.ID_EXT				,'') AS ID_EXT
	,ISNULL(SW.SCHEDULER_ACL_NAME	,'') AS SCHEDULER_ACL_NAME
	,ISNULL(SW.FF_SKILL_AVAILABILITY,'') AS FF_SKILL_AVAILABILITY
	,ISNULL(SW.EMPLOYEE_ID			,'') AS EMPLOYEE_ID
	,MAX(RESOURCE_NAME)					 AS RESOURCE_NAME

	,(CASE WHEN @TIME_INTERVAL IN ('MR') THEN DT.CAL_YEAR_MONTH_NUM ELSE '' END ) AS CAL_YEAR_MONTH_NUM
	,(CASE WHEN @TIME_INTERVAL IN ('MR') THEN LEFT(DT.CAL_MONTH_NAME,3) + ' ' + DT.CAL_YEAR_STRING
		   WHEN @TIME_INTERVAL IN ('DR') THEN ''  ELSE DT.CAL_DATE_STRING END ) AS DI
	,(CASE --WHEN @TIME_INTERVAL = '15' THEN DT.LABEL_HH24 + ':' + DT.LABEL_MI
		   --WHEN @TIME_INTERVAL = '30' THEN DT.LABEL_HH24 + ':' + DT.LABEL_30MI
		   WHEN @TIME_INTERVAL = 'HR' THEN DT.LABEL_HH24 ELSE '' END ) AS TI

	,MAX(SW.AIR_DAY_TYPE)               AS AIR_DAY_TYPE
	,MAX(SW.AIR_ACW_FONT_COLOR)         AS AIR_ACW_FONT_COLOR
	,MAX(SW.MIN_GUARANTEE_RATE)         AS MIN_GUARANTEE_RATE
	,MAX(SW.MIN_GUARANTEE_TYPE)         AS MIN_GUARANTEE_TYPE
	,MAX(SW.AUTHORIZED_TO_INVOICE_TYPE) AS AUTHORIZED_TO_INVOICE_TYPE
	,MAX(SW.HAS_HOLIDAYS)               AS HAS_HOLIDAYS
	,MAX(SW.INCLUDE_IN_CAS)             AS INCLUDE_IN_CAS
	,MAX(SW.READY_FOR_XML)              AS READY_FOR_XML
	,MAX(SW.SHOW_ID_EXTS)               AS SHOW_ID_EXTS

	,SUM(ISNULL(SW.LOGGED_IN_DUR				,0)) AS LOGGED_IN_DUR
	,SUM(ISNULL(SW.READY_DUR					,0)) AS READY_DUR
	,SUM(ISNULL(SW.RING_DUR						,0)) AS RING_DUR
	,SUM(ISNULL(SW.ON_CALL_DUR					,0)) AS ON_CALL_DUR
	,SUM(ISNULL(SW.ON_CALL_SILENT_DUR			,0)) AS ON_CALL_SILENT_DUR
	,SUM(ISNULL(SW.ACW_DUR						,0)) AS ACW_DUR
	,SUM(ISNULL(SW.ON_PARK_DUR					,0)) AS ON_PARK_DUR
	,SUM(ISNULL(SW.ON_VOICEMAIL_DUR				,0)) AS ON_VOICEMAIL_DUR
	,SUM(ISNULL(SW.ON_PREVIEW_DUR				,0)) AS ON_PREVIEW_DUR
	,SUM(ISNULL(SW.NRD_ACW_DUR					,0)) AS NRD_ACW_DUR
	,SUM(ISNULL(SW.NRD_TASK_COMP_DUR			,0)) AS NRD_TASK_COMP_DUR
	,SUM(ISNULL(SW.NRD_SYSTEM_OBC_DUR			,0)) AS NRD_SYSTEM_OBC_DUR
	,SUM(ISNULL(SW.ON_HOLD_DUR					,0)) AS ON_HOLD_DUR
	,SUM(ISNULL(SW.NRD_TRAINING_DUR				,0)) AS NRD_TRAINING_DUR
	,SUM(ISNULL(SW.NRD_MEETING_DUR				,0)) AS NRD_MEETING_DUR
	,SUM(ISNULL(SW.NRD_MANDATORY_REPORTING_DUR	,0)) AS NRD_MANDATORY_REPORTING_DUR
	,SUM(ISNULL(SW.NRD_MANUAL_OBC_DUR			,0)) AS NRD_MANUAL_OBC_DUR
	,SUM(ISNULL(SW.NRD_ACW_AGENT_DUR			,0)) AS NRD_ACW_AGENT_DUR
	,SUM(ISNULL(SW.NRD_OFFLINE_VENDOR_UNPAID_DUR,0)) AS NRD_OFFLINE_VENDOR_UNPAID_DUR
	,SUM(ISNULL(SW.NRD_REASON_4_DUR				,0)) AS NRD_REASON_4_DUR
	,SUM(ISNULL(SW.NOT_READY_BILLABLE			,0)) AS NOT_READY_BILLABLE
	,SUM(ISNULL(SW.NOT_READY_NON_BILLABLE		,0)) AS NOT_READY_NON_BILLABLE
	,SUM(ISNULL(SW.NON_BILLABLE_SKILL_DUR		,0)) AS NON_BILLABLE_SKILL_DUR
	,SUM(ISNULL(SW.NON_BILLABLE_STATE_REASON_DUR,0)) AS NON_BILLABLE_STATE_REASON_DUR
	,SUM(ISNULL(SW.BILLABLE_CLIENT				,0)) AS BILLABLE_CLIENT
	,SUM(ISNULL(SW.TOTAL_TALK					,0)) AS TOTAL_TALK
	,SUM(ISNULL(SW.TOTAL_ACW					,0)) AS TOTAL_ACW
	,SUM(ISNULL(SW.AUTHORIZED					,0)) AS AUTHORIZED
	
	FROM            #IMPORTS_APFM_AIA_REPORTING		SW
	INNER JOIN      DATE_TIME					    DT   ON DT.DATE_TIME_KEY              = SW.STD_TENANT_START_DATE_TIME_KEY
													 
	--WHERE DT.CAL_DATE >= @DTM_BEG AND DT.CAL_DATE <  @DTM_END		  --AND (@TENANT_KEY   IN ('0','') OR SW.TENANT_KEY   = CAST(@TENANT_KEY AS INT) )

	GROUP BY 
	 ISNULL(SW.TENANT_NAME			,'') --AS TENANT_NAME
	,ISNULL(SW.ID_EXT				,'') --AS ID_EXT
	,ISNULL(SW.SCHEDULER_ACL_NAME	,'') --AS SCHEDULER_ACL_NAME
	,ISNULL(SW.FF_SKILL_AVAILABILITY,'') --AS FF_SKILL_AVAILABILITY
	,ISNULL(SW.EMPLOYEE_ID			,'') --AS EMPLOYEE_ID

	,(CASE WHEN @TIME_INTERVAL IN ('MR') THEN DT.CAL_YEAR_MONTH_NUM ELSE '' END ) --AS CAL_YEAR_MONTH_NUM
	,(CASE WHEN @TIME_INTERVAL IN ('MR') THEN LEFT(DT.CAL_MONTH_NAME,3) + ' ' + DT.CAL_YEAR_STRING
		   WHEN @TIME_INTERVAL IN ('DR') THEN ''  ELSE DT.CAL_DATE_STRING END ) --AS DI
	,(CASE --WHEN @TIME_INTERVAL = '15' THEN DT.LABEL_HH24 + ':' + DT.LABEL_MI
		   --WHEN @TIME_INTERVAL = '30' THEN DT.LABEL_HH24 + ':' + DT.LABEL_30MI
		   WHEN @TIME_INTERVAL = 'HR' THEN DT.LABEL_HH24 ELSE '' END ) --AS TI
) GG



--==================================
--IS A HOLIDAY DATE IN THE MIX:
--==================================
DECLARE @HOLIDAY_IN VARCHAR(1)
SET @HOLIDAY_IN = 'N'
DECLARE @I INT
SET @I = (SELECT COUNT(*) FROM #IMPORTS_APFM_AIA_REPORTING_RTN WHERE AIR_DAY_TYPE = 'H')  --  AND INCLUDE_IN_CAS = 'Y')
IF @I > 0 BEGIN
	SET @HOLIDAY_IN = 'Y'
END
--==================================
UPDATE #IMPORTS_APFM_AIA_REPORTING_RTN SET
 AIR_HOLIDAY_IN = @HOLIDAY_IN

--======================================================
--UPDATE TOTALS LINE ON REPORT FOR STANDARD AND HOLIDAY:
--======================================================
UPDATE #IMPORTS_APFM_AIA_REPORTING_RTN SET
 ALL_AUTHORIZED_TIME = ISNULL(LOJ.ALL_AUTHORIZED_TIME,0.0)
FROM #IMPORTS_APFM_AIA_REPORTING_RTN TA
LEFT OUTER JOIN
(	SELECT
	 SCHEDULER_ACL_NAME
--	,FF_SKILL_AVAILABILITY
	,EMPLOYEE_ID
	,AIR_DAY_TYPE
	,SUM(AUTHORIZED) AS ALL_AUTHORIZED_TIME
	FROM #IMPORTS_APFM_AIA_REPORTING_RTN 
	GROUP BY 
	 SCHEDULER_ACL_NAME
--	,FF_SKILL_AVAILABILITY
	,EMPLOYEE_ID
	,AIR_DAY_TYPE
) LOJ ON LOJ.SCHEDULER_ACL_NAME		= TA.SCHEDULER_ACL_NAME
--	 AND LOJ.FF_SKILL_AVAILABILITY	= TA.FF_SKILL_AVAILABILITY
	 AND LOJ.EMPLOYEE_ID			= TA.EMPLOYEE_ID
	 AND LOJ.AIR_DAY_TYPE			= TA.AIR_DAY_TYPE

--==================================
--RETURN DATA
--==================================
--==================================
--POPULATE TABLE READ BY SSIS TO GET END DATE OF DATA REPORT/FILE HAS BEEN RUN FOR:
--==================================
INSERT INTO YZ_TB_FILENAMES_FOR_SSIS
SELECT
 'uspIMPORTS_APFM_AIA_REPORTING'						--SQL_JOB_NAME
,REPLACE(CONVERT(VARCHAR(10),@DTM_END - 1,111),'/','')  --FILENM   YYYYMMDD_...
,dbo.getdate()												--CST_ROW_CREATED_TIME

--=====================================
--RETURN DATASET:
--=====================================
SELECT 
 CASE WHEN @DUR_IN = 'SS' THEN '' ELSE 'F' END AS DUR_FORMAT
,CONVERT(VARCHAR(10),@DTM_BEG,101) + '-' + CONVERT(VARCHAR(10),@DTM_END - 1,101)  AS DATE_RANGE
,V.*

FROM      #IMPORTS_APFM_AIA_REPORTING_RTN  V

ORDER BY 
 V.GRPNO
,V.SCHEDULER_ACL_NAME
,V.FF_SKILL_AVAILABILITY
,V.EMPLOYEE_ID
,V.CAL_YEAR_MONTH_NUM
,V.DATE_INTERVAL
,V.TIME_INTERVAL  --SINCE IN MILITARY TIME!




--===============================
EARLY_EXIT:
--===============================
--IMPOSSIBLE:  SELECT 1/0    POSSIBLE:  SELECT 0/1