
CREATE PROCEDURE [dbo].[uspIMPORTS_APFM_DEFAULT_SCHEDULER_GROUPS]
 @DATE_BEG           DATETIME
,@DATE_END           DATETIME
AS
SET NOCOUNT ON

--  EXECUTE [dbo].[uspIMPORTS_APFM_DEFAULT_SCHEDULER_GROUPS] '05/12/2014','05/12/2014'
--  EXECUTE [dbo].[uspIMPORTS_APFM_DEFAULT_SCHEDULER_GROUPS] '05/12/2014','05/12/2014'
--~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
DECLARE
 @DTM_BEG AS DATETIME
,@DTM_END AS DATETIME
SET @DTM_BEG = CAST(CONVERT(VARCHAR(10),@DATE_BEG,101) AS DATETIME) 
SET @DTM_END = CAST(CONVERT(VARCHAR(10),@DATE_END,101) AS DATETIME) + 1
--~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
--~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
SELECT
 UA.SCHEDULER_ACL_NAME
,UA.DISPLAY_NAME
FROM 
(	SELECT
	 CASE WHEN ISNULL(YT.INVOICE_ID,'') = '' THEN 'NO INVOICE GROUP' ELSE YT.INVOICE_ID END AS SCHEDULER_ACL_NAME
	,CASE WHEN ISNULL(YT.INVOICE_ID,'') = '' THEN 'NO INVOICE GROUP' ELSE YT.INVOICE_ID END AS DISPLAY_NAME
	--  SELECT *
	FROM WSOL_TB_IMPORTS_APFM_INVOICING YT

	WHERE ( YT.DATETIME >= @DTM_BEG AND YT.DATETIME <  @DTM_END )

	GROUP BY
	 CASE WHEN ISNULL(YT.INVOICE_ID,'') = '' THEN 'NO INVOICE GROUP' ELSE YT.INVOICE_ID END
) UA
ORDER BY UA.SCHEDULER_ACL_NAME

--~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~