CREATE TABLE [dbo].[APLCONTRACT] (
    [IDAPLCONTRACT]           NUMERIC (20)     NOT NULL,
    [IDAPPLICANT]             NUMERIC (20)     NOT NULL,
    [IDCLIENT]                NUMERIC (20)     NOT NULL,
    [CONTRACTDATE]            DATETIME2 (0)    NOT NULL,
    [NOTE]                    VARCHAR (4000)   NOT NULL,
    [IDUSER]                  NUMERIC (20)     NOT NULL,
    [DATECREATED]             DATETIME2 (0)    NOT NULL,
    [CONTACTCONTENT]          VARBINARY (MAX)  NULL,
    [CONTACTFILENAME]         VARCHAR (1000)   NULL,
    [CONTACTFILESIZE]         NUMERIC (20)     NULL,
    [CONTACTDATE]             DATETIME2 (0)    NULL,
    [APLCONTRACT_TYPE_DOC_ID] NUMERIC (20)     DEFAULT ((1)) NOT NULL,
    [ROWID]                   UNIQUEIDENTIFIER DEFAULT (newid()) NOT NULL,
    CONSTRAINT [SYS_C0013256] PRIMARY KEY CLUSTERED ([IDAPLCONTRACT] ASC),
    CONSTRAINT [SYS_C0013664] FOREIGN KEY ([IDUSER]) REFERENCES [dbo].[USERS] ([IDUSER]),
    CONSTRAINT [SYS_C0013665] FOREIGN KEY ([IDAPPLICANT]) REFERENCES [dbo].[applicant] ([IDAPPLICANT])
);






GO
CREATE NONCLUSTERED INDEX [XIF3APLCONTRACT]
    ON [dbo].[APLCONTRACT]([IDCLIENT] ASC);


GO
CREATE NONCLUSTERED INDEX [XIF2APLCONTRACT]
    ON [dbo].[APLCONTRACT]([IDUSER] ASC);


GO
CREATE NONCLUSTERED INDEX [XIF1APLCONTRACT]
    ON [dbo].[APLCONTRACT]([IDAPPLICANT] ASC);


GO
CREATE UNIQUE NONCLUSTERED INDEX [ROWID$INDEX]
    ON [dbo].[APLCONTRACT]([ROWID] ASC);


GO

CREATE   TRIGGER [dbo].[TI_APLCONTRACT$AfterInsert]
   ON [dbo].[APLCONTRACT]
    AFTER INSERT
      AS 
         /*Generated by SQL Server Migration Assistant for Oracle version 7.0.0.*/
         BEGIN

            SET  NOCOUNT  ON

            /* column variables declaration*/
            DECLARE
               @new$0 uniqueidentifier, 
               @new$IDAPPLICANT numeric(20, 0), 
               @new$IDCLIENT numeric(20, 0), 
               @new$IDUSER numeric(20, 0)

            DECLARE
                ForEachInsertedRowTriggerCursor CURSOR LOCAL FORWARD_ONLY READ_ONLY FOR 
                  SELECT ROWID, IDAPPLICANT, IDCLIENT, IDUSER
                  FROM inserted

            OPEN ForEachInsertedRowTriggerCursor

            FETCH ForEachInsertedRowTriggerCursor
                INTO @new$0, @new$IDAPPLICANT, @new$IDCLIENT, @new$IDUSER

            WHILE @@fetch_status = 0
            
               BEGIN

                  /* trigger implementation: begin*/
                  BEGIN

                     DECLARE
                        @numrows int

                     
                     /*
                     *    ERwin Builtin Fri Jan 21 15:46:27 2005
                     *    client R/93 aplcontract ON CHILD INSERT RESTRICT
                     *    ERWIN_RELATION:PARENT_OWNER="", PARENT_TABLE="client"
                     *       CHILD_OWNER="", CHILD_TABLE="aplcontract"
                     *       P2C_VERB_PHRASE="R/93", C2P_VERB_PHRASE="",
                     *       FK_CONSTRAINT="R_93", FK_COLUMNS="idclient"
                     */
                     SELECT @numrows = count_big(*)
                     FROM dbo.CLIENT
                     WHERE /* %JoinFKPK(:%New,client," = "," and")*/@new$IDCLIENT = CLIENT.ID

                     IF (/* %NotnullFK(:%New," is not null and")*/@numrows = 0)
                        BEGIN

                           DECLARE
                              @db_raise_application_error_message nvarchar(4000)

						    DECLARE @NewLineChar AS CHAR(2) = CHAR(13) + CHAR(10)
         SET @db_raise_application_error_message = 'Cannot INSERT aplcontract because client does not exist.' + @NewLineChar + 'Error code used in Oracle: ' + CAST(-20002 AS nvarchar)+'.';
         THROW 60001, @db_raise_application_error_message, 1;

                        END

                     
                     /*
                     *    ERwin Builtin Fri Jan 21 15:46:27 2005
                     *    users R/92 aplcontract ON CHILD INSERT RESTRICT
                     *    ERWIN_RELATION:PARENT_OWNER="", PARENT_TABLE="users"
                     *       CHILD_OWNER="", CHILD_TABLE="aplcontract"
                     *       P2C_VERB_PHRASE="R/92", C2P_VERB_PHRASE="",
                     *       FK_CONSTRAINT="R_92", FK_COLUMNS="iduser"
                     */
                     SELECT @numrows = count_big(*)
                     FROM dbo.USERS
                     WHERE /* %JoinFKPK(:%New,users," = "," and")*/@new$IDUSER = USERS.IDUSER

                     IF (/* %NotnullFK(:%New," is not null and")*/@numrows = 0)
                        BEGIN

                           DECLARE
                              @db_raise_application_error_message$2 nvarchar(4000)

						   
         SET @db_raise_application_error_message = 'Cannot INSERT aplcontract because users does not exist.' + @NewLineChar + 'Error code used in Oracle: ' + CAST(-20002 AS nvarchar)+'.';
         THROW 60001, @db_raise_application_error_message, 1;

                        END

                     
                     /*
                     *    ERwin Builtin Fri Jan 21 15:46:27 2005
                     *    applicant R/91 aplcontract ON CHILD INSERT RESTRICT
                     *    ERWIN_RELATION:PARENT_OWNER="", PARENT_TABLE="applicant"
                     *       CHILD_OWNER="", CHILD_TABLE="aplcontract"
                     *       P2C_VERB_PHRASE="R/91", C2P_VERB_PHRASE="",
                     *       FK_CONSTRAINT="R_91", FK_COLUMNS="idapplicant"
                     */
                     SELECT @numrows = count_big(*)
                     FROM dbo.APPLICANT
                     WHERE /* %JoinFKPK(:%New,applicant," = "," and")*/@new$IDAPPLICANT = APPLICANT.IDAPPLICANT

                     IF (/* %NotnullFK(:%New," is not null and")*/@numrows = 0)
                        BEGIN

                           DECLARE
                              @db_raise_application_error_message$3 nvarchar(4000)

						   
         SET @db_raise_application_error_message = 'Cannot INSERT aplcontract because applicant does not exist.' + @NewLineChar + 'Error code used in Oracle: ' + CAST(-20002 AS nvarchar)+'.';
         THROW 60001, @db_raise_application_error_message, 1;

                        END
                     /* ERwin Builtin Fri Jan 21 15:46:27 2005*/

                  END
                  /* trigger implementation: end*/

                  FETCH ForEachInsertedRowTriggerCursor
                      INTO @new$0, @new$IDAPPLICANT, @new$IDCLIENT, @new$IDUSER

               END

            CLOSE ForEachInsertedRowTriggerCursor

            DEALLOCATE ForEachInsertedRowTriggerCursor

         END
GO

CREATE   TRIGGER [dbo].[TU_APLCONTRACT$AfterUpdate]
   ON [dbo].[APLCONTRACT]
    AFTER UPDATE
      AS 
         /*Generated by SQL Server Migration Assistant for Oracle version 7.0.0.*/
         BEGIN

            SET  NOCOUNT  ON

            /* column variables declaration*/
            DECLARE
               @new$0 uniqueidentifier, 
               @old$0 uniqueidentifier, 
               @new$IDAPPLICANT numeric(20, 0), 
               @new$IDCLIENT numeric(20, 0), 
               @new$IDUSER numeric(20, 0)

            DECLARE
                ForEachInsertedRowTriggerCursor CURSOR LOCAL FORWARD_ONLY READ_ONLY FOR 
                  SELECT ROWID, IDAPPLICANT, IDCLIENT, IDUSER
                  FROM inserted

            OPEN ForEachInsertedRowTriggerCursor

            FETCH ForEachInsertedRowTriggerCursor
                INTO @new$0, @new$IDAPPLICANT, @new$IDCLIENT, @new$IDUSER

            WHILE @@fetch_status = 0
            
               BEGIN

                  /* trigger implementation: begin*/
                  BEGIN

                     DECLARE
                        @numrows int

                     
                     /*
                     *    ERwin Builtin Fri Jan 21 15:46:27 2005
                     *    client R/93 aplcontract ON CHILD UPDATE RESTRICT
                     *    ERWIN_RELATION:PARENT_OWNER="", PARENT_TABLE="client"
                     *       CHILD_OWNER="", CHILD_TABLE="aplcontract"
                     *       P2C_VERB_PHRASE="R/93", C2P_VERB_PHRASE="",
                     *       FK_CONSTRAINT="R_93", FK_COLUMNS="idclient"
                     */
                     SELECT @numrows = count_big(*)
                     FROM dbo.CLIENT
                     WHERE /* %JoinFKPK(:%New,client," = "," and")*/@new$IDCLIENT = CLIENT.ID

                     IF (/* %NotnullFK(:%New," is not null and")*/@numrows = 0)
                        BEGIN

                           DECLARE
                              @db_raise_application_error_message nvarchar(4000)
							  
						    DECLARE @NewLineChar AS CHAR(2) = CHAR(13) + CHAR(10)
         SET @db_raise_application_error_message = 'Cannot UPDATE aplcontract because client does not exist.' + @NewLineChar + 'Error code used in Oracle: ' + CAST(-20007 AS nvarchar)+'.';
         THROW 60000, @db_raise_application_error_message, 1;

                        END

                     
                     /*
                     *    ERwin Builtin Fri Jan 21 15:46:27 2005
                     *    users R/92 aplcontract ON CHILD UPDATE RESTRICT
                     *    ERWIN_RELATION:PARENT_OWNER="", PARENT_TABLE="users"
                     *       CHILD_OWNER="", CHILD_TABLE="aplcontract"
                     *       P2C_VERB_PHRASE="R/92", C2P_VERB_PHRASE="",
                     *       FK_CONSTRAINT="R_92", FK_COLUMNS="iduser"
                     */
                     SELECT @numrows = count_big(*)
                     FROM dbo.USERS
                     WHERE /* %JoinFKPK(:%New,users," = "," and")*/@new$IDUSER = USERS.IDUSER

                     IF (/* %NotnullFK(:%New," is not null and")*/@numrows = 0)
                        BEGIN

                           DECLARE
                              @db_raise_application_error_message$2 nvarchar(4000)

						   
         SET @db_raise_application_error_message = 'Cannot UPDATE aplcontract because users does not exist.' + @NewLineChar + 'Error code used in Oracle: ' + CAST(-20007 AS nvarchar)+'.';
         THROW 60000, @db_raise_application_error_message, 1;

                        END

                     
                     /*
                     *    ERwin Builtin Fri Jan 21 15:46:27 2005
                     *    applicant R/91 aplcontract ON CHILD UPDATE RESTRICT
                     *    ERWIN_RELATION:PARENT_OWNER="", PARENT_TABLE="applicant"
                     *       CHILD_OWNER="", CHILD_TABLE="aplcontract"
                     *       P2C_VERB_PHRASE="R/91", C2P_VERB_PHRASE="",
                     *       FK_CONSTRAINT="R_91", FK_COLUMNS="idapplicant"
                     */
                     SELECT @numrows = count_big(*)
                     FROM dbo.APPLICANT
                     WHERE /* %JoinFKPK(:%New,applicant," = "," and")*/@new$IDAPPLICANT = APPLICANT.IDAPPLICANT

                     IF (/* %NotnullFK(:%New," is not null and")*/@numrows = 0)
                        BEGIN

                           DECLARE
                              @db_raise_application_error_message$3 nvarchar(4000)

						   
         SET @db_raise_application_error_message = 'Cannot UPDATE aplcontract because applicant does not exist.' + @NewLineChar + 'Error code used in Oracle: ' + CAST(-20007 AS nvarchar)+'.';
         THROW 60000, @db_raise_application_error_message, 1;

                        END
                     /* ERwin Builtin Fri Jan 21 15:46:27 2005*/

                  END
                  /* trigger implementation: end*/

                  FETCH ForEachInsertedRowTriggerCursor
                      INTO @new$0, @new$IDAPPLICANT, @new$IDCLIENT, @new$IDUSER

               END

            CLOSE ForEachInsertedRowTriggerCursor

            DEALLOCATE ForEachInsertedRowTriggerCursor

         END