CREATE TABLE [dbo].[APLCONTRACT_TYPE_DOC] (
    [ID]      NUMERIC (20)  NOT NULL,
    [NAME]    VARCHAR (100) NOT NULL,
    [VISIBLE] CHAR (1)      NOT NULL,
    CONSTRAINT [SYS_C0013300] PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [APLCONTRACT_TYPE_DOC_C1] CHECK ([VISIBLE]='N' OR [VISIBLE]='Y')
);

