CREATE TABLE [dbo].[APOSTSTATUS] (
    [IDAPOSTSTATUS] NUMERIC (20)     NOT NULL,
    [NAME]          VARCHAR (500)    NOT NULL,
    [VISIBLE]       CHAR (1)         NOT NULL,
    [ROWID]         UNIQUEIDENTIFIER DEFAULT (newid()) NOT NULL,
    CONSTRAINT [SYS_C0013111] PRIMARY KEY CLUSTERED ([IDAPOSTSTATUS] ASC)
);


GO
CREATE UNIQUE NONCLUSTERED INDEX [ROWID$INDEX]
    ON [dbo].[APOSTSTATUS]([ROWID] ASC);


GO
