CREATE TABLE [dbo].[APOST] (
    [IDAPOST]       NUMERIC (20)     NOT NULL,
    [IDAPPLICANT]   NUMERIC (20)     NOT NULL,
    [IDAPOSTPR]     NUMERIC (20)     NOT NULL,
    [REPLY1]        VARCHAR (4000)   NOT NULL,
    [REPLY2]        VARCHAR (4000)   NOT NULL,
    [REPLY3]        VARCHAR (4000)   NOT NULL,
    [REPLY4]        VARCHAR (4000)   NOT NULL,
    [REPLY5]        VARCHAR (4000)   NOT NULL,
    [HOURSWEEK]     NUMERIC (20)     NOT NULL,
    [DATEINSERT]    DATETIME2 (0)    NOT NULL,
    [IDAPOSTSTATUS] NUMERIC (20)     NULL,
    [REASON1]       CHAR (1)         NULL,
    [REASON2]       CHAR (1)         NULL,
    [REASON3]       CHAR (1)         NULL,
    [REASON4]       CHAR (1)         NULL,
    [REASON5]       CHAR (1)         NULL,
    [REASON6]       CHAR (1)         NULL,
    [REASON7]       CHAR (1)         NULL,
    [REASON8]       CHAR (1)         NULL,
    [REASON9]       CHAR (1)         NULL,
    [REASON10]      CHAR (1)         NULL,
    [COMMENTS]      VARCHAR (4000)   NULL,
    [SHOULDCONSID]  CHAR (1)         NULL,
    [ROWID]         UNIQUEIDENTIFIER DEFAULT (newid()) NOT NULL,
    CONSTRAINT [SYS_C0013109] PRIMARY KEY CLUSTERED ([IDAPOST] ASC),
    CONSTRAINT [SYS_C0013536] FOREIGN KEY ([IDAPOSTPR]) REFERENCES [dbo].[APOSTPR] ([IDAPOSTPR]),
    CONSTRAINT [SYS_C0013537] FOREIGN KEY ([IDAPPLICANT]) REFERENCES [dbo].[applicant] ([IDAPPLICANT]),
    CONSTRAINT [SYS_C0013538] FOREIGN KEY ([IDAPOSTSTATUS]) REFERENCES [dbo].[APOSTSTATUS] ([IDAPOSTSTATUS])
);






GO
CREATE NONCLUSTERED INDEX [XIF3APOST]
    ON [dbo].[APOST]([IDAPOSTSTATUS] ASC);


GO
CREATE NONCLUSTERED INDEX [XIF2APOST]
    ON [dbo].[APOST]([IDAPOSTPR] ASC);


GO
CREATE NONCLUSTERED INDEX [XIF1APOST]
    ON [dbo].[APOST]([IDAPPLICANT] ASC);


GO
CREATE UNIQUE NONCLUSTERED INDEX [ROWID$INDEX]
    ON [dbo].[APOST]([ROWID] ASC);


GO
