CREATE TABLE [dbo].[APOSTPR] (
    [IDAPOSTPR]     NUMERIC (20)     NOT NULL,
    [NAME]          VARCHAR (500)    NOT NULL,
    [VISIBLEAGENT]  CHAR (1)         DEFAULT ('Y') NOT NULL,
    [VISIBLEREPORT] CHAR (1)         DEFAULT ('Y') NOT NULL,
    [IDPROJECT]     NUMERIC (20)     NULL,
    [ROWID]         UNIQUEIDENTIFIER DEFAULT (newid()) NOT NULL,
    CONSTRAINT [SYS_C0013110] PRIMARY KEY CLUSTERED ([IDAPOSTPR] ASC),
    CONSTRAINT [SYS_C0013541] FOREIGN KEY ([IDPROJECT]) REFERENCES [dbo].[PROJECT] ([IDPROJECT])
);


GO
CREATE NONCLUSTERED INDEX [XIF1APOSTPR]
    ON [dbo].[APOSTPR]([IDPROJECT] ASC);


GO
CREATE UNIQUE NONCLUSTERED INDEX [ROWID$INDEX]
    ON [dbo].[APOSTPR]([ROWID] ASC);


GO
