CREATE TABLE [dbo].[APOSTEVAL] (
    [IDAPOST]     NUMERIC (20)     NOT NULL,
    [IDUSER]      NUMERIC (20)     NOT NULL,
    [DATECREATED] DATETIME2 (0)    NOT NULL,
    [ROWID]       UNIQUEIDENTIFIER DEFAULT (newid()) NOT NULL,
    CONSTRAINT [SYS_C0013539] FOREIGN KEY ([IDUSER]) REFERENCES [dbo].[USERS] ([IDUSER]),
    CONSTRAINT [SYS_C0013540] FOREIGN KEY ([IDAPOST]) REFERENCES [dbo].[APOST] ([IDAPOST])
);


GO
CREATE NONCLUSTERED INDEX [XIF2APOSTEVAL]
    ON [dbo].[APOSTEVAL]([IDUSER] ASC);


GO
CREATE NONCLUSTERED INDEX [XIF1APOSTEVAL]
    ON [dbo].[APOSTEVAL]([IDAPOST] ASC);


GO
CREATE UNIQUE NONCLUSTERED INDEX [ROWID$INDEX]
    ON [dbo].[APOSTEVAL]([ROWID] ASC);


GO
