CREATE TABLE [dbo].[APPLICANT] (
    [IDAPPLICANT]               INT              IDENTITY (1, 1) NOT NULL,
    [FIRSTNAME]                 VARCHAR (100)    NOT NULL,
    [LASTNAME]                  VARCHAR (100)    NOT NULL,
    [MAILADDR]                  VARCHAR (4000)   NOT NULL,
    [MAILADDR2]                 VARCHAR (4000)   NULL,
    [CITY]                      VARCHAR (300)    NOT NULL,
    [IDSTATE]                   CHAR (2)         NOT NULL,
    [IDCOUNTRY]                 CHAR (2)         NOT NULL,
    [ZIP]                       VARCHAR (20)     NOT NULL,
    [PHONE]                     VARCHAR (4000)   NOT NULL,
    [PHONEALT]                  VARCHAR (4000)   NOT NULL,
    [EMAIL]                     VARCHAR (1000)   NOT NULL,
    [AIMNAME]                   VARCHAR (500)    NOT NULL,
    [PASSWORD]                  VARCHAR (20)     NOT NULL,
    [FLG_PWD_EXPIRED]           BIT              CONSTRAINT [FLG_PWD_EXPIRED_Default] DEFAULT ((0)) NULL,
    [IDSECRETQUESTION]          NUMERIC (20)     NOT NULL,
    [SECRETANSWER]              VARCHAR (500)    NOT NULL,
    [IDTIMEZONE]                NUMERIC (20)     NOT NULL,
    [IDMODEM]                   NUMERIC (20)     NOT NULL,
    [IDABLEOBTAINBB]            NUMERIC (20)     NOT NULL,
    [IDOPERSYSTEM]              NUMERIC (20)     NOT NULL,
    [IDABLEWIN2K]               NUMERIC (20)     NOT NULL,
    [IDOFTENUSE]                NUMERIC (20)     NOT NULL,
    [IDWORKPLACE]               NUMERIC (20)     NOT NULL,
    [HOURSWEEK]                 NUMERIC (20)     NOT NULL,
    [LANGOTHER]                 VARCHAR (4000)   NOT NULL,
    [YEARS18]                   CHAR (1)         DEFAULT ('Y') NOT NULL,
    [WPM]                       NUMERIC (20)     NOT NULL,
    [INDACCOU]                  NUMERIC (20, 2)  NOT NULL,
    [INDADMIN]                  NUMERIC (20, 2)  NOT NULL,
    [INDCALLCEN]                NUMERIC (20, 2)  NOT NULL,
    [INDCUSTF2F]                NUMERIC (20, 2)  NOT NULL,
    [INDCUSTTEL]                NUMERIC (20, 2)  NOT NULL,
    [INDDATEENT]                NUMERIC (20, 2)  NOT NULL,
    [INDFINANC]                 NUMERIC (20, 2)  NOT NULL,
    [INDHUMRES]                 NUMERIC (20, 2)  NOT NULL,
    [INDINSURAN]                NUMERIC (20, 2)  NOT NULL,
    [INDLEGAL]                  NUMERIC (20, 2)  NOT NULL,
    [INDMEDICAL]                NUMERIC (20, 2)  NOT NULL,
    [INDMARKET]                 NUMERIC (20, 2)  NOT NULL,
    [INDMARKRES]                NUMERIC (20, 2)  NOT NULL,
    [INDPROGR]                  NUMERIC (20, 2)  NOT NULL,
    [INDPRMAN]                  NUMERIC (20, 2)  NOT NULL,
    [INDREALEST]                NUMERIC (20, 2)  NOT NULL,
    [INDRETAIL]                 NUMERIC (20, 2)  NOT NULL,
    [INDSALES]                  NUMERIC (20, 2)  NOT NULL,
    [INDTECHSUP]                NUMERIC (20, 2)  NOT NULL,
    [INDTELEMAR]                NUMERIC (20, 2)  NOT NULL,
    [INDTRANMUL]                NUMERIC (20, 2)  NOT NULL,
    [INDWEBDES]                 NUMERIC (20, 2)  NOT NULL,
    [INDOTHER]                  VARCHAR (4000)   NOT NULL,
    [IDLEVELEDUC]               NUMERIC (20)     NOT NULL,
    [OPTPROF]                   VARCHAR (4000)   NOT NULL,
    [IDHEARABOUT]               NUMERIC (20)     NOT NULL,
    [OPTREFBY]                  VARCHAR (2000)   NOT NULL,
    [IDINTEREST]                NUMERIC (20)     NOT NULL,
    [OPTMOTIV]                  VARCHAR (4000)   NOT NULL,
    [IDSEX]                     CHAR (1)         NOT NULL,
    [IDRACE]                    NUMERIC (20)     NOT NULL,
    [IDAGE]                     NUMERIC (20)     NOT NULL,
    [OPTADDINFO]                VARCHAR (4000)   NOT NULL,
    [DATECREATED]               DATETIME2 (6)    NOT NULL,
    [DATEUPDATED]               DATETIME2 (6)    NOT NULL,
    [IDAPPSTATUS]               NUMERIC (20)     NOT NULL,
    [AGENTID]                   VARCHAR (100)    NOT NULL,
    [WANTNEWSLETTER]            CHAR (1)         NOT NULL,
    [UPPER_FIRSTNAME]           VARCHAR (100)    NULL,
    [UPPER_LASTNAME]            VARCHAR (100)    NULL,
    [HIDDEN_PHONE]              VARCHAR (4000)   NULL,
    [HIDDEN_PHONEALT]           VARCHAR (4000)   NULL,
    [MIDDLINIT]                 VARCHAR (100)    NULL,
    [CORPORATNAME]              VARCHAR (4000)   NULL,
    [CORPORATNAMEPAID]          CHAR (1)         NULL,
    [W9]                        CHAR (1)         DEFAULT ('N') NOT NULL,
    [INDTRAVEL]                 NUMERIC (20, 2)  DEFAULT ((0)) NOT NULL,
    [NICKNAME]                  VARCHAR (500)    DEFAULT (' ') NOT NULL,
    [PENDINGPURGE]              CHAR (1)         DEFAULT ('N') NOT NULL,
    [PENDINGPURGEDATE]          DATETIME2 (6)    DEFAULT (sysdatetime()) NOT NULL,
    [AGENTIDENTNUM]             VARCHAR (9)      DEFAULT ('
') NOT NULL,
    [SFID]                      VARCHAR (50)     NULL,
    [INDCALLCENQA]              NUMERIC (20, 2)  DEFAULT ((0)) NOT NULL,
    [REFERREDBYREWARDPAID]      CHAR (1)         DEFAULT ('N') NOT NULL,
    [REFERREDBYREWARDPAIDDATE]  DATETIME2 (0)    DEFAULT ('01-JAN-70') NOT NULL,
    [CORPORATEW9]               CHAR (1)         DEFAULT ('N') NOT NULL,
    [CORPORATEW9DATECREATED]    DATETIME2 (6)    DEFAULT (sysdatetime()) NOT NULL,
    [PART1ASSESSMENTKEYSPEECH]  VARCHAR (250)    DEFAULT ('??????') NOT NULL,
    [PART2ASSESSMENTKEYGENERAL] CHAR (6)         DEFAULT ('??????') NOT NULL,
    [CONVICTED]                 CHAR (1)         DEFAULT (NULL) NULL,
    [BIRTHDATEMMDD]             CHAR (4)         DEFAULT ('0000') NOT NULL,
    [SSNLAST4DIGITS]            CHAR (4)         DEFAULT ('0000') NOT NULL,
    [MOBILEPHONE]               VARCHAR (4000)   NULL,
    [HIDDEN_MOBILEPHONE]        VARCHAR (4000)   NULL,
    [MOBILETERMS]               CHAR (1)         NOT NULL,
    [INTPROVIDER]               VARCHAR (500)    NOT NULL,
    [TELPROVIDER]               VARCHAR (500)    NOT NULL,
    [OPTFIELDSTUDY]             VARCHAR (4000)   NULL,
    [TSIPADDRESS]               VARCHAR (4000)   NOT NULL,
    [TSPLATFORM]                VARCHAR (4000)   NOT NULL,
    [TSBROWSER]                 VARCHAR (4000)   NOT NULL,
    [TSRESOLUTION]              VARCHAR (4000)   NOT NULL,
    [TSDLBANDWIDTH]             VARCHAR (4000)   NOT NULL,
    [TSMICROPHONE]              CHAR (1)         NOT NULL,
    [INDDBMANAGMENT]            NUMERIC (20, 2)  DEFAULT ((0)) NOT NULL,
    [INDWORKFROMHOME]           NUMERIC (20, 2)  DEFAULT ((0)) NOT NULL,
    [ADDITINDUSORSKILL]         VARCHAR (4000)   DEFAULT (' ') NOT NULL,
    [ALLFIELDSOFSTUDY]          VARCHAR (4000)   DEFAULT (' ') NOT NULL,
    [PROFCERTIFICAT]            VARCHAR (4000)   DEFAULT (' ') NOT NULL,
    [WHATMOTIVATESYOU]          VARCHAR (4000)   DEFAULT (' ') NOT NULL,
    [TELLUSMORE]                VARCHAR (4000)   DEFAULT (' ') NOT NULL,
    [MILITARY_MEMBER_ID]        NUMERIC (20)     DEFAULT ((5)) NOT NULL,
    [IDTELEPHONESERVICETYPE]    NUMERIC (20)     DEFAULT ((1)) NOT NULL,
    [IDHEARABOUT_DATE]          DATETIME2 (6)    DEFAULT ('01-MAY-01') NOT NULL,
    [ENG_LANG_PROF]             VARCHAR (100)    NULL,
    [IC_AWARENESS]              INT              NULL,
    [WORKSPACE_AWARENESS]       INT              NULL,
    [TECH_AWARENESS]            INT              NULL,
    [RESUME]                    VARCHAR (50)     NULL,
    [PHOTO_UPLOAD]              VARCHAR (50)     NULL,
    [ROWID]                     UNIQUEIDENTIFIER DEFAULT (newid()) NOT NULL,
    CONSTRAINT [PK__APPLICAN__CB056AAB6B87CB82] PRIMARY KEY CLUSTERED ([IDAPPLICANT] ASC),
    CONSTRAINT [APPLICANT_C_CONV] CHECK ([CONVICTED]='N' OR [CONVICTED]='Y')
);








GO
CREATE NONCLUSTERED INDEX [XIF5APPLICANT]
    ON [dbo].[APPLICANT]([IDOPERSYSTEM] ASC);


GO
CREATE NONCLUSTERED INDEX [XIF20APPLICANT]
    ON [dbo].[APPLICANT]([IDAPPSTATUS] ASC);


GO
CREATE NONCLUSTERED INDEX [XIF1APPLICANT]
    ON [dbo].[APPLICANT]([IDSTATE] ASC);


GO
CREATE NONCLUSTERED INDEX [XIF11APPLICANT]
    ON [dbo].[APPLICANT]([IDHEARABOUT] ASC);


GO
CREATE NONCLUSTERED INDEX [XIE1APPLICANT]
    ON [dbo].[APPLICANT]([FIRSTNAME] ASC, [LASTNAME] ASC);


GO
CREATE UNIQUE NONCLUSTERED INDEX [XAK1APPLICANT]
    ON [dbo].[APPLICANT]([EMAIL] ASC);


GO
CREATE UNIQUE NONCLUSTERED INDEX [ROWID$INDEX]
    ON [dbo].[APPLICANT]([ROWID] ASC);


GO
CREATE NONCLUSTERED INDEX [nci_wi_APPLICANT_C101B3A9C2B5D721B563073D664EACC6]
    ON [dbo].[APPLICANT]([IDCOUNTRY] ASC)
    INCLUDE([ADDITINDUSORSKILL], [AGENTID], [AGENTIDENTNUM], [AIMNAME], [ALLFIELDSOFSTUDY], [BIRTHDATEMMDD], [CITY], [CONVICTED], [CORPORATEW9], [CORPORATEW9DATECREATED], [CORPORATNAME], [CORPORATNAMEPAID], [DATECREATED], [DATEUPDATED], [EMAIL], [FIRSTNAME], [HIDDEN_MOBILEPHONE], [HIDDEN_PHONE], [HIDDEN_PHONEALT], [HOURSWEEK], [IDABLEOBTAINBB], [IDABLEWIN2K], [IDAGE], [IDAPPSTATUS], [IDHEARABOUT], [IDHEARABOUT_DATE], [IDINTEREST], [IDLEVELEDUC], [IDMODEM], [IDOFTENUSE], [IDOPERSYSTEM], [IDRACE], [IDSECRETQUESTION], [IDSEX], [IDSTATE], [IDTELEPHONESERVICETYPE], [IDTIMEZONE], [IDWORKPLACE], [INDACCOU], [INDADMIN], [INDCALLCEN], [INDCALLCENQA], [INDCUSTF2F], [INDCUSTTEL], [INDDATEENT], [INDDBMANAGMENT], [INDFINANC], [INDHUMRES], [INDINSURAN], [INDLEGAL], [INDMARKET], [INDMARKRES], [INDMEDICAL], [INDOTHER], [INDPRMAN], [INDPROGR], [INDREALEST], [INDRETAIL], [INDSALES], [INDTECHSUP], [INDTELEMAR], [INDTRANMUL], [INDTRAVEL], [INDWEBDES], [INDWORKFROMHOME], [INTPROVIDER], [LANGOTHER], [LASTNAME], [MAILADDR], [MIDDLINIT], [MILITARY_MEMBER_ID], [MOBILEPHONE], [MOBILETERMS], [NICKNAME], [OPTADDINFO], [OPTFIELDSTUDY], [OPTMOTIV], [OPTPROF], [OPTREFBY], [PART1ASSESSMENTKEYSPEECH], [PART2ASSESSMENTKEYGENERAL], [PASSWORD], [PENDINGPURGE], [PENDINGPURGEDATE], [PHONE], [PHONEALT], [PROFCERTIFICAT], [REFERREDBYREWARDPAID], [REFERREDBYREWARDPAIDDATE], [ROWID], [SECRETANSWER], [SSNLAST4DIGITS], [TELLUSMORE], [TELPROVIDER], [TSBROWSER], [TSDLBANDWIDTH], [TSIPADDRESS], [TSMICROPHONE], [TSPLATFORM], [TSRESOLUTION], [UPPER_FIRSTNAME], [UPPER_LASTNAME], [W9], [WANTNEWSLETTER], [WHATMOTIVATESYOU], [WPM], [YEARS18], [ZIP]);


GO
CREATE NONCLUSTERED INDEX [nci_wi_APPLICANT_6D8C063F1E5CF35D69618424519E6CF9]
    ON [dbo].[APPLICANT]([IDAPPSTATUS] ASC, [IDCOUNTRY] ASC)
    INCLUDE([ADDITINDUSORSKILL], [AGENTID], [AGENTIDENTNUM], [AIMNAME], [ALLFIELDSOFSTUDY], [BIRTHDATEMMDD], [CITY], [CONVICTED], [CORPORATEW9], [CORPORATEW9DATECREATED], [CORPORATNAME], [CORPORATNAMEPAID], [DATECREATED], [DATEUPDATED], [EMAIL], [FIRSTNAME], [HIDDEN_MOBILEPHONE], [HIDDEN_PHONE], [HIDDEN_PHONEALT], [HOURSWEEK], [IDABLEOBTAINBB], [IDABLEWIN2K], [IDAGE], [IDHEARABOUT], [IDHEARABOUT_DATE], [IDINTEREST], [IDLEVELEDUC], [IDMODEM], [IDOFTENUSE], [IDOPERSYSTEM], [IDRACE], [IDSECRETQUESTION], [IDSEX], [IDSTATE], [IDTELEPHONESERVICETYPE], [IDTIMEZONE], [IDWORKPLACE], [INDACCOU], [INDADMIN], [INDCALLCEN], [INDCALLCENQA], [INDCUSTF2F], [INDCUSTTEL], [INDDATEENT], [INDDBMANAGMENT], [INDFINANC], [INDHUMRES], [INDINSURAN], [INDLEGAL], [INDMARKET], [INDMARKRES], [INDMEDICAL], [INDOTHER], [INDPRMAN], [INDPROGR], [INDREALEST], [INDRETAIL], [INDSALES], [INDTECHSUP], [INDTELEMAR], [INDTRANMUL], [INDTRAVEL], [INDWEBDES], [INDWORKFROMHOME], [INTPROVIDER], [LANGOTHER], [LASTNAME], [MAILADDR], [MIDDLINIT], [MILITARY_MEMBER_ID], [MOBILEPHONE], [MOBILETERMS], [NICKNAME], [OPTADDINFO], [OPTFIELDSTUDY], [OPTMOTIV], [OPTPROF], [OPTREFBY], [PART1ASSESSMENTKEYSPEECH], [PART2ASSESSMENTKEYGENERAL], [PASSWORD], [PENDINGPURGE], [PENDINGPURGEDATE], [PHONE], [PHONEALT], [PROFCERTIFICAT], [REFERREDBYREWARDPAID], [REFERREDBYREWARDPAIDDATE], [ROWID], [SECRETANSWER], [SSNLAST4DIGITS], [TELLUSMORE], [TELPROVIDER], [TSBROWSER], [TSDLBANDWIDTH], [TSIPADDRESS], [TSMICROPHONE], [TSPLATFORM], [TSRESOLUTION], [UPPER_FIRSTNAME], [UPPER_LASTNAME], [W9], [WANTNEWSLETTER], [WHATMOTIVATESYOU], [WPM], [YEARS18], [ZIP]);


GO
CREATE NONCLUSTERED INDEX [nci_wi_APPLICANT_4E36382D100909F3F15AEEF86730B0AE]
    ON [dbo].[APPLICANT]([UPPER_LASTNAME] ASC, [IDAPPSTATUS] ASC);


GO
CREATE NONCLUSTERED INDEX [nci_wi_APPLICANT]
    ON [dbo].[APPLICANT]([UPPER_FIRSTNAME] ASC, [UPPER_LASTNAME] ASC)
    INCLUDE([CITY], [DATECREATED], [EMAIL], [FIRSTNAME], [IDAPPSTATUS], [IDCOUNTRY], [IDSTATE], [LASTNAME], [PHONE], [ZIP]);


GO
CREATE NONCLUSTERED INDEX [APPLICANTPART1KEY]
    ON [dbo].[APPLICANT]([PART1ASSESSMENTKEYSPEECH] ASC);


GO
CREATE UNIQUE NONCLUSTERED INDEX [AGENTIDENTNUM]
    ON [dbo].[APPLICANT]([AGENTIDENTNUM] ASC);


GO

GO

