CREATE TABLE [dbo].[ARPKUDOS] (
    [IDARPKUDOS]  NUMERIC (20)    NOT NULL,
    [IDAPPLICANT] NUMERIC (20)    NOT NULL,
    [IDAGENT]     NUMERIC (20)    NOT NULL,
    [IDPROG]      NUMERIC (20)    NOT NULL,
    [UNITS]       NUMERIC (20)    NOT NULL,
    [BONUSAMOUNT] NUMERIC (20, 2) NOT NULL,
    [COMMENTS]    VARCHAR (4000)  NOT NULL,
    [IDSUBMMYSQL] NUMERIC (20)    NOT NULL,
    [IDUSER]      NUMERIC (20)    NOT NULL,
    [DATEW]       DATETIME2 (0)   NOT NULL,
    CONSTRAINT [ARPKUDOS_KEY00] PRIMARY KEY CLUSTERED ([IDARPKUDOS] ASC),
    CONSTRAINT [ARPKUDOS_KEY01] FOREIGN KEY ([IDUSER]) REFERENCES [dbo].[USERS] ([IDUSER])
);

