CREATE TABLE [dbo].[ARPREFER] (
    [IDARPREFER]  NUMERIC (20)    NOT NULL,
    [IDAPPLICANT] NUMERIC (20)    NOT NULL,
    [REFERREDBY]  NUMERIC (20)    NOT NULL,
    [BONUS]       NUMERIC (20, 2) NOT NULL,
    [IDSUBMMYSQL] NUMERIC (20)    NOT NULL,
    [DATEW]       DATETIME2 (0)   NOT NULL,
    CONSTRAINT [ARPREFER_KEY0] PRIMARY KEY CLUSTERED ([IDARPREFER] ASC)
);


GO
CREATE NONCLUSTERED INDEX [ARPREFER_I04]
    ON [dbo].[ARPREFER]([DATEW] ASC);


GO
CREATE NONCLUSTERED INDEX [ARPREFER_I03]
    ON [dbo].[ARPREFER]([REFERREDBY] ASC);


GO
CREATE UNIQUE NONCLUSTERED INDEX [ARPREFER_I02]
    ON [dbo].[ARPREFER]([IDAPPLICANT] ASC, [REFERREDBY] ASC);


GO
CREATE NONCLUSTERED INDEX [ARPREFER_I01]
    ON [dbo].[ARPREFER]([IDAPPLICANT] ASC);

