CREATE TABLE [dbo].[AVAILABILITYUSEPREL] (
    [IDAPPLICANT]        NUMERIC (20) NOT NULL,
    [IDAVAILABILITYLIST] NUMERIC (20) NOT NULL,
    CONSTRAINT [SYS_C0013464] FOREIGN KEY ([IDAPPLICANT]) REFERENCES [dbo].[APPLICANT_PRELIMINARY] ([ID]) ON DELETE CASCADE,
    CONSTRAINT [SYS_C0013465] FOREIGN KEY ([IDAVAILABILITYLIST]) REFERENCES [dbo].[AVAILABILITYLIST] ([IDAVAILABILITYLIST]),
    CONSTRAINT [SYS_C0013675] FOREIGN KEY ([IDAVAILABILITYLIST]) REFERENCES [dbo].[AVAILABILITYLIST] ([IDAVAILABILITYLIST])
);


GO
CREATE NONCLUSTERED INDEX [AVAILABILITYUSEPRELI02]
    ON [dbo].[AVAILABILITYUSEPREL]([IDAPPLICANT] ASC);


GO
CREATE UNIQUE NONCLUSTERED INDEX [AVAILABILITYUSEPRELI01]
    ON [dbo].[AVAILABILITYUSEPREL]([IDAPPLICANT] ASC, [IDAVAILABILITYLIST] ASC);

