CREATE TABLE [dbo].[bookitcombookingagentmonitor] (
    [idBookItcomBookingAgentMonitor] BIGINT          IDENTITY (688, 1) NOT NULL,
    [idagent]                        BIGINT          NOT NULL,
    [idproject]                      BIGINT          NOT NULL,
    [idmonitname]                    BIGINT          NOT NULL,
    [monitname]                      VARCHAR (250)   DEFAULT (N'') NOT NULL,
    [callDateTime]                   DATETIME2 (0)   NOT NULL,
    [callersName]                    VARCHAR (250)   NOT NULL,
    [sessionId]                      VARCHAR (250)   NOT NULL,
    [bookingNumber]                  VARCHAR (250)   NOT NULL,
    [f1]                             TINYINT         NOT NULL,
    [f1Text]                         VARCHAR (3)     NOT NULL,
    [f2]                             TINYINT         NOT NULL,
    [f2Text]                         VARCHAR (3)     NOT NULL,
    [f3]                             TINYINT         NOT NULL,
    [f3Text]                         VARCHAR (3)     NOT NULL,
    [f4]                             TINYINT         NOT NULL,
    [f4Text]                         VARCHAR (3)     NOT NULL,
    [f5]                             TINYINT         NOT NULL,
    [f5Text]                         VARCHAR (3)     NOT NULL,
    [f6]                             TINYINT         NOT NULL,
    [f6Text]                         VARCHAR (3)     NOT NULL,
    [f7]                             TINYINT         NOT NULL,
    [f7Text]                         VARCHAR (3)     NOT NULL,
    [f8]                             TINYINT         NOT NULL,
    [f8Text]                         VARCHAR (3)     NOT NULL,
    [f9]                             TINYINT         NOT NULL,
    [f9Text]                         VARCHAR (3)     NOT NULL,
    [f10]                            TINYINT         NOT NULL,
    [f10Text]                        VARCHAR (3)     NOT NULL,
    [f11]                            TINYINT         NOT NULL,
    [f11Text]                        VARCHAR (3)     NOT NULL,
    [f12]                            TINYINT         NOT NULL,
    [f12Text]                        VARCHAR (3)     NOT NULL,
    [f13]                            TINYINT         NOT NULL,
    [f13Text]                        VARCHAR (3)     NOT NULL,
    [f14]                            TINYINT         NOT NULL,
    [f14Text]                        VARCHAR (3)     NOT NULL,
    [f15]                            TINYINT         NOT NULL,
    [f15Text]                        VARCHAR (3)     NOT NULL,
    [f16]                            TINYINT         NOT NULL,
    [f16Text]                        VARCHAR (3)     NOT NULL,
    [f17]                            TINYINT         NOT NULL,
    [f17Text]                        VARCHAR (3)     NOT NULL,
    [score]                          INT             NOT NULL,
    [percent]                        DECIMAL (12, 2) NOT NULL,
    [idqualityqaq10]                 BIGINT          NOT NULL,
    [idqualitysrcform]               BIGINT          NOT NULL,
    [comments]                       VARCHAR (MAX)   NOT NULL,
    [datew]                          DATE            NOT NULL,
    [timew]                          TIME (7)        NOT NULL,
    CONSTRAINT [PK_bookitcombookingagentmonitor_idBookItcomBookingAgentMonitor] PRIMARY KEY CLUSTERED ([idBookItcomBookingAgentMonitor] ASC)
);


GO
CREATE NONCLUSTERED INDEX [bookitcombookingagentmonitori01]
    ON [dbo].[bookitcombookingagentmonitor]([datew] ASC);

