CREATE TABLE [dbo].[COMPAPPLIST] (
    [IDCOMPAPPLIST] NUMERIC (20)     NOT NULL,
    [NAME]          VARCHAR (500)    NOT NULL,
    [VISIBLE]       CHAR (1)         DEFAULT ('Y') NOT NULL,
    [ROWID]         UNIQUEIDENTIFIER DEFAULT (newid()) NOT NULL,
    CONSTRAINT [SYS_C0013118] PRIMARY KEY CLUSTERED ([IDCOMPAPPLIST] ASC)
);


GO
CREATE UNIQUE NONCLUSTERED INDEX [ROWID$INDEX]
    ON [dbo].[COMPAPPLIST]([ROWID] ASC);


GO
