CREATE TABLE [dbo].[CONTRACTTRAINERINVOICETMP] (
    [ID]                NUMERIC (20)    NOT NULL,
    [IDPREPARATIONUSER] NUMERIC (20)    NOT NULL,
    [IDCLIENT]          NUMERIC (20)    NOT NULL,
    [WORKPRODUCT]       VARCHAR (200)   NOT NULL,
    [INVOICEAMOUNT]     NUMERIC (20, 2) NOT NULL,
    [CREATED]           DATETIME2 (0)   NOT NULL,
    [STATUS]            CHAR (1)        NOT NULL,
    [INVOICETMPCOMM_ID] NUMERIC (20)    NOT NULL,
    [TRAININGDAYS]      NUMERIC (20)    DEFAULT ((0)) NOT NULL,
    [TRAINEECOUNT]      NUMERIC (20)    DEFAULT ((0)) NOT NULL,
    [ACTIVITYDATE]      DATETIME2 (0)   NULL,
    CONSTRAINT [CONTRACTTRAINERINVOICETMP_C00] PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [SYS_C0013524] CHECK ([STATUS]='D' OR [STATUS]='N'),
    CONSTRAINT [SYS_C0018941] CHECK ([STATUS]='D' OR [STATUS]='N'),
    CONSTRAINT [CONTRACTTRAINERINVOICETMP_C01] FOREIGN KEY ([IDPREPARATIONUSER]) REFERENCES [dbo].[PREPARATIONUSER] ([IDPREPARATIONUSER]),
    CONSTRAINT [CONTRACTTRAINERINVOICETMP_C03] FOREIGN KEY ([INVOICETMPCOMM_ID]) REFERENCES [dbo].[CONTRACTTRAINERINVOICETMPCOMM] ([ID])
);


GO
CREATE NONCLUSTERED INDEX [CONTRACTTRAINERINVOICETMP1]
    ON [dbo].[CONTRACTTRAINERINVOICETMP]([IDPREPARATIONUSER] ASC, [STATUS] ASC);

