CREATE TABLE [dbo].[CONTRACTTRAINERINVOICEMAP] (
    [ID]          NUMERIC (20)  NOT NULL,
    [IDCLIENT]   NUMERIC (20)  NOT NULL,
    [WORKPRODUCT] VARCHAR (200) NOT NULL,
    [PROJECT_ID]  NUMERIC (20)  NOT NULL,
    [CREATED]     DATETIME2 (0) NOT NULL,
    [VISIBLE]     CHAR (1)      DEFAULT ('Y') NOT NULL,
    CONSTRAINT [CONTRACTTRAINERINVOICEMAP_C00] PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [SYS_C0013315] CHECK ([VISIBLE]='N' OR [VISIBLE]='Y'),
    CONSTRAINT [SYS_C0013522] CHECK ([VISIBLE]='N' OR [VISIBLE]='Y'),
    CONSTRAINT [CONTRACTTRAINERINVOICEMAP_C01] FOREIGN KEY ([IDCLIENT]) REFERENCES [dbo].[client] ([ID]),
    CONSTRAINT [CONTRACTTRAINERINVOICEMAP_C02] FOREIGN KEY ([PROJECT_ID]) REFERENCES [dbo].[PROJECT] ([IDPROJECT])
);


GO
CREATE UNIQUE NONCLUSTERED INDEX [CONTRACTTRAINERINVOICEMAP_I03]
    ON [dbo].[CONTRACTTRAINERINVOICEMAP]([IDCLIENT] ASC, [WORKPRODUCT] ASC);


GO
CREATE NONCLUSTERED INDEX [CONTRACTTRAINERINVOICEMAP_I02]
    ON [dbo].[CONTRACTTRAINERINVOICEMAP]([PROJECT_ID] ASC);


GO
CREATE NONCLUSTERED INDEX [CONTRACTTRAINERINVOICEMAP_I01]
    ON [dbo].[CONTRACTTRAINERINVOICEMAP]([IDCLIENT] ASC);

