CREATE TABLE [dbo].[CONVICTEDPREL] (
    [ID]          NUMERIC (20)   NOT NULL,
    [IDAPPLICANT] NUMERIC (20)   NULL,
    [OFFENSE]     VARCHAR (4000) NOT NULL,
    [OFFENSEDATE] DATETIME2 (0)  NOT NULL,
    [LOCATION]    VARCHAR (100)  NOT NULL,
    [OFFENSETYPE] CHAR (1)       NOT NULL,
    [DATEW]       DATETIME2 (0)  NOT NULL,
    [IDSTATE]     CHAR (2)       NOT NULL,
    CONSTRAINT [SYS_C0013278] PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [CONVICTEDPREL_C2] CHECK ([OFFENSETYPE]='M' OR [OFFENSETYPE]='F'),
    CONSTRAINT [CONVICTEDPREL_C1] FOREIGN KEY ([IDAPPLICANT]) REFERENCES [dbo].[APPLICANT_PRELIMINARY] ([ID]) ON DELETE CASCADE
);


GO
CREATE NONCLUSTERED INDEX [CONVICTEDPREL_I3]
    ON [dbo].[CONVICTEDPREL]([IDAPPLICANT] ASC);

