CREATE TABLE [dbo].[CONVICTED] (
    [ID]          NUMERIC (20)   NOT NULL,
    [IDAPPLICANT] NUMERIC (20)   NULL,
    [OFFENSE]     VARCHAR (4000) NOT NULL,
    [OFFENSEDATE] DATETIME2 (0)  NOT NULL,
    [LOCATION]    VARCHAR (100)  NOT NULL,
    [OFFENSETYPE] CHAR (1)       NOT NULL,
    [DATEW]       DATETIME2 (0)  NOT NULL,
    [IDSTATE]     CHAR (2)       DEFAULT ('00') NOT NULL,
    CONSTRAINT [SYS_C0013252] PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [CONVICTED_C04] CHECK ([OFFENSETYPE]='M' OR [OFFENSETYPE]='F'),
    CONSTRAINT [APPLICANTFORM_URL_PARAMS_C6] FOREIGN KEY ([IDAPPLICANT]) REFERENCES [dbo].[applicant] ([IDAPPLICANT])
);






GO
CREATE NONCLUSTERED INDEX [CONVICTED_I3]
    ON [dbo].[CONVICTED]([IDAPPLICANT] ASC);

