CREATE TABLE [dbo].[COUNTRY] (
    [IDCOUNTRY] CHAR (2)         NOT NULL,
    [NAME]      VARCHAR (500)    NOT NULL,
    [VISIBLE]   CHAR (1)         DEFAULT ('Y') NOT NULL,
    [ROWID]     UNIQUEIDENTIFIER DEFAULT (newid()) NOT NULL,
    CONSTRAINT [SYS_C0013120] PRIMARY KEY CLUSTERED ([IDCOUNTRY] ASC)
);


GO
CREATE UNIQUE NONCLUSTERED INDEX [ROWID$INDEX]
    ON [dbo].[COUNTRY]([ROWID] ASC);


GO
