CREATE TABLE [dbo].[egenciaqaform] (
    [idEgenciaQAForm]  BIGINT        IDENTITY (1357, 1) NOT NULL,
    [typeOfCall]       VARCHAR (21)  DEFAULT (N'') NOT NULL,
    [idagent]          BIGINT        DEFAULT ((0)) NOT NULL,
    [idproject]        BIGINT        DEFAULT ((0)) NOT NULL,
    [idmonitname]      BIGINT        DEFAULT ((0)) NOT NULL,
    [callDateTime]     DATETIME2 (0) DEFAULT ([dbo].[GETDATE]()) NOT NULL,
    [sessionID]        VARCHAR (50)  DEFAULT (N'') NOT NULL,
    [itinNo]           VARCHAR (50)  DEFAULT (N'') NOT NULL,
    [callersName]      VARCHAR (50)  DEFAULT (N'') NOT NULL,
    [f1]               TINYINT       DEFAULT ((0)) NOT NULL,
    [f1Text]           VARCHAR (3)   DEFAULT (N'') NOT NULL,
    [f2]               TINYINT       DEFAULT ((0)) NOT NULL,
    [f2Text]           VARCHAR (3)   DEFAULT (N'') NOT NULL,
    [f3]               TINYINT       DEFAULT ((0)) NOT NULL,
    [f3Text]           VARCHAR (3)   DEFAULT (N'') NOT NULL,
    [f4]               TINYINT       DEFAULT ((0)) NOT NULL,
    [f4Text]           VARCHAR (3)   DEFAULT (N'') NOT NULL,
    [f5]               TINYINT       DEFAULT ((0)) NOT NULL,
    [f5Text]           VARCHAR (3)   DEFAULT (N'') NOT NULL,
    [f6]               TINYINT       DEFAULT ((0)) NOT NULL,
    [f6Text]           VARCHAR (3)   DEFAULT (N'') NOT NULL,
    [f7]               TINYINT       DEFAULT ((0)) NOT NULL,
    [f7Text]           VARCHAR (3)   DEFAULT (N'') NOT NULL,
    [f8]               TINYINT       DEFAULT ((0)) NOT NULL,
    [f8Text]           VARCHAR (3)   DEFAULT (N'') NOT NULL,
    [f9]               TINYINT       DEFAULT ((0)) NOT NULL,
    [f9Text]           VARCHAR (3)   DEFAULT (N'') NOT NULL,
    [f10]              TINYINT       DEFAULT ((0)) NOT NULL,
    [f10Text]          VARCHAR (3)   DEFAULT (N'') NOT NULL,
    [f11]              TINYINT       DEFAULT ((0)) NOT NULL,
    [f11Text]          VARCHAR (3)   DEFAULT (N'') NOT NULL,
    [f12]              TINYINT       DEFAULT ((0)) NOT NULL,
    [f12Text]          VARCHAR (3)   DEFAULT (N'') NOT NULL,
    [f13]              TINYINT       DEFAULT ((0)) NOT NULL,
    [f13Text]          VARCHAR (3)   DEFAULT (N'') NOT NULL,
    [f14]              TINYINT       DEFAULT ((0)) NOT NULL,
    [f14Text]          VARCHAR (3)   DEFAULT (N'') NOT NULL,
    [f15]              TINYINT       DEFAULT ((0)) NOT NULL,
    [f15Text]          VARCHAR (3)   DEFAULT (N'') NOT NULL,
    [f16]              TINYINT       DEFAULT ((0)) NOT NULL,
    [f16Text]          VARCHAR (3)   DEFAULT (N'') NOT NULL,
    [f17]              TINYINT       DEFAULT ((0)) NOT NULL,
    [f17Text]          VARCHAR (3)   DEFAULT (N'') NOT NULL,
    [f18]              TINYINT       DEFAULT ((0)) NOT NULL,
    [f18Text]          VARCHAR (3)   DEFAULT (N'') NOT NULL,
    [f19]              TINYINT       DEFAULT ((0)) NOT NULL,
    [f19Text]          VARCHAR (3)   DEFAULT (N'') NOT NULL,
    [f20]              TINYINT       DEFAULT ((0)) NOT NULL,
    [f20Text]          VARCHAR (3)   DEFAULT (N'') NOT NULL,
    [f21]              TINYINT       DEFAULT ((0)) NOT NULL,
    [f21Text]          VARCHAR (3)   DEFAULT (N'') NOT NULL,
    [f22]              TINYINT       DEFAULT ((0)) NOT NULL,
    [f22Text]          VARCHAR (3)   DEFAULT (N'') NOT NULL,
    [f23]              TINYINT       DEFAULT ((0)) NOT NULL,
    [f23Text]          VARCHAR (3)   DEFAULT (N'') NOT NULL,
    [f24]              TINYINT       DEFAULT ((0)) NOT NULL,
    [f24Text]          VARCHAR (3)   DEFAULT (N'') NOT NULL,
    [f25]              TINYINT       DEFAULT ((0)) NOT NULL,
    [f25Text]          VARCHAR (3)   DEFAULT (N'') NOT NULL,
    [f26]              TINYINT       DEFAULT ((0)) NOT NULL,
    [f26Text]          VARCHAR (3)   DEFAULT (N'') NOT NULL,
    [f27]              TINYINT       DEFAULT ((0)) NOT NULL,
    [f27Text]          VARCHAR (3)   DEFAULT (N'') NOT NULL,
    [f28]              TINYINT       DEFAULT ((0)) NOT NULL,
    [f28Text]          VARCHAR (3)   DEFAULT (N'') NOT NULL,
    [f29]              TINYINT       DEFAULT ((0)) NOT NULL,
    [f29Text]          VARCHAR (3)   DEFAULT (N'') NOT NULL,
    [f30]              TINYINT       DEFAULT ((0)) NOT NULL,
    [f30Text]          VARCHAR (3)   DEFAULT (N'') NOT NULL,
    [score]            INT           DEFAULT ((0)) NOT NULL,
    [percent]          INT           DEFAULT ((0)) NOT NULL,
    [idqualityqaq10]   BIGINT        DEFAULT ((0)) NOT NULL,
    [idqualitysrcform] BIGINT        DEFAULT ((0)) NOT NULL,
    [datew]            DATETIME2 (0) DEFAULT ([dbo].[GETDATE]()) NOT NULL,
    CONSTRAINT [PK_egenciaqaform_idEgenciaQAForm] PRIMARY KEY CLUSTERED ([idEgenciaQAForm] ASC)
);


GO
CREATE NONCLUSTERED INDEX [EgenciaQAFormi01]
    ON [dbo].[egenciaqaform]([datew] ASC);


GO
ALTER INDEX [EgenciaQAFormi01]
    ON [dbo].[egenciaqaform] DISABLE;

