CREATE TABLE [dbo].[egenciaopclientbilling] (
    [id]                    BIGINT          IDENTITY (688, 1) NOT NULL,
    [EgenciaOPIncomFile_id] BIGINT          NOT NULL,
    [loginId]               VARCHAR (500)   NOT NULL,
    [dateFld]               DATE            NOT NULL,
    [cmsGroup]              VARCHAR (500)   NOT NULL,
    [intervalPst]           TIME (7)        DEFAULT (NULL) NULL,
    [staffedTime]           DECIMAL (14, 2) NOT NULL,
    [availTime]             DECIMAL (14, 2) NOT NULL,
    [acdTime]               DECIMAL (14, 2) NOT NULL,
    [acwTime]               DECIMAL (14, 2) NOT NULL,
    [holdTime]              DECIMAL (14, 2) NOT NULL,
    [agentRingTime]         DECIMAL (14, 2) NOT NULL,
    [auxTime]               DECIMAL (14, 2) NOT NULL,
    [aux0]                  DECIMAL (14, 2) NOT NULL,
    [breakFld]              DECIMAL (14, 2) NOT NULL,
    [oneOnOneCoaching]      DECIMAL (14, 2) NOT NULL,
    [meeting]               DECIMAL (14, 2) NOT NULL,
    [project]               DECIMAL (14, 2) NOT NULL,
    [trainingEge]           DECIMAL (14, 2) NOT NULL,
    [outbound]              DECIMAL (14, 2) NOT NULL,
    [email]                 DECIMAL (14, 2) NOT NULL,
    [qaQueueWork]           DECIMAL (14, 2) NOT NULL,
    [systemDown]            DECIMAL (14, 2) NOT NULL,
    [exchangeDesk]          DECIMAL (14, 2) NOT NULL,
    [discretionaryTime]     DECIMAL (14, 2) NOT NULL,
    [siteTraining]          DECIMAL (14, 2) NOT NULL,
    [created]               DATETIME2 (0)   NOT NULL,
    [dateCdtConv]           DATETIME2 (0)   DEFAULT (NULL) NULL,
    [cprodR1]               DECIMAL (15, 3) NOT NULL,
    [cprodRRqv]             DECIMAL (15, 3) NOT NULL,
    [cprodS1]               DECIMAL (15, 3) NOT NULL,
    [cprodSRqv]             DECIMAL (15, 3) NOT NULL,
    [aimR]                  DECIMAL (15, 3) NOT NULL,
    [aimS]                  DECIMAL (15, 3) NOT NULL,
    CONSTRAINT [PK_egenciaopclientbilling_id] PRIMARY KEY CLUSTERED ([id] ASC),
    CONSTRAINT [egenciaopclientbilling$fk_ClientBilling_IncomFile1_idx] UNIQUE NONCLUSTERED ([EgenciaOPIncomFile_id] ASC)
);

