CREATE TABLE [dbo].[generalassemblyqaform] (
    [id]               BIGINT          IDENTITY (45, 1) NOT NULL,
    [agents_id]        BIGINT          NOT NULL,
    [monitoredBy]      BIGINT          NOT NULL,
    [f1]               DECIMAL (5, 2)  NOT NULL,
    [f1Text]           VARCHAR (19)    NOT NULL,
    [f2]               DECIMAL (5, 2)  NOT NULL,
    [f2Text]           VARCHAR (19)    NOT NULL,
    [f3]               DECIMAL (5, 2)  NOT NULL,
    [f3Text]           VARCHAR (19)    NOT NULL,
    [f4]               DECIMAL (5, 2)  NOT NULL,
    [f4Text]           VARCHAR (19)    NOT NULL,
    [f5]               DECIMAL (5, 2)  NOT NULL,
    [f5Text]           VARCHAR (19)    NOT NULL,
    [f6]               DECIMAL (5, 2)  NOT NULL,
    [f6Text]           VARCHAR (19)    NOT NULL,
    [f7]               DECIMAL (5, 2)  NOT NULL,
    [f7Text]           VARCHAR (19)    NOT NULL,
    [f8]               DECIMAL (5, 2)  NOT NULL,
    [f8Text]           VARCHAR (19)    NOT NULL,
    [f9]               DECIMAL (5, 2)  NOT NULL,
    [f9Text]           VARCHAR (19)    NOT NULL,
    [f10]              DECIMAL (5, 2)  NOT NULL,
    [f10Text]          VARCHAR (19)    NOT NULL,
    [f11]              DECIMAL (5, 2)  NOT NULL,
    [f11Text]          VARCHAR (19)    NOT NULL,
    [f12]              DECIMAL (5, 2)  NOT NULL,
    [f12Text]          VARCHAR (19)    NOT NULL,
    [f13]              DECIMAL (5, 2)  NOT NULL,
    [f13Text]          VARCHAR (19)    NOT NULL,
    [f14Text]          VARCHAR (3)     NOT NULL,
    [note]             VARCHAR (MAX)   NOT NULL,
    [score]            DECIMAL (12, 2) NOT NULL,
    [percent]          DECIMAL (12, 2) NOT NULL,
    [idqualitysrcform] BIGINT          NOT NULL,
    [idqualityqaq10]   BIGINT          NOT NULL,
    [datew]            DATE            NOT NULL,
    [timew]            TIME (7)        NOT NULL,
    CONSTRAINT [PK_generalassemblyqaform_id] PRIMARY KEY CLUSTERED ([id] ASC)
);

