CREATE TABLE [dbo].[HEARABOUT] (
    [IDHEARABOUT]    NUMERIC (20)     NOT NULL,
    [NAME]           VARCHAR (500)    NOT NULL,
    [VISIBLE]        CHAR (1)         DEFAULT ('Y') NOT NULL,
    [FIELDSORTINDEX] NUMERIC (20)     DEFAULT ((0)) NOT NULL,
    [ROWID]          UNIQUEIDENTIFIER DEFAULT (newid()) NOT NULL,
    CONSTRAINT [SYS_C0013122] PRIMARY KEY CLUSTERED ([IDHEARABOUT] ASC)
);


GO
CREATE UNIQUE NONCLUSTERED INDEX [ROWID$INDEX]
    ON [dbo].[HEARABOUT]([ROWID] ASC);


GO
