CREATE TABLE [dbo].[HIREIQ_CATS_IMPORT] (
    [ID]                NUMERIC (20)   NOT NULL,
    [CANDIDATEFULLNAME] VARCHAR (200)  NOT NULL,
    [CANDIDATEEMAIL]    VARCHAR (200)  NOT NULL,
    [REVIEWINGLINK]     VARCHAR (4000) NOT NULL,
    [COMPLETEDDATE]     VARCHAR (100)  NOT NULL,
    [RISKBAND]          VARCHAR (1000) NOT NULL,
    [QUIZSCORE]         VARCHAR (100)  NOT NULL,
    [WORDSPERMINUTE]    VARCHAR (100)  NOT NULL,
    [ERRORRATE]         VARCHAR (100)  NOT NULL,
    [LANGUAGEIQSCORE]   VARCHAR (100)  NOT NULL,
    [IDAPPLICANT]       NUMERIC (20)   NOT NULL,
    [CREATOR]           NUMERIC (20)   NOT NULL,
    [CREATED]           DATETIME2 (0)  NOT NULL,
    CONSTRAINT [SYS_C0013295] PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [HIREIQ_CATS_IMPORT_C2] FOREIGN KEY ([CREATOR]) REFERENCES [dbo].[USERS] ([IDUSER])
);


GO
CREATE NONCLUSTERED INDEX [nci_wi_HIREIQ_CATS_IMPORT_E5410B4EA70003E8A27EED0B9D1CF03A]
    ON [dbo].[HIREIQ_CATS_IMPORT]([IDAPPLICANT] ASC);


GO
CREATE UNIQUE NONCLUSTERED INDEX [HIREIQ_CATS_IMPORT_I1]
    ON [dbo].[HIREIQ_CATS_IMPORT]([CANDIDATEEMAIL] ASC, [COMPLETEDDATE] ASC);

