CREATE TABLE [dbo].[HireIQResult] (
    [ID]                BIGINT         IDENTITY (1, 1) NOT NULL,
    [IDAPPLICANT]       NUMERIC (20)   NOT NULL,
    [CANDIDATEFULLNAME] VARCHAR (200)  NOT NULL,
    [CANDIDATEEMAIL]    VARCHAR (200)  NOT NULL,
    [SCREENID]          BIGINT         NOT NULL,
    [STATE]             VARCHAR (100)  NULL,
    [APPLYURL]          VARCHAR (4000) NOT NULL,
    [OVERALLSCORE]      VARCHAR (100)  NULL,
    [QUALIFIERSSCORE]   VARCHAR (100)  NULL,
    [QUIZSCORE]         VARCHAR (100)  NULL,
    [TYPINGSCORE]       VARCHAR (100)  NULL,
    [LANGUAGEIQSCORE]   VARCHAR (100)  NULL,
    [PHONESCREENSCORE]  VARCHAR (100)  NULL,
    [REVIEWINGLINK]     VARCHAR (4000) NULL,
    [CREATEDDATE]       DATETIME2 (0)  NULL,
    [RISKBAND]          VARCHAR (1000) NULL,
    [WORDSPERMINUTE]    VARCHAR (100)  NULL,
    [ERRORRATE]         VARCHAR (100)  NULL,
    [COMPLETEDDATE]     DATETIME2 (0)  NULL,
    CONSTRAINT [HireIQResult_p1] PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [FK_HireIQResult] FOREIGN KEY ([IDAPPLICANT]) REFERENCES [dbo].[applicant] ([IDAPPLICANT]),
    UNIQUE NONCLUSTERED ([IDAPPLICANT] ASC)
);






GO
CREATE NONCLUSTERED INDEX [nci_wi_HireIQResult_D7513A17F0151CCF1A06DCE64248782D]
    ON [dbo].[HireIQResult]([IDAPPLICANT] ASC)
    INCLUDE([APPLYURL], [CANDIDATEEMAIL], [CANDIDATEFULLNAME], [COMPLETEDDATE], [CREATEDDATE], [ERRORRATE], [LANGUAGEIQSCORE], [OVERALLSCORE], [PHONESCREENSCORE], [QUALIFIERSSCORE], [QUIZSCORE], [REVIEWINGLINK], [RISKBAND], [SCREENID], [STATE], [TYPINGSCORE], [WORDSPERMINUTE]);

