CREATE TABLE [dbo].[HRNOTE] (
    [IDHRNOTE]    NUMERIC (20)     NOT NULL,
    [IDAPPLICANT] NUMERIC (20)     NOT NULL,
    [NOTE]        VARCHAR (4000)   NOT NULL,
    [DATECREATED] DATETIME2 (0)    NOT NULL,
    [IDUSER]      NUMERIC (20)     NOT NULL,
    [ROWID]       UNIQUEIDENTIFIER DEFAULT (newid()) NOT NULL,
    CONSTRAINT [SYS_C0013123] PRIMARY KEY CLUSTERED ([IDHRNOTE] ASC),
    CONSTRAINT [SYS_C0013565] FOREIGN KEY ([IDUSER]) REFERENCES [dbo].[USERS] ([IDUSER]),
    CONSTRAINT [SYS_C0013566] FOREIGN KEY ([IDAPPLICANT]) REFERENCES [dbo].[applicant] ([IDAPPLICANT])
);






GO
CREATE NONCLUSTERED INDEX [XIF2HRNOTE]
    ON [dbo].[HRNOTE]([IDUSER] ASC);


GO
CREATE NONCLUSTERED INDEX [XIF1HRNOTE]
    ON [dbo].[HRNOTE]([IDAPPLICANT] ASC);


GO
CREATE UNIQUE NONCLUSTERED INDEX [ROWID$INDEX]
    ON [dbo].[HRNOTE]([ROWID] ASC);


GO
