CREATE TABLE [dbo].[i9sportsqamonitorform] (
    [id]               BIGINT          IDENTITY (1, 1) NOT NULL,
    [agents_id]        BIGINT          NOT NULL,
    [monitoredBy]      BIGINT          NOT NULL,
    [interactDate]     DATETIME2 (0)   DEFAULT (NULL) NULL,
    [ani]              VARCHAR (250)   NOT NULL,
    [f1]               DECIMAL (12, 4) NOT NULL,
    [f1Text]           VARCHAR (3)     NOT NULL,
    [f2]               DECIMAL (12, 4) NOT NULL,
    [f2Text]           VARCHAR (3)     NOT NULL,
    [f3]               DECIMAL (12, 4) NOT NULL,
    [f3Text]           VARCHAR (3)     NOT NULL,
    [f4]               DECIMAL (12, 4) NOT NULL,
    [f4Text]           VARCHAR (3)     NOT NULL,
    [f5]               DECIMAL (12, 4) NOT NULL,
    [f5Text]           VARCHAR (3)     NOT NULL,
    [f6]               DECIMAL (12, 4) NOT NULL,
    [f6Text]           VARCHAR (3)     NOT NULL,
    [f7]               DECIMAL (12, 4) NOT NULL,
    [f7Text]           VARCHAR (3)     NOT NULL,
    [f8]               DECIMAL (12, 4) NOT NULL,
    [f8Text]           VARCHAR (3)     NOT NULL,
    [f9]               DECIMAL (12, 4) NOT NULL,
    [f9Text]           VARCHAR (3)     NOT NULL,
    [f10]              DECIMAL (12, 4) NOT NULL,
    [f10Text]          VARCHAR (3)     NOT NULL,
    [f11]              DECIMAL (12, 4) NOT NULL,
    [f11Text]          VARCHAR (3)     NOT NULL,
    [f12]              DECIMAL (12, 4) NOT NULL,
    [f12Text]          VARCHAR (3)     NOT NULL,
    [f13]              DECIMAL (12, 4) NOT NULL,
    [f13Text]          VARCHAR (3)     NOT NULL,
    [f14]              DECIMAL (12, 4) NOT NULL,
    [f14Text]          VARCHAR (3)     NOT NULL,
    [f15]              DECIMAL (12, 4) NOT NULL,
    [f15Text]          VARCHAR (3)     NOT NULL,
    [f16]              DECIMAL (12, 4) NOT NULL,
    [f16Text]          VARCHAR (3)     NOT NULL,
    [f17]              DECIMAL (12, 4) NOT NULL,
    [f17Text]          VARCHAR (3)     NOT NULL,
    [f18]              DECIMAL (12, 4) NOT NULL,
    [f18Text]          VARCHAR (3)     NOT NULL,
    [f19]              DECIMAL (12, 4) NOT NULL,
    [f19Text]          VARCHAR (3)     NOT NULL,
    [f20]              DECIMAL (12, 4) NOT NULL,
    [f20Text]          VARCHAR (3)     NOT NULL,
    [f21]              DECIMAL (12, 4) NOT NULL,
    [f21Text]          VARCHAR (3)     NOT NULL,
    [f22]              DECIMAL (12, 4) NOT NULL,
    [f22Text]          VARCHAR (3)     NOT NULL,
    [f23]              DECIMAL (12, 4) NOT NULL,
    [f23Text]          VARCHAR (3)     NOT NULL,
    [f24]              DECIMAL (12, 4) NOT NULL,
    [f24Text]          VARCHAR (3)     NOT NULL,
    [f25]              DECIMAL (12, 4) NOT NULL,
    [f25Text]          VARCHAR (3)     NOT NULL,
    [f26]              DECIMAL (12, 4) NOT NULL,
    [f26Text]          VARCHAR (3)     NOT NULL,
    [f27]              DECIMAL (12, 4) NOT NULL,
    [f27Text]          VARCHAR (3)     NOT NULL,
    [comments]         VARCHAR (MAX)   NOT NULL,
    [score]            DECIMAL (12, 4) NOT NULL,
    [percent]          DECIMAL (12, 2) NOT NULL,
    [idqualitysrcform] BIGINT          NOT NULL,
    [idqualityqaq10]   BIGINT          NOT NULL,
    [datew]            DATE            NOT NULL,
    [timew]            TIME (7)        NOT NULL,
    CONSTRAINT [PK_i9sportsqamonitorform_id] PRIMARY KEY CLUSTERED ([id] ASC)
);

