CREATE TABLE [dbo].[icims_person] (
    [id]                 BIGINT        IDENTITY (40301, 1) NOT NULL,
    [icims_import_id]    BIGINT        NOT NULL,
    [PSystemID]          VARCHAR (250) NOT NULL,
    [PExternalID]        VARCHAR (250) NOT NULL,
    [JSystemID]          VARCHAR (250) NOT NULL,
    [JExternalID]        VARCHAR (250) NOT NULL,
    [FirstName]          VARCHAR (250) NOT NULL,
    [MiddleName]         VARCHAR (250) NOT NULL,
    [LastName]           VARCHAR (250) NOT NULL,
    [ApplicatCorpName]   VARCHAR (250) NOT NULL,
    [OverallCatsStatus]  VARCHAR (250) NOT NULL,
    [Email]              VARCHAR (250) NOT NULL,
    [AlternativeEmail]   VARCHAR (250) NOT NULL,
    [WsolEmail]          VARCHAR (250) NOT NULL,
    [CatsAgentId]        VARCHAR (250) NOT NULL,
    [Number]             VARCHAR (250) NOT NULL,
    [ApplicationNumber]  VARCHAR (250) NOT NULL,
    [MobileNumber]       VARCHAR (250) NOT NULL,
    [MobileTermsCond]    VARCHAR (250) NOT NULL,
    [OfficApplStartDate] VARCHAR (250) NOT NULL,
    [TechScanDate]       VARCHAR (250) NOT NULL,
    [BandwidthTier]      VARCHAR (250) NOT NULL,
    [OperatingSystem]    VARCHAR (250) NOT NULL,
    [OsStatus]           VARCHAR (250) NOT NULL,
    [HireIQAssessDate]   VARCHAR (250) NOT NULL,
    [Address]            VARCHAR (250) NOT NULL,
    [Address2]           VARCHAR (250) NOT NULL,
    [City]               VARCHAR (250) NOT NULL,
    [State]              VARCHAR (250) NOT NULL,
    [PostalCode]         VARCHAR (250) NOT NULL,
    [Country]            VARCHAR (250) NOT NULL,
    [PairingStatus]      VARCHAR (8)   NOT NULL,
    [ResumeStatus]       VARCHAR (250) NOT NULL,
    [reportStatus]       VARCHAR (4)   NOT NULL,
    [reportDate]         DATETIME2 (0) NOT NULL,
    CONSTRAINT [PK_icims_person_id] PRIMARY KEY CLUSTERED ([id] ASC)
);

