CREATE TABLE [dbo].[IDAPPSTATUSHISTORY] (
    [IDAPPSTATUSHISTORY] NUMERIC (20)   NOT NULL,
    [IDAPPLICANT]        NUMERIC (20)   NOT NULL,
    [IDAPPSTATUS]        NUMERIC (20)   NOT NULL,
    [COMMENTS]           VARCHAR (4000) NOT NULL,
    [IDUSER]             NUMERIC (20)   NOT NULL,
    [CHANGEDDATE]        DATETIME2 (0)  NOT NULL,
    CONSTRAINT [IDAPPSTATUSHISTORY_C00] PRIMARY KEY CLUSTERED ([IDAPPSTATUSHISTORY] ASC),
    CONSTRAINT [IDAPPSTATUSHISTORY_C01] FOREIGN KEY ([IDAPPLICANT]) REFERENCES [dbo].[applicant] ([IDAPPLICANT]) ON DELETE CASCADE,
    CONSTRAINT [IDAPPSTATUSHISTORY_C03] FOREIGN KEY ([IDAPPSTATUS]) REFERENCES [dbo].[APPSTATUS] ([IDAPPSTATUS]),
    CONSTRAINT [IDAPPSTATUSHISTORY_C04] FOREIGN KEY ([IDUSER]) REFERENCES [dbo].[USERS] ([IDUSER])
);






GO
CREATE NONCLUSTERED INDEX [IDAPPSTATUSHISTORY_I02]
    ON [dbo].[IDAPPSTATUSHISTORY]([IDAPPSTATUS] ASC, [IDUSER] ASC, [CHANGEDDATE] ASC);


GO
CREATE NONCLUSTERED INDEX [IDAPPSTATUSHISTORY_I01]
    ON [dbo].[IDAPPSTATUSHISTORY]([IDAPPLICANT] ASC);

