CREATE TABLE [dbo].[INTERVIEWED] (
    [IDINTERVIEWED]      NUMERIC (20)     NOT NULL,
    [IDAPPLICANT]        NUMERIC (20)     NOT NULL,
    [NOTE]               VARCHAR (4000)   NOT NULL,
    [DATEFORM]           DATETIME2 (0)    NOT NULL,
    [DATECREATED]        DATETIME2 (0)    NOT NULL,
    [IDUSER]             NUMERIC (20)     NOT NULL,
    [IDPROJECT]          NUMERIC (20)     NULL,
    [INTERVRATING]       VARCHAR (10)     NULL,
    [IDINTERVIEWEDRECOM] NUMERIC (20)     NULL,
    [ROWID]              UNIQUEIDENTIFIER DEFAULT (newid()) NOT NULL,
    CONSTRAINT [SYS_C0013125] PRIMARY KEY CLUSTERED ([IDINTERVIEWED] ASC),
    CONSTRAINT [SYS_C0013392] FOREIGN KEY ([IDPROJECT]) REFERENCES [dbo].[PROJECT] ([IDPROJECT]),
    CONSTRAINT [SYS_C0013567] FOREIGN KEY ([IDUSER]) REFERENCES [dbo].[USERS] ([IDUSER]),
    CONSTRAINT [SYS_C0013568] FOREIGN KEY ([IDAPPLICANT]) REFERENCES [dbo].[applicant] ([IDAPPLICANT]), 
    CONSTRAINT [FK_INTERVIEWED_INTERVIEWEDRECOM] FOREIGN KEY ([IDINTERVIEWEDRECOM]) REFERENCES [INTERVIEWEDRECOM]([IDINTERVIEWEDRECOM])
);






GO
CREATE NONCLUSTERED INDEX [XIF4INTERVIEWED]
    ON [dbo].[INTERVIEWED]([IDINTERVIEWEDRECOM] ASC);


GO
CREATE NONCLUSTERED INDEX [XIF2INTERVIEWED]
    ON [dbo].[INTERVIEWED]([IDUSER] ASC);


GO
CREATE NONCLUSTERED INDEX [XIF1INTERVIEWED]
    ON [dbo].[INTERVIEWED]([IDAPPLICANT] ASC);


GO
CREATE UNIQUE NONCLUSTERED INDEX [ROWID$INDEX]
    ON [dbo].[INTERVIEWED]([ROWID] ASC);


GO
