CREATE TABLE [dbo].[INTEREST] (
    [IDINTEREST] NUMERIC (20)     NOT NULL,
    [NAME]       VARCHAR (500)    NOT NULL,
    [VISIBLE]    CHAR (1)         NOT NULL,
    [ROWID]      UNIQUEIDENTIFIER DEFAULT (newid()) NOT NULL,
    CONSTRAINT [SYS_C0013124] PRIMARY KEY CLUSTERED ([IDINTEREST] ASC)
);


GO
CREATE UNIQUE NONCLUSTERED INDEX [ROWID$INDEX]
    ON [dbo].[INTEREST]([ROWID] ASC);


GO
