CREATE TABLE [dbo].[INTERVIEWEDRECOM] (
    [IDINTERVIEWEDRECOM] NUMERIC (20)     NOT NULL,
    [NAME]               VARCHAR (500)    NOT NULL,
    [VISIBLE]            CHAR (1)         DEFAULT ('Y') NOT NULL,
    [ROWID]              UNIQUEIDENTIFIER DEFAULT (newid()) NOT NULL,
    CONSTRAINT [SYS_C0013126] PRIMARY KEY CLUSTERED ([IDINTERVIEWEDRECOM] ASC)
);


GO
CREATE UNIQUE NONCLUSTERED INDEX [ROWID$INDEX]
    ON [dbo].[INTERVIEWEDRECOM]([ROWID] ASC);


GO
