CREATE TABLE [dbo].[invoicemakeruser] (
    [ID]          BIGINT        NOT NULL,
    [USERNAME]    VARCHAR (20)  NOT NULL,
    [USERPASS]    VARCHAR (20)  NOT NULL,
    [FIRSTNAME]   VARCHAR (100) NULL,
    [LASTNAME]    VARCHAR (100) NULL,
    [USEREMAIL]   VARCHAR (500) NOT NULL,
    [USERCREATED] DATETIME2 (6) NULL,
    PRIMARY KEY CLUSTERED ([ID] ASC)
);

