CREATE TABLE [dbo].[KUDOSDEPARTMENT] (
    [ID]    NUMERIC (20)  NOT NULL,
    [NAME]  VARCHAR (100) NOT NULL,
    [DATEW] DATETIME2 (0) NOT NULL,
    CONSTRAINT [SYS_C0013245] PRIMARY KEY CLUSTERED ([ID] ASC)
);

