CREATE TABLE [dbo].[LANGLIST] (
    [IDLANGLIST] NUMERIC (20)     NOT NULL,
    [NAME]       VARCHAR (100)    NOT NULL,
    [VISIBLE]    CHAR (1)         DEFAULT ('Y') NOT NULL,
    [ROWID]      UNIQUEIDENTIFIER DEFAULT (newid()) NOT NULL,
    CONSTRAINT [SYS_C0013127] PRIMARY KEY CLUSTERED ([IDLANGLIST] ASC)
);


GO
CREATE UNIQUE NONCLUSTERED INDEX [ROWID$INDEX]
    ON [dbo].[LANGLIST]([ROWID] ASC);


GO
