CREATE TABLE [dbo].[LANGUSEPREL] (
    [IDAPPLICANT] NUMERIC (20) NOT NULL,
    [IDLANGLIST]  NUMERIC (20) NOT NULL,
    CONSTRAINT [SYS_C0013276] PRIMARY KEY CLUSTERED ([IDAPPLICANT] ASC, [IDLANGLIST] ASC),
    CONSTRAINT [SYS_C0013470] FOREIGN KEY ([IDAPPLICANT]) REFERENCES [dbo].[APPLICANT_PRELIMINARY] ([ID]) ON DELETE CASCADE,
    CONSTRAINT [SYS_C0013471] FOREIGN KEY ([IDLANGLIST]) REFERENCES [dbo].[LANGLIST] ([IDLANGLIST]),
    CONSTRAINT [SYS_C0013681] FOREIGN KEY ([IDLANGLIST]) REFERENCES [dbo].[LANGLIST] ([IDLANGLIST])
);


GO
CREATE NONCLUSTERED INDEX [LANGUSEPRELI2]
    ON [dbo].[LANGUSEPREL]([IDAPPLICANT] ASC);

