CREATE TABLE [dbo].[LANGUSE] (
    [IDAPPLICANT] NUMERIC (20)     NOT NULL,
    [IDLANGLIST]  NUMERIC (20)     NOT NULL,
    [ROWID]       UNIQUEIDENTIFIER DEFAULT (newid()) NOT NULL,
    CONSTRAINT [SYS_C0013128] PRIMARY KEY CLUSTERED ([IDAPPLICANT] ASC, [IDLANGLIST] ASC),
    CONSTRAINT [SYS_C0013569] FOREIGN KEY ([IDLANGLIST]) REFERENCES [dbo].[LANGLIST] ([IDLANGLIST]),
    CONSTRAINT [SYS_C0013570] FOREIGN KEY ([IDAPPLICANT]) REFERENCES [dbo].[applicant] ([IDAPPLICANT])
);






GO
CREATE NONCLUSTERED INDEX [XIF2LANGUSE]
    ON [dbo].[LANGUSE]([IDLANGLIST] ASC);


GO
CREATE NONCLUSTERED INDEX [XIF1LANGUSE]
    ON [dbo].[LANGUSE]([IDAPPLICANT] ASC);


GO
CREATE UNIQUE NONCLUSTERED INDEX [ROWID$INDEX]
    ON [dbo].[LANGUSE]([ROWID] ASC);


GO
