CREATE TABLE [dbo].[LETTERTEMPLATE] (
    [IDLETTERTEMPLATE] NUMERIC (20)   NOT NULL,
    [TEMPLATENAME]     VARCHAR (200)  NOT NULL,
    [SUBJECT]          VARCHAR (500)  NOT NULL,
    [BODY]             VARCHAR (4000) NOT NULL,
    [VISIBLE]          CHAR (1)       NOT NULL,
    [CREATEDBY]        NUMERIC (20)   NOT NULL,
    [CREATEDDATE]      DATETIME2 (0)  NOT NULL,
    CONSTRAINT [LETTERTEMPLATE_C00] PRIMARY KEY CLUSTERED ([IDLETTERTEMPLATE] ASC),
    CONSTRAINT [LETTERTEMPLATE_C01] CHECK ([VISIBLE]='N' OR [VISIBLE]='Y'),
    CONSTRAINT [LETTERTEMPLATE_C02] FOREIGN KEY ([CREATEDBY]) REFERENCES [dbo].[USERS] ([IDUSER])
);


