CREATE TABLE [dbo].[LEVELEDUC] (
    [IDLEVELEDUC] NUMERIC (20)     NOT NULL,
    [NAME]        VARCHAR (500)    NOT NULL,
    [VISIBLE]     CHAR (1)         DEFAULT ('Y') NOT NULL,
    [INDEXORDER]  NUMERIC (20)     DEFAULT ((0)) NOT NULL,
    [ROWID]       UNIQUEIDENTIFIER DEFAULT (newid()) NOT NULL,
    CONSTRAINT [SYS_C0013129] PRIMARY KEY CLUSTERED ([IDLEVELEDUC] ASC)
);


GO
CREATE UNIQUE NONCLUSTERED INDEX [ROWID$INDEX]
    ON [dbo].[LEVELEDUC]([ROWID] ASC);


GO
