CREATE TABLE [dbo].[LINEOFBUS] (
    [ID]      NUMERIC (20)     IDENTITY (4, 1) NOT NULL,
    [name]    VARCHAR (250)    NOT NULL,
    [VISIBLE] CHAR (1)         NOT NULL,
    [ROWID]   UNIQUEIDENTIFIER NOT NULL,
    [datecr]  DATETIME2 (0)    NOT NULL,
    CONSTRAINT [SYS_C0013130] PRIMARY KEY CLUSTERED ([ID] ASC)
);


GO
