CREATE TABLE [dbo].[MILITARY_MEMBER] (
    [ID]      NUMERIC (20)  NOT NULL,
    [NAME]    VARCHAR (100) NOT NULL,
    [VISIBLE] CHAR (1)      DEFAULT ('Y') NOT NULL,
    CONSTRAINT [SYS_C0013285] PRIMARY KEY CLUSTERED ([ID] ASC)
);

