CREATE TABLE [dbo].[MODEM] (
    [IDMODEM] NUMERIC (20)     NOT NULL,
    [NAME]    VARCHAR (500)    NOT NULL,
    [VISIBLE] CHAR (1)         DEFAULT ('Y') NOT NULL,
    [ROWID]   UNIQUEIDENTIFIER DEFAULT (newid()) NOT NULL,
    CONSTRAINT [SYS_C0013131] PRIMARY KEY CLUSTERED ([IDMODEM] ASC)
);


GO
CREATE UNIQUE NONCLUSTERED INDEX [ROWID$INDEX]
    ON [dbo].[MODEM]([ROWID] ASC);


GO
