CREATE TABLE [dbo].[NAMECHAGEHISTTORY] (
    [IDNAMECHAGEHISTTORY] NUMERIC (20)   NOT NULL,
    [IDAPPLICANT]         NUMERIC (20)   NOT NULL,
    [FIRSTNAME]           VARCHAR (100)  NOT NULL,
    [MIDDLINIT]           VARCHAR (100)  NULL,
    [LASTNAME]            VARCHAR (100)  NOT NULL,
    [CORPORATNAME]        VARCHAR (4000) NULL,
    [FIRSTNAMEOLD]        VARCHAR (100)  NOT NULL,
    [MIDDLINITOLD]        VARCHAR (100)  NULL,
    [LASTNAMEOLD]         VARCHAR (100)  NOT NULL,
    [CORPORATNAMEOLD]     VARCHAR (4000) NULL,
    [CREATEDDATE]         DATETIME2 (0)  NOT NULL,
    [EMAIL]               VARCHAR (1000) DEFAULT (' ') NOT NULL,
    [EMAILOLD]            VARCHAR (1000) DEFAULT (' ') NOT NULL,
    [MAILADDR]            VARCHAR (4000) DEFAULT (' ') NOT NULL,
    [MAILADDROLD]         VARCHAR (4000) DEFAULT (' ') NOT NULL,
    [CITY]                VARCHAR (300)  DEFAULT (' ') NOT NULL,
    [CITYOLD]             VARCHAR (300)  DEFAULT (' ') NOT NULL,
    [IDSTATE]             CHAR (2)       DEFAULT ('00') NOT NULL,
    [IDSTATEOLD]          CHAR (2)       DEFAULT ('00') NOT NULL,
    [ZIP]                 VARCHAR (20)   DEFAULT (' ') NOT NULL,
    [ZIPOLD]              VARCHAR (20)   DEFAULT (' ') NOT NULL,
    CONSTRAINT [NAMECHAGEHISTTORY_C00] PRIMARY KEY CLUSTERED ([IDNAMECHAGEHISTTORY] ASC),
    CONSTRAINT [NAMECHAGEHISTTORY_C01] FOREIGN KEY ([IDAPPLICANT]) REFERENCES [dbo].[applicant] ([IDAPPLICANT]),
    CONSTRAINT [SYS_C0013398] FOREIGN KEY ([IDSTATE]) REFERENCES [dbo].[STATE] ([IDSTATE]),
    CONSTRAINT [SYS_C0013399] FOREIGN KEY ([IDSTATEOLD]) REFERENCES [dbo].[STATE] ([IDSTATE]),
    CONSTRAINT [SYS_C0013608] FOREIGN KEY ([IDSTATE]) REFERENCES [dbo].[STATE] ([IDSTATE]),
    CONSTRAINT [SYS_C0013609] FOREIGN KEY ([IDSTATEOLD]) REFERENCES [dbo].[STATE] ([IDSTATE])
);






GO
CREATE NONCLUSTERED INDEX [NAMECHAGEHISTTORY_I01]
    ON [dbo].[NAMECHAGEHISTTORY]([IDAPPLICANT] ASC);

