CREATE TABLE [dbo].[OFTENUSE] (
    [IDOFTENUSE] NUMERIC (20)     NOT NULL,
    [NAME]       VARCHAR (500)    NOT NULL,
    [VISIBLE]    CHAR (1)         DEFAULT ('Y') NOT NULL,
    [ROWID]      UNIQUEIDENTIFIER DEFAULT (newid()) NOT NULL,
    CONSTRAINT [SYS_C0013132] PRIMARY KEY CLUSTERED ([IDOFTENUSE] ASC)
);


GO
CREATE UNIQUE NONCLUSTERED INDEX [ROWID$INDEX]
    ON [dbo].[OFTENUSE]([ROWID] ASC);


GO
