CREATE TABLE [dbo].[PREPARATIONREASON] (
    [IDPREPARATIONREASON] NUMERIC (20)  NOT NULL,
    [COMPLETION]          CHAR (1)      NOT NULL,
    [NAME]                VARCHAR (100) NOT NULL,
    [VISIBLE]             CHAR (1)      NOT NULL,
    [CREATED]             DATETIME2 (0) NOT NULL,
    CONSTRAINT [PREPARATIONREASON_C00] PRIMARY KEY CLUSTERED ([IDPREPARATIONREASON] ASC)
);

