CREATE TABLE [dbo].[PREPARATIONTRAINER4LIST2] (
    [ID]                   NUMERIC (20) NOT NULL,
    [IDPREPARATIONTRAINER] NUMERIC (20) NOT NULL,
    CONSTRAINT [PREPARATIONTRAINER4LIST2C0] PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [PREPARATIONTRAINER4LIST2C1] FOREIGN KEY ([IDPREPARATIONTRAINER]) REFERENCES [dbo].[PREPARATIONTRAINER] ([IDPREPARATIONTRAINER])
);


GO
CREATE NONCLUSTERED INDEX [PREPARATIONTRAINER4LIST2]
    ON [dbo].[PREPARATIONTRAINER4LIST2]([IDPREPARATIONTRAINER] ASC);

