CREATE TABLE [dbo].[PREPARATIONUSER] (
    [IDPREPARATIONUSER] NUMERIC (20)  NOT NULL,
    [FIRSTNAME]         VARCHAR (100) NOT NULL,
    [LASTNAME]          VARCHAR (100) NOT NULL,
    [EMAIL]             VARCHAR (100) NOT NULL,
    [PASSWORD]          VARCHAR (100) NOT NULL,
    [ISLOCKED]          CHAR (1)      NOT NULL,
    [CREATED]           DATETIME2 (0) NOT NULL,
    CONSTRAINT [PREPARATIONUSER_C00] PRIMARY KEY CLUSTERED ([IDPREPARATIONUSER] ASC)
);

