CREATE TABLE [dbo].[PREPARATIONAGENTONGOING] (
    [IDPREPARATIONAGENT]  NUMERIC (20)   NOT NULL,
    [IDPREPARATIONDATA]   NUMERIC (20)   NOT NULL,
    [CORPNAME]            VARCHAR (100)  NULL,
    [AIMNAME]             VARCHAR (100)  NULL,
    [FIRSTNAME]           VARCHAR (100)  NOT NULL,
    [MIDDLENAME]          VARCHAR (100)  NULL,
    [LASTNAME]            VARCHAR (100)  NOT NULL,
    [EMAIL]               VARCHAR (200)  NOT NULL,
    [IDAPPSTATUS]         NUMERIC (20)   NOT NULL,
    [COMPLETION]          CHAR (1)       NOT NULL,
    [IDPREPARATIONREASON] NUMERIC (20)   NOT NULL,
    [COMMENTS]            VARCHAR (4000) NULL,
    [CREATED]             DATETIME2 (0)  NOT NULL,
    CONSTRAINT [IDPREPARATIONAGENTONG_C00] PRIMARY KEY CLUSTERED ([IDPREPARATIONAGENT] ASC),
    CONSTRAINT [SYS_C0013301] CHECK ([COMPLETION]='M' OR [COMPLETION]='A' OR [COMPLETION]='I' OR [COMPLETION]='N' OR [COMPLETION]='Y'),
    CONSTRAINT [SYS_C0013302] CHECK ([COMPLETION]='M' OR [COMPLETION]='A' OR [COMPLETION]='N' OR [COMPLETION]='Y'),
    CONSTRAINT [SYS_C0013508] CHECK ([COMPLETION]='M' OR [COMPLETION]='A' OR [COMPLETION]='I' OR [COMPLETION]='N' OR [COMPLETION]='Y'),
    CONSTRAINT [SYS_C0013509] CHECK ([COMPLETION]='M' OR [COMPLETION]='A' OR [COMPLETION]='N' OR [COMPLETION]='Y'),
    CONSTRAINT [IDAPPSTATUSONG_C01] FOREIGN KEY ([IDAPPSTATUS]) REFERENCES [dbo].[APPSTATUS] ([IDAPPSTATUS]),
    CONSTRAINT [IDPREPARATIONDATAONG_C01] FOREIGN KEY ([IDPREPARATIONDATA]) REFERENCES [dbo].[PREPARATIONDATA] ([IDPREPARATIONDATA]),
    CONSTRAINT [IDPREPARATIONREASONONG_C01] FOREIGN KEY ([IDPREPARATIONREASON]) REFERENCES [dbo].[PREPARATIONREASON] ([IDPREPARATIONREASON])
);


GO
CREATE UNIQUE NONCLUSTERED INDEX [PREPARATIONAGENTONGI01]
    ON [dbo].[PREPARATIONAGENTONGOING]([IDPREPARATIONDATA] ASC, [EMAIL] ASC);

