CREATE TABLE [dbo].[PREPSTATUS] (
    [IDPREPSTATUS] NUMERIC (20)     NOT NULL,
    [NAME]         VARCHAR (500)    NOT NULL,
    [VISIBLE]      CHAR (1)         DEFAULT ('Y') NOT NULL,
    [ROWID]        UNIQUEIDENTIFIER DEFAULT (newid()) NOT NULL,
    CONSTRAINT [SYS_C0013137] PRIMARY KEY CLUSTERED ([IDPREPSTATUS] ASC)
);


GO
CREATE UNIQUE NONCLUSTERED INDEX [ROWID$INDEX]
    ON [dbo].[PREPSTATUS]([ROWID] ASC);


GO
