CREATE TABLE [dbo].[PREPARATIONGROUPOFCLASSES] (
    [IDPREPARATIONGROUPOFCLASSES] NUMERIC (20)  NOT NULL,
    [CREATED]                     DATETIME2 (0) NOT NULL,
    CONSTRAINT [PREPARATIONGROUPOFCLASSES_C00] PRIMARY KEY CLUSTERED ([IDPREPARATIONGROUPOFCLASSES] ASC)
);

