CREATE TABLE [dbo].[PREPARATIONTRAINER4LIST3] (
    [ID]                   NUMERIC (20) NOT NULL,
    [IDPREPARATIONTRAINER] NUMERIC (20) NOT NULL,
    CONSTRAINT [PREPARATIONTRAINER4LIST3C0] PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [PREPARATIONTRAINER4LIST3C1] FOREIGN KEY ([IDPREPARATIONTRAINER]) REFERENCES [dbo].[PREPARATIONTRAINER] ([IDPREPARATIONTRAINER])
);


GO
CREATE NONCLUSTERED INDEX [PREPARATIONTRAINER4LIST3]
    ON [dbo].[PREPARATIONTRAINER4LIST3]([IDPREPARATIONTRAINER] ASC);

