CREATE TABLE [dbo].[PREPARATIONAGENT] (
    [IDPREPARATIONAGENT]  NUMERIC (20)   NOT NULL,
    [IDPREPARATIONDATA]   NUMERIC (20)   NOT NULL,
    [FIRSTNAME]           VARCHAR (100)  NOT NULL,
    [MIDDLENAME]          VARCHAR (100)  NULL,
    [LASTNAME]            VARCHAR (100)  NOT NULL,
    [EMAIL]               VARCHAR (200)  NOT NULL,
    [IDAPPSTATUS]         NUMERIC (20)   NOT NULL,
    [COMPLETION]          CHAR (1)       NOT NULL,
    [IDPREPARATIONREASON] NUMERIC (20)   NOT NULL,
    [DAYSATTENDED]        NUMERIC (20)   NOT NULL,
    [COMMENTS]            VARCHAR (4000) NULL,
    [CREATED]             DATETIME2 (0)  NOT NULL,
    [CORPNAME]            VARCHAR (100)  NULL,
    [AIMNAME]             VARCHAR (100)  NULL,
    CONSTRAINT [IDPREPARATIONAGENT_C00] PRIMARY KEY CLUSTERED ([IDPREPARATIONAGENT] ASC),
    CONSTRAINT [SYS_C0013199] CHECK ([COMPLETION]='M' OR [COMPLETION]='A' OR [COMPLETION]='I' OR [COMPLETION]='N' OR [COMPLETION]='Y'),
    CONSTRAINT [SYS_C0013406] CHECK ([COMPLETION]='M' OR [COMPLETION]='A' OR [COMPLETION]='I' OR [COMPLETION]='N' OR [COMPLETION]='Y'),
    CONSTRAINT [IDAPPSTATUS_C01] FOREIGN KEY ([IDAPPSTATUS]) REFERENCES [dbo].[APPSTATUS] ([IDAPPSTATUS]),
    CONSTRAINT [IDPREPARATIONDATA_C01] FOREIGN KEY ([IDPREPARATIONDATA]) REFERENCES [dbo].[PREPARATIONDATA] ([IDPREPARATIONDATA]),
    CONSTRAINT [IDPREPARATIONREASON_C01] FOREIGN KEY ([IDPREPARATIONREASON]) REFERENCES [dbo].[PREPARATIONREASON] ([IDPREPARATIONREASON])
);


GO
CREATE NONCLUSTERED INDEX [nci_wi_PREPARATIONAGENT_DFEC4636528E97714524855B4C4E3538]
    ON [dbo].[PREPARATIONAGENT]([COMPLETION] ASC)
    INCLUDE([IDPREPARATIONDATA], [IDPREPARATIONREASON]);


GO
CREATE UNIQUE NONCLUSTERED INDEX [PREPARATIONAGENTI01]
    ON [dbo].[PREPARATIONAGENT]([IDPREPARATIONDATA] ASC, [EMAIL] ASC);

