CREATE TABLE [dbo].[PROJECT] (
    [IDPROJECT]   NUMERIC (20)     NOT NULL,
    [NAME]        VARCHAR (250)    NOT NULL,
    [IDCLIENT]    NUMERIC (20)     NOT NULL,
    [IDPAYTYPE]   NUMERIC (20)     NOT NULL,
    [IDLINEOFBUS] NUMERIC (20)     NOT NULL,
    [VISIBLE]     CHAR (1)         DEFAULT ('Y') NOT NULL,
    [PAYRATE]     NUMERIC (20, 4)  NOT NULL,
    [DATEUPDATED] DATETIME2 (0)    NOT NULL,
    [ISSHOW]      CHAR (1)         DEFAULT ('Y') NOT NULL,
    [ISSHOWLB]    CHAR (1)         DEFAULT ('Y') NOT NULL,
    [ROWID]       UNIQUEIDENTIFIER DEFAULT (newid()) NOT NULL,
    CONSTRAINT [SYS_C0013138] PRIMARY KEY CLUSTERED ([IDPROJECT] ASC)
);




GO
CREATE NONCLUSTERED INDEX [XIF3PROJECT]
    ON [dbo].[PROJECT]([IDLINEOFBUS] ASC);


GO
CREATE NONCLUSTERED INDEX [XIF2PROJECT]
    ON [dbo].[PROJECT]([IDPAYTYPE] ASC);


GO
CREATE NONCLUSTERED INDEX [XIF1PROJECT]
    ON [dbo].[PROJECT]([IDCLIENT] ASC);


GO
CREATE UNIQUE NONCLUSTERED INDEX [ROWID$INDEX]
    ON [dbo].[PROJECT]([ROWID] ASC);


GO

