CREATE TABLE [dbo].[PROJTYPESABLEUSE] (
    [IDAPPLICANT]         NUMERIC (20) NOT NULL,
    [IDPROJTYPESABLELIST] NUMERIC (20) NOT NULL,
    CONSTRAINT [SYS_C0013142] PRIMARY KEY CLUSTERED ([IDAPPLICANT] ASC, [IDPROJTYPESABLELIST] ASC)
);


GO
CREATE NONCLUSTERED INDEX [XIF2PROJTYPESABLEUSE]
    ON [dbo].[PROJTYPESABLEUSE]([IDPROJTYPESABLELIST] ASC);


GO
CREATE NONCLUSTERED INDEX [XIF1PROJTYPESABLEUSE]
    ON [dbo].[PROJTYPESABLEUSE]([IDAPPLICANT] ASC);

