CREATE TABLE [dbo].[PROJECTSTATUSTYPE] (
    [IDPROJECTSTATUSTYPE] NUMERIC (20)     NOT NULL,
    [NAME]                VARCHAR (500)    NOT NULL,
    [VISIBLE]             CHAR (1)         DEFAULT ('Y') NOT NULL,
    [ROWID]               UNIQUEIDENTIFIER DEFAULT (newid()) NOT NULL,
    CONSTRAINT [SYS_C0013140] PRIMARY KEY CLUSTERED ([IDPROJECTSTATUSTYPE] ASC)
);


GO
CREATE UNIQUE NONCLUSTERED INDEX [ROWID$INDEX]
    ON [dbo].[PROJECTSTATUSTYPE]([ROWID] ASC);


GO
