CREATE TABLE [dbo].[PROJTYPESUSEPREL] (
    [IDAPPLICANT]     NUMERIC (20) NOT NULL,
    [IDPROJTYPESLIST] NUMERIC (20) NOT NULL,
    CONSTRAINT [SYS_C0013274] PRIMARY KEY CLUSTERED ([IDAPPLICANT] ASC, [IDPROJTYPESLIST] ASC),
    CONSTRAINT [SYS_C0013466] FOREIGN KEY ([IDAPPLICANT]) REFERENCES [dbo].[APPLICANT_PRELIMINARY] ([ID]) ON DELETE CASCADE,
    CONSTRAINT [SYS_C0013467] FOREIGN KEY ([IDPROJTYPESLIST]) REFERENCES [dbo].[PROJTYPESLIST] ([IDPROJTYPESLIST]),
    CONSTRAINT [SYS_C0013677] FOREIGN KEY ([IDPROJTYPESLIST]) REFERENCES [dbo].[PROJTYPESLIST] ([IDPROJTYPESLIST])
);


GO
CREATE NONCLUSTERED INDEX [PROJTYPESUSEPRELI02]
    ON [dbo].[PROJTYPESUSEPREL]([IDAPPLICANT] ASC);

