CREATE TABLE [dbo].[PROJTYPESLIST] (
    [IDPROJTYPESLIST] NUMERIC (20)     NOT NULL,
    [NAME]            VARCHAR (500)    NOT NULL,
    [VISIBLE]         CHAR (1)         DEFAULT ('Y') NOT NULL,
    [ROWID]           UNIQUEIDENTIFIER DEFAULT (newid()) NOT NULL,
    CONSTRAINT [SYS_C0013143] PRIMARY KEY CLUSTERED ([IDPROJTYPESLIST] ASC)
);


GO
CREATE UNIQUE NONCLUSTERED INDEX [ROWID$INDEX]
    ON [dbo].[PROJTYPESLIST]([ROWID] ASC);


GO
