CREATE TABLE [dbo].[PROJTYPESABLEUSEPREL] (
    [IDAPPLICANT]         NUMERIC (20) NOT NULL,
    [IDPROJTYPESABLELIST] NUMERIC (20) NOT NULL,
    CONSTRAINT [SYS_C0013275] PRIMARY KEY CLUSTERED ([IDAPPLICANT] ASC, [IDPROJTYPESABLELIST] ASC),
    CONSTRAINT [SYS_C0013468] FOREIGN KEY ([IDAPPLICANT]) REFERENCES [dbo].[APPLICANT_PRELIMINARY] ([ID]) ON DELETE CASCADE,
    CONSTRAINT [SYS_C0013469] FOREIGN KEY ([IDPROJTYPESABLELIST]) REFERENCES [dbo].[PROJTYPESABLELIST] ([IDPROJTYPESABLELIST]),
    CONSTRAINT [SYS_C0013679] FOREIGN KEY ([IDPROJTYPESABLELIST]) REFERENCES [dbo].[PROJTYPESABLELIST] ([IDPROJTYPESABLELIST])
);


GO
CREATE NONCLUSTERED INDEX [PROJTYPESABLEUSEPRELI2]
    ON [dbo].[PROJTYPESABLEUSEPREL]([IDAPPLICANT] ASC);

