CREATE TABLE [dbo].[PROJTYPESUSE] (
    [IDAPPLICANT]     NUMERIC (20)     NOT NULL,
    [IDPROJTYPESLIST] NUMERIC (20)     NOT NULL,
    [ROWID]           UNIQUEIDENTIFIER DEFAULT (newid()) NOT NULL,
    CONSTRAINT [SYS_C0013144] PRIMARY KEY CLUSTERED ([IDAPPLICANT] ASC, [IDPROJTYPESLIST] ASC),
    CONSTRAINT [SYS_C0013371] FOREIGN KEY ([IDPROJTYPESLIST]) REFERENCES [dbo].[PROJTYPESLIST] ([IDPROJTYPESLIST]),
    CONSTRAINT [SYS_C0013581] FOREIGN KEY ([IDPROJTYPESLIST]) REFERENCES [dbo].[PROJTYPESLIST] ([IDPROJTYPESLIST]),
    CONSTRAINT [SYS_C0013582] FOREIGN KEY ([IDAPPLICANT]) REFERENCES [dbo].[applicant] ([IDAPPLICANT])
);






GO
CREATE NONCLUSTERED INDEX [XIF2PROJTYPESUSE]
    ON [dbo].[PROJTYPESUSE]([IDPROJTYPESLIST] ASC);


GO
CREATE NONCLUSTERED INDEX [XIF1PROJTYPESUSE]
    ON [dbo].[PROJTYPESUSE]([IDAPPLICANT] ASC);


GO
CREATE UNIQUE NONCLUSTERED INDEX [ROWID$INDEX]
    ON [dbo].[PROJTYPESUSE]([ROWID] ASC);


GO
