CREATE TABLE [dbo].[qualityoffdep] (
    [idqualityoffdep] BIGINT        IDENTITY (341, 1) NOT NULL,
    [idqualityscores] BIGINT        DEFAULT ((0)) NOT NULL,
    [idreason]        BIGINT        DEFAULT ((0)) NOT NULL,
    [idprogram]       BIGINT        DEFAULT ((0)) NOT NULL,
    [idmonitor]       BIGINT        DEFAULT ((0)) NOT NULL,
    [ordernum]        VARCHAR (250) DEFAULT (NULL) NULL,
    [customernum]     VARCHAR (250) DEFAULT (NULL) NULL,
    [approach1]       VARCHAR (250) DEFAULT (NULL) NULL,
    [approach2]       VARCHAR (250) DEFAULT (NULL) NULL,
    [approach3]       VARCHAR (250) DEFAULT (NULL) NULL,
    [approach4]       VARCHAR (250) DEFAULT (NULL) NULL,
    [approach5]       VARCHAR (250) DEFAULT (NULL) NULL,
    [discovproc1]     VARCHAR (250) DEFAULT (NULL) NULL,
    [discovproc2]     VARCHAR (250) DEFAULT (NULL) NULL,
    [discovproc3]     VARCHAR (250) DEFAULT (NULL) NULL,
    [marketcust1]     VARCHAR (250) DEFAULT (NULL) NULL,
    [marketcust2]     VARCHAR (250) DEFAULT (NULL) NULL,
    [marketcust3]     VARCHAR (250) DEFAULT (NULL) NULL,
    [sales1]          VARCHAR (250) DEFAULT (NULL) NULL,
    [sales2]          VARCHAR (250) DEFAULT (NULL) NULL,
    [sales3]          VARCHAR (250) DEFAULT (NULL) NULL,
    [sales4]          VARCHAR (250) DEFAULT (NULL) NULL,
    [sales5]          VARCHAR (250) DEFAULT (NULL) NULL,
    [sales6]          VARCHAR (250) DEFAULT (NULL) NULL,
    [sales7]          VARCHAR (250) DEFAULT (NULL) NULL,
    [sales8]          VARCHAR (250) DEFAULT (NULL) NULL,
    [busproc1]        VARCHAR (250) DEFAULT (NULL) NULL,
    [busproc2]        VARCHAR (250) DEFAULT (NULL) NULL,
    [busproc3]        VARCHAR (250) DEFAULT (NULL) NULL,
    [busproc4]        VARCHAR (250) DEFAULT (NULL) NULL,
    [busproc5]        VARCHAR (250) DEFAULT (NULL) NULL,
    [idqualityqaq10]  BIGINT        DEFAULT ((0)) NOT NULL,
    CONSTRAINT [PK_qualityoffdep_idqualityoffdep] PRIMARY KEY CLUSTERED ([idqualityoffdep] ASC)
);

