CREATE TABLE [dbo].[qualitysalesmonit] (
    [idqualitysalesmonit] BIGINT       IDENTITY (4485, 1) NOT NULL,
    [idqualityscores]     BIGINT       DEFAULT ((0)) NOT NULL,
    [idreason]            BIGINT       DEFAULT ((0)) NOT NULL,
    [apprtime]            VARCHAR (50) DEFAULT (N'') NOT NULL,
    [idprogram]           BIGINT       DEFAULT ((0)) NOT NULL,
    [idmonitor]           BIGINT       DEFAULT ((0)) NOT NULL,
    [te_CallName]         VARCHAR (10) DEFAULT (N'') NOT NULL,
    [te_Greeting]         VARCHAR (10) DEFAULT (N'N/A') NOT NULL,
    [te_Demeanor]         VARCHAR (10) DEFAULT (N'N/A') NOT NULL,
    [te_Lang]             VARCHAR (10) DEFAULT (N'N/A') NOT NULL,
    [q1]                  VARCHAR (10) DEFAULT (NULL) NULL,
    [q2]                  VARCHAR (10) DEFAULT (NULL) NULL,
    [q3]                  VARCHAR (10) DEFAULT (NULL) NULL,
    [q4]                  VARCHAR (10) DEFAULT (NULL) NULL,
    [q5]                  VARCHAR (10) DEFAULT (NULL) NULL,
    [q6]                  VARCHAR (10) DEFAULT (NULL) NULL,
    [q7]                  VARCHAR (10) DEFAULT (NULL) NULL,
    [q8]                  VARCHAR (10) DEFAULT (NULL) NULL,
    [q9]                  VARCHAR (10) DEFAULT (NULL) NULL,
    [q10]                 VARCHAR (10) DEFAULT (NULL) NULL,
    [q11]                 VARCHAR (10) DEFAULT (NULL) NULL,
    [q12]                 VARCHAR (10) DEFAULT (NULL) NULL,
    [q13]                 VARCHAR (10) DEFAULT (NULL) NULL,
    [q14]                 VARCHAR (10) DEFAULT (NULL) NULL,
    [q15]                 VARCHAR (10) DEFAULT (NULL) NULL,
    [q16]                 VARCHAR (10) DEFAULT (NULL) NULL,
    [q17]                 VARCHAR (10) DEFAULT (NULL) NULL,
    [q18]                 VARCHAR (10) DEFAULT (NULL) NULL,
    [q19]                 VARCHAR (10) DEFAULT (NULL) NULL,
    [q20]                 VARCHAR (10) DEFAULT (NULL) NULL,
    [q21]                 VARCHAR (10) DEFAULT (NULL) NULL,
    [q22]                 VARCHAR (10) DEFAULT (NULL) NULL,
    [q23]                 VARCHAR (10) DEFAULT (NULL) NULL,
    [idqualityqaq10]      BIGINT       DEFAULT ((10)) NOT NULL,
    CONSTRAINT [PK_qualitysalesmonit_idqualitysalesmonit] PRIMARY KEY CLUSTERED ([idqualitysalesmonit] ASC)
);

