CREATE TABLE [dbo].[RACE] (
    [IDRACE]  NUMERIC (20)     NOT NULL,
    [NAME]    VARCHAR (100)    NOT NULL,
    [VISIBLE] CHAR (1)         DEFAULT ('Y') NOT NULL,
    [ROWID]   UNIQUEIDENTIFIER DEFAULT (newid()) NOT NULL,
    CONSTRAINT [SYS_C0013145] PRIMARY KEY CLUSTERED ([IDRACE] ASC)
);


GO
CREATE UNIQUE NONCLUSTERED INDEX [ROWID$INDEX]
    ON [dbo].[RACE]([ROWID] ASC);


GO
