CREATE TABLE [dbo].[REFERRALPROGRAM] (
    [ID]             NUMERIC (20)     NOT NULL,
    [IDAPPLICANT]    NUMERIC (20)     NOT NULL,
    [REWARDTYPE]     CHAR (1)         DEFAULT ('1') NOT NULL,
    [REWARDPAID]     CHAR (1)         DEFAULT ('N') NOT NULL,
    [NOTES]          VARCHAR (4000)   NOT NULL,
    [CREATED]        DATETIME2 (0)    NOT NULL,
    [REWARDPAIDDATE] DATETIME2 (0)    NULL,
    [ROWID]          UNIQUEIDENTIFIER DEFAULT (newid()) NOT NULL,
    CONSTRAINT [SYS_C0013290] PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [REFERRALPROGRAM_C1] CHECK ([REWARDTYPE]='2' OR [REWARDTYPE]='1'),
    CONSTRAINT [REFERRALPROGRAM_C2] CHECK ([REWARDPAID]='N' OR [REWARDPAID]='Y')
);




GO

CREATE NONCLUSTERED INDEX [REFERRALPROGRAMI1]
    ON [dbo].[REFERRALPROGRAM]([CREATED] ASC);




GO
CREATE UNIQUE NONCLUSTERED INDEX [REFERRALPROGRAMI02]
    ON [dbo].[REFERRALPROGRAM]([IDAPPLICANT] ASC, [REWARDTYPE] ASC);


GO
CREATE UNIQUE NONCLUSTERED INDEX [ROWID$INDEX]
    ON [dbo].[REFERRALPROGRAM]([ROWID] ASC);


GO
