CREATE TABLE [dbo].[REFERRALPROGRAMHIST] (
    [ID]          NUMERIC (20)  NOT NULL,
    [IDAPPLICANT] NUMERIC (20)  NOT NULL,
    [REWARDTYPE]  CHAR (1)      DEFAULT ('1') NOT NULL,
    [REWARDPAID]  CHAR (1)      DEFAULT ('N') NOT NULL,
    [CHANGED]     DATETIME2 (0) NOT NULL,
    CONSTRAINT [SYS_C0013293] PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [REFERRALPROGRAMHIST_C1] CHECK ([REWARDTYPE]='2' OR [REWARDTYPE]='1'),
    CONSTRAINT [REFERRALPROGRAMHIST_C2] CHECK ([REWARDPAID]='N' OR [REWARDPAID]='Y')
);

