CREATE TABLE [dbo].[RESUMEFILE] (
    [ID]              NUMERIC (20)   NOT NULL,
    [IDAPPLICANT]     NUMERIC (20)   NULL,
    [IDAPPLICANTPREL] NUMERIC (20)   NULL,
    [FILENAME]        VARCHAR (1000) NULL,
    [FILESIZE]        NUMERIC (20)   NULL,
    [FILEDATE]        DATETIME2 (0)  NULL,
    [CONTENTTYPE]     VARCHAR (500)  NULL,
    [CREATED]         DATETIME2 (0)  NOT NULL,
    CONSTRAINT [SYS_C0022969] PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [RESUMEFILE_C1] FOREIGN KEY ([IDAPPLICANT]) REFERENCES [dbo].[applicant] ([IDAPPLICANT]),
    CONSTRAINT [RESUMEFILE_C2] FOREIGN KEY ([IDAPPLICANTPREL]) REFERENCES [dbo].[APPLICANT_PRELIMINARY] ([ID])
);






GO
CREATE NONCLUSTERED INDEX [nci_wi_RESUMEFILE_BDC988BF73704664C0EEC1A13F498584]
    ON [dbo].[RESUMEFILE]([IDAPPLICANT] ASC)
    INCLUDE([CONTENTTYPE], [CREATED], [FILEDATE], [FILENAME], [FILESIZE]);


GO
CREATE UNIQUE NONCLUSTERED INDEX [resumeFile_i2]
    ON [dbo].[RESUMEFILE]([IDAPPLICANTPREL] ASC) WHERE ([idapplicantprel] IS NOT NULL);


GO
CREATE UNIQUE NONCLUSTERED INDEX [resumeFile_i1]
    ON [dbo].[RESUMEFILE]([IDAPPLICANT] ASC) WHERE ([idapplicant] IS NOT NULL);

