CREATE TABLE [dbo].[SATSDETAIL] (
    [IDSATSDETAIL] NUMERIC (20)   NOT NULL,
    [IDSATSINFO]   NUMERIC (20)   NOT NULL,
    [description]  VARCHAR (2000) NOT NULL,
    [component]    VARCHAR (500)  NOT NULL,
    [color]        VARCHAR (50)   NOT NULL,
    CONSTRAINT [SATSDETAIL_C00] PRIMARY KEY CLUSTERED ([IDSATSDETAIL] ASC),
    CONSTRAINT [SATSDETAIL_C01] FOREIGN KEY ([IDSATSINFO]) REFERENCES [dbo].[SATSINFO] ([IDSATSINFO]) ON DELETE CASCADE
);

