CREATE TABLE [dbo].[SATSNIC] (
    [IDSATSNIC]   NUMERIC (20)  NOT NULL,
    [IDSATSINFO]  NUMERIC (20)  NOT NULL,
    [DISPLAYNAME] VARCHAR (500) NOT NULL,
    [NICNAME]     VARCHAR (500) NOT NULL,
    [MACADDRESS]  VARCHAR (500) NOT NULL,
    CONSTRAINT [SATSNIC_C00] PRIMARY KEY CLUSTERED ([IDSATSNIC] ASC)
);


GO
CREATE NONCLUSTERED INDEX [SATSNICI01]
    ON [dbo].[SATSNIC]([IDSATSINFO] ASC);

