CREATE TABLE [dbo].[SATSINFO] (
    [IDSATSINFO]                  NUMERIC (20)    NOT NULL,
    [IDAPPLICANT]                 NUMERIC (20)    NOT NULL,
    [OPERATINGSYSTEMVERSION]      VARCHAR (500)   NOT NULL,
    [SERVICEPACKVERSION]          VARCHAR (500)   NOT NULL,
    [SYSTEMAARCHITECTURE]         VARCHAR (500)   NOT NULL,
    [SYSTEMARCHITECTUREDATAMODEL] VARCHAR (500)   NOT NULL,
    [RAM]                         NUMERIC (10)    NOT NULL,
    [PROCESSORMAKE]               VARCHAR (500)   NOT NULL,
    [PROCESSORMODEL]              VARCHAR (500)   NOT NULL,
    [NETVERSION]                  VARCHAR (500)   NOT NULL,
    [JAVAINTERPRETER]             VARCHAR (500)   NOT NULL,
    [JAVASPECVERSION]             VARCHAR (500)   NOT NULL,
    [JAVAVENDOR]                  VARCHAR (500)   NOT NULL,
    [INTERNETEXPLORER]            VARCHAR (500)   NOT NULL,
    [AOLAIM]                      VARCHAR (500)   NOT NULL,
    [ADOBEACROBATREADER]          VARCHAR (500)   NOT NULL,
    [FLASHPLAYER]                 VARCHAR (500)   NOT NULL,
    [SPEED]                       NUMERIC (10, 2) NOT NULL,
    [REMOTEADDR]                  VARCHAR (500)   NOT NULL,
    [REMOTEHOST]                  VARCHAR (500)   NOT NULL,
    [ANTIVIRUS]                   VARCHAR (500)   NOT NULL,
    [DATEW]                       DATETIME2 (0)   NOT NULL,
    [COMPUTERNAME]                VARCHAR (500)   DEFAULT (' ') NOT NULL,
    [IDSATSINFORESULT]            NUMERIC (20)    DEFAULT ((2)) NOT NULL,
    [SCREENWIDTH]                 NUMERIC (6)     DEFAULT ((0)) NOT NULL,
    [SCREENHEIGHT]                NUMERIC (6)     DEFAULT ((0)) NOT NULL,
    [MACADDRESS]                  VARCHAR (100)   DEFAULT (' ') NOT NULL,
    [salesforce_id]               VARCHAR (500)   DEFAULT ('') NOT NULL,
    [salesForceSuccess]           BIT             DEFAULT ('0') NOT NULL,
    [salesForceStatusReport]      VARCHAR (1000)  DEFAULT ('') NOT NULL,
    [salesForceScanStatus]        VARCHAR (100)   DEFAULT ('') NOT NULL,
    CONSTRAINT [SATSINFO_C00] PRIMARY KEY CLUSTERED ([IDSATSINFO] ASC),
    CONSTRAINT [SATSINFO_C01] FOREIGN KEY ([IDAPPLICANT]) REFERENCES [dbo].[APPLICANT] ([IDAPPLICANT]) ON DELETE CASCADE
);






GO
CREATE NONCLUSTERED INDEX [salesforceId]
    ON [dbo].[SATSINFO]([salesforce_id] ASC);


GO
CREATE NONCLUSTERED INDEX [nci_wi_SATSINFO_3C52B64C3B46DAE530CFF1DFE2FC876B]
    ON [dbo].[SATSINFO]([IDAPPLICANT] ASC)
    INCLUDE([ADOBEACROBATREADER], [AOLAIM], [DATEW], [FLASHPLAYER], [INTERNETEXPLORER], [JAVAINTERPRETER], [JAVASPECVERSION], [JAVAVENDOR], [NETVERSION], [OPERATINGSYSTEMVERSION], [PROCESSORMAKE], [PROCESSORMODEL], [RAM], [SERVICEPACKVERSION], [SPEED], [SYSTEMAARCHITECTURE], [SYSTEMARCHITECTUREDATAMODEL]);

