CREATE TABLE [dbo].[schtimes_tl] (
    [id]              BIGINT        IDENTITY (128446, 1) NOT NULL,
    [datesch]         DATE          DEFAULT ([dbo].[GETDATE]()) NOT NULL,
    [idprogr]         BIGINT        DEFAULT ((0)) NOT NULL,
    [limithr]         BIGINT        DEFAULT ((0)) NOT NULL,
    [f0000]           INT           DEFAULT ((0)) NOT NULL,
    [f0015]           INT           DEFAULT ((0)) NOT NULL,
    [f0030]           INT           DEFAULT ((0)) NOT NULL,
    [f0045]           INT           DEFAULT ((0)) NOT NULL,
    [f0100]           INT           DEFAULT ((0)) NOT NULL,
    [f0115]           INT           DEFAULT ((0)) NOT NULL,
    [f0130]           INT           DEFAULT ((0)) NOT NULL,
    [f0145]           INT           DEFAULT ((0)) NOT NULL,
    [f0200]           INT           DEFAULT ((0)) NOT NULL,
    [f0215]           INT           DEFAULT ((0)) NOT NULL,
    [f0230]           INT           DEFAULT ((0)) NOT NULL,
    [f0245]           INT           DEFAULT ((0)) NOT NULL,
    [f0300]           INT           DEFAULT ((0)) NOT NULL,
    [f0315]           INT           DEFAULT ((0)) NOT NULL,
    [f0330]           INT           DEFAULT ((0)) NOT NULL,
    [f0345]           INT           DEFAULT ((0)) NOT NULL,
    [f0400]           INT           DEFAULT ((0)) NOT NULL,
    [f0415]           INT           DEFAULT ((0)) NOT NULL,
    [f0430]           INT           DEFAULT ((0)) NOT NULL,
    [f0445]           INT           DEFAULT ((0)) NOT NULL,
    [f0500]           INT           DEFAULT ((0)) NOT NULL,
    [f0515]           INT           DEFAULT ((0)) NOT NULL,
    [f0530]           INT           DEFAULT ((0)) NOT NULL,
    [f0545]           INT           DEFAULT ((0)) NOT NULL,
    [f0600]           INT           DEFAULT ((0)) NOT NULL,
    [f0615]           INT           DEFAULT ((0)) NOT NULL,
    [f0630]           INT           DEFAULT ((0)) NOT NULL,
    [f0645]           INT           DEFAULT ((0)) NOT NULL,
    [f0700]           INT           DEFAULT ((0)) NOT NULL,
    [f0715]           INT           DEFAULT ((0)) NOT NULL,
    [f0730]           INT           DEFAULT ((0)) NOT NULL,
    [f0745]           INT           DEFAULT ((0)) NOT NULL,
    [f0800]           INT           DEFAULT ((0)) NOT NULL,
    [f0815]           INT           DEFAULT ((0)) NOT NULL,
    [f0830]           INT           DEFAULT ((0)) NOT NULL,
    [f0845]           INT           DEFAULT ((0)) NOT NULL,
    [f0900]           INT           DEFAULT ((0)) NOT NULL,
    [f0915]           INT           DEFAULT ((0)) NOT NULL,
    [f0930]           INT           DEFAULT ((0)) NOT NULL,
    [f0945]           INT           DEFAULT ((0)) NOT NULL,
    [f1000]           INT           DEFAULT ((0)) NOT NULL,
    [f1015]           INT           DEFAULT ((0)) NOT NULL,
    [f1030]           INT           DEFAULT ((0)) NOT NULL,
    [f1045]           INT           DEFAULT ((0)) NOT NULL,
    [f1100]           INT           DEFAULT ((0)) NOT NULL,
    [f1115]           INT           DEFAULT ((0)) NOT NULL,
    [f1130]           INT           DEFAULT ((0)) NOT NULL,
    [f1145]           INT           DEFAULT ((0)) NOT NULL,
    [f1200]           INT           DEFAULT ((0)) NOT NULL,
    [f1215]           INT           DEFAULT ((0)) NOT NULL,
    [f1230]           INT           DEFAULT ((0)) NOT NULL,
    [f1245]           INT           DEFAULT ((0)) NOT NULL,
    [f1300]           INT           DEFAULT ((0)) NOT NULL,
    [f1315]           INT           DEFAULT ((0)) NOT NULL,
    [f1330]           INT           DEFAULT ((0)) NOT NULL,
    [f1345]           INT           DEFAULT ((0)) NOT NULL,
    [f1400]           INT           DEFAULT ((0)) NOT NULL,
    [f1415]           INT           DEFAULT ((0)) NOT NULL,
    [f1430]           INT           DEFAULT ((0)) NOT NULL,
    [f1445]           INT           DEFAULT ((0)) NOT NULL,
    [f1500]           INT           DEFAULT ((0)) NOT NULL,
    [f1515]           INT           DEFAULT ((0)) NOT NULL,
    [f1530]           INT           DEFAULT ((0)) NOT NULL,
    [f1545]           INT           DEFAULT ((0)) NOT NULL,
    [f1600]           INT           DEFAULT ((0)) NOT NULL,
    [f1615]           INT           DEFAULT ((0)) NOT NULL,
    [f1630]           INT           DEFAULT ((0)) NOT NULL,
    [f1645]           INT           DEFAULT ((0)) NOT NULL,
    [f1700]           INT           DEFAULT ((0)) NOT NULL,
    [f1715]           INT           DEFAULT ((0)) NOT NULL,
    [f1730]           INT           DEFAULT ((0)) NOT NULL,
    [f1745]           INT           DEFAULT ((0)) NOT NULL,
    [f1800]           INT           DEFAULT ((0)) NOT NULL,
    [f1815]           INT           DEFAULT ((0)) NOT NULL,
    [f1830]           INT           DEFAULT ((0)) NOT NULL,
    [f1845]           INT           DEFAULT ((0)) NOT NULL,
    [f1900]           INT           DEFAULT ((0)) NOT NULL,
    [f1915]           INT           DEFAULT ((0)) NOT NULL,
    [f1930]           INT           DEFAULT ((0)) NOT NULL,
    [f1945]           INT           DEFAULT ((0)) NOT NULL,
    [f2000]           INT           DEFAULT ((0)) NOT NULL,
    [f2015]           INT           DEFAULT ((0)) NOT NULL,
    [f2030]           INT           DEFAULT ((0)) NOT NULL,
    [f2045]           INT           DEFAULT ((0)) NOT NULL,
    [f2100]           INT           DEFAULT ((0)) NOT NULL,
    [f2115]           INT           DEFAULT ((0)) NOT NULL,
    [f2130]           INT           DEFAULT ((0)) NOT NULL,
    [f2145]           INT           DEFAULT ((0)) NOT NULL,
    [f2200]           INT           DEFAULT ((0)) NOT NULL,
    [f2215]           INT           DEFAULT ((0)) NOT NULL,
    [f2230]           INT           DEFAULT ((0)) NOT NULL,
    [f2245]           INT           DEFAULT ((0)) NOT NULL,
    [f2300]           INT           DEFAULT ((0)) NOT NULL,
    [f2315]           INT           DEFAULT ((0)) NOT NULL,
    [f2330]           INT           DEFAULT ((0)) NOT NULL,
    [f2345]           INT           DEFAULT ((0)) NOT NULL,
    [dateins]         DATETIME2 (0) DEFAULT ([dbo].[GETDATE]()) NOT NULL,
    [dateupd]         DATETIME2 (0) DEFAULT ([dbo].[GETDATE]()) NOT NULL,
    [limitHoursUntil] DATETIME2 (0) DEFAULT ('1970-01-01 00:00:00') NOT NULL,
    CONSTRAINT [PK_schtimes_tl_id] PRIMARY KEY CLUSTERED ([id] ASC),
    CONSTRAINT [schtimes_tl$datesch] UNIQUE NONCLUSTERED ([datesch] ASC, [idprogr] ASC)
);


GO
CREATE NONCLUSTERED INDEX [idprogr]
    ON [dbo].[schtimes_tl]([idprogr] ASC, [datesch] ASC);


GO
ALTER INDEX [idprogr]
    ON [dbo].[schtimes_tl] DISABLE;

