CREATE TABLE [dbo].[SEX] (
    [IDSEX]   CHAR (1)         NOT NULL,
    [NAME]    VARCHAR (10)     NOT NULL,
    [VISIBLE] CHAR (1)         NOT NULL,
    [ROWID]   UNIQUEIDENTIFIER DEFAULT (newid()) NOT NULL,
    CONSTRAINT [SYS_C0013147] PRIMARY KEY CLUSTERED ([IDSEX] ASC)
);


GO
CREATE UNIQUE NONCLUSTERED INDEX [ROWID$INDEX]
    ON [dbo].[SEX]([ROWID] ASC);


GO
