CREATE TABLE [dbo].[TELEPHONESERVICETYPE] (
    [ID]      NUMERIC (20)  NOT NULL,
    [NAME]    VARCHAR (100) NOT NULL,
    [VISIBLE] CHAR (1)      DEFAULT ('Y') NOT NULL,
    CONSTRAINT [SYS_C0013287] PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [TELEPHONESERVICETYPE_C1] CHECK ([VISIBLE]='N' OR [VISIBLE]='Y')
);

