CREATE TABLE [dbo].[TESTEDSTATUS] (
    [IDTESTEDSTATUS] NUMERIC (20)     NOT NULL,
    [NAME]           VARCHAR (500)    NOT NULL,
    [VISIBLE]        CHAR (1)         NOT NULL,
    [ROWID]          UNIQUEIDENTIFIER DEFAULT (newid()) NOT NULL,
    CONSTRAINT [SYS_C0013151] PRIMARY KEY CLUSTERED ([IDTESTEDSTATUS] ASC)
);


GO
CREATE UNIQUE NONCLUSTERED INDEX [ROWID$INDEX]
    ON [dbo].[TESTEDSTATUS]([ROWID] ASC);


GO
