CREATE TABLE [dbo].[TESTED] (
    [IDTESTED]       NUMERIC (20)     NOT NULL,
    [IDAPPLICANT]    NUMERIC (20)     NOT NULL,
    [NOTE]           VARCHAR (4000)   NOT NULL,
    [DATEFORM]       DATETIME2 (0)    NOT NULL,
    [IDTESTEDTYPE]   NUMERIC (20)     NOT NULL,
    [IDTESTEDSTATUS] NUMERIC (20)     NOT NULL,
    [DATECREATED]    DATETIME2 (0)    NOT NULL,
    [IDUSER]         NUMERIC (20)     NOT NULL,
    [ROWID]          UNIQUEIDENTIFIER DEFAULT (newid()) NOT NULL,
    CONSTRAINT [SYS_C0013150] PRIMARY KEY CLUSTERED ([IDTESTED] ASC),
    CONSTRAINT [SYS_C0013586] FOREIGN KEY ([IDUSER]) REFERENCES [dbo].[USERS] ([IDUSER]),
    CONSTRAINT [SYS_C0013587] FOREIGN KEY ([IDTESTEDSTATUS]) REFERENCES [dbo].[TESTEDSTATUS] ([IDTESTEDSTATUS]),
    CONSTRAINT [SYS_C0013588] FOREIGN KEY ([IDTESTEDTYPE]) REFERENCES [dbo].[TESTEDTYPE] ([IDTESTEDTYPE]),
    CONSTRAINT [SYS_C0013589] FOREIGN KEY ([IDAPPLICANT]) REFERENCES [dbo].[applicant] ([IDAPPLICANT])
);






GO
CREATE NONCLUSTERED INDEX [XIF4TESTED]
    ON [dbo].[TESTED]([IDUSER] ASC);


GO
CREATE NONCLUSTERED INDEX [XIF3TESTED]
    ON [dbo].[TESTED]([IDTESTEDSTATUS] ASC);


GO
CREATE NONCLUSTERED INDEX [XIF2TESTED]
    ON [dbo].[TESTED]([IDTESTEDTYPE] ASC);


GO
CREATE NONCLUSTERED INDEX [XIF1TESTED]
    ON [dbo].[TESTED]([IDAPPLICANT] ASC);


GO
CREATE UNIQUE NONCLUSTERED INDEX [ROWID$INDEX]
    ON [dbo].[TESTED]([ROWID] ASC);


GO
