CREATE TABLE [dbo].[TIMEZONE] (
    [IDTIMEZONE]        NUMERIC (20)     NOT NULL,
    [NAME]              VARCHAR (100)    NOT NULL,
    [VISIBLE]           CHAR (1)         DEFAULT ('Y') NULL,
    [SHIFTTOGMTHOURS]   NUMERIC (20)     DEFAULT ((0)) NOT NULL,
    [SHIFTTOGMTMINUTES] NUMERIC (20)     DEFAULT ((0)) NOT NULL,
    [ROWID]             UNIQUEIDENTIFIER DEFAULT (newid()) NOT NULL,
    CONSTRAINT [SYS_C0013153] PRIMARY KEY CLUSTERED ([IDTIMEZONE] ASC)
);


GO
CREATE UNIQUE NONCLUSTERED INDEX [ROWID$INDEX]
    ON [dbo].[TIMEZONE]([ROWID] ASC);


GO
