CREATE TABLE [dbo].[tmp_APPLICANT] (
    [IDAPPLICANT]               INT              IDENTITY (1, 1) NOT NULL,
    [FIRSTNAME]                 VARCHAR (100)    NOT NULL,
    [LASTNAME]                  VARCHAR (100)    NOT NULL,
    [MAILADDR]                  VARCHAR (4000)   NOT NULL,
    [CITY]                      VARCHAR (300)    NOT NULL,
    [IDSTATE]                   CHAR (2)         NOT NULL,
    [IDCOUNTRY]                 CHAR (2)         NOT NULL,
    [ZIP]                       VARCHAR (20)     NOT NULL,
    [PHONE]                     VARCHAR (4000)   NOT NULL,
    [PHONEALT]                  VARCHAR (4000)   NOT NULL,
    [EMAIL]                     VARCHAR (1000)   NOT NULL,
    [AIMNAME]                   VARCHAR (500)    NOT NULL,
    [PASSWORD]                  VARCHAR (20)     NOT NULL,
    [IDSECRETQUESTION]          NUMERIC (20)     NOT NULL,
    [SECRETANSWER]              VARCHAR (500)    NOT NULL,
    [IDTIMEZONE]                NUMERIC (20)     NOT NULL,
    [IDMODEM]                   NUMERIC (20)     NOT NULL,
    [IDABLEOBTAINBB]            NUMERIC (20)     NOT NULL,
    [IDOPERSYSTEM]              NUMERIC (20)     NOT NULL,
    [IDABLEWIN2K]               NUMERIC (20)     NOT NULL,
    [IDOFTENUSE]                NUMERIC (20)     NOT NULL,
    [IDWORKPLACE]               NUMERIC (20)     NOT NULL,
    [HOURSWEEK]                 NUMERIC (20)     NOT NULL,
    [LANGOTHER]                 VARCHAR (4000)   NOT NULL,
    [YEARS18]                   CHAR (1)         NOT NULL,
    [WPM]                       NUMERIC (20)     NOT NULL,
    [INDACCOU]                  NUMERIC (20, 2)  NOT NULL,
    [INDADMIN]                  NUMERIC (20, 2)  NOT NULL,
    [INDCALLCEN]                NUMERIC (20, 2)  NOT NULL,
    [INDCUSTF2F]                NUMERIC (20, 2)  NOT NULL,
    [INDCUSTTEL]                NUMERIC (20, 2)  NOT NULL,
    [INDDATEENT]                NUMERIC (20, 2)  NOT NULL,
    [INDFINANC]                 NUMERIC (20, 2)  NOT NULL,
    [INDHUMRES]                 NUMERIC (20, 2)  NOT NULL,
    [INDINSURAN]                NUMERIC (20, 2)  NOT NULL,
    [INDLEGAL]                  NUMERIC (20, 2)  NOT NULL,
    [INDMEDICAL]                NUMERIC (20, 2)  NOT NULL,
    [INDMARKET]                 NUMERIC (20, 2)  NOT NULL,
    [INDMARKRES]                NUMERIC (20, 2)  NOT NULL,
    [INDPROGR]                  NUMERIC (20, 2)  NOT NULL,
    [INDPRMAN]                  NUMERIC (20, 2)  NOT NULL,
    [INDREALEST]                NUMERIC (20, 2)  NOT NULL,
    [INDRETAIL]                 NUMERIC (20, 2)  NOT NULL,
    [INDSALES]                  NUMERIC (20, 2)  NOT NULL,
    [INDTECHSUP]                NUMERIC (20, 2)  NOT NULL,
    [INDTELEMAR]                NUMERIC (20, 2)  NOT NULL,
    [INDTRANMUL]                NUMERIC (20, 2)  NOT NULL,
    [INDWEBDES]                 NUMERIC (20, 2)  NOT NULL,
    [INDOTHER]                  VARCHAR (4000)   NOT NULL,
    [IDLEVELEDUC]               NUMERIC (20)     NOT NULL,
    [OPTPROF]                   VARCHAR (4000)   NOT NULL,
    [IDHEARABOUT]               NUMERIC (20)     NOT NULL,
    [OPTREFBY]                  VARCHAR (2000)   NOT NULL,
    [IDINTEREST]                NUMERIC (20)     NOT NULL,
    [OPTMOTIV]                  VARCHAR (4000)   NOT NULL,
    [IDSEX]                     CHAR (1)         NOT NULL,
    [IDRACE]                    NUMERIC (20)     NOT NULL,
    [IDAGE]                     NUMERIC (20)     NOT NULL,
    [OPTADDINFO]                VARCHAR (4000)   NOT NULL,
    [DATECREATED]               DATETIME2 (6)    NOT NULL,
    [DATEUPDATED]               DATETIME2 (6)    NOT NULL,
    [IDAPPSTATUS]               NUMERIC (20)     NOT NULL,
    [AGENTID]                   VARCHAR (100)    NOT NULL,
    [WANTNEWSLETTER]            CHAR (1)         NOT NULL,
    [UPPER_FIRSTNAME]           VARCHAR (100)    NULL,
    [UPPER_LASTNAME]            VARCHAR (100)    NULL,
    [HIDDEN_PHONE]              VARCHAR (4000)   NULL,
    [HIDDEN_PHONEALT]           VARCHAR (4000)   NULL,
    [MIDDLINIT]                 VARCHAR (100)    NULL,
    [CORPORATNAME]              VARCHAR (4000)   NULL,
    [CORPORATNAMEPAID]          CHAR (1)         NULL,
    [W9]                        CHAR (1)         NOT NULL,
    [INDTRAVEL]                 NUMERIC (20, 2)  NOT NULL,
    [NICKNAME]                  VARCHAR (500)    NOT NULL,
    [PENDINGPURGE]              CHAR (1)         NOT NULL,
    [PENDINGPURGEDATE]          DATETIME2 (6)    NOT NULL,
    [AGENTIDENTNUM]             VARCHAR (9)      NOT NULL,
    [SFID]                      VARCHAR (50)     NULL,
    [INDCALLCENQA]              NUMERIC (20, 2)  NOT NULL,
    [REFERREDBYREWARDPAID]      CHAR (1)         NOT NULL,
    [REFERREDBYREWARDPAIDDATE]  DATETIME2 (0)    NOT NULL,
    [CORPORATEW9]               CHAR (1)         NOT NULL,
    [CORPORATEW9DATECREATED]    DATETIME2 (6)    NOT NULL,
    [PART1ASSESSMENTKEYSPEECH]  VARCHAR (250)    NOT NULL,
    [PART2ASSESSMENTKEYGENERAL] CHAR (6)         NOT NULL,
    [CONVICTED]                 CHAR (1)         NULL,
    [BIRTHDATEMMDD]             CHAR (4)         NOT NULL,
    [SSNLAST4DIGITS]            CHAR (4)         NOT NULL,
    [MOBILEPHONE]               VARCHAR (4000)   NULL,
    [HIDDEN_MOBILEPHONE]        VARCHAR (4000)   NULL,
    [MOBILETERMS]               CHAR (1)         NOT NULL,
    [INTPROVIDER]               VARCHAR (500)    NOT NULL,
    [TELPROVIDER]               VARCHAR (500)    NOT NULL,
    [OPTFIELDSTUDY]             VARCHAR (4000)   NULL,
    [TSIPADDRESS]               VARCHAR (4000)   NOT NULL,
    [TSPLATFORM]                VARCHAR (4000)   NOT NULL,
    [TSBROWSER]                 VARCHAR (4000)   NOT NULL,
    [TSRESOLUTION]              VARCHAR (4000)   NOT NULL,
    [TSDLBANDWIDTH]             VARCHAR (4000)   NOT NULL,
    [TSMICROPHONE]              CHAR (1)         NOT NULL,
    [INDDBMANAGMENT]            NUMERIC (20, 2)  NOT NULL,
    [INDWORKFROMHOME]           NUMERIC (20, 2)  NOT NULL,
    [ADDITINDUSORSKILL]         VARCHAR (4000)   NOT NULL,
    [ALLFIELDSOFSTUDY]          VARCHAR (4000)   NOT NULL,
    [PROFCERTIFICAT]            VARCHAR (4000)   NOT NULL,
    [WHATMOTIVATESYOU]          VARCHAR (4000)   NOT NULL,
    [TELLUSMORE]                VARCHAR (4000)   NOT NULL,
    [MILITARY_MEMBER_ID]        NUMERIC (20)     NOT NULL,
    [IDTELEPHONESERVICETYPE]    NUMERIC (20)     NOT NULL,
    [IDHEARABOUT_DATE]          DATETIME2 (6)    NOT NULL,
    [ROWID]                     UNIQUEIDENTIFIER NOT NULL,
    CONSTRAINT [SYS_blrC0013113] PRIMARY KEY CLUSTERED ([IDAPPLICANT] ASC)
);

