CREATE TABLE [dbo].[TRAINEDON] (
    [IDTRAINEDON] NUMERIC (20)     NOT NULL,
    [NAME]        VARCHAR (500)    NOT NULL,
    [VISIBLE]     CHAR (1)         DEFAULT ('Y') NOT NULL,
    [ROWID]       UNIQUEIDENTIFIER DEFAULT (newid()) NOT NULL,
    CONSTRAINT [SYS_C0013155] PRIMARY KEY CLUSTERED ([IDTRAINEDON] ASC)
);


GO
CREATE UNIQUE NONCLUSTERED INDEX [ROWID$INDEX]
    ON [dbo].[TRAINEDON]([ROWID] ASC);


GO
