CREATE TABLE [dbo].[TYPEOFUSER] (
    [IDTYPEOFUSER]    NUMERIC (20)     NOT NULL,
    [NAME]            VARCHAR (60)     NOT NULL,
    [FULLDESCR]       VARCHAR (500)    NOT NULL,
    [SEE_SEARCH]      CHAR (1)         NOT NULL,
    [SEE_PROJECTS]    CHAR (1)         NOT NULL,
    [SEE_REPORTS]     CHAR (1)         NOT NULL,
    [SEE_USERS]       CHAR (1)         NOT NULL,
    [LASTVISPERSONAL] CHAR (1)         NOT NULL,
    [CREATED]         DATETIME2 (6)    NOT NULL,
    [ROWID]           UNIQUEIDENTIFIER DEFAULT (newid()) NOT NULL,
    CONSTRAINT [SYS_C0013156] PRIMARY KEY CLUSTERED ([IDTYPEOFUSER] ASC)
);



GO
CREATE UNIQUE NONCLUSTERED INDEX [ROWID$INDEX]
    ON [dbo].[TYPEOFUSER]([ROWID] ASC);


GO
