CREATE TABLE [dbo].[USERS] (
    [IDUSER]       NUMERIC (20)     NOT NULL,
    [USERNAME]     VARCHAR (20)     NOT NULL,
    [USERPASS]     VARCHAR (20)     NOT NULL,
    [FIRSTNAME]    VARCHAR (100)    NOT NULL,
    [LASTNAME]     VARCHAR (100)    NOT NULL,
    [USEREMAIL]    VARCHAR (500)    NOT NULL,
    [USERCREATED]  DATETIME2 (6)    NOT NULL,
    [ISADMIN]      CHAR (1)         NOT NULL,
    [ISDELETED]    CHAR (1)         NOT NULL,
    [ISLOCKED]     CHAR (1)         NOT NULL,
    [IDGROUPS]     NUMERIC (20)     NOT NULL,
    [IDTYPEOFUSER] NUMERIC (20)     NOT NULL,
    [ROWID]        UNIQUEIDENTIFIER DEFAULT (newid()) NOT NULL,
    CONSTRAINT [SYS_C0013157] PRIMARY KEY CLUSTERED ([IDUSER] ASC),
    CONSTRAINT [SYS_C0013386] FOREIGN KEY ([IDTYPEOFUSER]) REFERENCES [dbo].[TYPEOFUSER] ([IDTYPEOFUSER])
);


GO
CREATE NONCLUSTERED INDEX [XIF2USERS]
    ON [dbo].[USERS]([IDTYPEOFUSER] ASC);


GO
CREATE NONCLUSTERED INDEX [XIF1USERS]
    ON [dbo].[USERS]([IDGROUPS] ASC);


GO
CREATE NONCLUSTERED INDEX [XIE1USERS]
    ON [dbo].[USERS]([USERNAME] ASC);


GO
CREATE UNIQUE NONCLUSTERED INDEX [ROWID$INDEX]
    ON [dbo].[USERS]([ROWID] ASC);


GO
