CREATE TABLE [dbo].[W9RECORDS] (
    [IDW9RECORDS] NUMERIC (20)    NOT NULL,
    [IDAPPLICANT] NUMERIC (20)    NOT NULL,
    [IDUSER]      NUMERIC (20)    NOT NULL,
    [TYPEOFW9]    CHAR (1)        NOT NULL,
    [DATECREATED] DATETIME2 (0)   NOT NULL,
    [W9CONTENT]   VARBINARY (MAX) NULL,
    [W9FILENAME]  VARCHAR (1000)  NULL,
    [W9FILESIZE]  NUMERIC (20)    NULL,
    [W9DATE]      DATETIME2 (0)   NULL,
    CONSTRAINT [SYS_C0013260] PRIMARY KEY CLUSTERED ([IDW9RECORDS] ASC),
    CONSTRAINT [TYPEOFW9_C00] CHECK ([TYPEOFW9]='C' OR [TYPEOFW9]='I')
);


GO
CREATE NONCLUSTERED INDEX [nci_wi_W9RECORDS_E5410B4EA70003E8A27EED0B9D1CF03A]
    ON [dbo].[W9RECORDS]([IDAPPLICANT] ASC);

