CREATE TABLE [dbo].[WORKSTATIONPROFILE] (
    [ID]          NUMERIC (20)  NOT NULL,
    [IDAPPLICANT] NUMERIC (20)  NOT NULL,
    [ISMANAGER]   CHAR (1)      NOT NULL,
    [ISADMIN]     CHAR (1)      NOT NULL,
    [CREATEDAT]   DATETIME2 (0) NOT NULL,
    [CREATEDBY]   NUMERIC (20)  NULL,
    [VERSION]     NUMERIC (20)  NOT NULL,
    CONSTRAINT [SYS_C0013312] PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [WORKSTATIONPROFILE_C1] CHECK ([ISMANAGER]='N' OR [ISMANAGER]='Y'),
    CONSTRAINT [WORKSTATIONPROFILE_C2] CHECK ([ISADMIN]='N' OR [ISADMIN]='Y'),
    CONSTRAINT [WORKSTATIONPROFILE_C0] FOREIGN KEY ([IDAPPLICANT]) REFERENCES [dbo].[applicant] ([IDAPPLICANT]),
    CONSTRAINT [WORKSTATIONPROFILE_C3] FOREIGN KEY ([CREATEDBY]) REFERENCES [dbo].[applicant] ([IDAPPLICANT])
);






GO
CREATE NONCLUSTERED INDEX [WORKSTATIONPROFILE_I02]
    ON [dbo].[WORKSTATIONPROFILE]([CREATEDBY] ASC);


GO
CREATE NONCLUSTERED INDEX [WORKSTATIONPROFILE_I01]
    ON [dbo].[WORKSTATIONPROFILE]([IDAPPLICANT] ASC);


GO
CREATE NONCLUSTERED INDEX [fk_WorkstationProfile_agents2]
    ON [dbo].[WORKSTATIONPROFILE]([CREATEDBY] ASC);


GO
ALTER INDEX [fk_WorkstationProfile_agents2]
    ON [dbo].[WORKSTATIONPROFILE] DISABLE;

