CREATE TABLE [dbo].[WORKPLACE] (
    [IDWORKPLACE] NUMERIC (20)     NOT NULL,
    [NAME]        VARCHAR (500)    NOT NULL,
    [VISIBLE]     CHAR (1)         DEFAULT ('Y') NOT NULL,
    [ROWID]       UNIQUEIDENTIFIER DEFAULT (newid()) NOT NULL,
    CONSTRAINT [SYS_C0013158] PRIMARY KEY CLUSTERED ([IDWORKPLACE] ASC)
);


GO
CREATE UNIQUE NONCLUSTERED INDEX [ROWID$INDEX]
    ON [dbo].[WORKPLACE]([ROWID] ASC);


GO
