CREATE TABLE [dbo].[DATE_TIME_backup_2018data] (
    [DATE_TIME_KEY]                 INT          NOT NULL,
    [DATE_TIME_30MIN_KEY]           INT          NULL,
    [DATE_TIME_HOUR_KEY]            INT          NOT NULL,
    [DATE_TIME_DAY_KEY]             INT          NOT NULL,
    [DATE_TIME_WEEK_KEY]            INT          NOT NULL,
    [DATE_TIME_MONTH_KEY]           INT          NOT NULL,
    [DATE_TIME_QUARTER_KEY]         INT          NOT NULL,
    [DATE_TIME_YEAR_KEY]            INT          NOT NULL,
    [DATE_TIME_NEXT_KEY]            INT          NOT NULL,
    [DATE_TIME_NEXT_30MIN_KEY]      INT          NULL,
    [DATE_TIME_NEXT_HOUR_KEY]       INT          NOT NULL,
    [DATE_TIME_NEXT_DAY_KEY]        INT          NOT NULL,
    [DATE_TIME_NEXT_WEEK_KEY]       INT          NOT NULL,
    [DATE_TIME_NEXT_MONTH_KEY]      INT          NOT NULL,
    [DATE_TIME_NEXT_QUARTER_KEY]    INT          NOT NULL,
    [DATE_TIME_NEXT_YEAR_KEY]       INT          NOT NULL,
    [CREATE_AUDIT_KEY]              INT          NOT NULL,
    [UPDATE_AUDIT_KEY]              INT          NOT NULL,
    [CAL_DATE]                      DATETIME     NULL,
    [CAL_DATE_STRING]               VARCHAR (64) NULL,
    [CAL_DAY_NUM_IN_WEEK]           SMALLINT     NULL,
    [CAL_DAY_NAME]                  VARCHAR (32) NULL,
    [CAL_DAY_NUM_IN_MONTH]          SMALLINT     NULL,
    [CAL_DAY_NUM_IN_YEAR]           SMALLINT     NULL,
    [CAL_LAST_DAY_IN_WEEK]          NUMERIC (1)  NULL,
    [CAL_LAST_DAY_IN_MONTH]         NUMERIC (1)  NULL,
    [CAL_WEEK_NUM_IN_YEAR]          SMALLINT     NULL,
    [WEEK_YEAR]                     SMALLINT     NULL,
    [CAL_YEAR_WEEK_NUM]             VARCHAR (32) NULL,
    [CAL_WEEK_START_DATE]           DATETIME     NULL,
    [CAL_WEEK_END_DATE]             DATETIME     NULL,
    [CAL_MONTH_NUM_IN_YEAR]         SMALLINT     NULL,
    [CAL_MONTH_NUM_IN_YEAR_STRING]  VARCHAR (32) NULL,
    [CAL_YEAR_MONTH_DAY_NUM]        VARCHAR (32) NULL,
    [CAL_MONTH_NAME]                VARCHAR (32) NULL,
    [CAL_YEAR_MONTH]                VARCHAR (32) NULL,
    [CAL_YEAR_MONTH_NUM]            VARCHAR (32) NULL,
    [CAL_QUARTER_NUM_IN_YEAR]       SMALLINT     NULL,
    [CAL_YEAR_QUARTER]              VARCHAR (32) NULL,
    [CAL_HALF_NUM_IN_YEAR]          SMALLINT     NULL,
    [CAL_YEAR_HALF_YEAR]            VARCHAR (32) NULL,
    [CAL_YEAR_NUM]                  SMALLINT     NULL,
    [CAL_YEAR_STRING]               VARCHAR (32) NULL,
    [CAL_SHORT_YEAR_STRING]         VARCHAR (32) NULL,
    [CAL_HOUR_NUM_IN_DAY]           SMALLINT     NULL,
    [CAL_HOUR_NUM_IN_DAY_STRING]    VARCHAR (32) NULL,
    [CAL_HOUR_24_NUM_IN_DAY]        SMALLINT     NULL,
    [CAL_HOUR_24_NUM_IN_DAY_STRING] VARCHAR (32) NULL,
    [CAL_MINUTE_NUM_IN_HOUR]        SMALLINT     NULL,
    [CAL_30MINUTE_NUM_IN_HOUR]      SMALLINT     NULL,
    [LABEL_YYYY]                    VARCHAR (32) NULL,
    [LABEL_YYYY_QQ]                 VARCHAR (32) NULL,
    [LABEL_YYYY_MM]                 VARCHAR (32) NULL,
    [LABEL_YYYY_WE]                 VARCHAR (32) NULL,
    [LABEL_YYYY_MM_DD]              VARCHAR (32) NULL,
    [LABEL_YYYY_MM_DD_HH]           VARCHAR (32) NULL,
    [LABEL_YYYY_MM_DD_HH24]         VARCHAR (32) NULL,
    [LABEL_YYYY_MM_DD_HH_30MI]      VARCHAR (32) NULL,
    [LABEL_YYYY_MM_DD_HH24_30MI]    VARCHAR (32) NULL,
    [LABEL_YYYY_MM_DD_HH_MI]        VARCHAR (32) NULL,
    [LABEL_YYYY_MM_DD_HH24_MI]      VARCHAR (32) NULL,
    [LABEL_YYYY_MM_DD_HH_15INT]     VARCHAR (32) NULL,
    [LABEL_YYYY_MM_DD_HH24_15INT]   VARCHAR (32) NULL,
    [LABEL_YYYY_MM_DD_HH_30INT]     VARCHAR (32) NULL,
    [LABEL_YYYY_MM_DD_HH24_30INT]   VARCHAR (32) NULL,
    [LABEL_QQ]                      VARCHAR (32) NULL,
    [LABEL_MM]                      VARCHAR (32) NULL,
    [LABEL_WE]                      VARCHAR (32) NULL,
    [LABEL_DD]                      VARCHAR (32) NULL,
    [LABEL_HH]                      VARCHAR (32) NULL,
    [LABEL_HH24]                    VARCHAR (32) NULL,
    [LABEL_30MI]                    VARCHAR (32) NULL,
    [LABEL_MI]                      VARCHAR (32) NULL,
    [TIME_INTERVAL_15_MINUTE]       VARCHAR (16) NULL,
    [TIME_INTERVAL_30_MINUTE]       VARCHAR (16) NULL,
    [TIME_INTERVAL_60_MINUTE]       VARCHAR (16) NULL,
    [TIME_INTERVAL_15_MINUTE_NUM]   INT          NULL,
    [TIME_INTERVAL_30_MINUTE_NUM]   INT          NULL,
    [TIME_INTERVAL_60_MINUTE_NUM]   INT          NULL,
    [AMPM_INDICATOR]                VARCHAR (4)  NULL,
    [RUNNING_YEAR_NUM]              INT          NULL,
    [RUNNING_QUARTER_NUM]           INT          NULL,
    [RUNNING_MONTH_NUM]             INT          NULL,
    [RUNNING_WEEK_NUM]              INT          NULL,
    [RUNNING_DAY_NUM]               INT          NULL,
    [RUNNING_HOUR_NUM]              INT          NULL,
    [RUNNING_30MIN_NUM]             INT          NULL,
    [GMT_ROW_CREATED_TIME]          DATETIME     NULL,
    [GMT_ROW_UPDATED_TIME]          DATETIME     NULL,
    [PURGE_FLAG]                    NUMERIC (1)  NULL,
    [ID]                            INT          NOT NULL
);

