CREATE TABLE [dbo].[WSOL_TB_IMPORTS_VYNE_PATS_ACCESS_0_Audit] (
    [FF_OFFICIAL_ACL_FIRST_NAME]  VARCHAR (50)  NULL,
    [FF_OFFICIAL_ACL_LAST_NAME]   VARCHAR (50)  NULL,
    [FF_OFFICIAL_CORPORATE_NAME]  VARCHAR (200) NULL,
    [FF_AGENT_ID]                 VARCHAR (50)  NULL,
    [FF_IDENTIFICATION_NUMBER]    VARCHAR (50)  NOT NULL,
    [FF_OVERALL_CATS_STATUS_CODE] VARCHAR (100) NULL,
    [FF_PRIMARY_PHONE]            VARCHAR (500) NULL,
    [FF_MOBILE_PHONE]             VARCHAR (50)  NULL,
    [FF_MOBILE_TERMS]             VARCHAR (50)  NULL,
    [FF_USERNAME]                 VARCHAR (100) NULL,
    [FF_PASSWORD]                 VARCHAR (50)  NULL,
    [FF_PROGRAM]                  VARCHAR (50)  NULL,
    [FF_GROUP]                    VARCHAR (50)  NULL,
    [FF_PATS_ROSTER_NUMBER]       VARCHAR (50)  NULL,
    [FF_TYPE_OF_PREP]             VARCHAR (50)  NULL,
    [FF_TRAINER]                  VARCHAR (50)  NULL,
    [FF_START_DATE]               VARCHAR (50)  NULL,
    [FF_END_DATE]                 VARCHAR (50)  NULL,
    [FF_COMPLETION_STATUS]        VARCHAR (50)  NULL,
    [FF_REASON_CODE]              VARCHAR (50)  NULL,
    [FF_DOB]                      VARCHAR (50)  NULL,
    [FF_SSN]                      VARCHAR (50)  NULL,
    [FF_PATS_ROSTER_STATUS]       VARCHAR (50)  NULL,
    [FF_STREET_ADDRESS]           VARCHAR (500) NULL,
    [FF_CITY]                     VARCHAR (50)  NULL,
    [FF_STATE_PROVINCE]           VARCHAR (50)  NULL,
    [FF_ZIP]                      VARCHAR (50)  NULL,
    [FF_COUNTRY]                  VARCHAR (50)  NULL,
    [FF_C_NAME]                   VARCHAR (200) NULL,
    [SEQNO_ADDED_TIME]            DATETIME      NOT NULL,
    [SEQNO]                       INT           NOT NULL,
    [FTP_FILE_NAME]               VARCHAR (100) NOT NULL,
    [ID]                          INT           IDENTITY (1, 1) NOT NULL,
    CONSTRAINT [PK_WSOL_TB_IMPORTS_VYNE_PATS_ACCESS_0_Audit] PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [UQC_WSOL_TB_IMPORTS_VYNE_PATS_ACCESS_0_Audit] UNIQUE NONCLUSTERED ([SEQNO_ADDED_TIME] ASC, [SEQNO] ASC, [FTP_FILE_NAME] ASC)
);

