CREATE TABLE [dbo].[WSOL_TB_IMPORTS_MONAT_INVOICING_1] (
    [FF_AGENT_NAME]                  VARCHAR (200)   NULL,
    [FF_DATE]                        VARCHAR (50)    NULL,
    [FF_TIME]                        VARCHAR (50)    NULL,
    [FF_BUSINESS_UNIT]               VARCHAR (100)   NULL,
    [FF_TEAM]                        VARCHAR (100)   NULL,
    [FF_GROUPS]                      VARCHAR (50)    NULL,
    [FF_ANSWERED_SESSIONS]           VARCHAR (50)    NULL,
    [FF_RONAS]                       VARCHAR (50)    NULL,
    [FF_DIDS]                        VARCHAR (50)    NULL,
    [FF_DODS]                        VARCHAR (50)    NULL,
    [FF_STARTED_IMS]                 VARCHAR (50)    NULL,
    [FF_STARTED_CALLS]               VARCHAR (50)    NULL,
    [FF_ESCALATIONS]                 VARCHAR (50)    NULL,
    [FF_CONSULTS]                    VARCHAR (50)    NULL,
    [FF_TRANSFERS]                   VARCHAR (50)    NULL,
    [FF_SUPERVISOR_JOINS]            VARCHAR (50)    NULL,
    [FF_AVAILABLE_TIME]              VARCHAR (50)    NULL,
    [FF_RINGING_TIME1]               VARCHAR (50)    NULL,
    [FF_CONNECT_IM_SESSION_TIME]     VARCHAR (50)    NULL,
    [FF_CONNECT_PHONE_CALL_TIME]     VARCHAR (50)    NULL,
    [FF_CONNECT_DID_CALL_TIME]       VARCHAR (50)    NULL,
    [FF_CONNECT_DOD_CALL_TIME]       VARCHAR (50)    NULL,
    [FF_NON_CONNECT_CALL_TIME]       VARCHAR (50)    NULL,
    [FF_AFTERCALL_TIME]              VARCHAR (50)    NULL,
    [FF_RONA_TIME]                   VARCHAR (50)    NULL,
    [FF_UNAVAILABLE_TIME]            VARCHAR (50)    NULL,
    [FF_OFF_WORK_TIME]               VARCHAR (50)    NULL,
    [FF_LOGGED_OUT_TIME]             VARCHAR (50)    NULL,
    [FF_ON_PHONE_TIME]               VARCHAR (50)    NULL,
    [FF_Q_ON_PHONE_TIME]             VARCHAR (50)    NULL,
    [FF_TALK_TIME]                   VARCHAR (50)    NULL,
    [FF_Q_TALK_TIME]                 VARCHAR (50)    NULL,
    [FF_HANDLE_TIME]                 VARCHAR (50)    NULL,
    [FF_Q_HANDLE_TIME]               VARCHAR (50)    NULL,
    [FF_OCC_PERCENT]                 VARCHAR (50)    NULL,
    [FF_Q_OCC_PERCENT]               VARCHAR (50)    NULL,
    [FF_TALK_PERCENT]                VARCHAR (50)    NULL,
    [FF_Q_TALK_PERCENT]              VARCHAR (50)    NULL,
    [FF_ACW_PERCENT]                 VARCHAR (50)    NULL,
    [FF_IDLE_PERCENT]                VARCHAR (50)    NULL,
    [FF_AVG_TALK_TIME_PERCENT]       VARCHAR (50)    NULL,
    [FF_AVG_Q_TALK_TIME_PERCENT]     VARCHAR (50)    NULL,
    [FF_AVG_ACW_TIME_PERCENT]        VARCHAR (50)    NULL,
    [FF_AVG_Q_ACW_TIME_PERCENT]      VARCHAR (50)    NULL,
    [FF_AVG_HANDLE_TIME_PERCENT]     VARCHAR (50)    NULL,
    [FF_AVG_Q_HANDLE_TIME_PERCENT]   VARCHAR (50)    NULL,
    [SEQNO_ADDED_TIME]               DATETIME        NOT NULL,
    [SEQNO]                          INT             NOT NULL,
    [FTP_FILE_NAME]                  VARCHAR (100)   NOT NULL,
    [DATETIME]                       DATETIME        NULL,
    [HOUR_INTERVAL]                  INT             NULL,
    [AGENT_NAME]                     VARCHAR (200)   NULL,
    [ANSWERED_SESSIONS]              INT             NULL,
    [RONA_CNT]                       INT             NULL,
    [DID_CNT]                        INT             NULL,
    [DOD_CNT]                        INT             NULL,
    [STARTED_IMS]                    INT             NULL,
    [STARTED_CALLS]                  INT             NULL,
    [ESCALATIONS]                    INT             NULL,
    [CONSULTS]                       INT             NULL,
    [TRANSFERS]                      INT             NULL,
    [SUPERVISOR_JOINS]               INT             NULL,
    [AVAILABLE_TIME]                 DECIMAL (10, 2) NULL,
    [RING_TIME]                      DECIMAL (10, 2) NULL,
    [CONNECT_IM_SESSION_TIME]        DECIMAL (10, 2) NULL,
    [CONNECT_PHONE_CALL_TIME]        DECIMAL (10, 2) NULL,
    [CONNECT_DID_CALL_TIME]          DECIMAL (10, 2) NULL,
    [CONNECT_DOD_CALL_TIME]          DECIMAL (10, 2) NULL,
    [NON_CONNECT_CALL_TIME]          DECIMAL (10, 2) NULL,
    [ACW_TIME]                       DECIMAL (10, 2) NULL,
    [RONA_TIME]                      DECIMAL (10, 2) NULL,
    [UNAVAILABLE_TIME]               DECIMAL (10, 2) NULL,
    [OFF_WORK_TIME]                  DECIMAL (10, 2) NULL,
    [LOGGED_OUT_TIME]                DECIMAL (10, 2) NULL,
    [ON_PHONE_TIME]                  DECIMAL (10, 2) NULL,
    [Q_ON_PHONE_TIME]                DECIMAL (10, 2) NULL,
    [TALK_TIME]                      DECIMAL (10, 2) NULL,
    [Q_TALK_TIME]                    DECIMAL (10, 2) NULL,
    [HANDLE_TIME]                    DECIMAL (10, 2) NULL,
    [Q_HANDLE_TIME]                  DECIMAL (10, 2) NULL,
    [CPROD]                          DECIMAL (10, 2) NULL,
    [MING]                           DECIMAL (10, 2) NULL,
    [AUT2]                           DECIMAL (10, 2) NULL,
    [EMAIL]                          VARCHAR (100)   NULL,
    [ID_EXT]                         VARCHAR (3)     NULL,
    [SCHEDULER_ACL_NAME]             VARCHAR (100)   NULL,
    [STD_TENANT_START_DATE_TIME_KEY] INT             NULL,
    [CAL_DATE]                       DATETIME        NULL,
    [TENANT_KEY]                     INT             NULL,
    [AIR_DAY_TYPE]                   VARCHAR (1)     NULL,
    [AIR_ACW_FONT_COLOR]             VARCHAR (50)    NULL,
    [MIN_GUARANTEE_MINUTES]          DECIMAL (6, 3)  NULL,
    [MIN_GUARANTEE_TYPE]             VARCHAR (50)    NULL,
    [AUTHORIZED_TO_INVOICE_TYPE]     VARCHAR (50)    NULL,
    [HAS_HOLIDAYS]                   VARCHAR (1)     NULL,
    [INCLUDE_IN_CAS]                 VARCHAR (1)     NULL,
    [READY_FOR_XML]                  VARCHAR (1)     NULL,
    [SHOW_ID_EXTS]                   VARCHAR (1)     NULL,
    [INVOICE_ID]                     VARCHAR (100)   NULL,
    [RESOURCE_NAME]                  VARCHAR (100)   NULL,
    [CATS_ID]                        VARCHAR (20)    NULL,
    [PAY_GROUP]                      INT             NULL,
    [ID]                             INT             IDENTITY (1, 1) NOT NULL,
    CONSTRAINT [PK_WSOL_TB_IMPORTS_MONAT_INVOICING_1] PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [UQC_WSOL_TB_IMPORTS_MONAT_INVOICING_1] UNIQUE NONCLUSTERED ([SEQNO_ADDED_TIME] ASC, [SEQNO] ASC, [FTP_FILE_NAME] ASC)
);

