CREATE TABLE [dbo].[WSOL_TB_IMPORTS_BRIGHT_PATTERN_INVOICING_4] (
    [FF_LOGIN_ID]                     VARCHAR (50)    NULL,
    [FF_AGENT_FIRST_NAME]             VARCHAR (50)    NULL,
    [FF_AGENT_LAST_NAME]              VARCHAR (50)    NULL,
    [FF_TEAM]                         VARCHAR (50)    NULL,
    [EVENT_DURATION_IN_INTERVAL_SECS] FLOAT (53)      NULL,
    [SEQNO_ADDED_TIME]                DATETIME        NOT NULL,
    [SEQNO]                           INT             NOT NULL,
    [FTP_FILE_NAME]                   VARCHAR (100)   NULL,
    [RESOURCE_NAME]                   VARCHAR (100)   NULL,
    [DATETIME]                        DATETIME        NULL,
    [HOUR_INTERVAL]                   INT             NULL,
    [EMPLOYEE_ID]                     VARCHAR (50)    NULL,
    [STD_TENANT_START_TIME]           DATETIME        NULL,
    [INBOUND_CALLS]                   INT             NULL,
    [OUTBOUND_CALLS]                  INT             NULL,
    [TOTAL_CALLS]                     INT             NULL,
    [LOGGED_IN_TIME]                  DECIMAL (10, 2) NULL,
    [READY_TIME]                      DECIMAL (10, 2) NULL,
    [INBOUND_VOICE_TIME]              DECIMAL (10, 2) NULL,
    [OUTBOUND_VOICE_TIME]             DECIMAL (10, 2) NULL,
    [ACW_VOICE_TIME]                  DECIMAL (10, 2) NULL,
    [NOT_READY_TIME]                  DECIMAL (10, 2) NULL,
    [NOT_READY_BREAK_TIME]            DECIMAL (10, 2) NULL,
    [NOT_READY_NO_ANSWER_TIME]        DECIMAL (10, 2) NULL,
    [SUPERVISION_TIME]                DECIMAL (10, 2) NULL,
    [UNKNOWN_TIME]                    DECIMAL (10, 2) NULL,
    [TOTAL_TALK_TIME]                 DECIMAL (10, 2) NULL,
    [TOTAL_NOT_READY_TIME]            DECIMAL (10, 2) NULL,
    [AUTHORIZED_ACW_TIME]             DECIMAL (10, 2) NULL,
    [CPROD]                           DECIMAL (10, 2) NULL,
    [MINIMUM_GUARANTEE]               DECIMAL (10, 2) NULL,
    [AUTHORIZED]                      DECIMAL (10, 2) NULL,
    [EMAIL]                           VARCHAR (100)   NULL,
    [ID_EXT]                          VARCHAR (3)     NULL,
    [SCHEDULER_ACL_NAME]              VARCHAR (100)   NULL,
    [STD_TENANT_START_DATE_TIME_KEY]  INT             NULL,
    [CAL_DATE]                        DATETIME        NULL,
    [TENANT_KEY]                      INT             NULL,
    [AIR_DAY_TYPE]                    VARCHAR (1)     NULL,
    [AIR_ACW_FONT_COLOR]              VARCHAR (50)    NULL,
    [MIN_GUARANTEE_MINUTES]           DECIMAL (6, 3)  NULL,
    [MIN_GUARANTEE_TYPE]              VARCHAR (50)    NULL,
    [AUTHORIZED_TO_INVOICE_TYPE]      VARCHAR (50)    NULL,
    [HAS_HOLIDAYS]                    VARCHAR (1)     NULL,
    [INCLUDE_IN_CAS]                  VARCHAR (1)     NULL,
    [READY_FOR_XML]                   VARCHAR (1)     NULL,
    [SHOW_ID_EXTS]                    VARCHAR (1)     NULL,
    [INVOICE_ID]                      VARCHAR (500)   NULL,
    [WS_ROW_CREATED_TIME]             DATETIME        NULL,
    [WS_ROW_UPDATED_TIME]             DATETIME        NULL,
    [ID]                              INT             IDENTITY (1, 1) NOT NULL,
    CONSTRAINT [PK_WSOL_TB_IMPORTS_BRIGHT_PATTERN_INVOICING_4] PRIMARY KEY CLUSTERED ([ID] ASC)
);

