CREATE TABLE [dbo].[WSOL_TB_IMPORTS_MONAT_INVOICING_3] (
    [FF_AGENT]                         VARCHAR (200)   NULL,
    [FF_AGENT_STATE]                   VARCHAR (200)   NULL,
    [FF_REASON_CODE]                   VARCHAR (500)   NULL,
    [EVENT_DURATION_SECS]              DECIMAL (10, 2) NULL,
    [EVENT_DURATION_IN_INTERVAL_SECS]  FLOAT (53)      NULL,
    [SEQNO_ADDED_TIME]                 DATETIME        NOT NULL,
    [SEQNO]                            INT             NOT NULL,
    [FTP_FILE_NAME]                    VARCHAR (100)   NULL,
    [RESOURCE_NAME]                    VARCHAR (100)   NULL,
    [DATETIME]                         DATETIME        NULL,
    [HOUR_INTERVAL]                    INT             NULL,
    [EMPLOYEE_ID]                      VARCHAR (50)    NULL,
    [STD_TENANT_START_TIME]            DATETIME        NULL,
    [INBOUND_CALLS]                    INT             NULL,
    [OUTBOUND_CALLS]                   INT             NULL,
    [LOGGED_IN_DUR]                    DECIMAL (10, 2) NULL,
    [AVAILABLE_DUR]                    DECIMAL (10, 2) NULL,
    [BUSY_DUR]                         DECIMAL (10, 2) NULL,
    [DIRECT_CALL_DUR]                  DECIMAL (10, 2) NULL,
    [DIRECT_OB_DIAL_DUR]               DECIMAL (10, 2) NULL,
    [OFF_WORK_DUR]                     DECIMAL (10, 2) NULL,
    [UNKNOWN_DUR]                      DECIMAL (10, 2) NULL,
    [RONA_DUR]                         DECIMAL (10, 2) NULL,
    [RONA_SPECIAL_PROJECT_DUR]         DECIMAL (10, 2) NULL,
    [RONA_SYSTEM_ISSUES_IT_DUR]        DECIMAL (10, 2) NULL,
    [RONA_IDLE_DUR]                    DECIMAL (10, 2) NULL,
    [RONA_CALL_BACK_DUR]               DECIMAL (10, 2) NULL,
    [INCALL_DUR]                       DECIMAL (10, 2) NULL,
    [INCALL_IDLE_DUR]                  DECIMAL (10, 2) NULL,
    [INCALL_CALL_BACK_DUR]             DECIMAL (10, 2) NULL,
    [INCALL_SPECIAL_PROJECT_DUR]       DECIMAL (10, 2) NULL,
    [INCALL_ON_BREAK_DUR]              DECIMAL (10, 2) NULL,
    [ACW_DUR]                          DECIMAL (10, 2) NULL,
    [ACW_ON_BREAK_DUR]                 DECIMAL (10, 2) NULL,
    [ACW_CALL_BACK_DUR]                DECIMAL (10, 2) NULL,
    [ACW_IDLE_DUR]                     DECIMAL (10, 2) NULL,
    [ACW_SPECIAL_PROJECT_DUR]          DECIMAL (10, 2) NULL,
    [ACW_FLOOR_SUPPORT_DUR]            DECIMAL (10, 2) NULL,
    [ACW_SYSTEM_ISSUES_IT_DUR]         DECIMAL (10, 2) NULL,
    [RING_DUR]                         DECIMAL (10, 2) NULL,
    [RING_BREAK_DUR]                   DECIMAL (10, 2) NULL,
    [RING_SPECIAL_PROJECT_DUR]         DECIMAL (10, 2) NULL,
    [RING_IDLE_DUR]                    DECIMAL (10, 2) NULL,
    [RING_SYSTEM_ISSUES_IT_DUR]        DECIMAL (10, 2) NULL,
    [RING_CALL_BACK_DUR]               DECIMAL (10, 2) NULL,
    [UNAVAILABLE_DUR]                  DECIMAL (10, 2) NULL,
    [UNAVAILABLE_ON_BREAK_DUR]         DECIMAL (10, 2) NULL,
    [UNAVAILABLE_CALL_BACK_DUR]        DECIMAL (10, 2) NULL,
    [UNAVAILABLE_IDLE_DUR]             DECIMAL (10, 2) NULL,
    [UNAVAILABLE_PERSONAL_TIME_DUR]    DECIMAL (10, 2) NULL,
    [UNAVAILABLE_RR_DUR]               DECIMAL (10, 2) NULL,
    [UNAVAILABLE_SPECIAL_PROJECT_DUR]  DECIMAL (10, 2) NULL,
    [UNAVAILABLE_FLOOR_SUPPORT_DUR]    DECIMAL (10, 2) NULL,
    [UNAVAILABLE_SYSTEM_ISSUES_IT_DUR] DECIMAL (10, 2) NULL,
    [UNAVAILABLE_EMAIL_DUR]            DECIMAL (10, 2) NULL,
    [WS_ROW_CREATED_TIME]              DATETIME        NULL,
    [WS_ROW_UPDATED_TIME]              DATETIME        NULL,
    [ID]                               INT             IDENTITY (1, 1) NOT NULL,
    CONSTRAINT [PK_WSOL_TB_IMPORTS_MONAT_INVOICING_3] PRIMARY KEY CLUSTERED ([ID] ASC)
);

