CREATE TABLE [dbo].[WSOL_TB_IMPORTS_STUBHUB_CHAT_PERFORMANCE_0_Audit] (
    [FF_DATE]                   VARCHAR (300) NULL,
    [FF_LOGIN]                  VARCHAR (50)  NULL,
    [FF_DEPARTMENT]             VARCHAR (50)  NULL,
    [FF_NO_CHATS_TAKEN]         VARCHAR (50)  NULL,
    [FF_AVG_SESSION_TIME]       VARCHAR (50)  NULL,
    [FF_CHAT_AVG_HANDLE_TIME]   VARCHAR (50)  NULL,
    [FF_AVG_RESPONSE_TIME]      VARCHAR (50)  NULL,
    [FF_AVG_EXCHANGES_PER_CHAT] VARCHAR (50)  NULL,
    [FF_TOTAL_WORK_TIME]        VARCHAR (50)  NULL,
    [FF_CONCURRENCY_RATE]       VARCHAR (50)  NULL,
    [FF_CPH_PRIOR_9_1]          VARCHAR (50)  NULL,
    [FF_WORKING_TIME]           VARCHAR (50)  NULL,
    [FF_CHAT_AVG_WRAP_TIME]     VARCHAR (50)  NULL,
    [FF_PDA_CHAT_TIME]          VARCHAR (50)  NULL,
    [FF_CPH_9_1_FORWARD]        VARCHAR (50)  NULL,
    [FF_TOTAL_HANDLE_TIME]      VARCHAR (50)  NULL,
    [SEQNO_ADDED_TIME]          DATETIME      NOT NULL,
    [SEQNO]                     INT           NOT NULL,
    [FTP_FILE_NAME]             VARCHAR (100) NOT NULL,
    [ID]                        INT           IDENTITY (1, 1) NOT NULL,
    CONSTRAINT [PK_WSOL_TB_IMPORTS_STUBHUB_CHAT_PERFORMANCE_0_Audit] PRIMARY KEY CLUSTERED ([ID] ASC)
);

