CREATE TABLE [dbo].[WSOL_TB_IMPORTS_EGENCIA_ASPECT_EXCEPTIONS] (
    [FF_REPORT_DATE]                 VARCHAR (50)  NULL,
    [FF_REPORT_NAME]                 VARCHAR (50)  NULL,
    [FF_RUN_DATES]                   VARCHAR (50)  NULL,
    [FF_EMPLOYEE_GROUP]              VARCHAR (50)  NULL,
    [FF_NOMINAL_DATE]                VARCHAR (50)  NULL,
    [FF_CODE]                        VARCHAR (50)  NULL,
    [FF_HEADER_01]                   VARCHAR (50)  NULL,
    [FF_HEADER_02]                   VARCHAR (50)  NULL,
    [FF_HEADER_03]                   VARCHAR (50)  NULL,
    [FF_HEADER_04]                   VARCHAR (50)  NULL,
    [FF_HEADER_05]                   VARCHAR (50)  NULL,
    [FF_EMPLOYEE_NAME]               VARCHAR (50)  NULL,
    [FF_START_TIME]                  VARCHAR (50)  NULL,
    [FF_EXCEEDS_DATE]                VARCHAR (50)  NULL,
    [FF_STOP_TIME]                   VARCHAR (50)  NULL,
    [FF_DURATION]                    VARCHAR (50)  NULL,
    [FF_MEMO]                        VARCHAR (50)  NULL,
    [FF_SYSTEM_NAME]                 VARCHAR (50)  NULL,
    [FF_PAGE_FOOTER]                 VARCHAR (50)  NULL,
    [FF_FOOTER]                      VARCHAR (50)  NULL,
    [DATA_DATE]                      DATETIME      NULL,
    [SEQNO_ADDED_TIME]               DATETIME      NOT NULL,
    [SEQNO]                          INT           NOT NULL,
    [FTP_FILE_NAME]                  VARCHAR (100) NOT NULL,
    [DATETIME]                       DATETIME      NULL,
    [HOUR_INTERVAL]                  VARCHAR (50)  NULL,
    [STD_TENANT_START_DATE_TIME_KEY] INT           NULL,
    [TENANT_KEY]                     INT           NULL,
    [RESOURCE_NAME]                  VARCHAR (100) NULL,
    [WS_ROW_CREATED_TIME]            DATETIME      NULL,
    [WS_ROW_UPDATED_TIME]            DATETIME      NULL,
    [ID]                             INT           IDENTITY (1, 1) NOT NULL,
    CONSTRAINT [PK_WSOL_TB_IMPORTS_EGENCIA_ASPECT_EXCEPTIONS] PRIMARY KEY CLUSTERED ([ID] ASC)
);

