CREATE TABLE [dbo].[WSOL_TB_IMPORTS_EGENCIA_CMS_0_Audit] (
    [FF_DATE]          VARCHAR (50)  NULL,
    [FF_LOGIN_ID]      VARCHAR (50)  NULL,
    [FF_TIME]          VARCHAR (50)  NULL,
    [FF_SPLIT_SKILL]   VARCHAR (50)  NULL,
    [FF_ACD_CALLS]     VARCHAR (50)  NULL,
    [FF_RINGTIME]      VARCHAR (50)  NULL,
    [FF_ACD_TIME]      VARCHAR (50)  NULL,
    [FF_HOLD_TIME]     VARCHAR (50)  NULL,
    [FF_HOLD_ACD_TIME] VARCHAR (50)  NULL,
    [FF_ACW_ATTACHED]  VARCHAR (50)  NULL,
    [FF_ACW_OUT_TIME]  VARCHAR (50)  NULL,
    [FF_AUX_OUT_TIME]  VARCHAR (50)  NULL,
    [FF_ACW_OUT_CALLS] VARCHAR (50)  NULL,
    [FF_AUX_OUT_CALLS] VARCHAR (50)  NULL,
    [FF_ACW_ALL]       VARCHAR (50)  NULL,
    [SEQNO_ADDED_TIME] DATETIME      NOT NULL,
    [SEQNO]            INT           NOT NULL,
    [FTP_FILE_NAME]    VARCHAR (100) NOT NULL,
    [ID]               INT           IDENTITY (1, 1) NOT NULL,
    CONSTRAINT [PK_WSOL_TB_IMPORTS_EGENCIA_CMS_0_Audit] PRIMARY KEY CLUSTERED ([ID] ASC)
);

