CREATE TABLE [dbo].[WSOL_TB_IMPORTS_EGENCIA_CMS] (
    [FF_DATE]                        VARCHAR (50)  NULL,
    [FF_LOGIN_ID]                    VARCHAR (50)  NULL,
    [FF_TIME]                        VARCHAR (50)  NULL,
    [FF_SPLIT_SKILL]                 VARCHAR (50)  NULL,
    [FF_ACD_CALLS]                   VARCHAR (50)  NULL,
    [FF_RINGTIME]                    VARCHAR (50)  NULL,
    [FF_ACD_TIME]                    VARCHAR (50)  NULL,
    [FF_HOLD_TIME]                   VARCHAR (50)  NULL,
    [FF_HOLD_ACD_TIME]               VARCHAR (50)  NULL,
    [FF_ACW_ATTACHED]                VARCHAR (50)  NULL,
    [FF_ACW_OUT_TIME]                VARCHAR (50)  NULL,
    [FF_AUX_OUT_TIME]                VARCHAR (50)  NULL,
    [FF_ACW_OUT_CALLS]               VARCHAR (50)  NULL,
    [FF_AUX_OUT_CALLS]               VARCHAR (50)  NULL,
    [FF_ACW_ALL]                     VARCHAR (50)  NULL,
    [SEQNO_ADDED_TIME]               DATETIME      NOT NULL,
    [SEQNO]                          INT           NOT NULL,
    [FTP_FILE_NAME]                  VARCHAR (100) NOT NULL,
    [DATETIME]                       DATETIME      NULL,
    [HOUR_INTERVAL]                  VARCHAR (50)  NULL,
    [STD_TENANT_START_DATE_TIME_KEY] INT           NULL,
    [TENANT_KEY]                     INT           NULL,
    [RESOURCE_NAME]                  VARCHAR (100) NULL,
    [EMAIL]                          VARCHAR (100) NULL,
    [WS_ROW_CREATED_TIME]            DATETIME      NULL,
    [WS_ROW_UPDATED_TIME]            DATETIME      NULL,
    [ID]                             INT           IDENTITY (1, 1) NOT NULL,
    CONSTRAINT [PK_WSOL_TB_IMPORTS_EGENCIA_CMS] PRIMARY KEY CLUSTERED ([ID] ASC)
);

