CREATE TABLE [dbo].[WSOL_TB_IMPORTS_GA_INVOICING_0_Audit] (
    [FF_RECORD_ID]      VARCHAR (100) NULL,
    [FF_DATE]           VARCHAR (50)  NULL,
    [FF_AGENT_ID]       VARCHAR (50)  NULL,
    [FF_AGENT_NAME]     VARCHAR (100) NULL,
    [FF_EVENT_KEY]      VARCHAR (200) NULL,
    [FF_START_TIME]     VARCHAR (50)  NULL,
    [FF_AGENT_STATE]    VARCHAR (100) NULL,
    [FF_STATE_DURATION] VARCHAR (50)  NULL,
    [SEQNO_ADDED_TIME]  DATETIME      NOT NULL,
    [SEQNO]             INT           NOT NULL,
    [FTP_FILE_NAME]     VARCHAR (100) NOT NULL,
    [ID]                INT           IDENTITY (1, 1) NOT NULL,
    CONSTRAINT [PK_WSOL_TB_IMPORTS_GA_INVOICING_0_Audit] PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [UQC_WSOL_TB_IMPORTS_GA_INVOICING_0_Audit] UNIQUE NONCLUSTERED ([SEQNO_ADDED_TIME] ASC, [SEQNO] ASC, [FTP_FILE_NAME] ASC)
);

