CREATE TABLE [dbo].[WSOL_TB_IMPORTS_SABRE_SYNXIS_1] (
    [FF_TEXTBOX56]                       VARCHAR (50)   NULL,
    [FF_CHAIN_TOTAL]                     VARCHAR (50)   NULL,
    [FF_USER]                            VARCHAR (50)   NULL,
    [FF_CHAIN]                           VARCHAR (300)  NULL,
    [FF_HOTEL]                           VARCHAR (50)   NULL,
    [FF_CRO]                             VARCHAR (2500) NULL,
    [FF_CONFIRMED_REZ]                   VARCHAR (50)   NULL,
    [FF_CONFIRMED_ROOM]                  VARCHAR (50)   NULL,
    [FF_CONFIRMED_ROOM_NIGHTS]           VARCHAR (50)   NULL,
    [FF_CONFIRMED_REVENUE]               VARCHAR (50)   NULL,
    [FF_CONFIRMED_LOS]                   VARCHAR (50)   NULL,
    [FF_CONFIRMED_ADR]                   VARCHAR (50)   NULL,
    [FF_CANCELLED_REZ]                   VARCHAR (50)   NULL,
    [FF_CANCELLED_ROOMS]                 VARCHAR (50)   NULL,
    [FF_CANCELLED_ROOMS_NIGHTS]          VARCHAR (50)   NULL,
    [FF_CANCELLED_REVENUE]               VARCHAR (50)   NULL,
    [FF_CANCELLED_LOS]                   VARCHAR (50)   NULL,
    [FF_CANCELLED_ADR]                   VARCHAR (50)   NULL,
    [FF_NET_REZ]                         VARCHAR (50)   NULL,
    [FF_NET_ROOMS]                       VARCHAR (50)   NULL,
    [FF_NET_ROOMS_NIGHTS]                VARCHAR (50)   NULL,
    [FF_NET_REVENUE]                     VARCHAR (50)   NULL,
    [FF_NET_LOS]                         VARCHAR (50)   NULL,
    [FF_NET_ADR]                         VARCHAR (50)   NULL,
    [FF_SUBTOTAL]                        VARCHAR (100)  NULL,
    [FF_SUBTOTAL_CONFIRMED_REZ]          VARCHAR (50)   NULL,
    [FF_SUBTOTAL_CONFIRMED_ROOM]         VARCHAR (50)   NULL,
    [FF_SUBTOTAL_CONFIRMED_ROOM_NIGHTS]  VARCHAR (50)   NULL,
    [FF_SUBTOTAL_CONFIRMED_REVENUE]      VARCHAR (50)   NULL,
    [FF_SUBTOTAL_CONFIRMED_LOS]          VARCHAR (50)   NULL,
    [FF_SUBTOTAL_CONFIRMED_ADR]          VARCHAR (50)   NULL,
    [FF_SUBTOTAL_CANCELLED_REZ]          VARCHAR (50)   NULL,
    [FF_SUBTOTAL_CANCELLED_ROOMS]        VARCHAR (50)   NULL,
    [FF_SUBTOTAL_CANCELLED_ROOMS_NIGHTS] VARCHAR (50)   NULL,
    [FF_SUBTOTAL_CANCELLED_REVENUE]      VARCHAR (50)   NULL,
    [FF_SUBTOTAL_CANCELLED_LOS]          VARCHAR (50)   NULL,
    [FF_SUBTOTAL_CANCELLED_ADR]          VARCHAR (50)   NULL,
    [FF_SUBTOTAL_NET_REZ]                VARCHAR (50)   NULL,
    [FF_SUBTOTAL_NET_ROOMS]              VARCHAR (50)   NULL,
    [FF_SUBTOTAL_NET_ROOMS_NIGHTS]       VARCHAR (50)   NULL,
    [FF_SUBTOTAL_NET_REVENUE]            VARCHAR (50)   NULL,
    [FF_SUBTOTAL_NET_LOS]                VARCHAR (50)   NULL,
    [FF_SUBTOTAL_NET_ADR]                VARCHAR (50)   NULL,
    [FF_CHAIN_CONFIRMED_REZ]             VARCHAR (50)   NULL,
    [FF_CHAIN_CONFIRMED_ROOM]            VARCHAR (50)   NULL,
    [FF_CHAIN_CONFIRMED_ROOM_NIGHTS]     VARCHAR (50)   NULL,
    [FF_CHAIN_CONFIRMED_REVENUE]         VARCHAR (50)   NULL,
    [FF_CHAIN_CONFIRMED_LOS]             VARCHAR (50)   NULL,
    [FF_CHAIN_CONFIRMED_ADR]             VARCHAR (50)   NULL,
    [FF_CHAIN_CANCELLED_REZ]             VARCHAR (50)   NULL,
    [FF_CHAIN_CANCELLED_ROOMS]           VARCHAR (50)   NULL,
    [FF_CHAIN_CANCELLED_ROOMS_NIGHTS]    VARCHAR (50)   NULL,
    [FF_CHAIN_CANCELLED_REVENUE]         VARCHAR (50)   NULL,
    [FF_CHAIN_CANCELLED_LOS]             VARCHAR (50)   NULL,
    [FF_CHAIN_CANCELLED_ADR]             VARCHAR (50)   NULL,
    [FF_CHAIN_NET_REZ]                   VARCHAR (50)   NULL,
    [FF_CHAIN_NET_ROOMS]                 VARCHAR (50)   NULL,
    [FF_CHAIN_NET_ROOMS_NIGHTS]          VARCHAR (50)   NULL,
    [FF_CHAIN_NET_REVENUE]               VARCHAR (50)   NULL,
    [FF_CHAIN_NET_LOS]                   VARCHAR (50)   NULL,
    [FF_CHAIN_NET_ADR]                   VARCHAR (50)   NULL,
    [FF_REPORT_CONFIRMED_REZ]            VARCHAR (50)   NULL,
    [FF_REPORT_CONFIRMED_ROOM]           VARCHAR (50)   NULL,
    [FF_REPORT_CONFIRMED_ROOM_NIGHTS]    VARCHAR (50)   NULL,
    [FF_REPORT_CONFIRMED_REVENUE]        VARCHAR (50)   NULL,
    [FF_REPORT_CONFIRMED_LOS]            VARCHAR (50)   NULL,
    [FF_REPORT_CONFIRMED_ADR]            VARCHAR (50)   NULL,
    [FF_REPORT_CANCELLED_REZ]            VARCHAR (50)   NULL,
    [FF_REPORT_CANCELLED_ROOMS]          VARCHAR (50)   NULL,
    [FF_REPORT_CANCELLED_ROOMS_NIGHTS]   VARCHAR (50)   NULL,
    [FF_REPORT_CANCELLED_REVENUE]        VARCHAR (50)   NULL,
    [FF_REPORT_CANCELLED_LOS]            VARCHAR (50)   NULL,
    [FF_REPORT_CANCELLED_ADR]            VARCHAR (50)   NULL,
    [FF_REPORT_NET_REZ]                  VARCHAR (50)   NULL,
    [FF_REPORT_NET_ROOMS]                VARCHAR (50)   NULL,
    [FF_REPORT_NET_ROOMS_NIGHTS]         VARCHAR (50)   NULL,
    [FF_REPORT_NET_REVENUE]              VARCHAR (50)   NULL,
    [FF_REPORT_NET_LOS]                  VARCHAR (50)   NULL,
    [FF_REPORT_NET_ADR]                  VARCHAR (50)   NULL,
    [DATA_DATE]                          DATETIME       NULL,
    [SEQNO_ADDED_TIME]                   DATETIME       NOT NULL,
    [SEQNO]                              INT            NOT NULL,
    [FTP_FILE_NAME]                      VARCHAR (100)  NOT NULL,
    [DATETIME]                           DATETIME       NULL,
    [HOUR_INTERVAL]                      VARCHAR (50)   NULL,
    [STD_TENANT_START_DATE_TIME_KEY]     INT            NULL,
    [TENANT_KEY]                         INT            NULL,
    [ID]                                 INT            IDENTITY (1, 1) NOT NULL,
    CONSTRAINT [PK_WSOL_TB_IMPORTS_SABRE_SYNXIS_1] PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [UQC_WSOL_TB_IMPORTS_SABRE_SYNXIS_1] UNIQUE NONCLUSTERED ([SEQNO_ADDED_TIME] ASC, [SEQNO] ASC, [FTP_FILE_NAME] ASC)
);

