CREATE TABLE [dbo].[WSOL_TB_IMPORTS_SALESFORCE_INFORMATICA_WFM] (
    [SCHEDULER_ACL]                  VARCHAR (200) NOT NULL,
    [FIELD_MAP_NAME]                 VARCHAR (100) NOT NULL,
    [PROGRAM_ID]                     INT           NOT NULL,
    [COMMON_TEAM_NAME]               VARCHAR (100) NULL,
    [FIELD_MAP_ID]                   VARCHAR (100) NOT NULL,
    [CLIENT_NAME]                    VARCHAR (200) NULL,
    [CLIENT_ID]                      INT           NOT NULL,
    [JOBCOST_ID]                     VARCHAR (50)  NULL,
    [SCHEDULED_TIME]                 INT           NOT NULL,
    [CANCELLED_TIME]                 INT           NOT NULL,
    [CONFIRMED_TIME]                 INT           NOT NULL,
    [SCHEDULED_TIME_7]               INT           NOT NULL,
    [CANCELLED_TIME_7]               INT           NOT NULL,
    [CONFIRMED_TIME_7]               INT           NOT NULL,
    [SCHEDULED_TIME_30]              INT           NOT NULL,
    [CANCELLED_TIME_30]              INT           NOT NULL,
    [CONFIRMED_TIME_30]              INT           NOT NULL,
    [RECORD_FILE_DATE]               DATETIME      NOT NULL,
    [AGENT_ID]                       VARCHAR (50)  NOT NULL,
    [FIRST_NAME]                     VARCHAR (50)  NOT NULL,
    [LAST_NAME]                      VARCHAR (50)  NOT NULL,
    [CORPORATE_NAME]                 VARCHAR (200) NULL,
    [EMAIL_ADDRESS]                  VARCHAR (200) NOT NULL,
    [PASSWORD]                       VARCHAR (50)  NOT NULL,
    [CATS_STATUS]                    VARCHAR (100) NOT NULL,
    [PRIMARY_PHONE]                  VARCHAR (50)  NULL,
    [ALTERNATE_PHONE]                VARCHAR (50)  NULL,
    [MOBILE_PHONE]                   VARCHAR (50)  NULL,
    [STREET_ADDRESS]                 VARCHAR (200) NULL,
    [CITY]                           VARCHAR (50)  NULL,
    [STATE_PROVINCE]                 VARCHAR (50)  NULL,
    [ZIP_POSTAL]                     VARCHAR (50)  NULL,
    [MOBILE_TERMS]                   INT           NULL,
    [APPLICATION_DATE]               DATETIME      NULL,
    [LAST_APP_UPDATE]                DATETIME      NULL,
    [BIRTH_MONTH_DAY]                VARCHAR (50)  NULL,
    [L4_SSN]                         VARCHAR (4)   NULL,
    [AIM_NAME]                       VARCHAR (100) NULL,
    [ID_AGENT]                       VARCHAR (50)  NULL,
    [OS]                             VARCHAR (50)  NULL,
    [DOWNLOAD_SPEED]                 VARCHAR (50)  NULL,
    [UPLOAD_SPEED]                   VARCHAR (50)  NULL,
    [INDIVIDUAL_W9]                  INT           NULL,
    [CORPORATE_W9]                   INT           NULL,
    [MARKETING_CODE]                 INT           NULL,
    [CATS_PROFILE_NAME]              VARCHAR (200) NULL,
    [NICKNAME]                       VARCHAR (100) NULL,
    [STD_TENANT_START_DATE_TIME_KEY] INT           NOT NULL,
    [SEQNO_ADDED_TIME]               DATETIME      NOT NULL,
    [SEQNO]                          INT           NOT NULL,
    [FTP_FILE_NAME]                  VARCHAR (100) NOT NULL,
    [WS_ROW_CREATED_TIME]            DATETIME      NULL,
    [WS_ROW_UPDATED_TIME]            DATETIME      NULL,
    [ID]                             INT           IDENTITY (1, 1) NOT NULL,
    CONSTRAINT [PK_WSOL_TB_IMPORTS_SALESFORCE_INFORMATICA_WFM] PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [UQC_WSOL_TB_IMPORTS_SALESFORCE_INFORMATICA_WFM] UNIQUE NONCLUSTERED ([SCHEDULER_ACL] ASC, [FIELD_MAP_NAME] ASC, [PROGRAM_ID] ASC, [FIELD_MAP_ID] ASC, [CLIENT_ID] ASC, [AGENT_ID] ASC, [EMAIL_ADDRESS] ASC, [CATS_STATUS] ASC, [STD_TENANT_START_DATE_TIME_KEY] ASC, [SEQNO_ADDED_TIME] ASC, [SEQNO] ASC, [FTP_FILE_NAME] ASC)
);

