CREATE TABLE [dbo].[WSOL_TB_IMPORTS_APFM_INVOICING_BAD_1] (
    [BAD_IMPORTS_NO]        TINYINT       NOT NULL,
    [BAD_IMPORTS_FILE_TYPE] VARCHAR (3)   NULL,
    [WS_ROW_CREATED_TIME]   DATETIME      NOT NULL,
    [FF_DATE]               VARCHAR (50)  NULL,
    [FF_HOUR]               VARCHAR (50)  NULL,
    [FF_SKILL_AVAILABILITY] VARCHAR (500) NULL,
    [FF_AGENT_NAME]         VARCHAR (100) NULL,
    [FF_STATE]              VARCHAR (50)  NULL,
    [FF_REASON_CODE]        VARCHAR (50)  NULL,
    [FF_AGENT_STATE_TIME]   VARCHAR (50)  NULL,
    [FF_TIMESTAMP]          VARCHAR (50)  NULL,
    [SEQNO_ADDED_TIME]      DATETIME      NOT NULL,
    [SEQNO]                 INT           NOT NULL,
    [FTP_FILE_NAME]         VARCHAR (100) NOT NULL,
    [ID]                    INT           IDENTITY (1, 1) NOT NULL,
    CONSTRAINT [PK_WSOL_TB_IMPORTS_APFM_INVOICING_BAD_1] PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [UQC_WSOL_TB_IMPORTS_APFM_INVOICING_BAD_1] UNIQUE NONCLUSTERED ([BAD_IMPORTS_NO] ASC, [WS_ROW_CREATED_TIME] ASC, [SEQNO_ADDED_TIME] ASC, [SEQNO] ASC, [FTP_FILE_NAME] ASC)
);

