CREATE TABLE [dbo].[WSOL_TB_IMPORTS_EGENCIA_AIA_AGENT_MAPPING] (
    [INVOICE_MAP_KEY]      VARCHAR (100) NOT NULL,
    [SKILL]                VARCHAR (50)  NOT NULL,
    [EMAIL_ADDRESS]        VARCHAR (100) NULL,
    [EFFECTIVE_DATE]       DATETIME      NULL,
    [RESOURCE_NAME]        VARCHAR (100) NULL,
    [FTP_FILE_NAME]        VARCHAR (100) NULL,
    [CST_ROW_CREATED_TIME] DATETIME      NOT NULL,
    [CST_ROW_UPDATED_TIME] DATETIME      NULL,
    [ID]                   INT           IDENTITY (1, 1) NOT NULL,
    CONSTRAINT [PK_WSOL_TB_IMPORTS_EGENCIA_AIA_AGENT_MAPPING] PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [UQC_WSOL_TB_IMPORTS_EGENCIA_AIA_AGENT_MAPPING] UNIQUE NONCLUSTERED ([RESOURCE_NAME] ASC, [SKILL] ASC, [INVOICE_MAP_KEY] ASC)
);

