CREATE TABLE [dbo].[WSOL_TB_IMPORTS_GA_INVOICING_BAD] (
    [BAD_IMPORTS_CODE]                VARCHAR (3)     NOT NULL,
    [BAD_IMPORTS_FILE_TYPE]           VARCHAR (3)     NULL,
    [FF_RECORD_ID]                    VARCHAR (100)   NULL,
    [FF_DATE]                         VARCHAR (50)    NULL,
    [FF_AGENT_ID]                     VARCHAR (50)    NULL,
    [FF_AGENT_NAME]                   VARCHAR (100)   NULL,
    [FF_EVENT_KEY]                    VARCHAR (200)   NULL,
    [FF_EVENT_START_TIME]             VARCHAR (50)    NULL,
    [FF_AGENT_STATE]                  VARCHAR (100)   NULL,
    [FF_EVENT_DURATION]               VARCHAR (50)    NULL,
    [EVENT_DURATION_SECS]             DECIMAL (10, 2) NULL,
    [EVENT_DURATION_IN_INTERVAL_SECS] FLOAT (53)      NOT NULL,
    [SEQNO_ADDED_TIME]                DATETIME        NOT NULL,
    [SEQNO]                           INT             NOT NULL,
    [FTP_FILE_NAME]                   VARCHAR (100)   NOT NULL,
    [RESOURCE_NAME]                   VARCHAR (100)   NULL,
    [DATETIME]                        DATETIME        NOT NULL,
    [HOUR_INTERVAL]                   INT             NULL,
    [EMPLOYEE_ID]                     VARCHAR (50)    NULL,
    [STD_TENANT_START_DATE_TIME_KEY]  INT             NULL,
    [LOGGED_IN_SECS]                  DECIMAL (10, 2) NULL,
    [READY_SECS]                      DECIMAL (10, 2) NULL,
    [READY_FOR_OUTBOUND_SECS]         DECIMAL (10, 2) NULL,
    [AWAY_SECS]                       DECIMAL (10, 2) NULL,
    [AWAY_BREAK_SECS]                 DECIMAL (10, 2) NULL,
    [AWAY_COMFORT_BREAK_SECS]         DECIMAL (10, 2) NULL,
    [BUSY_OUTBOUND_SECS]              DECIMAL (10, 2) NULL,
    [BUSY_INTERNAL_SECS]              DECIMAL (10, 2) NULL,
    [CALL_TRANSFERRED_SECS]           DECIMAL (10, 2) NULL,
    [WRAP_UP_AUTO_SECS]               DECIMAL (10, 2) NULL,
    [WRAP_UP_MANUAL_SECS]             DECIMAL (10, 2) NULL,
    [LOGGED_OUT_SECS]                 DECIMAL (10, 2) NULL,
    [EXTENDED_AWAY_SECS]              DECIMAL (10, 2) NULL,
    [EXTENDED_AWAY_PAPERWORK_SECS]    DECIMAL (10, 2) NULL,
    [EXTENDED_AWAY_LUNCH_SECS]        DECIMAL (10, 2) NULL,
    [EXTENDED_AWAY_TRAINING_SECS]     DECIMAL (10, 2) NULL,
    [EXTENDED_AWAY_MEETING_SECS]      DECIMAL (10, 2) NULL,
    [EXTENDED_AWAY_TEAM_MEETING_SECS] DECIMAL (10, 2) NULL,
    [TOTAL_READY_SECS]                DECIMAL (10, 2) NULL,
    [TOTAL_BUSY_SECS]                 DECIMAL (10, 2) NULL,
    [TOTAL_AWAY_SECS]                 DECIMAL (10, 2) NULL,
    [TOTAL_WRAP_SECS]                 DECIMAL (10, 2) NULL,
    [TOTAL_EXTENDED_AWAY_SECS]        DECIMAL (10, 2) NULL,
    [OUTBOUND_CALLS]                  INT             NULL,
    [CALLS_TRANSFERRED]               INT             NULL,
    [CPROD]                           DECIMAL (10, 2) NULL,
    [MINIMUM_GUARANTEE]               DECIMAL (10, 2) NULL,
    [AUTHORIZED_SECS]                 DECIMAL (10, 2) NULL,
    [EMAIL]                           VARCHAR (100)   NULL,
    [ID_EXT]                          VARCHAR (3)     NULL,
    [SCHEDULER_ACL_NAME]              VARCHAR (50)    NULL,
    [CAL_DATE]                        DATETIME        NULL,
    [TENANT_KEY]                      INT             NULL,
    [AIR_DAY_TYPE]                    VARCHAR (1)     NULL,
    [AIR_ACW_FONT_COLOR]              VARCHAR (50)    NULL,
    [MIN_GUARANTEE_RATE]              DECIMAL (6, 3)  NULL,
    [MIN_GUARANTEE_TYPE]              VARCHAR (50)    NULL,
    [AUTHORIZED_TO_INVOICE_TYPE]      VARCHAR (50)    NULL,
    [HAS_HOLIDAYS]                    VARCHAR (1)     NULL,
    [INCLUDE_IN_CAS]                  VARCHAR (1)     NULL,
    [READY_FOR_XML]                   VARCHAR (1)     NULL,
    [SHOW_ID_EXTS]                    VARCHAR (1)     NULL,
    [INVOICE_ID]                      VARCHAR (50)    NULL,
    [WS_ROW_CREATED_TIME]             DATETIME        NOT NULL,
    [WS_ROW_UPDATED_TIME]             DATETIME        NULL,
    [ID]                              INT             IDENTITY (1, 1) NOT NULL,
    CONSTRAINT [PK_WSOL_TB_IMPORTS_GA_INVOICING_BAD] PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [UQC_WSOL_TB_IMPORTS_GA_INVOICING_BAD] UNIQUE NONCLUSTERED ([BAD_IMPORTS_CODE] ASC, [SEQNO_ADDED_TIME] ASC, [SEQNO] ASC, [FTP_FILE_NAME] ASC, [DATETIME] ASC, [WS_ROW_CREATED_TIME] ASC)
);

