CREATE TABLE [dbo].[WSOL_TB_IMPORTS_EGENCIA_QA_0_Audit] (
    [FF_TYPE]                              VARCHAR (50)  NULL,
    [FF_EVALUATOR_NAME]                    VARCHAR (100) NULL,
    [FF_EVALUATION_CREATION_DATE]          VARCHAR (50)  NULL,
    [FF_EVALUATION_MODIFICATION_DATE]      VARCHAR (50)  NULL,
    [FF_EVALUATED_NAME]                    VARCHAR (100) NULL,
    [FF_SCORE]                             VARCHAR (50)  NULL,
    [FF_REQUIRES_CALIBRATION]              VARCHAR (50)  NULL,
    [FF_REVIEWED_BY_EVALUATOR]             VARCHAR (50)  NULL,
    [FF_REVIEWED_BY_AGENT]                 VARCHAR (50)  NULL,
    [FF_EVALUATION_TYPE_DESCRIPTION]       VARCHAR (50)  NULL,
    [FF_BOUND_CONTACT_START_TIME]          VARCHAR (50)  NULL,
    [FF_BOUND_INTERACTION_START_TIME]      VARCHAR (50)  NULL,
    [FF_BASIC_SCORE]                       VARCHAR (50)  NULL,
    [FF_CALIBRATION_SCORE]                 VARCHAR (50)  NULL,
    [FF_EVALUATED_AGENT_ID]                VARCHAR (50)  NULL,
    [FF_EVALUATED_FIRST_NAME]              VARCHAR (50)  NULL,
    [FF_EVALUATED_LAST_NAME]               VARCHAR (50)  NULL,
    [FF_EVALUATION_COMMENT]                VARCHAR (500) NULL,
    [FF_EVALUATION_CREATED_BY_USER_ID]     VARCHAR (50)  NULL,
    [FF_EVALUATION_ID]                     VARCHAR (50)  NULL,
    [FF_EVALUATION_SITE_ID]                VARCHAR (50)  NULL,
    [FF_EVALUATOR_FIRST_NAME]              VARCHAR (50)  NULL,
    [FF_EVALUATOR_LAST_NAME]               VARCHAR (50)  NULL,
    [FF_FORM_ID]                           VARCHAR (50)  NULL,
    [FF_FORM_NAME]                         VARCHAR (50)  NULL,
    [FF_IS_CALIBRATION]                    VARCHAR (50)  NULL,
    [FF_ITEM_ADDED_ON]                     VARCHAR (50)  NULL,
    [FF_ORIGINAL_EVALUATION_TYPE]          VARCHAR (50)  NULL,
    [FF_QPLAN_TASK_NAME]                   VARCHAR (50)  NULL,
    [FF_QUALITY_PLAN_ID]                   VARCHAR (50)  NULL,
    [FF_QUALITY_PLAN_NAME]                 VARCHAR (50)  NULL,
    [FF_SEGMENT_ID_ATTACHED_TO_EVALUATION] VARCHAR (50)  NULL,
    [SEQNO_ADDED_TIME]                     DATETIME      NOT NULL,
    [SEQNO]                                INT           NOT NULL,
    [FTP_FILE_NAME]                        VARCHAR (100) NOT NULL,
    [ID]                                   INT           IDENTITY (1, 1) NOT NULL,
    CONSTRAINT [PK_WSOL_TB_IMPORTS_EGENCIA_QA_0_Audit] PRIMARY KEY CLUSTERED ([ID] ASC)
);

