CREATE TABLE [dbo].[WSOL_TB_IMPORTS_BRIGHT_PATTERN_INVOICING_BAD] (
    [BAD_IMPORTS_CODE]                VARCHAR (3)     NOT NULL,
    [BAD_IMPORTS_FILE_TYPE]           VARCHAR (3)     NULL,
    [WS_ROW_CREATED_TIME]             DATETIME        NOT NULL,
    [FF_TIME]                         VARCHAR (50)    NULL,
    [FF_LOGIN_ID]                     VARCHAR (50)    NULL,
    [FF_AGENT_FIRST_NAME]             VARCHAR (50)    NULL,
    [FF_AGENT_LAST_NAME]              VARCHAR (50)    NULL,
    [FF_TEAM]                         VARCHAR (50)    NULL,
    [FF_ACTIVITY]                     VARCHAR (50)    NULL,
    [FF_DURATION]                     VARCHAR (50)    NULL,
    [FF_DETAIL]                       VARCHAR (50)    NULL,
    [FF_SERVICE]                      VARCHAR (200)   NULL,
    [FF_MEDIA_TYPE]                   VARCHAR (50)    NULL,
    [FF_GLOBAL_ID]                    VARCHAR (100)   NULL,
    [EVENT_START_TIME]                DATETIME        NULL,
    [EVENT_DURATION_SECS]             DECIMAL (10, 2) NULL,
    [EVENT_END_TIME]                  DATETIME        NULL,
    [INTERVAL_START_TIME]             DATETIME        NULL,
    [INTERVAL_END_TIME]               DATETIME        NULL,
    [EVENT_DURATION_IN_INTERVAL_SECS] FLOAT (53)      NULL,
    [SEQNO_ADDED_TIME]                DATETIME        NOT NULL,
    [SEQNO]                           INT             NOT NULL,
    [FTP_FILE_NAME]                   VARCHAR (100)   NOT NULL,
    [PARENT_SEQNO]                    INT             NULL,
    [ID]                              INT             IDENTITY (1, 1) NOT NULL,
    CONSTRAINT [PK_WSOL_TB_IMPORTS_BRIGHT_PATTERN_INVOICING_BAD] PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [UQC_WSOL_TB_IMPORTS_BRIGHT_PATTERN_INVOICING_BAD] UNIQUE NONCLUSTERED ([BAD_IMPORTS_CODE] ASC, [SEQNO_ADDED_TIME] ASC, [SEQNO] ASC, [FTP_FILE_NAME] ASC, [WS_ROW_CREATED_TIME] ASC, [INTERVAL_START_TIME] ASC)
);

