CREATE TABLE [dbo].[WSOL_TB_HIREIQ_CATS_IMPORT] (
    [ID]                NUMERIC (20)   NOT NULL,
    [CANDIDATEFULLNAME] VARCHAR (200)  NOT NULL,
    [CANDIDATEEMAIL]    VARCHAR (200)  NOT NULL,
    [REVIEWINGLINK]     VARCHAR (4000) NOT NULL,
    [COMPLETEDDATE]     VARCHAR (100)  NOT NULL,
    [RISKBAND]          VARCHAR (1000) NOT NULL,
    [QUIZSCORE]         VARCHAR (100)  NOT NULL,
    [WORDSPERMINUTE]    VARCHAR (100)  NOT NULL,
    [ERRORRATE]         VARCHAR (100)  NOT NULL,
    [LANGUAGEIQSCORE]   VARCHAR (100)  NOT NULL,
    [IDAPPLICANT]       NUMERIC (20)   NOT NULL,
    [CREATOR]           NUMERIC (20)   NOT NULL,
    [CREATED]           DATETIME2 (0)  NOT NULL
);

