CREATE TABLE [dbo].[WSOL_TB_IMPORTS_DAILY_SCHEDULE_0_Audit] (
    [FF_OFFICIAL_ACL_NAME] VARCHAR (200) NULL,
    [FF_ROLE]              VARCHAR (50)  NULL,
    [FF_FIELD_MAP_ID]      VARCHAR (100) NULL,
    [FF_EMAIL]             VARCHAR (100) NULL,
    [FF_AGENT_NAME]        VARCHAR (200) NOT NULL,
    [FF_SCHEDULED_HOURS]   VARCHAR (50)  NULL,
    [FF_WORKED_HOURS]      VARCHAR (50)  NULL,
    [FF_CANCELLED_HOURS]   VARCHAR (50)  NULL,
    [FF_CANCELLED_PERCENT] VARCHAR (50)  NULL,
    [SEQNO_ADDED_TIME]     DATETIME      NOT NULL,
    [SEQNO]                INT           NOT NULL,
    [FTP_FILE_NAME]        VARCHAR (100) NOT NULL,
    [ID]                   INT           IDENTITY (1, 1) NOT NULL,
    CONSTRAINT [PK_WSOL_TB_IMPORTS_DAILY_SCHEDULE_0_Audit] PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [UQC_WSOL_TB_IMPORTS_DAILY_SCHEDULE_0_Audit] UNIQUE NONCLUSTERED ([SEQNO_ADDED_TIME] ASC, [SEQNO] ASC, [FTP_FILE_NAME] ASC)
);

