CREATE TABLE [dbo].[WSOL_TB_IMPORTS_STUBHUB_CHAT_INVOICING_0_Audit] (
    [FF_LOGIN]              VARCHAR (50)  NULL,
    [FF_STATUS]             VARCHAR (50)  NULL,
    [FF_START_TIME]         VARCHAR (50)  NULL,
    [FF_END_TIME]           VARCHAR (50)  NULL,
    [FF_TOTAL_TIME_SPENT]   VARCHAR (50)  NULL,
    [FF_TIME_SPENT_SECONDS] VARCHAR (50)  NULL,
    [SEQNO_ADDED_TIME]      DATETIME      NOT NULL,
    [SEQNO]                 INT           NOT NULL,
    [FTP_FILE_NAME]         VARCHAR (100) NOT NULL,
    [ID]                    INT           IDENTITY (1, 1) NOT NULL,
    CONSTRAINT [PK_WSOL_TB_WSOL_TB_IMPORTS_STUBHUB_CHAT_INVOICING_0_Audit] PRIMARY KEY CLUSTERED ([ID] ASC)
);

