CREATE TABLE [dbo].[WSOL_TB_IMPORTS_VYNE_PATS_ACCESS_BAD] (
    [BAD_IMPORTS_NO]                 TINYINT       NOT NULL,
    [BAD_IMPORTS_FILE_TYPE]          VARCHAR (3)   NULL,
    [WS_ROW_CREATED_TIME]            DATETIME      NOT NULL,
    [FF_OFFICIAL_ACL_FIRST_NAME]     VARCHAR (50)  NULL,
    [FF_OFFICIAL_ACL_LAST_NAME]      VARCHAR (50)  NULL,
    [FF_OFFICIAL_CORPORATE_NAME]     VARCHAR (200) NULL,
    [FF_AGENT_ID]                    VARCHAR (50)  NULL,
    [FF_IDENTIFICATION_NUMBER]       VARCHAR (50)  NOT NULL,
    [FF_OVERALL_CATS_STATUS_CODE]    VARCHAR (100) NULL,
    [FF_PRIMARY_PHONE]               VARCHAR (500) NULL,
    [FF_MOBILE_PHONE]                VARCHAR (50)  NULL,
    [FF_MOBILE_TERMS]                VARCHAR (50)  NULL,
    [FF_USERNAME]                    VARCHAR (100) NULL,
    [FF_PASSWORD]                    VARCHAR (50)  NULL,
    [FF_PROGRAM]                     VARCHAR (50)  NULL,
    [FF_GROUP]                       VARCHAR (50)  NULL,
    [FF_PATS_ROSTER_NUMBER]          VARCHAR (50)  NULL,
    [FF_TYPE_OF_PREP]                VARCHAR (50)  NULL,
    [FF_TRAINER]                     VARCHAR (50)  NULL,
    [FF_START_DATE]                  VARCHAR (50)  NULL,
    [FF_END_DATE]                    VARCHAR (50)  NULL,
    [FF_COMPLETION_STATUS]           VARCHAR (50)  NULL,
    [FF_REASON_CODE]                 VARCHAR (50)  NULL,
    [FF_DOB]                         VARCHAR (50)  NULL,
    [FF_SSN]                         VARCHAR (50)  NULL,
    [FF_PATS_ROSTER_STATUS]          VARCHAR (50)  NULL,
    [FF_STREET_ADDRESS]              VARCHAR (500) NULL,
    [FF_CITY]                        VARCHAR (50)  NULL,
    [FF_STATE_PROVINCE]              VARCHAR (50)  NULL,
    [FF_ZIP]                         VARCHAR (50)  NULL,
    [FF_COUNTRY]                     VARCHAR (50)  NULL,
    [FF_C_NAME]                      VARCHAR (200) NULL,
    [SEQNO_ADDED_TIME]               DATETIME      NOT NULL,
    [SEQNO]                          INT           NOT NULL,
    [FTP_FILE_NAME]                  VARCHAR (100) NOT NULL,
    [DATETIME]                       DATETIME      NULL,
    [STD_TENANT_START_DATE_TIME_KEY] INT           NULL,
    [CAL_DATE]                       DATETIME      NULL,
    [TENANT_KEY]                     INT           NULL,
    [AGENT_FULL_NAME]                VARCHAR (100) NULL,
    [CORPORATE_NAME]                 VARCHAR (200) NULL,
    [AGENT_ID]                       VARCHAR (50)  NULL,
    [ID_NUMBER]                      VARCHAR (50)  NULL,
    [CATS_STATUS_CODE]               VARCHAR (100) NULL,
    [PRIMARY_PHONE]                  VARCHAR (500) NULL,
    [MOBILE_PHONE]                   VARCHAR (50)  NULL,
    [MOBILE_TERMS]                   VARCHAR (50)  NULL,
    [USERNAME]                       VARCHAR (100) NULL,
    [PASSWORD]                       VARCHAR (50)  NULL,
    [PROGRAM_NAME]                   VARCHAR (50)  NULL,
    [GROUP]                          VARCHAR (50)  NULL,
    [PATS_ROSTER_NUMBER]             VARCHAR (50)  NULL,
    [TYPE_OF_PREP]                   VARCHAR (50)  NULL,
    [TRAINER_NAME]                   VARCHAR (50)  NULL,
    [START_DATE]                     DATETIME      NULL,
    [END_DATE]                       DATETIME      NULL,
    [COMPLETION_STATUS]              VARCHAR (50)  NULL,
    [REASON_CODE]                    VARCHAR (50)  NULL,
    [DOB]                            VARCHAR (50)  NULL,
    [LAST_4_SSN]                     VARCHAR (50)  NULL,
    [PATS_ROSTER_STATUS]             VARCHAR (50)  NULL,
    [STREET_ADDRESS]                 VARCHAR (500) NULL,
    [CITY]                           VARCHAR (50)  NULL,
    [STATE_PROVINCE]                 VARCHAR (50)  NULL,
    [ZIP]                            VARCHAR (50)  NULL,
    [COUNTRY]                        VARCHAR (50)  NULL,
    [CATS_PROFILE_NAME]              VARCHAR (200) NULL,
    [ID]                             INT           IDENTITY (1, 1) NOT NULL,
    CONSTRAINT [PK_WSOL_TB_IMPORTS_VYNE_PATS_ACCESS_BAD] PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [UQC_WSOL_TB_IMPORTS_VYNE_PATS_ACCESS_BAD] UNIQUE NONCLUSTERED ([BAD_IMPORTS_NO] ASC, [WS_ROW_CREATED_TIME] ASC, [SEQNO_ADDED_TIME] ASC, [SEQNO] ASC, [FTP_FILE_NAME] ASC)
);

