CREATE TABLE [dbo].[WSOL_TB_IMPORTS_MONAT_AIA_AGENT_MAPPING] (
    [RESOURCE_NAME]        VARCHAR (200) NULL,
    [INVOICE_MAP_KEY]      VARCHAR (200) NOT NULL,
    [EMAIL]                VARCHAR (100) NULL,
    [INVOICE_GROUP]        VARCHAR (50)  NOT NULL,
    [PAY_GROUP]            VARCHAR (50)  NULL,
    [FTP_FILE_NAME]        VARCHAR (100) NULL,
    [CST_ROW_CREATED_TIME] DATETIME      NOT NULL,
    [CST_ROW_UPDATED_TIME] DATETIME      NULL,
    [ID]                   INT           IDENTITY (1, 1) NOT NULL,
    CONSTRAINT [PK_WSOL_TB_IMPORTS_MONAT_AIA_AGENT_MAPPING] PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [UQC_WSOL_TB_IMPORTS_MONAT_AIA_AGENT_MAPPING] UNIQUE NONCLUSTERED ([RESOURCE_NAME] ASC, [INVOICE_MAP_KEY] ASC)
);

