CREATE TABLE [dbo].[WSOL_TB_IMPORTS_SABRE_SD_INVOICE_HOLIDAYS] (
    [HOLIDAY_DATE] SMALLDATETIME NOT NULL,
    [ID]           INT           IDENTITY (1, 1) NOT NULL,
    CONSTRAINT [PK_WSOL_TB_IMPORTS_SABRE_SD_INVOICE_HOLIDAYS] PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [UQC_WSOL_TB_IMPORTS_SABRE_INVOICE_HOLIDAYS] UNIQUE NONCLUSTERED ([HOLIDAY_DATE] ASC)
);

