CREATE TABLE [dbo].[WSOL_TB_IMPORTS_EGENCIA_AIA_AGENT_MAPPING_1] (
    [INVOICE_MAP_KEY]      VARCHAR (50)  NOT NULL,
    [FF_SKILL]             VARCHAR (50)  NOT NULL,
    [FF_EMAIL_ADDRESS]     VARCHAR (100) NULL,
    [FF_EFFECTIVE_DATE]    VARCHAR (50)  NULL,
    [FF_OFFICIAL_ACL_NAME] VARCHAR (100) NULL,
    [FTP_FILE_NAME]        VARCHAR (100) NULL,
    [ID]                   INT           IDENTITY (1, 1) NOT NULL,
    CONSTRAINT [PK_WSOL_TB_IMPORTS_EGENCIA_AIA_AGENT_MAPPING_1] PRIMARY KEY CLUSTERED ([ID] ASC)
);

