CREATE TABLE [dbo].[WSOL_TB_IMPORTS_MONAT_INVOICING_0_Audit_1] (
    [FF_AGENT]            VARCHAR (200) NULL,
    [FF_STATE_START_TIME] VARCHAR (50)  NULL,
    [FF_AGENT_STATE]      VARCHAR (200) NULL,
    [FF_REASON_CODE]      VARCHAR (500) NULL,
    [FF_DURATION]         VARCHAR (50)  NULL,
    [SEQNO_ADDED_TIME]    DATETIME      NOT NULL,
    [SEQNO]               INT           NOT NULL,
    [FTP_FILE_NAME]       VARCHAR (100) NOT NULL,
    [ID]                  INT           IDENTITY (1, 1) NOT NULL,
    CONSTRAINT [PK_WSOL_TB_IMPORTS_MONAT_INVOICING_0_Audit_1] PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [UQC_WSOL_TB_IMPORTS_MONAT_INVOICING_0_Audit_1] UNIQUE NONCLUSTERED ([SEQNO_ADDED_TIME] ASC, [SEQNO] ASC, [FTP_FILE_NAME] ASC)
);

