CREATE TABLE [dbo].[WSOL_TB_IMPORTS_HUMACH_SD_INVOICE_HOLIDAYS_ADDL] (
    [HOLIDAY_DATE] DATETIME    NOT NULL,
    [ID_EXT]       VARCHAR (3) NOT NULL,
    [ID]           INT         IDENTITY (1, 1) NOT NULL,
    CONSTRAINT [PK_WSOL_TB_IMPORTS_HUMACH_SD_INVOICE_HOLIDAYS_ADDL] PRIMARY KEY CLUSTERED ([ID] ASC)
);

