CREATE TABLE [dbo].[YZ_TB_FILENAMES_FOR_SSIS] (
    [SQL_JOB_NAME]         VARCHAR (100) NOT NULL,
    [FILENM]               VARCHAR (50)  NOT NULL,
    [CST_ROW_CREATED_TIME] DATETIME      NULL,
    [ID]                   INT           IDENTITY (1, 1) NOT NULL,
    CONSTRAINT [PK_YZ_TB_FILENAMES_FOR_SSIS] PRIMARY KEY CLUSTERED ([ID] ASC)
);

