CREATE TABLE [dbo].[YZ_TB_IMPORTS_APFM_FIVE9_INVOICING_BAD] (
    [BAD_IMPORTS_NO]                 TINYINT         NOT NULL,
    [BAD_IMPORTS_FILE_TYPE]          VARCHAR (3)     NULL,
    [WS_ROW_CREATED_TIME]            DATETIME        NOT NULL,
    [FF_DATE]                        VARCHAR (50)    NULL,
    [FF_HOUR]                        VARCHAR (50)    NULL,
    [FF_SKILL_AVAILABILITY]          VARCHAR (2500)  NULL,
    [FF_AGENT_NAME]                  VARCHAR (100)   NULL,
    [FF_STATE]                       VARCHAR (50)    NULL,
    [FF_REASON_CODE]                 VARCHAR (50)    NULL,
    [FF_AGENT_STATE_TIME]            VARCHAR (50)    NULL,
    [FF_TIMESTAMP]                   VARCHAR (50)    NULL,
    [SEQNO_ADDED_TIME]               DATETIME        NOT NULL,
    [SEQNO]                          INT             NOT NULL,
    [FTP_FILE_NAME]                  VARCHAR (100)   NOT NULL,
    [RESOURCE_NAME]                  VARCHAR (100)   NULL,
    [DATETIME]                       DATETIME        NULL,
    [HOUR_INTERVAL]                  INT             NULL,
    [EMPLOYEE_ID]                    VARCHAR (50)    NULL,
    [STD_TENANT_START_TIME]          DATETIME        NULL,
    [PRESENCE_STATE]                 VARCHAR (50)    NULL,
    [NRD_RSN_NAME]                   VARCHAR (50)    NULL,
    [STATE_DUR]                      INT             NULL,
    [READY_DUR]                      INT             NULL,
    [RING_DUR]                       INT             NULL,
    [ON_CALL_DUR]                    INT             NULL,
    [ON_CALL_SILENT_DUR]             INT             NULL,
    [ACW_DUR]                        INT             NULL,
    [ON_PARK_DUR]                    INT             NULL,
    [ON_VOICEMAIL_DUR]               INT             NULL,
    [ON_PREVIEW_DUR]                 INT             NULL,
    [NRD_ACW_DUR]                    INT             NULL,
    [NRD_TASK_COMP_DUR]              INT             NULL,
    [NRD_SYSTEM_OBC_DUR]             INT             NULL,
    [ON_HOLD_DUR]                    INT             NULL,
    [NRD_TRAINING_DUR]               INT             NULL,
    [NRD_MEETING_DUR]                INT             NULL,
    [NRD_MANDATORY_REPORTING_DUR]    INT             NULL,
    [NRD_MANUAL_OBC_DUR]             INT             NULL,
    [NRD_ACW_AGENT_DUR]              INT             NULL,
    [NRD_OFFLINE_VENDOR_UNPAID_DUR]  INT             NULL,
    [NRD_REASON_4_DUR]               INT             NULL,
    [NOT_READY_BILLABLE]             INT             NULL,
    [NOT_READY_NON_BILLABLE]         INT             NULL,
    [BILLABLE_CLIENT]                INT             NULL,
    [TOTAL_TALK]                     INT             NULL,
    [TOTAL_ACW]                      INT             NULL,
    [AUTHORIZED]                     DECIMAL (10, 2) NULL,
    [EMAIL]                          VARCHAR (100)   NULL,
    [ID_EXT]                         VARCHAR (3)     NULL,
    [SCHEDULER_ACL_NAME]             VARCHAR (100)   NULL,
    [STD_TENANT_START_DATE_TIME_KEY] INT             NULL,
    [CAL_DATE]                       DATETIME        NULL,
    [TENANT_KEY]                     INT             NULL,
    [AIR_DAY_TYPE]                   VARCHAR (1)     NULL,
    [AIR_ACW_FONT_COLOR]             VARCHAR (50)    NULL,
    [MIN_GUARANTEE_RATE]             DECIMAL (6, 3)  NULL,
    [MIN_GUARANTEE_TYPE]             VARCHAR (50)    NULL,
    [AUTHORIZED_TO_INVOICE_TYPE]     VARCHAR (50)    NULL,
    [HAS_HOLIDAYS]                   VARCHAR (1)     NULL,
    [INCLUDE_IN_CAS]                 VARCHAR (1)     NULL,
    [READY_FOR_XML]                  VARCHAR (1)     NULL,
    [SHOW_ID_EXTS]                   VARCHAR (1)     NULL,
    [INVOICE_ID]                     VARCHAR (50)    NULL,
    [ID]                             INT             IDENTITY (1, 1) NOT NULL,
    CONSTRAINT [PK_YZ_TB_IMPORTS_APFM_FIVE9_INVOICING_BAD] PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [UQC_YZ_TB_IMPORTS_APFM_FIVE9_INVOICING_BAD] UNIQUE NONCLUSTERED ([BAD_IMPORTS_NO] ASC, [WS_ROW_CREATED_TIME] ASC, [SEQNO_ADDED_TIME] ASC, [SEQNO] ASC, [FTP_FILE_NAME] ASC)
);

