CREATE TABLE [dbo].[YZ_TB_IMPORTS_STUBHUB_INVOICING_1] (
    [FF_AGENT_NAME]                  VARCHAR (100)   NULL,
    [FF_USER_NAME]                   VARCHAR (50)    NULL,
    [FF_HOUR]                        VARCHAR (50)    NULL,
    [FF_ACTIVE_TIME]                 VARCHAR (50)    NULL,
    [FF_READY_TIME]                  VARCHAR (50)    NULL,
    [FF_NOT_READY_TIME]              VARCHAR (50)    NULL,
    [FF_ACCEPTED]                    VARCHAR (50)    NULL,
    [FF_INVITE_TIME]                 VARCHAR (50)    NULL,
    [FF_ENGAGE_TIME]                 VARCHAR (50)    NULL,
    [FF_HOLD_TIME]                   VARCHAR (50)    NULL,
    [FF_WRAP_TIME]                   VARCHAR (50)    NULL,
    [FF_CONSULT_RECEIVED_TIME]       VARCHAR (50)    NULL,
    [FF_TALK_TIME]                   VARCHAR (50)    NULL,
    [FF_HANDLE_TIME]                 VARCHAR (50)    NULL,
    [FF_MINIMUM_GUARANTEE]           VARCHAR (50)    NULL,
    [FF_AUTHORIZED_TO_INVOICE]       VARCHAR (50)    NULL,
    [SEQNO_ADDED_TIME]               DATETIME        NOT NULL,
    [SEQNO]                          INT             NOT NULL,
    [FTP_FILE_NAME]                  VARCHAR (100)   NOT NULL,
    [DATETIME]                       DATETIME        NULL,
    [HOUR_INTERVAL]                  INT             NULL,
    [LOGGED_IN_TIME]                 INT             NULL,
    [READY_TIME]                     INT             NULL,
    [NOT_READY_TIME]                 INT             NULL,
    [CALLS_ACCEPTED]                 INT             NULL,
    [RING_TIME]                      INT             NULL,
    [TALK_TIME]                      INT             NULL,
    [HOLD_TIME]                      INT             NULL,
    [WRAP_TIME]                      INT             NULL,
    [CONSULT_TIME]                   INT             NULL,
    [TALK_HOLD_CONSULT_TIME]         INT             NULL,
    [HANDLE_TIME]                    INT             NULL,
    [TOTAL_TALK]                     DECIMAL (10, 2) NULL,
    [CPROD]                          DECIMAL (10, 2) NULL,
    [MING]                           DECIMAL (10, 2) NULL,
    [AUT2]                           DECIMAL (10, 2) NULL,
    [EMAIL]                          VARCHAR (100)   NULL,
    [ID_EXT]                         VARCHAR (3)     NULL,
    [SCHEDULER_ACL_NAME]             VARCHAR (50)    NULL,
    [PAY_GROUP]                      INT             NULL,
    [STD_TENANT_START_DATE_TIME_KEY] INT             NULL,
    [CAL_DATE]                       DATETIME        NULL,
    [TENANT_KEY]                     INT             NULL,
    [AIR_DAY_TYPE]                   VARCHAR (1)     NULL,
    [AIR_ACW_FONT_COLOR]             VARCHAR (50)    NULL,
    [MIN_GUARANTEE_RATE]             DECIMAL (6, 3)  NULL,
    [MIN_GUARANTEE_TYPE]             VARCHAR (50)    NULL,
    [AUTHORIZED_TO_INVOICE_TYPE]     VARCHAR (50)    NULL,
    [HAS_HOLIDAYS]                   VARCHAR (1)     NULL,
    [INCLUDE_IN_CAS]                 VARCHAR (1)     NULL,
    [READY_FOR_XML]                  VARCHAR (1)     NULL,
    [SHOW_ID_EXTS]                   VARCHAR (1)     NULL,
    [INVOICE_ID]                     VARCHAR (50)    NULL,
    [RESOURCE_NAME]                  VARCHAR (100)   NULL,
    [AIRITKDUR]                      INT             NULL,
    [AIRIACDUR]                      INT             NULL,
    [ID]                             INT             IDENTITY (1, 1) NOT NULL,
    CONSTRAINT [PK_YZ_TB_IMPORTS_STUBHUB_INVOICING_1] PRIMARY KEY CLUSTERED ([ID] ASC)
);

