CREATE TABLE [dbo].[YZ_TB_IMPORTS_APFM_FIVE9_INVOICING_0_Audit] (
    [FF_DATE]               VARCHAR (50)   NULL,
    [FF_HOUR]               VARCHAR (50)   NULL,
    [FF_SKILL_AVAILABILITY] VARCHAR (2500) NULL,
    [FF_AGENT_NAME]         VARCHAR (100)  NULL,
    [FF_STATE]              VARCHAR (50)   NULL,
    [FF_REASON_CODE]        VARCHAR (50)   NULL,
    [FF_AGENT_STATE_TIME]   VARCHAR (50)   NULL,
    [FF_TIMESTAMP]          VARCHAR (50)   NULL,
    [SEQNO_ADDED_TIME]      DATETIME       NOT NULL,
    [SEQNO]                 INT            NOT NULL,
    [FTP_FILE_NAME]         VARCHAR (100)  NOT NULL,
    [ID]                    INT            IDENTITY (1, 1) NOT NULL,
    CONSTRAINT [PK_YZ_TB_IMPORTS_APFM_FIVE9_INVOICING_0_Audit] PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [UQC_YZ_TB_IMPORTS_APFM_FIVE9_INVOICING_0_Audit] UNIQUE NONCLUSTERED ([SEQNO_ADDED_TIME] ASC, [SEQNO] ASC, [FTP_FILE_NAME] ASC)
);

