CREATE TABLE [dbo].[YZ_TB_IMPORTS_DATALOT_INVOICING_XML_XFER_BONUS] (
    [INVOICE_MAP_KEY]             VARCHAR (50)    NOT NULL,
    [LOGGED_IN_HOURS]             DECIMAL (10, 3) NULL,
    [THREE_MINUTE_XFERS]          INT             NULL,
    [THREE_MINUTE_XFERS_PER_HOUR] DECIMAL (10, 3) NULL,
    [ELIGIBLE_FOR_XFER_BONUS]     VARCHAR (1)     NULL,
    [ACD_ID_EXTENSION]            VARCHAR (3)     NOT NULL,
    [ID]                          INT             IDENTITY (1, 1) NOT NULL,
    CONSTRAINT [PK_YZ_TB_IMPORTS_DATALOT_INVOICING_XML_XFER_BONUS] PRIMARY KEY CLUSTERED ([ID] ASC)
);

