CREATE TABLE [dbo].[YZ_TB_IMPORTS_DATALOT_SD_INVOICE_HOLIDAYS] (
    [HOLIDAY_DATE] SMALLDATETIME NOT NULL,
    [ID]           INT           IDENTITY (1, 1) NOT NULL,
    CONSTRAINT [PK_YZ_TB_IMPORTS_DATALOT_SD_INVOICE_HOLIDAYS] PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [UQC_YZ_TB_IMPORTS_DATALOT_INVOICE_HOLIDAYS] UNIQUE NONCLUSTERED ([HOLIDAY_DATE] ASC)
);

