CREATE TABLE [dbo].[YZ_TB_ERRORS_FOUND] (
    [TENANT_KEY]     INT            NOT NULL,
    [SUB_GROUP_NAME] VARCHAR (100)  NULL,
    [ERROR_MSG]      VARCHAR (1500) NULL,
    [ID]             INT            IDENTITY (1, 1) NOT NULL,
    CONSTRAINT [PK_YZ_TB_ERRORS_FOUND] PRIMARY KEY CLUSTERED ([ID] ASC)
);

