CREATE TABLE [dbo].[YZ_TB_IMPORTS_DATALOT_AIA_AGENT_MAPPING] (
    [RESOURCE_NAME]        VARCHAR (100) NULL,
    [EMAIL]                VARCHAR (100) NULL,
    [FF_USERNAME]          VARCHAR (50)  NULL,
    [FF_AGENT_ID]          VARCHAR (50)  NOT NULL,
    [INVOICE_MAP_KEY]      VARCHAR (50)  NOT NULL,
    [FF_RESOURCE]          VARCHAR (50)  NOT NULL,
    [FTP_FILE_NAME]        VARCHAR (100) NULL,
    [PAY_GROUP]            VARCHAR (50)  NOT NULL,
    [FF_ASA_NAME]          VARCHAR (100) NULL,
    [CST_ROW_CREATED_TIME] DATETIME      NOT NULL,
    [CST_ROW_UPDATED_TIME] DATETIME      NULL,
    [ID]                   INT           IDENTITY (1, 1) NOT NULL,
    CONSTRAINT [PK_YZ_TB_IMPORTS_DATALOT_AIA_AGENT_MAPPING] PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [UQC_YZ_TB_IMPORTS_DATALOT_AIA_AGENT_MAPPING] UNIQUE NONCLUSTERED ([INVOICE_MAP_KEY] ASC)
);

