CREATE TABLE [dbo].[YZ_TB_IMPORTS_STUBHUB_UV_ANT_AIA] (
    [PLATFORM]                           VARCHAR (50)    NULL,
    [STATUS]                             VARCHAR (50)    NULL,
    [INVOICE_MAP_KEY]                    VARCHAR (50)    NOT NULL,
    [FIELD_NAME]                         VARCHAR (50)    NULL,
    [SCHEDULER_PROJECT_ID]               VARCHAR (50)    NULL,
    [SCHEDULER_ACL_NAME]                 VARCHAR (50)    NOT NULL,
    [ACD_ID_EXTENSION]                   VARCHAR (50)    NOT NULL,
    [OFFICIAL_WSOL_CLIENT_ID]            VARCHAR (50)    NULL,
    [OFFICIAL_WSOL_CLIENT_NAME]          VARCHAR (50)    NULL,
    [OFFICIAL_ACD_CLIENT_ID]             VARCHAR (50)    NOT NULL,
    [OFFICIAL_ACD_CLIENT_NAME]           VARCHAR (50)    NULL,
    [PRIMARY_PROJECT_MANAGER_ID]         VARCHAR (150)   NULL,
    [DIRECTOR_OF_PROJECT_MANAGEMENT_ID]  VARCHAR (150)   NULL,
    [AGENT_TECHNOLOGY_MANAGER_ID]        VARCHAR (150)   NULL,
    [CONTRACTOR_SUPPORT_PATHWAY]         VARCHAR (150)   NULL,
    [INVOICE_SYSTEM_ID]                  VARCHAR (50)    NOT NULL,
    [HOLIDAY_INVOICE_ID]                 VARCHAR (50)    NOT NULL,
    [HOLIDAY]                            VARCHAR (50)    NOT NULL,
    [FILE_FORMAT_OF_PUSH]                VARCHAR (50)    NULL,
    [AGENT_PREPARATION_INVOICE_ID]       VARCHAR (50)    NULL,
    [NEW_ACL]                            VARCHAR (50)    NULL,
    [CURRENT_CATS]                       VARCHAR (50)    NULL,
    [CATS_ID]                            VARCHAR (50)    NULL,
    [PATS_ID]                            VARCHAR (50)    NULL,
    [SMART_ELIGIBLE]                     VARCHAR (50)    NULL,
    [SMART_TIER_1]                       VARCHAR (50)    NULL,
    [SMART_TIER_2]                       VARCHAR (50)    NULL,
    [SMART_TIER_3]                       VARCHAR (50)    NULL,
    [INTERVAL]                           VARCHAR (50)    NULL,
    [DATE]                               VARCHAR (50)    NULL,
    [HOD_INTERVAL]                       VARCHAR (50)    NULL,
    [AU_DK_LOGGED_IN_DURATION]           DECIMAL (10, 2) NULL,
    [AU_DK_AVAILABLE_DURATION]           DECIMAL (10, 2) NULL,
    [AU_DK_TALK_DURATION]                DECIMAL (10, 2) NULL,
    [AU_DK_IB_TALK_DURATION]             DECIMAL (10, 2) NULL,
    [AU_DK_OB_TALK_DURATION]             DECIMAL (10, 2) NULL,
    [AU_DK_CONVENTIONAL_ACW]             DECIMAL (10, 2) NULL,
    [AU_DK_NR_DURATION]                  DECIMAL (10, 2) NULL,
    [AU_DK_PSEUDO_PRODUCTIVE_DURATION]   DECIMAL (10, 2) NULL,
    [AU_DK_ADJUSTED_NR_DURATION]         DECIMAL (10, 2) NULL,
    [AU_DK_TOTAL_PRODUCTIVE_DURATION]    DECIMAL (10, 2) NULL,
    [AU_DK_WPSEUDO_PRODUCTIVE_DURATIONS] DECIMAL (10, 2) NULL,
    [AU_DK_XFER_COUNT]                   INT             NULL,
    [AU_DK_HOLD_COUNT]                   INT             NULL,
    [AU_DK_CONFERENCE_COUNT]             INT             NULL,
    [AU_DK_CONSULT_COUNT]                INT             NULL,
    [AU_DK_PUP_COUNT]                    INT             NULL,
    [AU_DK_OFFERED_COUNT]                INT             NULL,
    [AU_DK_HANDLED_COUNT]                INT             NULL,
    [AU_DK_IB_HANDLE_COUNT]              INT             NULL,
    [AU_DK_OB_HANDLE_COUNT]              INT             NULL,
    [AU_DK_RONA_COUNT]                   INT             NULL,
    [AU_DK_AWR_COUNT]                    INT             NULL,
    [MINIMUM_GUARANTEE]                  DECIMAL (10, 2) NULL,
    [AUTHORIZED_TO_INVOICE]              DECIMAL (10, 2) NULL,
    [WEEK_ENDING_DATE]                   VARCHAR (10)    NULL,
    [PAY_CYCLE_CLOSURE_DATE]             VARCHAR (10)    NULL,
    [FTP_FILE_NAME]                      VARCHAR (100)   NOT NULL,
    [EMAIL]                              VARCHAR (100)   NULL,
    [STD_TENANT_START_DATE_TIME_KEY]     INT             NOT NULL,
    [CAL_DATE]                           DATETIME        NULL,
    [TENANT_KEY]                         INT             NOT NULL,
    [AIR_DAY_TYPE]                       VARCHAR (1)     NOT NULL,
    [AIR_ACW_FONT_COLOR]                 VARCHAR (50)    NULL,
    [MIN_GUARANTEE_RATE]                 DECIMAL (6, 3)  NULL,
    [MIN_GUARANTEE_TYPE]                 VARCHAR (50)    NULL,
    [AUTHORIZED_TO_INVOICE_TYPE]         VARCHAR (50)    NULL,
    [HAS_HOLIDAYS]                       VARCHAR (1)     NULL,
    [INCLUDE_IN_CAS]                     VARCHAR (1)     NULL,
    [READY_FOR_XML]                      VARCHAR (1)     NULL,
    [SHOW_ID_EXTS]                       VARCHAR (1)     NULL,
    [INVOICE_ID]                         VARCHAR (50)    NULL,
    [RESOURCE_NAME]                      VARCHAR (100)   NULL,
    [PAY_GROUP]                          INT             NULL,
    [AIRITKDUR]                          DECIMAL (10, 2) NULL,
    [AIRIACDUR]                          DECIMAL (10, 2) NULL,
    [WS_ROW_CREATED_TIME]                DATETIME        NULL,
    [WS_ROW_UPDATED_TIME]                DATETIME        NULL,
    [ID]                                 INT             IDENTITY (1, 1) NOT NULL,
    CONSTRAINT [PK_YZ_TB_IMPORTS_STUBHUB_UV_ANT_AIA] PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [UQC_YZ_TB_IMPORTS_STUBHUB_UV_ANT_AIA] UNIQUE NONCLUSTERED ([INVOICE_MAP_KEY] ASC, [SCHEDULER_ACL_NAME] ASC, [ACD_ID_EXTENSION] ASC, [HOLIDAY] ASC, [STD_TENANT_START_DATE_TIME_KEY] ASC, [TENANT_KEY] ASC)
);

