
-----------------------------------------------------------------------------------------------------------------
--DROP STORED PROCEDURES
--these are only the ones that use the external tables or views or functions
-----------------------------------------------------------------------------------------------------------------
/****** Object:  StoredProcedure [dbo].[uspWSOL_SSRS_SCHEDULE_STAFFING_BY_PROGRAM_PROGRAMS]    Script Date: 2/20/2018 12:54:27 PM ******/
IF EXISTS(SELECT top(1)* FROM sysobjects WHERE name='uspWSOL_SSRS_SCHEDULE_STAFFING_BY_PROGRAM_PROGRAMS')
BEGIN
	DROP PROCEDURE [dbo].[uspWSOL_SSRS_SCHEDULE_STAFFING_BY_PROGRAM_PROGRAMS]
END
GO

/****** Object:  StoredProcedure [dbo].[uspWSOL_SSRS_SCHEDULE_STAFFING_BY_PROGRAM_CLIENTS]    Script Date: 2/20/2018 12:54:27 PM ******/
IF EXISTS(SELECT top(1)* FROM sysobjects WHERE name='uspWSOL_SSRS_SCHEDULE_STAFFING_BY_PROGRAM_CLIENTS')
BEGIN
	DROP PROCEDURE [dbo].[uspWSOL_SSRS_SCHEDULE_STAFFING_BY_PROGRAM_CLIENTS]
END
GO

/****** Object:  StoredProcedure [dbo].[uspWSOL_SSRS_SCHEDULE_STAFFING_BY_PROGRAM]    Script Date: 2/20/2018 12:54:27 PM ******/
IF EXISTS(SELECT top(1)* FROM sysobjects WHERE name='uspWSOL_SSRS_SCHEDULE_STAFFING_BY_PROGRAM')
BEGIN
	DROP PROCEDURE [dbo].[uspWSOL_SSRS_SCHEDULE_STAFFING_BY_PROGRAM]
END
GO

/****** Object:  StoredProcedure [dbo].[uspWSOL_SSRS_SCHEDULE_PROGRAMS]    Script Date: 2/20/2018 12:54:27 PM ******/
IF EXISTS(SELECT top(1)* FROM sysobjects WHERE name='uspWSOL_SSRS_SCHEDULE_PROGRAMS')
BEGIN
	DROP PROCEDURE [dbo].[uspWSOL_SSRS_SCHEDULE_PROGRAMS]
END
GO

/****** Object:  StoredProcedure [dbo].[uspWSOL_SSRS_SCHEDULE_DETAIL]    Script Date: 2/20/2018 12:54:27 PM ******/
IF EXISTS(SELECT top(1)* FROM sysobjects WHERE name='uspWSOL_SSRS_SCHEDULE_DETAIL')
BEGIN
	DROP PROCEDURE [dbo].[uspWSOL_SSRS_SCHEDULE_DETAIL]
END
GO

/****** Object:  StoredProcedure [dbo].[uspWSOL_SSRS_SCHEDULE_CLIENTS]    Script Date: 2/20/2018 12:54:27 PM ******/
IF EXISTS(SELECT top(1)* FROM sysobjects WHERE name='uspWSOL_SSRS_SCHEDULE_CLIENTS')
BEGIN
	DROP PROCEDURE [dbo].[uspWSOL_SSRS_SCHEDULE_CLIENTS]
END
GO

/****** Object:  StoredProcedure [dbo].[uspWSOL_SSRS_SCHEDULE_BY_INTERVAL_WITH_DATE_SCHEDULED_PROGRAMS]    Script Date: 2/20/2018 12:54:27 PM ******/
IF EXISTS(SELECT top(1)* FROM sysobjects WHERE name='uspWSOL_SSRS_SCHEDULE_BY_INTERVAL_WITH_DATE_SCHEDULED_PROGRAMS')
BEGIN
	DROP PROCEDURE [dbo].[uspWSOL_SSRS_SCHEDULE_BY_INTERVAL_WITH_DATE_SCHEDULED_PROGRAMS]
END
GO

/****** Object:  StoredProcedure [dbo].[uspWSOL_SSRS_SCHEDULE_BY_INTERVAL_WITH_DATE_SCHEDULED_CLIENTS]    Script Date: 2/20/2018 12:54:27 PM ******/
IF EXISTS(SELECT top(1)* FROM sysobjects WHERE name='uspWSOL_SSRS_SCHEDULE_BY_INTERVAL_WITH_DATE_SCHEDULED_CLIENTS')
BEGIN
	DROP PROCEDURE [dbo].[uspWSOL_SSRS_SCHEDULE_BY_INTERVAL_WITH_DATE_SCHEDULED_CLIENTS]
END
GO

/****** Object:  StoredProcedure [dbo].[uspWSOL_SSRS_SCHEDULE_BY_INTERVAL_WITH_DATE_SCHEDULED]    Script Date: 2/20/2018 12:54:27 PM ******/
IF EXISTS(SELECT top(1)* FROM sysobjects WHERE name='uspWSOL_SSRS_SCHEDULE_BY_INTERVAL_WITH_DATE_SCHEDULED')
BEGIN
	DROP PROCEDURE [dbo].[uspWSOL_SSRS_SCHEDULE_BY_INTERVAL_WITH_DATE_SCHEDULED]
END
GO

/****** Object:  StoredProcedure [dbo].[uspWSOL_SSRS_SCHEDULE_ADHERENCE_WORK_ADHERENCE_CLIENTS]    Script Date: 2/20/2018 12:54:27 PM ******/
IF EXISTS(SELECT top(1)* FROM sysobjects WHERE name='uspWSOL_SSRS_SCHEDULE_ADHERENCE_WORK_ADHERENCE_CLIENTS')
BEGIN
	DROP PROCEDURE [dbo].[uspWSOL_SSRS_SCHEDULE_ADHERENCE_WORK_ADHERENCE_CLIENTS]
END
GO

/****** Object:  StoredProcedure [dbo].[uspWSOL_SSRS_SCHEDULE_ADHERENCE_WORK_ADHERENCE]    Script Date: 2/20/2018 12:54:27 PM ******/
IF EXISTS(SELECT top(1)* FROM sysobjects WHERE name='uspWSOL_SSRS_SCHEDULE_ADHERENCE_WORK_ADHERENCE')
BEGIN
	DROP PROCEDURE [dbo].[uspWSOL_SSRS_SCHEDULE_ADHERENCE_WORK_ADHERENCE]
END
GO

/****** Object:  StoredProcedure [dbo].[uspWSOL_SSRS_SATS_SCANNER_DETAILS]    Script Date: 2/20/2018 12:54:27 PM ******/
IF EXISTS(SELECT top(1)* FROM sysobjects WHERE name='uspWSOL_SSRS_SATS_SCANNER_DETAILS')
BEGIN
	DROP PROCEDURE [dbo].[uspWSOL_SSRS_SATS_SCANNER_DETAILS]
END
GO

/****** Object:  StoredProcedure [dbo].[uspWSOL_SSRS_SATS_SCANNER_CLIENTS]    Script Date: 2/20/2018 12:54:27 PM ******/
IF EXISTS(SELECT top(1)* FROM sysobjects WHERE name='uspWSOL_SSRS_SATS_SCANNER_CLIENTS')
BEGIN
	DROP PROCEDURE [dbo].[uspWSOL_SSRS_SATS_SCANNER_CLIENTS]
END
GO

/****** Object:  StoredProcedure [dbo].[uspWSOL_SSRS_SATS_SCANNER_AGENT_STATUSES]    Script Date: 2/20/2018 12:54:27 PM ******/
IF EXISTS(SELECT top(1)* FROM sysobjects WHERE name='uspWSOL_SSRS_SATS_SCANNER_AGENT_STATUSES')
BEGIN
	DROP PROCEDURE [dbo].[uspWSOL_SSRS_SATS_SCANNER_AGENT_STATUSES]
END
GO

/****** Object:  StoredProcedure [dbo].[uspWSOL_SSRS_NAME_ADDRESS_UPDATES]    Script Date: 2/20/2018 12:54:27 PM ******/
IF EXISTS(SELECT top(1)* FROM sysobjects WHERE name='uspWSOL_SSRS_NAME_ADDRESS_UPDATES')
BEGIN
	DROP PROCEDURE [dbo].[uspWSOL_SSRS_NAME_ADDRESS_UPDATES]
END
GO

/****** Object:  StoredProcedure [dbo].[uspWSOL_SSRS_AUTO_INVOICE_UNACCEPTED_INVOICES_PROJECTS]    Script Date: 2/20/2018 12:54:27 PM ******/
IF EXISTS(SELECT top(1)* FROM sysobjects WHERE name='uspWSOL_SSRS_AUTO_INVOICE_UNACCEPTED_INVOICES_PROJECTS')
BEGIN
	DROP PROCEDURE [dbo].[uspWSOL_SSRS_AUTO_INVOICE_UNACCEPTED_INVOICES_PROJECTS]
END
GO

/****** Object:  StoredProcedure [dbo].[uspWSOL_SSRS_AUTO_INVOICE_UNACCEPTED_INVOICES_CLIENTS]    Script Date: 2/20/2018 12:54:27 PM ******/
IF EXISTS(SELECT top(1)* FROM sysobjects WHERE name='uspWSOL_SSRS_AUTO_INVOICE_UNACCEPTED_INVOICES_CLIENTS')
BEGIN
	DROP PROCEDURE [dbo].[uspWSOL_SSRS_AUTO_INVOICE_UNACCEPTED_INVOICES_CLIENTS]
END
GO

/****** Object:  StoredProcedure [dbo].[uspWSOL_SSRS_AUTO_INVOICE_UNACCEPTED_INVOICES]    Script Date: 2/20/2018 12:54:27 PM ******/
IF EXISTS(SELECT top(1)* FROM sysobjects WHERE name='uspWSOL_SSRS_AUTO_INVOICE_UNACCEPTED_INVOICES')
BEGIN
	DROP PROCEDURE [dbo].[uspWSOL_SSRS_AUTO_INVOICE_UNACCEPTED_INVOICES]
END
GO

/****** Object:  StoredProcedure [dbo].[uspWSOL_SSRS_AGENT_TENURE]    Script Date: 2/20/2018 12:54:27 PM ******/
IF EXISTS(SELECT top(1)* FROM sysobjects WHERE name='uspWSOL_SSRS_AGENT_TENURE')
BEGIN
	DROP PROCEDURE [dbo].[uspWSOL_SSRS_AGENT_TENURE]
END
GO

/****** Object:  StoredProcedure [dbo].[uspWSOL_SSRS_AGENT_DETAILS_STATUSES]    Script Date: 2/20/2018 12:54:27 PM ******/
IF EXISTS(SELECT top(1)* FROM sysobjects WHERE name='uspWSOL_SSRS_AGENT_DETAILS_STATUSES')
BEGIN
	DROP PROCEDURE [dbo].[uspWSOL_SSRS_AGENT_DETAILS_STATUSES]
END
GO

/****** Object:  StoredProcedure [dbo].[uspWSOL_SSRS_AGENT_DETAILS_STATES]    Script Date: 2/20/2018 12:54:27 PM ******/
IF EXISTS(SELECT top(1)* FROM sysobjects WHERE name='uspWSOL_SSRS_AGENT_DETAILS_STATES')
BEGIN
	DROP PROCEDURE [dbo].[uspWSOL_SSRS_AGENT_DETAILS_STATES]
END
GO

/****** Object:  StoredProcedure [dbo].[uspWSOL_SSRS_AGENT_DETAILS]    Script Date: 2/20/2018 12:54:27 PM ******/
IF EXISTS(SELECT top(1)* FROM sysobjects WHERE name='uspWSOL_SSRS_AGENT_DETAILS')
BEGIN
	DROP PROCEDURE [dbo].[uspWSOL_SSRS_AGENT_DETAILS]
END
GO


