CREATE TABLE [smallforms].[bmsdata] (
    [id]         BIGINT        IDENTITY (399, 1) NOT NULL,
    [bmsabil]    CHAR (1)      DEFAULT (N'') NOT NULL,
    [bmsothdr]   CHAR (1)      DEFAULT (N'') NOT NULL,
    [callername] VARCHAR (250) DEFAULT (N'') NOT NULL,
    [callerrel]  VARCHAR (250) DEFAULT (N'') NOT NULL,
    [callerphon] VARCHAR (250) DEFAULT (N'') NOT NULL,
    [patname]    VARCHAR (250) DEFAULT (N'') NOT NULL,
    [patssn]     VARCHAR (250) DEFAULT (N'') NOT NULL,
    [patstreet]  VARCHAR (250) DEFAULT (N'') NOT NULL,
    [patcist]    VARCHAR (250) DEFAULT (N'') NOT NULL,
    [patzip]     VARCHAR (250) DEFAULT (N'') NOT NULL,
    [patphone1]  VARCHAR (250) DEFAULT (N'') NOT NULL,
    [patphone2]  VARCHAR (250) DEFAULT (N'') NOT NULL,
    [healprov]   VARCHAR (250) DEFAULT (N'') NOT NULL,
    [shipaddr]   VARCHAR (250) DEFAULT (N'') NOT NULL,
    [shipcist]   VARCHAR (250) DEFAULT (N'') NOT NULL,
    [shipzip]    VARCHAR (250) DEFAULT (N'') NOT NULL,
    [shipphone1] VARCHAR (250) DEFAULT (N'') NOT NULL,
    [shipphone2] VARCHAR (250) DEFAULT (N'') NOT NULL,
    [mailaddr]   VARCHAR (MAX) NOT NULL,
    [nameofmed]  VARCHAR (250) DEFAULT (N'') NOT NULL,
    [strength]   VARCHAR (250) DEFAULT (N'') NOT NULL,
    [amountday]  VARCHAR (250) DEFAULT (N'') NOT NULL,
    [comment]    VARCHAR (MAX) NOT NULL,
    [reqcallb]   CHAR (1)      DEFAULT (N'') NOT NULL,
    [agentname]  VARCHAR (250) DEFAULT (N'') NOT NULL,
    [datew]      DATE          DEFAULT ([dbo].[GETDATE]()) NOT NULL,
    [timew]      TIME (7)      DEFAULT ('00:00:00') NOT NULL,
    CONSTRAINT [PK_bmsdata_id] PRIMARY KEY CLUSTERED ([id] ASC)
);

